Updated to wine-20030618

diff --git a/emulators/wine/patches/patch-ac b/emulators/wine/patches/patch-ac
--- a/emulators/wine/patches/patch-ac
+++ b/emulators/wine/patches/patch-ac
@@ -1,8 +1,8 @@
-$NetBSD: patch-ac,v 1.5 2002/10/10 16:48:09 junyoung Exp $
+$NetBSD: patch-ac,v 1.6 2003/06/23 08:13:00 adam Exp $
 
---- configure.orig	Tue Oct  8 11:03:41 2002
-+++ configure	Fri Oct 11 00:54:07 2002
-@@ -10982,7 +10982,7 @@
+--- configure.orig	2003-06-18 22:35:38.000000000 +0200
++++ configure	2003-06-19 11:34:00.000000000 +0200
+@@ -12230,7 +12230,7 @@
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
@@ -11,7 +11,7 @@ $NetBSD: patch-ac,v 1.5 2002/10/10 16:48:09 junyoung Exp $
    if test "x$ac_cv_lib_soname_X11" = "x"
    then
       ac_cv_lib_soname_X11="libX11.so"
-@@ -11048,7 +11048,7 @@
+@@ -12295,7 +12295,7 @@
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
@@ -20,7 +20,7 @@ $NetBSD: patch-ac,v 1.5 2002/10/10 16:48:09 junyoung Exp $
    if test "x$ac_cv_lib_soname_Xext" = "x"
    then
       ac_cv_lib_soname_Xext="libXext.so"
-@@ -11114,7 +11114,7 @@
+@@ -12360,7 +12360,7 @@
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
@@ -29,7 +29,7 @@ $NetBSD: patch-ac,v 1.5 2002/10/10 16:48:09 junyoung Exp $
    if test "x$ac_cv_lib_soname_Xrender" = "x"
    then
       ac_cv_lib_soname_Xrender="libXrender.so"
-@@ -11180,7 +11180,7 @@
+@@ -12425,7 +12425,7 @@
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
@@ -38,3 +38,21 @@ $NetBSD: patch-ac,v 1.5 2002/10/10 16:48:09 junyoung Exp $
    if test "x$ac_cv_lib_soname_freetype" = "x"
    then
       ac_cv_lib_soname_freetype="libfreetype.so"
+@@ -14770,7 +14770,7 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  wine_cv_linux_gethostbyname_r_6=yes
++  wine_cv_linux_gethostbyname_r_6=no
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+@@ -15656,7 +15656,7 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_member_siginfo_t_si_fd=yes
++  ac_cv_member_siginfo_t_si_fd=no
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
