Use gtkhtml38 instead of gtkhtml36.  Bump PKGREVISION to 7.

diff --git a/time/gnotime/patches/patch-am b/time/gnotime/patches/patch-am
--- a/time/gnotime/patches/patch-am
+++ b/time/gnotime/patches/patch-am
@@ -1,4 +1,4 @@
-$NetBSD: patch-am,v 1.3 2005/06/26 18:45:44 jmmv Exp $
+$NetBSD: patch-am,v 1.4 2006/04/04 15:32:22 jmmv Exp $
 
 --- configure.orig	2004-05-23 22:09:39.000000000 +0200
 +++ configure
@@ -8,11 +8,11 @@ $NetBSD: patch-am,v 1.3 2005/06/26 18:45:44 jmmv Exp $
       if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
 -        echo "$as_me:$LINENO: checking for libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED" >&5
 -echo $ECHO_N "checking for libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED... $ECHO_C" >&6
-+        echo "$as_me:$LINENO: checking for libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED" >&5
-+echo $ECHO_N "checking for libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED... $ECHO_C" >&6
++        echo "$as_me:$LINENO: checking for libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED" >&5
++echo $ECHO_N "checking for libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED... $ECHO_C" >&6
  
 -        if $PKG_CONFIG --exists "libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED" ; then
-+        if $PKG_CONFIG --exists "libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED" ; then
++        if $PKG_CONFIG --exists "libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED" ; then
              echo "$as_me:$LINENO: result: yes" >&5
  echo "${ECHO_T}yes" >&6
              succeeded=yes
@@ -20,14 +20,14 @@ $NetBSD: patch-am,v 1.3 2005/06/26 18:45:44 jmmv Exp $
              echo "$as_me:$LINENO: checking LIBGTKHTML_CFLAGS" >&5
  echo $ECHO_N "checking LIBGTKHTML_CFLAGS... $ECHO_C" >&6
 -            LIBGTKHTML_CFLAGS=`$PKG_CONFIG --cflags "libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED"`
-+            LIBGTKHTML_CFLAGS=`$PKG_CONFIG --cflags "libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED"`
++            LIBGTKHTML_CFLAGS=`$PKG_CONFIG --cflags "libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED"`
              echo "$as_me:$LINENO: result: $LIBGTKHTML_CFLAGS" >&5
  echo "${ECHO_T}$LIBGTKHTML_CFLAGS" >&6
  
              echo "$as_me:$LINENO: checking LIBGTKHTML_LIBS" >&5
  echo $ECHO_N "checking LIBGTKHTML_LIBS... $ECHO_C" >&6
 -            LIBGTKHTML_LIBS=`$PKG_CONFIG --libs "libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED"`
-+            LIBGTKHTML_LIBS=`$PKG_CONFIG --libs "libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED"`
++            LIBGTKHTML_LIBS=`$PKG_CONFIG --libs "libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED"`
              echo "$as_me:$LINENO: result: $LIBGTKHTML_LIBS" >&5
  echo "${ECHO_T}$LIBGTKHTML_LIBS" >&6
          else
@@ -36,7 +36,7 @@ $NetBSD: patch-am,v 1.3 2005/06/26 18:45:44 jmmv Exp $
              ## If we have a custom action on failure, don't print errors, but
              ## do set a variable so people can do so.
 -            LIBGTKHTML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED"`
-+            LIBGTKHTML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED"`
++            LIBGTKHTML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED"`
              echo $LIBGTKHTML_PKG_ERRORS
          fi
  
@@ -46,8 +46,8 @@ $NetBSD: patch-am,v 1.3 2005/06/26 18:45:44 jmmv Exp $
    else
 -     { { echo "$as_me:$LINENO: error: Library requirements (libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
 -echo "$as_me: error: Library requirements (libgtkhtml-3.1 >= $LIBGTKHTML_REQUIRED) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
-+     { { echo "$as_me:$LINENO: error: Library requirements (libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-+echo "$as_me: error: Library requirements (libgtkhtml-3.6 >= $LIBGTKHTML_REQUIRED) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
++     { { echo "$as_me:$LINENO: error: Library requirements (libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
++echo "$as_me: error: Library requirements (libgtkhtml-3.8 >= $LIBGTKHTML_REQUIRED) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
     { (exit 1); exit 1; }; }
    fi
  
