make this work again after the tcl/tk package thread enabling

diff --git a/math/scilab/patches/patch-ab b/math/scilab/patches/patch-ab
--- a/math/scilab/patches/patch-ab
+++ b/math/scilab/patches/patch-ab
@@ -1,6 +1,6 @@
-$NetBSD: patch-ab,v 1.6 2003/11/01 12:26:21 dmcmahill Exp $
+$NetBSD: patch-ab,v 1.7 2004/03/28 17:26:21 dmcmahill Exp $
 
---- configure.orig	2003-02-06 02:42:04.000000000 -0500
+--- configure.orig	Thu Feb  6 07:42:04 2003
 +++ configure
 @@ -7085,8 +7085,8 @@ echo "$as_me: error: Unable to configure
    *-*-solaris*)
@@ -43,3 +43,43 @@ $NetBSD: patch-ab,v 1.6 2003/11/01 12:26:21 dmcmahill Exp $
     FC_PICFLAGS='-fPIC'
     # check for --export-dynamic
     ac_save_LDFLAGS="$LDFLAGS"
+@@ -13100,6 +13100,10 @@ CHK_TCL_MIN=$TCL_MINOR_VERSION
+ TCL_LIB_OK=0
+   echo "$as_me:13101: checking for tcl library tcl$TCL_MAJOR_VERSION.$TCL_MINOR_VERSION" >&5
+ echo $ECHO_N "checking for tcl library tcl$TCL_MAJOR_VERSION.$TCL_MINOR_VERSION... $ECHO_C" >&6
++if test -n "$TCL_CONFIG_SH" ; then  
++	. $TCL_CONFIG_SH
++fi    
++LDFLAGS="$LDFLAGS $TCL_LIBS" 
+ dirs="$USER_TCL_LIB_PATH /lib /usr/lib /usr/lib/tcl /usr/lib/tcl8.* /shlib /shlib/tcl /shlib/tcl8.* /usr/shlib /shlib/tcl /usr//shlib/tcl8.* /usr/local/lib /usr/local/lib/tcl /usr/local/lib/tcl8.* /usr/local/shlib /usr/X11/lib/tcl /usr/X11/lib/tcl8.* /usr/lib/X11 /usr/lib/X11/tcl /usr/lib/X11/tcl8.* ../lib ../../lib  /usr/local/tcl /usr/tcl /usr/tcl/lib /usr/local/tcl/lib /sw/lib/ ."
+ libexts="so so.1.0 sl dylib a"
+ libnames="tcl$CHK_TCL_MAJ.$CHK_TCL_MIN tcl.$CHK_TCL_MAJ.$CHK_TCL_MIN tcl$CHK_TCL_MAJ$CHK_TCL_MIN tcl.$CHK_TCL_MAJ$CHK_TCL_MIN"
+@@ -13256,7 +13260,7 @@ fi
+ done
+ 
+ 			if test $TCL_LIB_OK = 1; then
+-				TCLTK_LIBS=" $TCL_LIB $TCLTK_LIBS"
++				TCLTK_LIBS=" $TCL_LIB $TCL_LIBS $TCLTK_LIBS"
+ 				break;
+ 			fi
+ 		fi
+@@ -13376,6 +13380,10 @@ TK_LIB_OK=0
+ 
+ echo "$as_me:13377: checking for tk library tk$TK_MAJOR_VERSION.$TK_MINOR_VERSION" >&5
+ echo $ECHO_N "checking for tk library tk$TK_MAJOR_VERSION.$TK_MINOR_VERSION... $ECHO_C" >&6
++if test -n "$TK_CONFIG_SH" ; then  
++	. $TK_CONFIG_SH
++fi    
++LDFLAGS="$LDFLAGS $TK_LIBS" 
+ dirs="$USER_TK_LIB_PATH /lib /usr/lib /usr/lib/tk /usr/lib/tk8.* /shlib /shlib/tk /shlib/tk8.* /usr/shlib /shlib/tk /usr/shlib/tk8.* /usr/local/lib /usr/local/lib/tk /usr/local/lib/tk8.* /usr/local/shlib /usr/X11/lib/tk /usr/X11/lib/tk8.*  /usr/lib/X11 /usr/lib/X11/tk /usr/lib/X11/tk8.* ../lib ../../lib /usr/tk /usr/local/tk /usr/local/tk/lib /usr/tk/lib /usr/local/tcl /usr/tcl /usr/local/tcl/lib /usr/tcl/lib /sw/lib "
+ libexts="so so.1.0 sl dylib a"
+ libnames="tk$CHK_TK_MAJ.$CHK_TK_MIN tk.$CHK_TK_MAJ.$CHK_TK_MIN tk$CHK_TK_MAJ$CHK_TK_MIN tk.$CHK_TK_MAJ$CHK_TK_MIN"
+@@ -13553,7 +13561,7 @@ done
+ echo "$as_me: error: tk library not found" >&2;}
+    { (exit 1); exit 1; }; }
+   else
+-        TCLTK_LIBS=$TK_LIB" $TCLTK_LIBS"
++        TCLTK_LIBS=" $TK_LIB $TK_LIBS $TCLTK_LIBS"
+         WITH_TKSCI=1
+   fi
+ 
