Update mysql-{client,server} to 4.0.22.
Functionality added or changed:

    * The --with-openssl option for configure now accepts a path
      prefix as an argument. --with-openssl-includes and
      --with-openssl-libs are still supported, but are needed only
      to override the default values. (Bug #5494)
    * Added new --without-man option to configure to suppress
      building/installing the manual pages. (Bug #5379)
    * InnoDB: New mysqld option --innodb-table-locks and session
      variable innodb_table_locks (on by default). In applications
      using AUTOCOMMIT=1, InnoDB's internal table locks can cause
      deadlocks. You can set innodb_table_locks=0 in `my.cnf' to
      remove that problem. See section 16.17 Restrictions on InnoDB
      Tables. (Bug #3299, Bug #5998)
    * InnoDB: Added the startup option and settable global variable
      innodb_max_purge_lag for delaying INSERT, UPDATE and DELETE
      operations when the purge operations are lagging. The default
      value of this parameter is zero, meaning that there will not be
      any delays. See section 16.13 Implementation of Multi-Versioning.
    * InnoDB: Change error code to HA_ERR_ROW_IS_REFERENCED if we
      cannot DROP a parent table because it is referenced by a FOREIGN
      KEY constraint.

And a lot of bugfixes: http://dev.mysql.com/doc/mysql/en/News-4.0.22.html

diff --git a/databases/mysql-client/patches/patch-af b/databases/mysql-client/patches/patch-af
--- a/databases/mysql-client/patches/patch-af
+++ b/databases/mysql-client/patches/patch-af
@@ -1,12 +1,59 @@
-$NetBSD: patch-af,v 1.9 2004/10/28 01:08:15 xtraeme Exp $
+$NetBSD: patch-af,v 1.10 2004/11/09 06:11:48 xtraeme Exp $
 
---- configure.orig	Tue Feb 10 20:16:56 2004
-+++ configure	Sun Mar  7 19:58:04 2004
-@@ -32277,7 +32277,6 @@
+--- configure.orig	2004-11-08 20:11:05.000000000 +0100
++++ configure	2004-11-08 20:12:44.000000000 +0100
+@@ -22842,10 +22842,7 @@
+   return 0;
+ }
+ 
+-int link_test()
+-{
+   return compress(0, (unsigned long*) 0, "", 0);
+-}
+ 
+ _ACEOF
+ rm -f conftest$ac_exeext
+@@ -32058,34 +32055,10 @@
+   mysqlfs=no
+ fi;
+ 
+-
+-echo "$as_me:$LINENO: checking for ORBit" >&5
+-echo $ECHO_N "checking for ORBit... $ECHO_C" >&6
+-orbit_config_path=`which orbit-config`
+-if test -n "$orbit_config_path" -a $? = 0
+-then
+-  orbit_exec_prefix=`orbit-config --exec-prefix`
+-  orbit_includes=`orbit-config --cflags server`
+-  orbit_libs=`orbit-config --libs server`
+-  orbit_idl="$orbit_exec_prefix/bin/orbit-idl"
+-  echo "$as_me:$LINENO: result: found!" >&5
+-echo "${ECHO_T}found!" >&6
+-  cat >>confdefs.h <<\_ACEOF
+-#define HAVE_ORBIT 1
+-_ACEOF
+-
+-else
+   orbit_exec_prefix=
+   orbit_includes=
+   orbit_libs=
+   orbit_idl=
+-  echo "$as_me:$LINENO: result: not found" >&5
+-echo "${ECHO_T}not found" >&6
+-fi
+-
+-
+-
+-
+ 
+   echo "$as_me:$LINENO: checking if we should build MySQLFS" >&5
+ echo $ECHO_N "checking if we should build MySQLFS... $ECHO_C" >&6
+@@ -32358,7 +32331,7 @@
  else
    bench_dirs=""
  fi
 -bench_dirs="$bench_dirs mysql-test"
++#bench_dirs="$bench_dirs mysql-test"
  
  
  # Don't build readline, i have it already
