Clean this up, sync with the ssh package, and update to 1.2.2 (fixing PR 9304 by David Rankin <drankin@bohemians.lexington.ky.us>.
Changes:

20000125
 - Fix NULL pointer dereference in login.c. Fix from Andre Lucas
   <andre.lucas@dial.pipex.com>
 - Reorder PAM initialisation so it does not mess up lastlog. Reported
   by Andre Lucas <andre.lucas@dial.pipex.com>
 - Use preformatted manpages on SCO, report from Gary E. Miller
   <gem@rellim.com>
 - New URL for x11-ssh-askpass.
 - Fixpaths was missing /etc/ssh_known_hosts. Report from Jim Knoble
   <jmknoble@pobox.com>
 - Added 'DESTDIR' option to Makefile to ease package building. Patch from
   Jim Knoble <jmknoble@pobox.com>
 - Updated RPM spec files to use DESTDIR

20000124
 - Pick up version 1.2.2 from OpenBSD CVS (no changes, just version number
   increment)

20000123
 - OpenBSD CVS:
   - [packet.c]
     getsockname() requires initialized tolen; andy@guildsoftware.com
 - AIX patch from Matt Richards <v2matt@btv.ibm.com> and David Rankin
   <drankin@bohemians.lexington.ky.us>
 - Fix lastlog support, patch from Andre Lucas <andre.lucas@dial.pipex.com>

20000122
 - Fix compilation of bsd-snprintf.c on Solaris, fix from Ben Taylor
   <bent@clark.net>
 - Merge preformatted manpage patch from Andre Lucas
   <andre.lucas@dial.pipex.com>
 - Make IPv4 use the default in RPM packages
 - Irix uses preformatted manpages
 - Missing htons() in bsd-bindresvport.c, fix from Holger Trapp
   <Holger.Trapp@Informatik.TU-Chemnitz.DE>
 - OpenBSD CVS updates:
   - [packet.c]
     use getpeername() in packet_connection_is_on_socket(), fixes sshd -i;
     from Holger.Trapp@Informatik.TU-Chemnitz.DE
   - [sshd.c]
     log with level log() not fatal() if peer behaves badly.
   - [readpass.c]
     instead of blocking SIGINT, catch it ourselves, so that we can clean
     the tty modes up and kill ourselves -- instead of our process group
     leader (scp, cvs, ...) going away and leaving us in noecho mode.
     people with cbreak shells never even noticed..
   - [ssh-add.1 ssh-agent.1 ssh-keygen.1 ssh.1 sshd.8]
     ie. -> i.e.,

20000120
 - Don't use getaddrinfo on AIX
 - Update to latest OpenBSD CVS:
   - [auth-rsa.c]
     - fix user/1056, sshd keeps restrictions; dbt@meat.net
   - [sshconnect.c]
     - disable agent fwding for proto 1.3, remove abuse of auth-rsa flags.
     - destroy keys earlier
     - split key exchange (kex) and user authentication (user-auth),
       ok: provos@
   - [sshd.c]
     - no need for poll.h; from bright@wintelcom.net
     - disable agent fwding for proto 1.3, remove abuse of auth-rsa flags.
     - split key exchange (kex) and user authentication (user-auth),
       ok: provos@
   - [sshd.c]
     - no need for poll.h; from bright@wintelcom.net
     - disable agent fwding for proto 1.3, remove abuse of auth-rsa flags.
     - split key exchange (kex) and user authentication (user-auth),
       ok: provos@
 - Big manpage and config file cleanup from Andre Lucas
   <andre.lucas@dial.pipex.com>
   - Re-added latest (unmodified) OpenBSD manpages
 - Doc updates
 - NetBSD patch from David Rankin <drankin@bohemians.lexington.ky.us> and
   Christos Zoulas <christos@netbsd.org>

20000119
 - SCO compile fixes from Gary E. Miller <gem@rellim.com>
 - Compile fix from Darren_Hall@progressive.com
 - Linux/glibc-2.1.2 takes a *long* time to look up names for AF_UNSPEC
   addresses using getaddrinfo(). Added a configure switch to make the
   default lookup mode AF_INET

20000118
 - Fixed --with-pid-dir option
 - Makefile fix from Gary E. Miller <gem@rellim.com>
 - Compile fix for HPUX and Solaris from Andre Lucas
   <andre.lucas@dial.pipex.com>

diff --git a/security/openssh/patches/patch-aa b/security/openssh/patches/patch-aa
--- a/security/openssh/patches/patch-aa
+++ b/security/openssh/patches/patch-aa
@@ -1,17 +1,8 @@
-$NetBSD: patch-aa,v 1.2 2000/01/17 07:24:40 christos Exp $
+$NetBSD: patch-aa,v 1.3 2000/01/27 17:12:03 hubertf Exp $
 
---- configure.orig	Sat Jan 15 20:22:59 2000
-+++ configure	Mon Jan 17 02:21:54 2000
-@@ -1293,7 +1293,7 @@
- 
- echo $ac_n "checking for OpenSSL/SSLeay directory""... $ac_c" 1>&6
- echo "configure:1296: checking for OpenSSL/SSLeay directory" >&5
--for ssldir in /usr /usr/local/openssl /usr/lib/openssl /usr/local/ssl /usr/lib/ssl /usr/local $prefix /usr/pkg ; do
-+for ssldir in $prefix /usr /usr/local/openssl /usr/lib/openssl /usr/local/ssl /usr/lib/ssl /usr/local /usr/pkg ; do
- 	if test -f "$ssldir/include/openssl/crypto.h"; then
- 		cat >> confdefs.h <<\EOF
- #define HAVE_OPENSSL 1
-@@ -1321,7 +1321,7 @@
+--- configure.orig	Thu Jan 27 04:17:06 2000
++++ configure	Thu Jan 27 17:02:44 2000
+@@ -1271,7 +1271,7 @@
  
  if test "$ssldir" != "/usr"; then
  	CFLAGS="$CFLAGS -I$ssldir/include"
@@ -20,35 +11,32 @@ $NetBSD: patch-aa,v 1.2 2000/01/17 07:24:40 christos Exp $
  fi
  echo "$ac_t""$ssldir" 1>&6
  
-@@ -2224,6 +2224,7 @@
+@@ -2321,7 +2321,9 @@
  cat > conftest.$ac_ext <<EOF
- #line 2226 "configure"
- #include "confdefs.h"
-+#include <sys/types.h>
- #include <sys/socket.h>
- int main() {
- struct sockaddr_storage s;
-@@ -2252,6 +2253,7 @@
- cat > conftest.$ac_ext <<EOF
- #line 2254 "configure"
+ #line 2323 "configure"
  #include "confdefs.h"
 +#include <sys/types.h>
  #include <netinet/in.h>
++#include <netinet/in6.h>
  int main() {
  struct sockaddr_in6 s; s.sin6_family = 0;
-@@ -2280,6 +2282,7 @@
+ ; return 0; }
+@@ -2349,7 +2351,9 @@
  cat > conftest.$ac_ext <<EOF
- #line 2282 "configure"
+ #line 2351 "configure"
  #include "confdefs.h"
 +#include <sys/types.h>
  #include <netinet/in.h>
++#include <netinet/in6.h>
  int main() {
  struct in6_addr s; s.s6_addr[0] = 0;
-@@ -2309,6 +2312,7 @@
- #line 2310 "configure"
- #include "confdefs.h"
- 
-+		#include <sys/types.h>
- 		#include <sys/socket.h>
- 		#include <netdb.h>
- 	
+ ; return 0; }
+@@ -2545,7 +2549,7 @@
+   if test "$cross_compiling" = yes; then
+     { echo "configure: error: Cannot check for file existence when cross compiling" 1>&2; exit 1; }
+ else
+-  if test -r "/dev/urandom"; then
++  if test -r "/dev/urandom" && dd if=/dev/urandom of=/dev/null bs=1 count=1; then
+     eval "ac_cv_file_$ac_safe=yes"
+   else
+     eval "ac_cv_file_$ac_safe=no"
