Bail out before doing anything if PKG_PATH is set.

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# $NetBSD: bootstrap,v 1.146 2009/05/29 15:58:37 rillig Exp $
+# $NetBSD: bootstrap,v 1.147 2009/06/15 17:02:14 joerg Exp $
 #
 #
 # Copyright (c) 2001-2002 Alistair G. Crooks.  All rights reserved.
@@ -338,6 +338,11 @@ if [ "$dash_echo_test" = "@" ]; then
 	  echo "ERROR: Please select another shell by setting the environment"
 	  echo "ERROR: variable SH."
 	} 1>&2
+	exit 1;
+fi
+
+if [ -n "$PKG_PATH" ]; then
+	echo "ERROR: Please unset PKG_PATH before running bootstrap." 1>&2
 	exit 1;
 fi
 
