Provide a better mkdir -p replacement for the early build for platforms that don't have it. Explicitly bail out if the work directory exists already.

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# $NetBSD: bootstrap,v 1.142 2009/04/06 14:21:05 joerg Exp $
+# $NetBSD: bootstrap,v 1.143 2009/04/21 14:21:10 joerg Exp $
 #
 #
 # Copyright (c) 2001-2002 Alistair G. Crooks.  All rights reserved.
@@ -282,14 +282,14 @@ mkdir_p()
 
 mkdir_p_early()
 {
-	if [ ! -d "$1" ]; then
-		if mkdir -p "$1"; then
-			:
-		else
-			echo_msg "mkdir $1 exited with status $?"
-			die "aborted."
-		fi
+	[ -d "$1" ] && return 0	
+	mkdir -p "$1" 2> /dev/null && return 0
+	mkdir_p_early `basename "$1"`
+	if [ ! -d "$1" ] && mkdir "$1"; then
+		echo_msg "mkdir $1 exited with status $?"
+		die "aborted."
 	fi
+	return 0
 }
 
 copy_src()
@@ -691,6 +691,11 @@ check_prog rmdirprog rmdir
 check_prog sedprog sed
 check_prog shprog sh
 check_prog whoamiprog whoami
+
+if [ -d "${wrkdir}" ] || [ -f "${wrkdir}"; then
+	echo "\"${wrkdir}\" already exists, please remove it or use --workdir.";
+	exit 1
+fi
 
 mkdir_p_early ${wrkdir}
 if touch ${wrkdir}/.writeable; then
