Update pidgin and friends to 2.4.3. Done during pkgsrc freeze because of:  i) CVE-2008-2927 fix ii) the previous version was being rejected from the ICQ network. version 2.4.3 (07/01/2008): libpurple: * Yahoo! Japan now uses UTF-8, matching the behavior of official clients   and restoring compatibility with the web messenger (Yusuke Odate) * Setting your buddy icon once again works for Yahoo! accounts. * Fixes in the Yahoo! protocol to prevent a double free, crashes on   aliases, and alias functionality * Fix crashes in the bonjour protocol * Always use UTF-8 for Yahoo! (#5973) * Fix a crash when the given jabber id is invalid. * Make the IRC "unknown message" debugging messages UTF-8 safe. * Fix connecting to ICQ * Fix a memleak when handling jabber xforms. Pidgin: * Include the send button plugin in the win32 build * Various memory leak fixes

diff --git a/chat/libpurple/patches/patch-aa b/chat/libpurple/patches/patch-aa
--- a/chat/libpurple/patches/patch-aa
+++ b/chat/libpurple/patches/patch-aa
@@ -1,10 +1,10 @@
-$NetBSD: patch-aa,v 1.8 2008/05/17 22:56:17 tnn Exp $
+$NetBSD: patch-aa,v 1.9 2008/07/11 07:39:20 tnn Exp $
 
---- configure.orig	2008-05-16 20:53:50.000000000 +0200
+--- configure.orig	2008-07-02 02:47:08.000000000 +0200
 +++ configure
-@@ -20047,6 +20047,11 @@ INTLTOOL_SOUNDLIST_RULE='%.soundlist: %.
- 
- 
+@@ -20183,6 +20183,11 @@ echo "$as_me: error: GNU gettext tools n
+    { (exit 1); exit 1; }; }
+ fi
  
 +INTLTOOL_EXTRACT=intltool-extract
 +INTLTOOL_MERGE=intltool-merge
@@ -14,7 +14,7 @@ $NetBSD: patch-aa,v 1.8 2008/05/17 22:56:17 tnn Exp $
  # Use the tools built into the package, not the ones that are installed.
  INTLTOOL_EXTRACT='$(top_builddir)/intltool-extract'
  
-@@ -20117,6 +20122,7 @@ echo "$as_me: error: XML::Parser perl mo
+@@ -20253,6 +20258,7 @@ echo "$as_me: error: XML::Parser perl mo
     { (exit 1); exit 1; }; }
     fi
  fi
@@ -22,7 +22,7 @@ $NetBSD: patch-aa,v 1.8 2008/05/17 22:56:17 tnn Exp $
  
  # Substitute ALL_LINGUAS so we can use it in po/Makefile
  
-@@ -28293,7 +28299,7 @@ if test "${ac_cv_lib_panelw_update_panel
+@@ -28393,7 +28399,7 @@ if test "${ac_cv_lib_panelw_update_panel
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -31,7 +31,7 @@ $NetBSD: patch-aa,v 1.8 2008/05/17 22:56:17 tnn Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28349,7 +28355,7 @@ fi
+@@ -28449,7 +28455,7 @@ fi
  { echo "$as_me:$LINENO: result: $ac_cv_lib_panelw_update_panels" >&5
  echo "${ECHO_T}$ac_cv_lib_panelw_update_panels" >&6; }
  if test $ac_cv_lib_panelw_update_panels = yes; then
@@ -40,7 +40,7 @@ $NetBSD: patch-aa,v 1.8 2008/05/17 22:56:17 tnn Exp $
  else
    enable_consoleui=no
  fi
-@@ -28647,7 +28653,7 @@ if test "${ac_cv_lib_panel_update_panels
+@@ -28747,7 +28753,7 @@ if test "${ac_cv_lib_panel_update_panels
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -49,7 +49,7 @@ $NetBSD: patch-aa,v 1.8 2008/05/17 22:56:17 tnn Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28703,7 +28709,7 @@ fi
+@@ -28803,7 +28809,7 @@ fi
  { echo "$as_me:$LINENO: result: $ac_cv_lib_panel_update_panels" >&5
  echo "${ECHO_T}$ac_cv_lib_panel_update_panels" >&6; }
  if test $ac_cv_lib_panel_update_panels = yes; then
