Update to libpurple-2.4.2.
o In MySpaceIM, messages from spambots are discarded (Justin Williams)
o Strip mIRC formatting codes from quit and part messages.
o IRC now displays ban lists in-channel for joined channels.
o Fixed a bug where the list of loaded plugins would get removed when
  switching between different operating systems.
o Fix reception of IRC PART without a part message on Undernet
  (fixes a problem with litter in the channel user list).
o IRC no longer crashes on /list on servers which erroneously omit RPL_LISTSTART
o Update the NetworkManager support to use D-Bus directly, instead of
  libnm-glib. Hopefully it's stable now. It will now compile by default if you
  have D-Bus support and NetworkManager.h. (Elliott Sales de Andrade)
o MSN buddy list synchronization is now more forgiving, only asking about
  buddies who have disappeared completely from the server list and not those
  that have simply moved groups.
o IRC will now try to append 1-9 to your nick if it is in use, instead of
  substituting the last character with 1-9 where possible.
o Bonjour buddies will be saved persistently if they're moved out of the
  "Bonjour" group. (Eion Robb)

diff --git a/chat/libpurple/patches/patch-aa b/chat/libpurple/patches/patch-aa
--- a/chat/libpurple/patches/patch-aa
+++ b/chat/libpurple/patches/patch-aa
@@ -1,8 +1,8 @@
-$NetBSD: patch-aa,v 1.7 2007/09/30 13:47:03 tnn Exp $
+$NetBSD: patch-aa,v 1.8 2008/05/17 22:56:17 tnn Exp $
 
---- configure.orig	2007-09-29 18:40:51.000000000 +0200
+--- configure.orig	2008-05-16 20:53:50.000000000 +0200
 +++ configure
-@@ -19940,6 +19940,11 @@ INTLTOOL_SOUNDLIST_RULE='%.soundlist: %.
+@@ -20047,6 +20047,11 @@ INTLTOOL_SOUNDLIST_RULE='%.soundlist: %.
  
  
  
@@ -14,24 +14,42 @@ $NetBSD: patch-aa,v 1.7 2007/09/30 13:47:03 tnn Exp $
  # Use the tools built into the package, not the ones that are installed.
  INTLTOOL_EXTRACT='$(top_builddir)/intltool-extract'
  
-@@ -20173,6 +20178,7 @@ else
-   { echo "$as_me:$LINENO: result: no" >&5
- echo "${ECHO_T}no" >&6; }
+@@ -20117,6 +20122,7 @@ echo "$as_me: error: XML::Parser perl mo
+    { (exit 1); exit 1; }; }
+    fi
  fi
 +fi # pkgsrc
  
+ # Substitute ALL_LINGUAS so we can use it in po/Makefile
  
- 
-@@ -28484,7 +28490,7 @@ if test "${ac_cv_lib_panel_update_panels
+@@ -28293,7 +28299,7 @@ if test "${ac_cv_lib_panelw_update_panel
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lpanelw  $LIBS"
++LIBS="-lpanelw -lncursesw $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -28349,7 +28355,7 @@ fi
+ { echo "$as_me:$LINENO: result: $ac_cv_lib_panelw_update_panels" >&5
+ echo "${ECHO_T}$ac_cv_lib_panelw_update_panels" >&6; }
+ if test $ac_cv_lib_panelw_update_panels = yes; then
+-  GNT_LIBS="$GNT_LIBS -lpanelw"
++  GNT_LIBS="$GNT_LIBS -lpanelw -lncursesw"
+ else
+   enable_consoleui=no
+ fi
+@@ -28647,7 +28653,7 @@ if test "${ac_cv_lib_panel_update_panels
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
 -LIBS="-lpanel  $LIBS"
-+LIBS="-lpanel -lncurses  $LIBS"
++LIBS="-lpanel -lncurses $LIBS"
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28540,7 +28546,7 @@ fi
+@@ -28703,7 +28709,7 @@ fi
  { echo "$as_me:$LINENO: result: $ac_cv_lib_panel_update_panels" >&5
  echo "${ECHO_T}$ac_cv_lib_panel_update_panels" >&6; }
  if test $ac_cv_lib_panel_update_panels = yes; then
