Update the pidgin IM suite to version 2.2.0.
The intltool that comes bundled with libpurple doesn't like NetBSD's
/usr/bin/iconv, so switch libpurple to use intltool from pkgsrc.

ChangeLog:

Version 2.2.0 (09/13/2007):
http://developer.pidgin.im/query?status=closed&milestone=2.2.0

Libpurple:
* New protocol plugin: MySpaceIM (Jeff Connelly, Google Summer of
  Code)
* XMPP enhancements. See
	  http://www.adiumx.com/blog/2007/07/soc-xmpp-update.php (Andreas
  Monitzer, Google Summer of Code for Adium)
* Certificate management. Libpurple will validate certificates on
  SSL-encrypted protocols (William Ehlhardt, Google Summer of Code)
* Some adjustments were made to fix sending messages when using
  the MSN HTTP method. (Laszlo Pandy)
* Yahoo! Chat is fixed.
* Some AIM file transfer issues between Pidgin and other clients
  have been fixed. (Kyryll A Mirnenko)
* Properly restore idle status and time for AIM and ICQ accounts
  when they reconnect after being disconnected.

Pidgin:
* Insert Horizontal Rules and Strikethrough text from toolbar.
* Option to show protocol icons in the buddy list, from the
  Buddies > Show menu. (Justin Heiner)
* Ability to build with native, non-X11 GTK+ on OSX. (Anders
  Hasselqvist)
* Remember the 'Enable Sounds' setting for a conversation.
* Right-clicking the empty space in the formatting toolbar
  allows you to toggle back to the old "ungrouped" version.
* Protocols supporting account registration via Pidgin now show
  a descriptive checkbox instead of a vague "Register" button.
* Fixed a bug where a tab would be shown on single conversations
  when tabs were disabled.

Finch:
* Per-conversation mute and logging options (accessible from the menu).

Version 2.1.1 (08/20/2007):
Yahoo:
* Added an account action to open your inbox in the yahoo prpl.
* Added support for Unicode status messages in Yahoo.
* Server-stored aliases for Yahoo. (John Moody)
* Fixed support for Yahoo! doodling.
* Limited support for MSN Messenger contacts

Bonjour:
* Bonjour plugin uses native Avahi instead of Howl
* Bonjour plugin supports Buddy Icons

XMPP:
* Only report conversation close when 'send typing notifications'
  preference is turned on (Bob Rossi)

Pidgin:
* Show current outgoing conversation formatting on the font label on
  the toolbar
* Slim new redesign of conversation tabs to maximize number of
  conversations that can fit in a window
* Tab bar is not visible when only one conversation is open. You can
  drag and drop conversations from the infopane.
* Moved "Reset Formatting" toolbar button to Font menu.
* Double click on the infopane to alias buddies and set topics
  on chats
* New smiley style

Finch:
* Sound support (Eric Polino)

diff --git a/chat/libpurple/patches/patch-aa b/chat/libpurple/patches/patch-aa
--- a/chat/libpurple/patches/patch-aa
+++ b/chat/libpurple/patches/patch-aa
@@ -1,8 +1,28 @@
-$NetBSD: patch-aa,v 1.5 2007/08/30 16:08:03 joerg Exp $
+$NetBSD: patch-aa,v 1.6 2007/09/15 14:55:02 tnn Exp $
 
---- configure.orig	2007-08-30 15:40:54.000000000 +0000
+--- configure.orig	2007-09-14 09:31:39.000000000 +0200
 +++ configure
-@@ -28183,7 +28183,7 @@ if test "${ac_cv_lib_panel_update_panels
+@@ -20053,6 +20053,11 @@ INTLTOOL_SOUNDLIST_RULE='%.soundlist: %.
+ 
+ 
+ 
++INTLTOOL_EXTRACT=intltool-extract
++INTLTOOL_MERGE=intltool-merge
++INTLTOOL_UPDATE=intltool-update
++# disable pidgin's builtin intltool
++if test -n ""; then
+ # Use the tools built into the package, not the ones that are installed.
+ INTLTOOL_EXTRACT='$(top_builddir)/intltool-extract'
+ 
+@@ -20123,6 +20128,7 @@ echo "$as_me: error: XML::Parser perl mo
+    { (exit 1); exit 1; }; }
+    fi
+ fi
++fi # pkgsrc
+ 
+ # Substitute ALL_LINGUAS so we can use it in po/Makefile
+ 
+@@ -28428,7 +28434,7 @@ if test "${ac_cv_lib_panel_update_panels
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -11,7 +31,7 @@ $NetBSD: patch-aa,v 1.5 2007/08/30 16:08:03 joerg Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28239,7 +28239,7 @@ fi
+@@ -28484,7 +28490,7 @@ fi
  { echo "$as_me:$LINENO: result: $ac_cv_lib_panel_update_panels" >&5
  echo "${ECHO_T}$ac_cv_lib_panel_update_panels" >&6; }
  if test $ac_cv_lib_panel_update_panels = yes; then
