- make build stop on error - sprinkle const - should fix linux build

diff --git a/misc/vfu/patches/patch-ad b/misc/vfu/patches/patch-ad
--- a/misc/vfu/patches/patch-ad
+++ b/misc/vfu/patches/patch-ad
@@ -1,8 +1,18 @@
-$NetBSD: patch-ad,v 1.7 2003/07/14 10:07:12 jmmv Exp $
+$NetBSD: patch-ad,v 1.8 2014/06/29 19:43:54 dholland Exp $
 
---- build.netbsd.orig	2001-10-28 15:12:15.000000000 +0100
+- make build stop on error
+- honor PKG_SYSCONFDIR
+
+--- build.netbsd.orig	2001-10-28 14:12:15.000000000 +0000
 +++ build.netbsd
-@@ -15,7 +15,7 @@ cd ..
+@@ -9,17 +9,19 @@ if [ -e libvslib.a ]; then
+   echo "VSLIB compiled ok."
+ else
+   echo "VSLIB compilation failed..."
++  exit 1
+ fi
+ 
+ cd ..
  
  echo "Compiling VFU..."
  cd vfu
@@ -11,3 +21,15 @@ $NetBSD: patch-ad,v 1.7 2003/07/14 10:07:12 jmmv Exp $
  if [ -e vfu ]; then
    echo "VFU compiled ok."
  else
+   echo "VFU compilation failed..."
++  exit 1
+ fi
+ 
+ cd ..
+@@ -31,5 +33,6 @@ if [ -e ftparc ]; then
+   echo "ftparc compiled ok."
+ else
+   echo "ftparc compilation failed..."
++  exit 1
+ fi
+  
