Fix configure test for expect library.
Also merge patch-aa into patch-af as patching same file.

diff --git a/devel/py-expect/patches/patch-ab b/devel/py-expect/patches/patch-ab
--- a/devel/py-expect/patches/patch-ab
+++ b/devel/py-expect/patches/patch-ab
@@ -1,6 +1,6 @@
-$NetBSD: patch-ab,v 1.2 2004/03/11 17:43:50 minskim Exp $
+$NetBSD: patch-ab,v 1.3 2013/10/27 20:17:40 markd Exp $
 
---- configure.orig	2000-11-05 12:07:38.000000000 -0600
+--- configure.orig	2000-11-05 18:07:38.000000000 +0000
 +++ configure
 @@ -1357,7 +1357,7 @@ echo "$ac_t""$PYTH_vers" 1>&6
  # _multiply_ the python version major version by one thousand, but minor
@@ -11,14 +11,40 @@ $NetBSD: patch-ab,v 1.2 2004/03/11 17:43:50 minskim Exp $
    sed 's/^[0-9]\./0&/;s/\.\([0-9]\)\./.0\1./g;s/\.\([0-9]\)$/\.0\1/;s/\.//g' |
    sed 's/^\(....\)$/\100/'`
  
-@@ -1407,7 +1407,7 @@ if test -n "${EXP_LIB}"; then
-     fi
-   fi
- else
+@@ -1395,20 +1395,20 @@ echo "$ac_t""$EXP_vers" 1>&6
+ 
+ echo $ac_n "checking Expect library location""... $ac_c" 1>&6
+ echo "configure:1398: checking Expect library location" >&5
+-if test -n "${EXP_LIB}"; then
+-  if test x${enable_forcea:+X} = xX -a -f "${EXP_LIB}"; then
+-    :
+-  elif test x${enable_forcea:+X} = xX; then
+-    { echo "configure: error: Cannot find Expect library" 1>&2; exit 1; }
+-  else
+-    f="${EXP_LIBDIR}/lib${EXP_LIB}.*"
+-    if test "`echo $f`" = "$f"; then
+-      { echo "configure: error: Cannot find Expect library" 1>&2; exit 1; }
+-    fi
+-  fi
+-else
 -  EXP_LIB="expect${EXP_VERS}"
+-fi
++#if test -n "${EXP_LIB}"; then
++#  if test x${enable_forcea:+X} = xX -a -f "${EXP_LIB}"; then
++#    :
++#  elif test x${enable_forcea:+X} = xX; then
++#    { echo "configure: error: Cannot find Expect library" 1>&2; exit 1; }
++#  else
++#    f="${EXP_LIBDIR}/lib${EXP_LIB}.*"
++#    if test "`echo $f`" = "$f"; then
++#      { echo "configure: error: Cannot find Expect library" 1>&2; exit 1; }
++#    fi
++#  fi
++#else
 +  EXP_LIB="expect`echo ${EXP_VERS} | sed -e 's,\.,,'`"
- fi
++#fi
  echo "$ac_t""$EXP_LIB" 1>&6
+ 
  
 @@ -1542,7 +1542,7 @@ case ${EXP_VERS} in
  esac
