Update to 0.40. Add a tk option to install an additional tcl/tk frontend.
 0.40
       update PNM file reader to maxval > 255
       (make rpm) updated
       barcode-patch UPC_addon by Michael van Rooyen
       CAPITAL_LETTER_A_WITH_OGONEK added
       no "(PICTURE)" output for UTF8+ASCII (better for Mobile OCR project)
       smooth_borders() bug fixed and reworked
       5x7 and prop10 font adaptions
       objects now detected by flood-fill algorithm (better?)
       XML-output changed
       changed auto dust detection (not final)

 0.39
       XML output added (subject of change, suggestions are welcome)
       netpbm-link-error fixed in gocr.c and configure.in:
         gocr.c: <config.h> changed to "config.h"
       configure-option --with-netpbm=PATH and --without-netpbm added
       update configure.in according to autoconf 2.57
       wchar_h miss-configuration fixed in pgm2asc.c
       fix compiler warnings
       char filter accepts abbreviations now, like "0-9A-F" (but slow)
       update READMEde.txt
       output barcode tags (also improved recognition)
       fix pnm.c for files like example.eps.pbm
       fix detect.c for barcodes
       fix ocr0n.c 0<->8g

 0.38
       move UTF/HTML/TeX decoding to getTextLine, return (char *) now
       out_format HTML step towards detailed XML output
       correct line detection for footnotes (detect.c)
       "y" now seen as vowel (pgm2asc.c), I<vowel> susbtituted by l<vowel>
       &eacute;-detection, &aacute;-output fixed
       default dust_size is -1 now (auto detection = mean_size/10)
       char filter added
        ex: -C 0123456789ABCDEF    - recognize only hexcodes
       man page updated (hopefully correct syntax)
       database bug fixed (small fonts, example by Chris)
       several bugs fixed by W. Webber (thanks)
       speed improved by 3rd-pass matrix filter in pixel() (pixel.c) (code from W. Webber)
       bug in remove_dust (remove.c) fixed
       for fonts bigger than 20x40 smooth_borders() changed (b/w-scans)
       bug in O0-detection fixed

diff --git a/graphics/gocr/patches/patch-aa b/graphics/gocr/patches/patch-aa
--- a/graphics/gocr/patches/patch-aa
+++ b/graphics/gocr/patches/patch-aa
@@ -1,18 +1,22 @@
-$NetBSD: patch-aa,v 1.1.1.1 2005/10/16 20:20:41 wiz Exp $
+$NetBSD: patch-aa,v 1.2 2005/10/25 02:06:57 wiz Exp $
 
---- configure.orig	2002-08-12 17:18:53.000000000 +0200
+--- configure.orig	2005-03-13 20:23:07.000000000 +0100
 +++ configure
-@@ -946,9 +946,11 @@ else
- fi
- 
- 
--CPPFLAGS=-I/usr/X11R6/include
-+#CPPFLAGS=-I/usr/X11R6/include
-+CPPFLAGS=
- #LDFLAGS="-L/usr/X11R6/lib -lpbm -lpgm -lppm -lpnm"
--LDFLAGS="-L/usr/X11R6/lib -L/usr/local/netpbm/lib"
-+#LDFLAGS="-L/usr/X11R6/lib -L/usr/local/netpbm/lib"
-+LDFLAGS=
- 
- ## pnm can only be found, if LDFLAGS contains -lpgm -lpnm ... etc. 
- ## is there a better solution ?
+@@ -2489,7 +2489,7 @@ fi
+ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+ if test "$ac_cv_search_pnm_readpnminit" = no; then
+   for ac_lib in netpbm pnm; do
+-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
++    LIBS="-l$ac_lib -lm $ac_func_search_save_LIBS"
+     cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+ /* confdefs.h.  */
+@@ -2525,7 +2525,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_search_pnm_readpnminit="-l$ac_lib"
++  ac_cv_search_pnm_readpnminit="-l$ac_lib -lm"
+ break
+ else
+   echo "$as_me: failed program was:" >&5
