Remove dependency on GIF libraries.  Nothing in kdebase links against giflib.

diff --git a/x11/kdebase/patches/patch-aa b/x11/kdebase/patches/patch-aa
--- a/x11/kdebase/patches/patch-aa
+++ b/x11/kdebase/patches/patch-aa
@@ -1,7 +1,7 @@
-$NetBSD: patch-aa,v 1.10 1999/06/05 15:07:23 tron Exp $
+$NetBSD: patch-aa,v 1.11 1999/10/09 20:23:55 jlam Exp $
 
---- configure.orig	Wed Apr 28 17:21:06 1999
-+++ configure	Fri Jun  4 00:56:50 1999
+--- configure.orig	Tue Sep  7 11:21:06 1999
++++ configure	Sat Oct  9 13:37:53 1999
 @@ -517,9 +517,9 @@
  # Prefer explicitly selected file to automatically selected ones.
  if test -z "$CONFIG_SITE"; then
@@ -14,7 +14,7 @@ $NetBSD: patch-aa,v 1.10 1999/06/05 15:07:23 tron Exp $
    fi
  fi
  for ac_site_file in $CONFIG_SITE; do
-@@ -3988,37 +3988,37 @@
+@@ -3994,37 +3994,37 @@
  if test "$ac_use_path_checking" = "default"; then
  
    if test -z "$kde_htmldir"; then
@@ -63,16 +63,16 @@ $NetBSD: patch-aa,v 1.10 1999/06/05 15:07:23 tron Exp $
    fi
    if test -z "$kde_bindir"; then
      kde_bindir='\$(exec_prefix)/bin'
-@@ -4817,7 +4817,7 @@
+@@ -4823,7 +4823,7 @@
    echo $ac_n "(cached) $ac_c" 1>&6
  else
    ac_save_LIBS="$LIBS"
 -LIBS="-lpam -ldl $LIBS"
 +LIBS="-lpam $LIBS"
  cat > conftest.$ac_ext <<EOF
- #line 4823 "configure"
+ #line 4829 "configure"
  #include "confdefs.h"
-@@ -4841,7 +4841,7 @@
+@@ -4847,7 +4847,7 @@
  fi
  if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
    echo "$ac_t""yes" 1>&6
@@ -81,3 +81,12 @@ $NetBSD: patch-aa,v 1.10 1999/06/05 15:07:23 tron Exp $
    cat >> confdefs.h <<EOF
  #define HAVE_PAM_LIB 1
  EOF
+@@ -5162,8 +5162,6 @@
+ #define HAVE_LIBGIF 1
+ EOF
+ 
+-else
+-  { echo "configure: error: You need giflib30. Please install the kdesupport package" 1>&2; exit 1; }
+ fi
+ 
+ echo $ac_n "checking for jpeglib""... $ac_c" 1>&6
