Update "kdebase" package to version 1.1.1.

diff --git a/x11/kdebase/patches/patch-aa b/x11/kdebase/patches/patch-aa
--- a/x11/kdebase/patches/patch-aa
+++ b/x11/kdebase/patches/patch-aa
@@ -1,8 +1,8 @@
-$NetBSD: patch-aa,v 1.8 1999/02/17 00:02:14 tron Exp $
+$NetBSD: patch-aa,v 1.9 1999/06/04 00:05:51 tron Exp $
 
---- configure.orig	Sat Feb  6 18:49:38 1999
-+++ configure	Wed Feb 17 00:23:05 1999
-@@ -516,9 +516,9 @@
+--- configure.orig	Wed Apr 28 17:21:06 1999
++++ configure	Fri Jun  4 00:56:50 1999
+@@ -517,9 +517,9 @@
  # Prefer explicitly selected file to automatically selected ones.
  if test -z "$CONFIG_SITE"; then
    if test "x$prefix" != xNONE; then
@@ -14,65 +14,65 @@ $NetBSD: patch-aa,v 1.8 1999/02/17 00:02:14 tron Exp $
    fi
  fi
  for ac_site_file in $CONFIG_SITE; do
-@@ -3921,37 +3921,37 @@
- echo "configure:3922: checking for KDE paths" >&5
+@@ -3988,37 +3988,37 @@
+ if test "$ac_use_path_checking" = "default"; then
  
    if test -z "$kde_htmldir"; then
--    kde_htmldir="\$(prefix)/share/doc/HTML"
-+    kde_htmldir="\$(prefix)/share/doc/kde/HTML"
+-    kde_htmldir='\$(prefix)/share/doc/HTML'
++    kde_htmldir='\$(prefix)/share/doc/kde/HTML'
    fi
    if test -z "$kde_appsdir"; then
--    kde_appsdir="\$(prefix)/share/applnk"
-+    kde_appsdir="\$(prefix)/share/kde/applnk"
+-    kde_appsdir='\$(prefix)/share/applnk'
++    kde_appsdir='\$(prefix)/share/kde/applnk'
    fi
    if test -z "$kde_icondir"; then
--    kde_icondir="\$(prefix)/share/icons"
-+    kde_icondir="\$(prefix)/share/kde/icons"
+-    kde_icondir='\$(prefix)/share/icons'
++    kde_icondir='\$(prefix)/share/kde/icons'
    fi
    if test -z "$kde_sounddir"; then
--    kde_sounddir="\$(prefix)/share/sounds"
-+    kde_sounddir="\$(prefix)/share/kde/sounds"
+-    kde_sounddir='\$(prefix)/share/sounds'
++    kde_sounddir='\$(prefix)/share/kde/sounds'
    fi
    if test -z "$kde_datadir"; then
--    kde_datadir="\$(prefix)/share/apps"
-+    kde_datadir="\$(prefix)/share/kde/apps"
+-    kde_datadir='\$(prefix)/share/apps'
++    kde_datadir='\$(prefix)/share/kde/apps'
    fi
    if test -z "$kde_locale"; then
--    kde_locale="\$(prefix)/share/locale"
-+    kde_locale="\$(prefix)/share/kde/locale"
+-    kde_locale='\$(prefix)/share/locale'
++    kde_locale='\$(prefix)/share/kde/locale'
    fi
    if test -z "$kde_cgidir"; then
--    kde_cgidir="\$(exec_prefix)/cgi-bin"
-+    kde_cgidir="\$(libexecdir)/kde-cgi-bin"
+-    kde_cgidir='\$(exec_prefix)/cgi-bin'
++    kde_cgidir='\$(libexecdir)/kde-cgi-bin'
    fi
    if test -z "$kde_confdir"; then
--    kde_confdir="\$(prefix)/share/config"
-+    kde_confdir="\$(prefix)/share/kde/config"
+-    kde_confdir='\$(prefix)/share/config'
++    kde_confdir='\$(prefix)/share/kde/config'
    fi
    if test -z "$kde_mimedir"; then
--    kde_mimedir="\$(prefix)/share/mimelnk"
-+    kde_mimedir="\$(prefix)/share/kde/mimelnk"
+-    kde_mimedir='\$(prefix)/share/mimelnk'
++    kde_mimedir='\$(prefix)/share/kde/mimelnk'
    fi
    if test -z "$kde_toolbardir"; then
--    kde_toolbardir="\$(prefix)/share/toolbar"
-+    kde_toolbardir="\$(prefix)/share/kde/toolbar"
+-    kde_toolbardir='\$(prefix)/share/toolbar'
++    kde_toolbardir='\$(prefix)/share/kde/toolbar'
    fi
    if test -z "$kde_wallpaperdir"; then
--    kde_wallpaperdir="\$(prefix)/share/wallpapers"
-+    kde_wallpaperdir="\$(prefix)/share/kde/wallpapers"
+-    kde_wallpaperdir='\$(prefix)/share/wallpapers'
++    kde_wallpaperdir='\$(prefix)/share/kde/wallpapers'
    fi
    if test -z "$kde_bindir"; then
-     kde_bindir="\$(exec_prefix)/bin"
-@@ -4730,7 +4730,7 @@
+     kde_bindir='\$(exec_prefix)/bin'
+@@ -4817,7 +4817,7 @@
    echo $ac_n "(cached) $ac_c" 1>&6
  else
    ac_save_LIBS="$LIBS"
 -LIBS="-lpam -ldl $LIBS"
 +LIBS="-lpam $LIBS"
  cat > conftest.$ac_ext <<EOF
- #line 4736 "configure"
+ #line 4823 "configure"
  #include "confdefs.h"
-@@ -4754,7 +4754,7 @@
+@@ -4841,7 +4841,7 @@
  fi
  if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
    echo "$ac_t""yes" 1>&6
@@ -81,18 +81,18 @@ $NetBSD: patch-aa,v 1.8 1999/02/17 00:02:14 tron Exp $
    cat >> confdefs.h <<EOF
  #define HAVE_PAM_LIB 1
  EOF
-@@ -4984,6 +4984,7 @@
+@@ -5072,6 +5072,7 @@
  
  
  
 +if false; then
  echo $ac_n "checking for giflib""... $ac_c" 1>&6
- echo "configure:4989: checking for giflib" >&5
+ echo "configure:5077: checking for giflib" >&5
  if eval "test \"`echo '$''{'ac_cv_lib_gif'+set}'`\" = set"; then
-@@ -5030,6 +5031,7 @@
+@@ -5118,6 +5119,7 @@
  
  else
-   { echo "configure: error: You need giflib23. Please install the kdesupport package" 1>&2; exit 1; }
+   { echo "configure: error: You need giflib30. Please install the kdesupport package" 1>&2; exit 1; }
 +fi
  fi
  
