Update to 0.40.14, integrating a patch from http://bugs.backtrace.info/view.php?id=505 for libsoup>=2.4 support.
Changes:
* gcc 4.3 support thanks to Siavash and Alexander Kahl
* spectrum analyser fixed (nenolog)
* many bug fixes

diff --git a/audio/bmpx/patches/patch-aa b/audio/bmpx/patches/patch-aa
--- a/audio/bmpx/patches/patch-aa
+++ b/audio/bmpx/patches/patch-aa
@@ -1,4 +1,4 @@
-$NetBSD: patch-aa,v 1.5 2007/11/01 22:49:15 tnn Exp $
+$NetBSD: patch-aa,v 1.6 2008/10/28 22:23:40 wiz Exp $
 
 --- configure.orig	2007-10-18 19:18:23.000000000 +0200
 +++ configure
@@ -11,3 +11,148 @@ $NetBSD: patch-aa,v 1.5 2007/11/01 22:49:15 tnn Exp $
  *GNU* | *'with BFD'*)
    LDFLAGS="$LDFLAGS -Wl,--as-needed"
    { echo "$as_me:$LINENO: result: yes" >&5
+@@ -31606,12 +31606,12 @@ echo $ECHO_N "checking for SOUP... $ECHO
+ 
+ if test -n "$PKG_CONFIG"; then
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libsoup-2.2 >= 2.2.100\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libsoup-2.2 >= 2.2.100") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libsoup-2.4 >= 2.3.0.1\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libsoup-2.4 >= 2.3.0.1") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_SOUP_CFLAGS=`$PKG_CONFIG --cflags "libsoup-2.2 >= 2.2.100" 2>/dev/null`
++  pkg_cv_SOUP_CFLAGS=`$PKG_CONFIG --cflags "libsoup-2.4 >= 2.3.0.1" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -31620,12 +31620,12 @@ else
+ fi
+ if test -n "$PKG_CONFIG"; then
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libsoup-2.2 >= 2.2.100\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libsoup-2.2 >= 2.2.100") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libsoup-2.4 >= 2.3.0.1\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libsoup-2.4 >= 2.3.0.1") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_SOUP_LIBS=`$PKG_CONFIG --libs "libsoup-2.2 >= 2.2.100" 2>/dev/null`
++  pkg_cv_SOUP_LIBS=`$PKG_CONFIG --libs "libsoup-2.4 >= 2.3.0.1" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -31634,18 +31634,18 @@ else
+ fi
+ 
+ if test $pkg_failed = yes; then
+-	SOUP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libsoup-2.2 >= 2.2.100"`
++	SOUP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libsoup-2.4 >= 2.3.0.1"`
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$SOUP_PKG_ERRORS" 1>&5
+ 
+-	{ { echo "$as_me:$LINENO: error: Package requirements (libsoup-2.2 >= 2.2.100) were not met.
++	{ { echo "$as_me:$LINENO: error: Package requirements (libsoup-2.4 >= 2.3.0.1) were not met.
+ Consider adjusting the PKG_CONFIG_PATH environment variable if you
+ installed software in a non-standard prefix.
+ 
+ Alternatively you may set the SOUP_CFLAGS and SOUP_LIBS environment variables
+ to avoid the need to call pkg-config.  See the pkg-config man page for
+ more details." >&5
+-echo "$as_me: error: Package requirements (libsoup-2.2 >= 2.2.100) were not met.
++echo "$as_me: error: Package requirements (libsoup-2.4 >= 2.3.0.1) were not met.
+ Consider adjusting the PKG_CONFIG_PATH environment variable if you
+ installed software in a non-standard prefix.
+ 
+@@ -31683,90 +31683,6 @@ echo "${ECHO_T}yes" >&6; }
+ 	:
+ fi
+ 
+-	CPPFLAGS_SAVED="$CPPFLAGS"
+-	CPPFLAGS="$CPPFLAGS $SOUP_CFLAGS"
+-	export CPPFLAGS
+-
+-	LDFLAGS_SAVED="$LDFLAGS"
+-	LDFLAGS="$LDFLAGS $SOUP_LDFLAGS"
+-	export LDFLAGS
+-
+-	{ echo "$as_me:$LINENO: checking for extern in libsoup headers" >&5
+-echo $ECHO_N "checking for extern in libsoup headers... $ECHO_C" >&6; }
+-
+-	ac_ext=cpp
+-ac_cpp='$CXXCPP $CPPFLAGS'
+-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+-
+-	cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-
+-	#include <libsoup/soup.h>
+-
+-int
+-main ()
+-{
+-
+-	SoupSession * session = soup_session_sync_new ();
+-
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext
+-if { (ac_try="$ac_compile"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_compile") 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && {
+-	 test -z "$ac_cxx_werror_flag" ||
+-	 test ! -s conftest.err
+-       } && test -s conftest.$ac_objext; then
+-
+-	{ echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6; }
+-
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-
+-	{ echo "$as_me:$LINENO: result: yes" >&5
+-echo "${ECHO_T}yes" >&6; }
+-
+-cat >>confdefs.h <<\_ACEOF
+-#define LIBSOUP_HAS_EXTERN_C
+-_ACEOF
+-
+-
+-fi
+-
+-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+-	ac_ext=cpp
+-ac_cpp='$CXXCPP $CPPFLAGS'
+-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+-
+-
+-	CPPFLAGS="$CPPFLAGS_SAVED"
+-	LDFLAGS="$LDFLAGS_SAVED"
+-
+-
+ # sqlite
+ 
+ pkg_failed=no
