update to 0.5.6 New features include automatic handling of separate subtitles files, DVD title/chapter display, and improved playlist item management and creation. There are some small but potentially useful Javascript additions too, and quite a few small tweaks and fixes

diff --git a/multimedia/gxine/patches/patch-ak b/multimedia/gxine/patches/patch-ak
--- a/multimedia/gxine/patches/patch-ak
+++ b/multimedia/gxine/patches/patch-ak
@@ -1,14 +1,12 @@
-$NetBSD: patch-ak,v 1.3 2006/03/13 17:31:00 joerg Exp $
+$NetBSD: patch-ak,v 1.4 2006/05/03 12:47:47 drochner Exp $
 
---- configure.orig	2006-03-13 15:53:42.000000000 +0000
+--- configure.orig	2006-03-16 18:38:37.000000000 +0100
 +++ configure
-@@ -25003,6 +25003,9 @@ case $host in
-     CPPFLAGS="$CPPFLAGS -I/usr/local/include"
-     LDFLAGS="$LDFLAGS -L/usr/local/lib"
-     ;;
-+  *-*-dragonfly*)
-+    THREAD_LIBS="-pthread"
-+    ;;
-   *)
-     echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
- echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
+@@ -24585,6 +24585,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+   ac_cv_lib_Xinerama_XineramaQueryExtension=yes
++  X_EXTRA_LIBS="-lXinerama $X_EXTRA_LIBS"
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
