Some bugfixes and improvements from both Tomasz Luchowski <zuntum@eik.pl> and myself. Patch contributed in private mail.

diff --git a/pkgtools/pkgdiff/files/pkgvi b/pkgtools/pkgdiff/files/pkgvi
--- a/pkgtools/pkgdiff/files/pkgvi
+++ b/pkgtools/pkgdiff/files/pkgvi
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: pkgvi,v 1.2 2001/01/18 15:40:23 jlam Exp $
+# $NetBSD: pkgvi,v 1.3 2001/01/18 17:04:21 hubertf Exp $
 #
 # Copyright (c) 2001 Tomasz Luchowski. All rights reserved.
 #
@@ -31,19 +31,6 @@
 # SUCH DAMAGE.
 #
 
-#
-# Usage: pkgvi file
-#
-# The pkgvi utility runs user's favourite editor (it uses $PKG_EDITOR if
-# defined, then it looks for $EDITOR, if none is defined, it uses vi) on
-# copy of specified file. If no changes are made in the editor, nothing
-# happens, else original file is stored as $filename.orig, and modified
-# file is saved as $filename. If it founds $filename.orig, it behaves as
-# normal editor.
-#
-#  - Tomasz Luchowski <zuntum@eik.pl>
-#
-
 if [ "$PKGEDITOR" != "" ]; then
 	editor="$PKGEDITOR"
 elif [ "$EDITOR" != "" ]; then
@@ -72,28 +59,33 @@ fi
 if [ -f $file.orig ]
 then
 	$editor $file
-	echo "$progname: Backup already exists, for a diff type:"
+	echo "$progname: Backup already exists. For a diff type:"
         echo "pkgdiff $file"
 	exit 0
 fi
 
 tmp="$file.$$"
 
-cp $file $tmp
+cp "$file" "$tmp"
 
-$editor $tmp
-
-if cmp $file $tmp 2>&1 >/dev/null
-then
-	echo File unchanged.
-else
-	mv $file $file.orig
-	mv $tmp $file
-	echo $progname: File was modified. For a diff, type:
-	echo pkgdiff $file
+if [ $? -ne 0 ]; then
+	echo "$progname: unable to create temporary file"
+	exit 1
 fi
 
-if [ -f $tmp ]
+$editor "$tmp"
+
+if cmp "$file" "$tmp" 2>&1 >/dev/null
 then
-	rm $tmp
+	echo "$progname: File unchanged."
+else
+	mv "$file" "$file.orig"
+	mv "$tmp" "$file"
+	echo "$progname: File was modified. For a diff, type:"
+	echo "pkgdiff $file"
+fi
+
+if [ -f "$tmp" ]
+then
+	rm "$tmp"
 fi
