-libxml2 in bl3'd, so it should be used -- help "configure" finding it. -While the program is prepared to work w/o libxml2 (with some loss of  functionality), there is a little glitch -- see PR pkg/38446 by  Keith Waclena. The fix shouldn't be needed for pkgsrc anymore because  libxml2 should be found now, but add it anyway. bump PKGREVISION

diff --git a/fonts/fontforge/patches/patch-ae b/fonts/fontforge/patches/patch-ae
--- a/fonts/fontforge/patches/patch-ae
+++ b/fonts/fontforge/patches/patch-ae
@@ -1,7 +1,36 @@
-$NetBSD: patch-ae,v 1.13 2008/06/22 18:30:54 adam Exp $
+$NetBSD: patch-ae,v 1.14 2008/06/23 11:38:51 drochner Exp $
 
 --- configure.orig	2008-05-05 17:07:18.000000000 +0200
 +++ configure
+@@ -19201,8 +19201,8 @@ if test $ac_cv_file__usr_include_libxml2
+   CFLAGS="$CFLAGS -I/usr/include/libxml2/"
+ else
+ 
+- echo "$as_me:$LINENO: checking for /usr/local/include/libxml2/libxml" >&5
+-echo $ECHO_N "checking for /usr/local/include/libxml2/libxml... $ECHO_C" >&6
++ echo "$as_me:$LINENO: checking for ${LOCALBASE}/include/libxml2/libxml" >&5
++echo $ECHO_N "checking for ${LOCALBASE}/include/libxml2/libxml... $ECHO_C" >&6
+ if test "${ac_cv_file__usr_local_include_libxml2_libxml+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+@@ -19210,7 +19210,7 @@ else
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+    { (exit 1); exit 1; }; }
+-if test -r "/usr/local/include/libxml2/libxml"; then
++if test -r "${LOCALBASE}/include/libxml2/libxml"; then
+   ac_cv_file__usr_local_include_libxml2_libxml=yes
+ else
+   ac_cv_file__usr_local_include_libxml2_libxml=no
+@@ -19219,7 +19219,7 @@ fi
+ echo "$as_me:$LINENO: result: $ac_cv_file__usr_local_include_libxml2_libxml" >&5
+ echo "${ECHO_T}$ac_cv_file__usr_local_include_libxml2_libxml" >&6
+ if test $ac_cv_file__usr_local_include_libxml2_libxml = yes; then
+-  CFLAGS="$CFLAGS -I/usr/local/include -I/usr/local/include/libxml2/"
++  CFLAGS="$CFLAGS -I${LOCALBASE}/include -I${LOCALBASE}/include/libxml2/"
+ else
+   cat >>confdefs.h <<\_ACEOF
+ #define _NO_LIBXML 1
 @@ -22082,7 +22082,7 @@ fi
  
  # Standard set of common directories for X headers.
