Update to mpich2-1.0.7. From pkgsrc-wip, contributed by Aleksej Saushev.
MPICH2 is an all-new implementation of MPI from the group at Argonne
National Laboratory.  It shares many goals with the original MPICH but
no actual code.  It is a portable, high-performance implementation of
the entire MPI-2 standard.  This release has all MPI-2 functions and
features required by the standard with the exception of support for the
"external32" portable I/O format.

diff --git a/parallel/mpi-ch/patches/patch-ad b/parallel/mpi-ch/patches/patch-ad
--- a/parallel/mpi-ch/patches/patch-ad
+++ b/parallel/mpi-ch/patches/patch-ad
@@ -1,12 +1,15 @@
-$NetBSD: patch-ad,v 1.3 2006/03/14 01:10:49 joerg Exp $
+$NetBSD: patch-ad,v 1.4 2008/05/29 20:25:54 tnn Exp $
 
---- mpid/server/serv_p4.c.orig	2006-03-14 00:20:07.000000000 +0000
-+++ mpid/server/serv_p4.c
-@@ -170,7 +170,6 @@ extern char *crypt();
- extern char *sys_errlist[];
- #define strerror(n) sys_errlist[n]
- #endif
--extern int errno;
+"test ==" portability fix.
+
+--- configure.orig	Thu May 15 12:20:15 2008
++++ configure	Thu May 15 12:26:13 2008
+@@ -30782,7 +30782,7 @@
+ 	    ;;
+     esac
  
- char tmpbuf[1024];
- char *fromhost;
+-    if test "$cpu_gcc_x86_cycle" == "no" ; then
++    if test "$cpu_gcc_x86_cycle" = "no" ; then
+         { { echo "$as_me:$LINENO: error: Linux86 cycle counter is not available on this system and or with the $CC compiler" >&5
+ echo "$as_me: error: Linux86 cycle counter is not available on this system and or with the $CC compiler" >&2;}
+    { (exit 1); exit 1; }; }
