Update www/squid pacakge to 2.6.3 (squid 2.6.STABLE3).
Too may changes to mention here.
Please refer ${PREFIX}/share/doc/squid/RELEASENOTES.html.

diff --git a/www/squid/patches/patch-ag b/www/squid/patches/patch-ag
--- a/www/squid/patches/patch-ag
+++ b/www/squid/patches/patch-ag
@@ -1,92 +1,135 @@
-$NetBSD: patch-ag,v 1.23 2005/10/23 22:32:32 taca Exp $
+$NetBSD: patch-ag,v 1.24 2006/09/13 14:41:58 taca Exp $
 
---- configure.orig	2005-10-22 18:56:01.000000000 +0900
+--- configure.orig	2006-07-31 11:53:51.000000000 +0900
 +++ configure
-@@ -2249,7 +2238,7 @@ if test "${enable_snmp+set}" = set; then
+@@ -3970,7 +3970,7 @@ cat >>confdefs.h <<\_ACEOF
  #define SQUID_SNMP 1
- EOF
+ _ACEOF
  
 -    SNMPLIB='-L../snmplib -lsnmp'
 +    SNMPLIB='../snmplib/libsnmp.a'
-     
+ 
  
  if true; then
-@@ -4070,6 +4059,7 @@ for ac_hdr in \
+@@ -7057,6 +7057,7 @@ for ac_header in sys/types.h \
  	libc.h \
- 	limits.h \
  	linux/netfilter_ipv4.h \
+ 	linux/netfilter_ipv4/ip_tproxy.h \
 + 	machine/byte_swap.h \
  	malloc.h \
  	math.h \
  	memory.h \
-@@ -6317,47 +6307,45 @@ fi
- echo "$ac_t""$ac_cv_type_mode_t" 1>&6
- if test $ac_cv_type_mode_t = no; then
-   cat >> confdefs.h <<\EOF
--#define mode_t u_short
-+#define mode_t unsigned short
- EOF
+@@ -13512,9 +13513,9 @@ _ACEOF
  
  fi
  
--echo $ac_n "checking for fd_mask""... $ac_c" 1>&6
--echo "configure:6327: checking for fd_mask" >&5
--if eval "test \"`echo '$''{'ac_cv_type_fd_mask'+set}'`\" = set"; then
-+
-+echo $ac_n "checking for fd_set""... $ac_c" 1>&6
-+echo "configure:6318: checking for fd_set" >&5
-+if eval "test \"`echo '$''{'ac_cv_have_fd_mask'+set}'`\" = set"; then
-   echo $ac_n "(cached) $ac_c" 1>&6
+-echo "$as_me:$LINENO: checking for fd_mask" >&5
+-echo $ECHO_N "checking for fd_mask... $ECHO_C" >&6
+-if test "${ac_cv_type_fd_mask+set}" = set; then
++{ echo "$as_me:$LINENO: checking for fd_set" >&5
++echo $ECHO_N "checking for fd_set... $ECHO_C" >&6; }
++if test "${ac_cv_have_fd_mask+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
  else
-+  
-   cat > conftest.$ac_ext <<EOF
--#line 6332 "configure"
-+#line 6324 "configure"
- #include "confdefs.h"
- #include <sys/types.h>
+   cat >conftest.$ac_ext <<_ACEOF
+@@ -13523,46 +13524,64 @@ _ACEOF
+ cat confdefs.h >>conftest.$ac_ext
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+-
+-/* What a mess.. many systems have added the (now standard) bit types
+- * in their own ways, so we need to scan a wide variety of headers to
+- * find them..
+- */
+-#include <sys/types.h>
 -#if STDC_HEADERS
 -#include <stdlib.h>
 -#include <stddef.h>
 -#endif
+-#if HAVE_INTTYPES_H
+-#include <inttypes.h>
+-#endif
+-#if HAVE_SYS_TYPES_H
+ #include <sys/types.h>
+-#endif
+-#if HAVE_SYS_BITYPES_H
+-#include <sys/bitypes.h>
+-#endif
+-
 +#include <sys/time.h>
 +#include <sys/unistd.h>
-+int main() {
++int
++main ()
++{
 +fd_mask fds;
-+; return 0; }
- EOF
++  ;
++  return 0;
++}
+ _ACEOF
 -if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
--  egrep "(^|[^a-zA-Z_0-9])fd_mask[^a-zA-Z_0-9]" >/dev/null 2>&1; then
-+if { (eval echo configure:6333: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
-   rm -rf conftest*
+-  $EGREP "(^|[^a-zA-Z_0-9])fd_mask[^a-zA-Z_0-9]" >/dev/null 2>&1; then
 -  ac_cv_type_fd_mask=yes
++rm -f conftest.$ac_objext
++if { (ac_try="$ac_compile"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_compile") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
++  { (case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_try") 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest.$ac_objext'
++  { (case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_try") 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
 +  ac_cv_have_fd_mask="yes"
  else
-+  echo "configure: failed program was:" >&5
-+  cat conftest.$ac_ext >&5
-   rm -rf conftest*
 -  ac_cv_type_fd_mask=no
-+  ac_cv_have_fd_mask="no"
- fi
- rm -f conftest*
- 
- fi
--echo "$ac_t""$ac_cv_type_fd_mask" 1>&6
--if test $ac_cv_type_fd_mask = no; then
--  cat >> confdefs.h <<\EOF
--#define fd_mask int
--EOF
--
 -fi
+-rm -f conftest*
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
  
-+echo "$ac_t""$ac_cv_have_fd_mask" 1>&6
++	ac_cv_have_fd_mask="no"
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_type_fd_mask" >&5
+-echo "${ECHO_T}$ac_cv_type_fd_mask" >&6
+-if test $ac_cv_type_fd_mask = no; then
  
- echo $ac_n "checking size of off_t""... $ac_c" 1>&6
--echo "configure:6361: checking size of off_t" >&5
-+echo "configure:6349: checking size of off_t" >&5
- if eval "test \"`echo '$''{'ac_cv_sizeof_off_t'+set}'`\" = set"; then
-   echo $ac_n "(cached) $ac_c" 1>&6
- else
-@@ -7669,8 +7657,8 @@ if test "$GCC" = "yes"; then
+-cat >>confdefs.h <<\_ACEOF
+-#define fd_mask int
+-_ACEOF
++rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+ 
+ fi
+-
++{ echo "$as_me:$LINENO: result: $ac_cv_have_fd_mask" >&5
++echo "${ECHO_T}$ac_cv_have_fd_mask" >&6; }
+ 
+ echo "$as_me:$LINENO: checking size of off_t" >&5
+ echo $ECHO_N "checking size of off_t... $ECHO_C" >&6
+@@ -15530,8 +15549,8 @@ if test "$GCC" = "yes"; then
  	GCCVER=`$CC -v 2>&1 | awk '$2 ==  "version" {print $3}'`
  	case "$GCCVER" in
  	2.95.[123])
