further cleanup of handling the .broken.files and .make.files
- set BROKENF and BLDLOG in the 'build' script and pass those variables
  down to {pre,post}-build in the environment to make sure we only set them
  in one place.  The values are determined by a
      make show-var VARNAME=BROKENFILE
  This causes the default (set in bsd.bulk-pkg.mk) or the user overridden
  value from /etc/mk.conf or the environment to be correctly determined.  This
  is more robust that relying on a build.conf setting which may or may not be
  correctly set.

- have pre-build only clean up BROKENF and BLDLOG files instead of
  .broken* and .make*
  This avoids conflicts when pkgsrc is shared among different machines.

diff --git a/mk/bulk/pre-build b/mk/bulk/pre-build
--- a/mk/bulk/pre-build
+++ b/mk/bulk/pre-build
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: pre-build,v 1.7 2000/12/22 01:35:33 dmcmahill Exp $
+# $NetBSD: pre-build,v 1.8 2000/12/30 14:53:28 dmcmahill Exp $
 #
 # Clean up system to be ready for bulk pkg build
 #
@@ -16,6 +16,17 @@ else
 fi
 
 PRUNEDISTFILES=${PRUNEDISTFILES:-"yes"}
+
+if [ "$BROKENF" = "" ]; then
+        echo "Error:  BROKENF must be set to the name of the .broken.files"
+        echo "        This should have happened in the top level build script"
+	exit 1
+fi
+if [ "$BLDLOG" = "" ]; then
+        echo "Error:  BLDLOG must be set to the name of the .make.files"
+        echo "        This should have happened in the top level build script"
+	exit 1
+fi
 
 #
 # Install cvs package and do a cvs update here
@@ -89,8 +100,8 @@ rm -fr /nonexistant		# broken useradd on pop3d
 
 # Clean up state files
 cd ${USR_PKGSRC}
-rm -f .broken* */*/.broken*
-rm -f .make* */*/.make*
+rm -f $BROKENF */*/$BROKENF
+rm -f $BLDLOG */*/$BLDLOG
 rm -f .start*
 
 mount -o noasync -u /usr
