- Moved the "man page" comment into a real man page. - Added more sanity checks.

diff --git a/mk/bulk/printindex b/mk/bulk/printindex
--- a/mk/bulk/printindex
+++ b/mk/bulk/printindex
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: printindex,v 1.25 2005/11/16 22:11:11 rillig Exp $
+# $NetBSD: printindex,v 1.26 2005/11/19 10:55:45 rillig Exp $
 #
 
 # Copyright (c) 2001 The NetBSD Foundation, Inc.
@@ -36,23 +36,6 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 #
-
-# usage: printindex [brokenfile [bulkfilesdir]]
-#
-# Generates a mapping from pkgsrc directories to the current package
-# version and prints it on stdout. Each line of the output has two
-# fields: the package directory (in the form category/package) and the
-# package version (in the form package-1.456nb3).
-#
-# If <brokenfile> is given, package-specific errors are logged to
-# <bulkfilesdir>/${pkgdir}/<brokenfile>. Otherwise no additional logging
-# takes place.
-#
-# The default for <bulkfilesdir> is the pkgsrc directory itself. If
-# <bulkfilesdir> differs from the pkgsrc directory, all directories
-# that are needed for the log files are created automatically.
-#
-# Note: printindex must be called from a pkgsrc root directory.
 
 set -e
 
@@ -130,6 +113,22 @@ else
 	# fall back to all packages.
 	list=`${GREP} '^[[:space:]]*'SUBDIR */Makefile | ${SED} 's,/Makefile.*=[[:space:]]*,/,'`
 fi
+
+#
+# Sanity checks, part 2
+#
+
+case $BULK_PREREQ in
+*[!-\ +./0-9A-Z_a-z]*)
+	echo "$0: error: BULK_PREREQ contains invalid characters. (Its value is \"${BULK_PREREQ}\".)" 1>&2
+	exit 1
+esac
+case $list in
+*[!-\ +./0-9A-Z_a-z]*)
+	echo "$0: error: The package list contains invalid characters. (Its value is \"${list}\".)" 1>&2
+	echo "$list" | tr ' ' '\n' > .list
+	exit 1
+esac
 
 #
 # Print the table of PKGPATH and PKGNAME.
