add some more failure checks for robustness.
- if something fails while extracting the DEPENDS for a particular package,
  mark that package as broken and drop the DEPENDS info for it.  This allows
  the build to continue and properly marks the package as broken.

- if something fails while extracting the PKGNAME, also mark the pkg as broken.

- be more careful about seeing if directories exist before cd'ing to them.
  Lack of such a test has caused problems elsewhere, so hopefully this will
  make the system more robust.

diff --git a/mk/bulk/printindex b/mk/bulk/printindex
--- a/mk/bulk/printindex
+++ b/mk/bulk/printindex
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: printindex,v 1.5 2001/07/13 15:14:57 dmcmahill Exp $
+# $NetBSD: printindex,v 1.6 2001/10/14 20:34:53 dmcmahill Exp $
 #
 #
 # Copyright (c) 2001 The NetBSD Foundation, Inc.
@@ -38,7 +38,8 @@
 #
 
 
-# Generate package index.
+# Generate package index.  If an argument is given, use it as a file name
+# to contain any failure messages in each package directory.
 #
 # generates a pkgsrc directory <-> package name database.  eg.
 #              foo/bar  bar-2.0
@@ -46,6 +47,12 @@
 #
 # Start in /usr/pkgsrc.
 #
+
+if [ ! -z "$1" ]; then
+	brokenfile=$1
+else
+	brokenfile=/dev/null
+fi
 
 # /usr/pkgsrc
 cwd=$PWD
@@ -63,6 +70,12 @@ do
 	else
 		cd $pkgdir
 		pkgname=`make show-var VARNAME=PKGNAME`
+		if [ $? != 0 ]; then
+			echo "ERROR: printindex could not extract PKNAME for $pkgdir" > /dev/stderr
+			echo "make show-var VARNAME=PKGNAME failed" > $brokenfile
+			make show-var VARNAME=PKGNAME >> $brokenfile 2>&1
+			exit 1
+		fi
 		echo "$pkgdir          $pkgname "
 	fi
 	cd $cwd 
@@ -85,6 +98,12 @@ do
 		*)
 			cd $cwd/$pkgdir
 			pkgname=`make show-var VARNAME=PKGNAME`
+			if [ $? != 0 ]; then
+				echo "ERROR: printindex could not extract PKNAME for $pkgdir" > /dev/stderr
+				echo "make show-var VARNAME=PKGNAME failed" > $brokenfile
+				make show-var VARNAME=PKGNAME >> $brokenfile 2>&1
+				exit 1
+			fi
 			echo "$pkgdir          $pkgname "
 			cd $cwd 
 			;;
