when saving the rsync script for later, be sure and save the starting directory too.

diff --git a/mk/bulk/upload b/mk/bulk/upload
--- a/mk/bulk/upload
+++ b/mk/bulk/upload
@@ -69,6 +69,8 @@ echo "Uploading OSVERSION_SPECIFIC pkgs"
 cmd="rsync $RSFLAGS --include '*/' --exclude-from=$exf --include-from=$osf \
 	--exclude '*' . $RSYNC_DST_SPECIFIC"
 echo "#!/bin/sh" > $upload_specific
+echo "packages=$packages" >> $upload_specific
+echo "cd $packages || (echo \"could not cd to $packages\" ; exit 1)" >> $upload_specific
 echo $cmd >> $upload_specific
 chmod 755 $upload_specific
 echo $cmd
@@ -86,6 +88,8 @@ fi
 echo "Uploading non-OSVERSION_SPECIFIC pkgs"
 cmd="rsync $RSFLAGS --exclude-from=$exf --exclude-from=$osf . $RSYNC_DST_OTHER"
 echo "#!/bin/sh" > $upload_others
+echo "packages=$packages" >> $upload_others
+echo "cd $packages || (echo \"could not cd to $packages\" ; exit 1)" >> $upload_others
 echo $cmd >> $upload_others
 chmod 755 $upload_others
 echo $cmd
