Fixed an invalid use of backticks.

diff --git a/multimedia/gnash/patches/patch-aa b/multimedia/gnash/patches/patch-aa
--- a/multimedia/gnash/patches/patch-aa
+++ b/multimedia/gnash/patches/patch-aa
@@ -1,7 +1,10 @@
-$NetBSD: patch-aa,v 1.3 2006/12/06 00:26:10 wiz Exp $
+$NetBSD: patch-aa,v 1.4 2006/12/07 00:27:06 rillig Exp $
+
+* Fixed "test ==".
+* Fixed an invalid use of backticks (line 26598).
 
 --- configure.orig	2006-11-17 20:09:10.000000000 +0100
-+++ configure	2006-12-06 00:22:10.000000000 +0100
++++ configure	2006-12-07 01:23:40.000000000 +0100
 @@ -4303,13 +4303,13 @@
    LIBPRE="lib"
  
@@ -88,6 +91,15 @@ $NetBSD: patch-aa,v 1.3 2006/12/06 00:26:10 wiz Exp $
    fi
    if test -z "$xdg_appsdir"; then
      xdg_appsdir='\${datadir}/applications/kde'
+@@ -26598,7 +26598,7 @@
+     if test x"${with_atk_lib}" != x ; then
+       libname=atkatk-x11-${gnash_atk_version}
+       if test -f ${with_atk_lib}/lib${libname}.a -o -f ${with_atk_lib}/lib${libname}.so; then
+-        ac_cv_path_atk_lib="`-L(cd ${with_atk_lib}; pwd)` -l${libname}"
++        ac_cv_path_atk_lib="-L`cd ${with_atk_lib}; pwd` -l${libname}"
+       else
+         { { echo "$as_me:$LINENO: error: ${with_atk_lib} directory doesn't contain libatkatk." >&5
+ echo "$as_me: error: ${with_atk_lib} directory doesn't contain libatkatk." >&2;}
 @@ -45388,7 +45388,7 @@
  
  
