Upgrade to version 0.5.15 from 0.5.13nb1 of the ORBit package - diffs provided by Thomas Klausner.
Diffs from previous version:

2002-03-20  Michael Meeks  <michael@ximian.com>
        * configure.in: copy the autoconf macro into here so we
        can rely on it not changing across autoconf versions.
2002-03-11  Michael Meeks  <michael@ximian.com>
        * src/IIOP/giop-msg-buffer.c
        kill #define writev mess.
        (giop_send_buffer_write): handle EINTR, handle EAGAIN
        correctly, handle short writev's correctly, test
        thorougly.
        * src/ORBitutil/compat.c (g_writev): kill this
        abomination.
2002-02-11  Sebastian Wilhelmi  <wilhelmi@ira.uka.de>
        * src/orb/allocators.h, src/orb/allocators.c (ORBit_alloc_2,
        ORBit_free): Make the free marker really always sit directly in
        front of the memory block, not at some random lower position.
2002-02-09 Elliot Lee <sopwith@redhat.com>
        * src/ORBitutil/os-feature-alloca.h: Don't redefine alloca if it is already defined.
2002-01-27  Darin Adler  <darin@bentspoon.com>
        * test/everything/Makefile.am: Added -lm -- can't build without it.
2002-01-25  Mark McLoughlin  <mark@skynet.ie>
        * configure.in: (AC_CHECK_ALIGNOF): error out if an alignment
        is found to be zero.

Thomas thought that the modification to src/IIOP/giop-msg-buffer.c to
"kill #define writev mess" might mean that we could drop the
NetBSD-specific wrapper for writev(2), but sadly this isn't so -
configure undefines HAVE_LIMITED_WRITEV on NetBSD, and rightly so,
since IOV_MAX (1024) iovecs can be written, not 50.  However, we still
have the basic "attempt to send more than IOV_MAX iovecs and you get
EINVAL" problem with our writev(2) implementation.

diff --git a/net/ORBit/patches/patch-aa b/net/ORBit/patches/patch-aa
--- a/net/ORBit/patches/patch-aa
+++ b/net/ORBit/patches/patch-aa
@@ -1,18 +1,23 @@
-$NetBSD: patch-aa,v 1.10 2002/01/15 23:52:11 rh Exp $
+$NetBSD: patch-aa,v 1.11 2002/04/25 12:17:05 agc Exp $
 
---- popt/configure.orig	Mon Jan  7 19:10:01 2002
+--- popt/configure.orig	Wed Mar 20 15:45:04 2002
 +++ popt/configure
-@@ -2277,13 +2277,6 @@
- 	echo "$ac_t""no" 1>&6
+@@ -7298,18 +7298,6 @@
+ echo "${ECHO_T}no" >&6
  fi
  
--echo $ac_n "checking for GNU xgettext""... $ac_c" 1>&6
--echo "configure:2282: checking for GNU xgettext" >&5
--xgettext --version 2>&1 | grep 'GNU gettext' >/dev/null 2>&1 || { echo "configure: error: 
+-echo "$as_me:7301: checking for GNU xgettext" >&5
+-echo $ECHO_N "checking for GNU xgettext... $ECHO_C" >&6
+-xgettext --version 2>&1 | grep 'GNU gettext' >/dev/null 2>&1 || { { echo "$as_me:7303: error:
 -*** GNU gettext is required. The latest version
--*** is always available from ftp://ftp.gnu.org/gnu/gettext/." 1>&2; exit 1; }
--echo "$ac_t""yes" 1>&6
+-*** is always available from ftp://ftp.gnu.org/gnu/gettext/." >&5
+-echo "$as_me: error:
+-*** GNU gettext is required. The latest version
+-*** is always available from ftp://ftp.gnu.org/gnu/gettext/." >&2;}
+-   { (exit 1); exit 1; }; }
+-echo "$as_me:7310: result: yes" >&5
+-echo "${ECHO_T}yes" >&6
 -
  for ac_func in strerror mtrace
  do
- echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
+ as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
