Make this package build on NetBSD ports that do not have <machine/joystick.h>.

diff --git a/devel/SDL/patches/patch-am b/devel/SDL/patches/patch-am
--- a/devel/SDL/patches/patch-am
+++ b/devel/SDL/patches/patch-am
@@ -1,8 +1,8 @@
-$NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
+$NetBSD: patch-am,v 1.14 2004/07/13 20:51:58 kristerw Exp $
 
---- configure.orig	2004-02-22 13:32:33.000000000 -0800
-+++ configure	2004-04-10 16:06:11.000000000 -0700
-@@ -463,7 +463,7 @@ ac_includes_default="\
+--- configure.orig	Sun Feb 22 22:32:33 2004
++++ configure	Tue Jul 13 22:33:55 2004
+@@ -463,7 +463,7 @@
  # include <unistd.h>
  #endif"
  
@@ -11,7 +11,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  ac_subst_files=''
  
  # Initialize some variables set by options.
-@@ -1587,9 +1587,9 @@ SDL_VERSION=$SDL_MAJOR_VERSION.$SDL_MINO
+@@ -1587,9 +1587,9 @@
  
  # libtool versioning
  LT_RELEASE=$SDL_MAJOR_VERSION.$SDL_MINOR_VERSION
@@ -24,7 +24,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  
  
  
-@@ -21563,6 +21563,8 @@ rm -f conftest.err conftest.$ac_objext c
+@@ -21563,6 +21563,8 @@
  echo "${ECHO_T}$have_oss" >&6
          if test x$have_oss = xyes; then
              CFLAGS="$CFLAGS -DOSS_SUPPORT"
@@ -33,7 +33,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
              AUDIO_SUBDIRS="$AUDIO_SUBDIRS dsp"
              AUDIO_DRIVERS="$AUDIO_DRIVERS dsp/libaudio_dsp.la"
              AUDIO_SUBDIRS="$AUDIO_SUBDIRS dma"
-@@ -22262,9 +22264,9 @@ fi;
+@@ -22262,9 +22264,9 @@
          echo "$as_me:$LINENO: checking for NAS audio support" >&5
  echo $ECHO_N "checking for NAS audio support... $ECHO_C" >&6
          have_nas=no
@@ -45,7 +45,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
              SYSTEM_LIBS="$SYSTEM_LIBS -laudio -lXt"
              AUDIO_SUBDIRS="$AUDIO_SUBDIRS nas"
              AUDIO_DRIVERS="$AUDIO_DRIVERS nas/libaudio_nas.la"
-@@ -22530,7 +22532,7 @@ fi
+@@ -22530,7 +22532,7 @@
                    NASMFLAGS="-f aoutb"
                    ;;
                *)
@@ -54,7 +54,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
                    ;;
              esac
  
-@@ -25053,63 +25055,58 @@ else
+@@ -25053,63 +25055,58 @@
    enable_video_aalib=no
  fi;
      if test x$enable_video = xyes -a x$enable_video_aalib = xyes; then
@@ -162,7 +162,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  
              VIDEO_SUBDIRS="$VIDEO_SUBDIRS aalib"
              VIDEO_DRIVERS="$VIDEO_DRIVERS aalib/libvideo_aa.la"
-@@ -25837,16 +25834,17 @@ else
+@@ -25837,16 +25834,17 @@
    enable_pth=yes
  fi;
      if test x$enable_threads = xyes -a x$enable_pth = xyes; then
@@ -185,7 +185,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
    ;;
    *)
    as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-@@ -25856,32 +25854,32 @@ do
+@@ -25856,32 +25854,32 @@
    test -z "$as_dir" && as_dir=.
    for ac_exec_ext in '' $ac_executable_extensions; do
    if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
@@ -227,7 +227,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
              SDL_CFLAGS="$SDL_CFLAGS $PTH_CFLAGS"
              SDL_LIBS="$SDL_LIBS $PTH_LIBS"
              CFLAGS="$CFLAGS -DENABLE_PTH"
-@@ -25930,8 +25928,8 @@ fi;
+@@ -25930,8 +25928,8 @@
              pthread_lib="-pthread"
              ;;
          *-*-netbsd*)
@@ -238,7 +238,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
              ;;
          *-*-openbsd*)
              pthread_cflags="-D_REENTRANT"
-@@ -27751,93 +27749,21 @@ if test $ac_cv_lib_usbhid_hid_init = yes
+@@ -27751,93 +27749,21 @@
    have_libusbhid=yes
  fi
  
@@ -340,7 +340,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -27845,7 +27771,7 @@ cat confdefs.h >>conftest.$ac_ext
+@@ -27845,7 +27771,7 @@
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
  $ac_includes_default
@@ -349,7 +349,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  rm -f conftest.$ac_objext
  if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-@@ -27881,15 +27807,15 @@ echo "$as_me:$LINENO: result: $ac_header
+@@ -27881,15 +27807,15 @@
  echo "${ECHO_T}$ac_header_compiler" >&6
  
  # Is the header present?
@@ -368,7 +368,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
    (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-@@ -27923,25 +27849,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
+@@ -27923,25 +27849,25 @@
  # So?  What about this header?
  case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
    yes:no: )
@@ -410,7 +410,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
      (
        cat <<\_ASBOX
  ## ------------------------------------------ ##
-@@ -27952,34 +27878,34 @@ _ASBOX
+@@ -27952,34 +27878,34 @@
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
  esac
@@ -461,7 +461,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -27987,7 +27913,7 @@ cat confdefs.h >>conftest.$ac_ext
+@@ -27987,7 +27913,7 @@
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
  $ac_includes_default
@@ -470,7 +470,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  rm -f conftest.$ac_objext
  if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-@@ -28023,15 +27949,15 @@ echo "$as_me:$LINENO: result: $ac_header
+@@ -28023,15 +27949,15 @@
  echo "${ECHO_T}$ac_header_compiler" >&6
  
  # Is the header present?
@@ -489,7 +489,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
    (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-@@ -28065,25 +27991,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
+@@ -28065,25 +27991,25 @@
  # So?  What about this header?
  case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
    yes:no: )
@@ -497,13 +497,9 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
 -echo "$as_me: WARNING: usbhid.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: usbhid.h: proceeding with the compiler's result" >&5
 -echo "$as_me: WARNING: usbhid.h: proceeding with the compiler's result" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: libusbhid.h: accepted by the compiler, rejected by the preprocessor!" >&5
-+echo "$as_me: WARNING: libusbhid.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: libusbhid.h: proceeding with the compiler's result" >&5
-+echo "$as_me: WARNING: libusbhid.h: proceeding with the compiler's result" >&2;}
-     ac_header_preproc=yes
-     ;;
-   no:yes:* )
+-    ac_header_preproc=yes
+-    ;;
+-  no:yes:* )
 -    { echo "$as_me:$LINENO: WARNING: usbhid.h: present but cannot be compiled" >&5
 -echo "$as_me: WARNING: usbhid.h: present but cannot be compiled" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: usbhid.h:     check for missing prerequisite headers?" >&5
@@ -516,6 +512,13 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
 -echo "$as_me: WARNING: usbhid.h: proceeding with the preprocessor's result" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: usbhid.h: in the future, the compiler will take precedence" >&5
 -echo "$as_me: WARNING: usbhid.h: in the future, the compiler will take precedence" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libusbhid.h: accepted by the compiler, rejected by the preprocessor!" >&5
++echo "$as_me: WARNING: libusbhid.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libusbhid.h: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: libusbhid.h: proceeding with the compiler's result" >&2;}
++    ac_header_preproc=yes
++    ;;
++  no:yes:* )
 +    { echo "$as_me:$LINENO: WARNING: libusbhid.h: present but cannot be compiled" >&5
 +echo "$as_me: WARNING: libusbhid.h: present but cannot be compiled" >&2;}
 +    { echo "$as_me:$LINENO: WARNING: libusbhid.h:     check for missing prerequisite headers?" >&5
@@ -531,7 +534,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
      (
        cat <<\_ASBOX
  ## ------------------------------------------ ##
-@@ -28094,34 +28020,112 @@ _ASBOX
+@@ -28094,34 +28020,112 @@
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
  esac
@@ -573,7 +576,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
 +            echo "$as_me:$LINENO: checking for hid_init in -lusb" >&5
 +echo $ECHO_N "checking for hid_init in -lusb... $ECHO_C" >&6
 +if test "${ac_cv_lib_usb_hid_init+set}" = set; then
-+  echo $ECHO_N "(cached) $ECHO_C" >&6
+   echo $ECHO_N "(cached) $ECHO_C" >&6
 +else
 +  ac_check_lib_save_LIBS=$LIBS
 +LIBS="-lusb  $LIBS"
@@ -627,7 +630,9 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
 +sed 's/^/| /' conftest.$ac_ext >&5
 +
 +ac_cv_lib_usb_hid_init=no
-+fi
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_header_libusb_h" >&5
+-echo "${ECHO_T}$ac_cv_header_libusb_h" >&6
 +rm -f conftest.err conftest.$ac_objext \
 +      conftest$ac_exeext conftest.$ac_ext
 +LIBS=$ac_check_lib_save_LIBS
@@ -645,10 +650,8 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
 +  echo "$as_me:$LINENO: checking for usb.h" >&5
 +echo $ECHO_N "checking for usb.h... $ECHO_C" >&6
 +if test "${ac_cv_header_usb_h+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- fi
--echo "$as_me:$LINENO: result: $ac_cv_header_libusb_h" >&5
--echo "${ECHO_T}$ac_cv_header_libusb_h" >&6
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++fi
 +echo "$as_me:$LINENO: result: $ac_cv_header_usb_h" >&5
 +echo "${ECHO_T}$ac_cv_header_usb_h" >&6
  else
@@ -660,7 +663,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28129,7 +28133,7 @@ cat confdefs.h >>conftest.$ac_ext
+@@ -28129,7 +28133,7 @@
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
  $ac_includes_default
@@ -669,7 +672,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  rm -f conftest.$ac_objext
  if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-@@ -28165,15 +28169,15 @@ echo "$as_me:$LINENO: result: $ac_header
+@@ -28165,15 +28169,15 @@
  echo "${ECHO_T}$ac_header_compiler" >&6
  
  # Is the header present?
@@ -688,7 +691,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
    (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-@@ -28207,25 +28211,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
+@@ -28207,25 +28211,25 @@
  # So?  What about this header?
  case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
    yes:no: )
@@ -730,7 +733,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
      (
        cat <<\_ASBOX
  ## ------------------------------------------ ##
-@@ -28236,34 +28240,34 @@ _ASBOX
+@@ -28236,34 +28240,34 @@
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
  esac
@@ -781,7 +784,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28271,7 +28275,7 @@ cat confdefs.h >>conftest.$ac_ext
+@@ -28271,7 +28275,7 @@
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
  $ac_includes_default
@@ -790,7 +793,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  rm -f conftest.$ac_objext
  if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-@@ -28307,15 +28311,15 @@ echo "$as_me:$LINENO: result: $ac_header
+@@ -28307,15 +28311,15 @@
  echo "${ECHO_T}$ac_header_compiler" >&6
  
  # Is the header present?
@@ -809,7 +812,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
  _ACEOF
  if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
    (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-@@ -28349,25 +28353,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
+@@ -28349,25 +28353,25 @@
  # So?  What about this header?
  case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
    yes:no: )
@@ -851,7 +854,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
      (
        cat <<\_ASBOX
  ## ------------------------------------------ ##
-@@ -28378,33 +28382,29 @@ _ASBOX
+@@ -28378,33 +28382,29 @@
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
  esac
@@ -894,7 +897,78 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
          fi
  
          echo "$as_me:$LINENO: checking for usbhid" >&5
-@@ -28922,6 +28922,7 @@ __EOF__
+@@ -28628,6 +28628,70 @@
+     fi
+ }
+ 
++CheckMachineJoystick()
++{
++    if test x$enable_joystick = xyes; then
++        echo "$as_me:$LINENO: checking whether struct joystick is defined in machine/joystick.h" >&5
++echo $ECHO_N "checking whether struct joystick is defined in machine/joystick.h... $ECHO_C" >&6
++        have_machine_joystick=no
++        cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++          #include <machine/joystick.h>
++
++int
++main ()
++{
++
++          struct joystick t;
++
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext
++if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
++  (eval $ac_compile) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"
++			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest.$ac_objext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++
++        have_machine_joystick=yes
++
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++fi
++rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
++        echo "$as_me:$LINENO: result: $have_machine_joystick" >&5
++echo "${ECHO_T}$have_machine_joystick" >&6
++        if test x$have_machine_joystick = xyes; then
++            CFLAGS="$CFLAGS -DHAVE_MACHINE_JOYSTICK"
++        fi
++    fi
++}
++
+ CheckAltivec()
+ {
+     echo "$as_me:$LINENO: checking for GCC Altivec instruction support" >&5
+@@ -28922,16 +28986,18 @@
          CheckESD
          CheckNAS
          CheckX11
@@ -902,8 +976,9 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
          CheckAAlib
          CheckOpenGL
          CheckPTHREAD
-@@ -28929,9 +28930,9 @@ __EOF__
+         CheckSIGACTION
          CheckUSBHID
++	CheckMachineJoystick
          # Set up files for the audio library
          if test x$enable_audio = xyes; then
 -            CFLAGS="$CFLAGS -DSUNAUDIO_SUPPORT"
@@ -915,7 +990,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
          fi
          # Set up files for the cdrom library
          if test x$enable_cdrom = xyes; then
-@@ -28940,9 +28941,6 @@ __EOF__
+@@ -28940,9 +29006,6 @@
          fi
          # Set up files for the thread library
          if test x$enable_threads = xyes; then
@@ -925,7 +1000,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
              CopyUnixThreadSource
          fi
          # Set up files for the timer library
-@@ -30425,7 +30423,7 @@ fi
+@@ -30425,7 +30488,7 @@
  
  # Set runtime shared library paths as needed
  
@@ -934,7 +1009,7 @@ $NetBSD: patch-am,v 1.13 2004/04/17 00:15:21 snj Exp $
    SDL_RLD_FLAGS="-Wl,-rpath,\${exec_prefix}/lib"
  fi
  if test $ARCH = solaris; then
-@@ -31564,7 +31562,8 @@ s,@X_EXTRA_LIBS@,$X_EXTRA_LIBS,;t t
+@@ -31564,7 +31627,8 @@
  s,@PKG_CONFIG@,$PKG_CONFIG,;t t
  s,@DIRECTFB_CFLAGS@,$DIRECTFB_CFLAGS,;t t
  s,@DIRECTFB_LIBS@,$DIRECTFB_LIBS,;t t
