Update to R 2.3.1
This version contains several minor fixups and removes a couple of bad
bugs such as NA-handling of mean() for integer vectors.

Changes 2.3.0
This version contains several changes and additions, mostly incremental.

diff --git a/math/R/patches/patch-ac b/math/R/patches/patch-ac
--- a/math/R/patches/patch-ac
+++ b/math/R/patches/patch-ac
@@ -1,38 +1,17 @@
-$NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
+$NetBSD: patch-ac,v 1.17 2006/06/13 12:28:09 markd Exp $
 
---- configure.orig	2005-12-16 16:07:00.000000000 +1300
+--- configure.orig	2006-06-01 20:12:54.000000000 +1200
 +++ configure
-@@ -1910,17 +1910,17 @@ fi
- 
- ## R installation directories
- 
--if test -z ${rdocdir}; then
-+if test -z "${rdocdir}"; then
-   rdocdir='${rhome}/doc'
- fi
- 
- 
--if test -z ${rincludedir}; then
-+if test -z "${rincludedir}"; then
-   rincludedir='${rhome}/include'
- fi
- 
- 
--if test -z ${rsharedir}; then
-+if test -z "${rsharedir}"; then
-   rsharedir='${rhome}/share'
- fi
- 
-@@ -2246,7 +2246,7 @@ else
+@@ -2272,7 +2272,7 @@ else
  fi
  
  if test "${want_R_shlib}" = yes; then
--  LIBR="-L\$(R_HOME)/lib -lR"
-+  LIBR="-Wl,-R${prefix}/lib/R/lib -L\$(R_HOME)/lib -lR"
+-  LIBR="-L\$(R_HOME)/lib\$(R_ARCH) -lR"
++  LIBR="-Wl,-R${prefix}/lib/R/lib\$(R_ARCH) -L\$(R_HOME)/lib\$(R_ARCH) -lR"
  else
    LIBR=
  fi
-@@ -6438,7 +6438,7 @@ darwin* | rhapsody*)
+@@ -6580,7 +6580,7 @@ darwin* | rhapsody*)
    lt_cv_deplibs_check_method=pass_all
    ;;
  
@@ -41,7 +20,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
    if echo __ELF__ | $CC -E - | grep __ELF__ > /dev/null; then
      case $host_cpu in
      i*86 )
-@@ -8963,7 +8963,7 @@ if test -z "$aix_libpath"; then aix_libp
+@@ -9101,7 +9101,7 @@ if test -z "$aix_libpath"; then aix_libp
        ;;
  
      # FreeBSD 3 and greater uses gcc -shared to do shared libraries.
@@ -50,7 +29,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
        archive_cmds='$CC -shared -o $lib $libobjs $deplibs $compiler_flags'
        hardcode_libdir_flag_spec='-R$libdir'
        hardcode_direct=yes
-@@ -9541,7 +9541,7 @@ kfreebsd*-gnu)
+@@ -9679,7 +9679,7 @@ kfreebsd*-gnu)
    dynamic_linker='GNU ld.so'
    ;;
  
@@ -59,7 +38,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
    objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
    version_type=freebsd-$objformat
    case $version_type in
-@@ -11921,7 +11921,7 @@ if test -z "$aix_libpath"; then aix_libp
+@@ -12060,7 +12060,7 @@ if test -z "$aix_libpath"; then aix_libp
    freebsd-elf*)
      archive_cmds_need_lc_CXX=no
      ;;
@@ -68,7 +47,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
      # FreeBSD 3 and later use GNU C++ and GNU ld with standard ELF
      # conventions
      ld_shlibs_CXX=yes
-@@ -12632,7 +12632,7 @@ echo $ECHO_N "checking for $compiler opt
+@@ -12767,7 +12767,7 @@ echo $ECHO_N "checking for $compiler opt
  	    ;;
  	esac
  	;;
@@ -77,7 +56,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  	# FreeBSD uses GNU C++
  	;;
        hpux9* | hpux10* | hpux11*)
-@@ -13243,7 +13243,7 @@ kfreebsd*-gnu)
+@@ -13378,7 +13378,7 @@ kfreebsd*-gnu)
    dynamic_linker='GNU ld.so'
    ;;
  
@@ -86,7 +65,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
    objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
    version_type=freebsd-$objformat
    case $version_type in
-@@ -15814,7 +15814,7 @@ if test -z "$aix_libpath"; then aix_libp
+@@ -15949,7 +15949,7 @@ if test -z "$aix_libpath"; then aix_libp
        ;;
  
      # FreeBSD 3 and greater uses gcc -shared to do shared libraries.
@@ -95,7 +74,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
        archive_cmds_F77='$CC -shared -o $lib $libobjs $deplibs $compiler_flags'
        hardcode_libdir_flag_spec_F77='-R$libdir'
        hardcode_direct_F77=yes
-@@ -16392,7 +16392,7 @@ kfreebsd*-gnu)
+@@ -16527,7 +16527,7 @@ kfreebsd*-gnu)
    dynamic_linker='GNU ld.so'
    ;;
  
@@ -104,7 +83,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
    objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
    version_type=freebsd-$objformat
    case $version_type in
-@@ -18165,7 +18165,7 @@ if test -z "$aix_libpath"; then aix_libp
+@@ -18296,7 +18296,7 @@ if test -z "$aix_libpath"; then aix_libp
        ;;
  
      # FreeBSD 3 and greater uses gcc -shared to do shared libraries.
@@ -113,7 +92,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
        archive_cmds_GCJ='$CC -shared -o $lib $libobjs $deplibs $compiler_flags'
        hardcode_libdir_flag_spec_GCJ='-R$libdir'
        hardcode_direct_GCJ=yes
-@@ -18743,7 +18743,7 @@ kfreebsd*-gnu)
+@@ -18874,7 +18874,7 @@ kfreebsd*-gnu)
    dynamic_linker='GNU ld.so'
    ;;
  
@@ -122,7 +101,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
    objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
    version_type=freebsd-$objformat
    case $version_type in
-@@ -21746,13 +21746,13 @@ fi
+@@ -21901,13 +21901,13 @@ fi
      ## only need ncurses if libreadline is not statically linked against it
      unset ac_cv_lib_readline_rl_callback_read_char
  
@@ -131,7 +110,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
 -if test "${ac_cv_lib_ncurses_main+set}" = set; then
 +echo "$as_me:$LINENO: checking for main in -ltermcap" >&5
 +echo $ECHO_N "checking for main in -ltermcap... $ECHO_C" >&6
-+if test "${ac_cv_lib_termcap_main+set}" = set; then
++if test "${ac_cv_lib_termcap+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -140,7 +119,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -21791,35 +21791,35 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+@@ -21946,35 +21946,35 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
@@ -187,7 +166,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -21858,35 +21858,35 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+@@ -22013,35 +22013,35 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
@@ -234,7 +213,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -21925,25 +21925,25 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+@@ -22080,25 +22080,25 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
@@ -267,7 +246,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  
  fi
  
-@@ -27173,6 +27173,7 @@ cat > conftest.c <<EOF
+@@ -27727,6 +27727,7 @@ cat > conftest.c <<EOF
  #else
  # define F77_SYMBOL(x)   x
  #endif
@@ -275,7 +254,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  int main () {
    exit(0);
  }
-@@ -27243,6 +27244,9 @@ cat > conftest.c <<EOF
+@@ -27796,6 +27797,9 @@ cat > conftest.c <<EOF
  
  extern void F77_SYMBOL(cftest)(int *a, int *b, double *x, double *y);
  
@@ -285,7 +264,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  int main () {
    int a[3] = {17, 237, 2000000000}, b[2], res = 0;
    double x[3] = {3.14159265, 123.456789, 2.3e34}, z[3];
-@@ -27333,6 +27337,9 @@ typedef struct {
+@@ -27885,6 +27889,9 @@ typedef struct {
  
  extern void F77_SYMBOL(cftest)(Rcomplex *x);
  
@@ -295,7 +274,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
  int main () {
      Rcomplex z[3];
  
-@@ -28170,157 +28177,6 @@ echo "${ECHO_T}no" >&6
+@@ -28277,157 +28284,6 @@ echo "${ECHO_T}no" >&6
  fi
  
      fi
@@ -453,7 +432,16 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
      if test "${GXX}" = yes; then
        ac_safe=_mieee
  echo "$as_me:$LINENO: checking whether ${CXX-c++} accepts -mieee" >&5
-@@ -29210,7 +29066,7 @@ fi ;;
+@@ -28762,7 +28618,7 @@ _ACEOF
+     if test "${GCC}" = yes; then
+       ## only Apple build of gcc supports (and needs?) -no-cpp-precomp
+       ${CC} --version|grep Apple >/dev/null 2>/dev/null
+-      if test $? == 0; then
++      if test $? = 0; then
+         separator=""
+ test -z "${separator}" && separator=" "
+ if test -z "${R_XTRA_CPPFLAGS}"; then
+@@ -29726,7 +29582,7 @@ fi ;;
        SHLIB_LIBADD="-lcc_dynamic"
      fi
      ;;
@@ -462,7 +450,7 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
      ## Only sure for FreeBSD 3 and above.
      main_ldflags="-export-dynamic"
      shlib_ldflags="-shared"
-@@ -29458,6 +29314,7 @@ fi
+@@ -29814,6 +29670,7 @@ fi ;;
      fpicflags=
      ;;
    netbsd*)
@@ -470,3 +458,21 @@ $NetBSD: patch-ac,v 1.16 2006/02/04 22:25:06 markd Exp $
      if ${CPP} - -dM < /dev/null | grep __ELF__ >/dev/null ; then
        main_ldflags="-export-dynamic"
        shlib_ldflags="-shared"
+@@ -29912,7 +29769,7 @@ fi
+ : ${FPICFLAGS="${fpicflags}"}
+ if test -z "${FPICFLAGS}"; then
+   case "${host_os}" in
+-    aix*|irix*|mingw*|osf*)
++    aix*|irix*|mingw*|osf*|darwin*)
+       ;;
+     *)
+       { echo "$as_me:$LINENO: WARNING: I could not determine FPICFLAGS." >&5
+@@ -38863,7 +38720,7 @@ cat >>confdefs.h <<\_ACEOF
+ _ACEOF
+ 
+   r_save_LIBS=${LIBS}
+-  if test "$want_utf8_support" == yes ; then
++  if test "$want_utf8_support" = yes ; then
+     LIBS="${LIBS} ${X_LIBS}"
+ 
+ 
