Bump PKGREVISION for libpng shlib name change. Also add some patches to remove use of deprecated symbols and fix other problems when looking for or compiling against libpng-1.4.x.

diff --git a/x11/wxGTK28/patches/patch-aa b/x11/wxGTK28/patches/patch-aa
--- a/x11/wxGTK28/patches/patch-aa
+++ b/x11/wxGTK28/patches/patch-aa
@@ -1,6 +1,6 @@
-$NetBSD: patch-aa,v 1.2 2009/05/15 07:09:00 adam Exp $
+$NetBSD: patch-aa,v 1.3 2010/06/13 22:45:54 wiz Exp $
 
---- configure.orig	2009-03-06 13:17:38.000000000 +0100
+--- configure.orig	2009-03-06 12:17:38.000000000 +0000
 +++ configure
 @@ -1962,7 +1962,7 @@ _ACEOF
  
@@ -37,6 +37,59 @@ $NetBSD: patch-aa,v 1.2 2009/05/15 07:09:00 adam Exp $
      /usr/X11R6/include        \
      /usr/X11R6.4/include      \
                                \
+@@ -26379,9 +26380,9 @@ echo "${ECHO_T}$ac_cv_header_png_h" >&6
+ 
+ 
+             if test "$ac_cv_header_png_h" = "yes"; then
+-                echo "$as_me:$LINENO: checking for png_check_sig in -lpng" >&5
+-echo $ECHO_N "checking for png_check_sig in -lpng... $ECHO_C" >&6
+-if test "${ac_cv_lib_png_png_check_sig+set}" = set; then
++                echo "$as_me:$LINENO: checking for png_sig_cmp in -lpng" >&5
++echo $ECHO_N "checking for png_sig_cmp in -lpng... $ECHO_C" >&6
++if test "${ac_cv_lib_png_png_sig_cmp+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+@@ -26399,11 +26400,11 @@ extern "C"
+ #endif
+ /* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+-char png_check_sig ();
++char png_sig_cmp ();
+ int
+ main ()
+ {
+-png_check_sig ();
++png_sig_cmp ();
+   ;
+   return 0;
+ }
+@@ -26429,20 +26430,20 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_lib_png_png_check_sig=yes
++  ac_cv_lib_png_png_sig_cmp=yes
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-ac_cv_lib_png_png_check_sig=no
++ac_cv_lib_png_png_sig_cmp=no
+ fi
+ rm -f conftest.err conftest.$ac_objext \
+       conftest$ac_exeext conftest.$ac_ext
+ LIBS=$ac_check_lib_save_LIBS
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_lib_png_png_check_sig" >&5
+-echo "${ECHO_T}$ac_cv_lib_png_png_check_sig" >&6
+-if test $ac_cv_lib_png_png_check_sig = yes; then
++echo "$as_me:$LINENO: result: $ac_cv_lib_png_png_sig_cmp" >&5
++echo "${ECHO_T}$ac_cv_lib_png_png_sig_cmp" >&6
++if test $ac_cv_lib_png_png_sig_cmp = yes; then
+   PNG_LINK=" -lpng -lz"
+ fi
+ 
 @@ -39478,6 +39479,9 @@ echo "$as_me: WARNING: BeOS threads are 
                      THREAD_OPTS="-mt $THREAD_OPTS"
                  fi
