Update to 2.12.0.  Thanks go to the FreeBSD GNOME developers for all the patches I borrowed from them (patch-b*).
September 4, 2005: Overview of changes from 2.11.92 to 2.12.0
=============================================================
* Updated translations.

August 22, 2005: Overview of changes from 2.11.91 to 2.11.92
============================================================
* Linux:
  - fixed for 2.6 without /sys
  - glibtop_get_cpu() : Do not add irq, softirq and iowait to idle.

August 9, 2005: Overview of changes from 2.11.90 to 2.11.91
===========================================================
* All:
  - cleaned some headers.
  - removed static examples.
* Linux:
  - fixed some issues with 2.6 without /sys

July 24, 2005: Overview of changes from 2.11.2 to 2.11.90
=========================================================
* Linux:
  - fixed glibtop_uptime .flags.

July &3, 2005: Overview of changes from 2.11.1 to 2.11.2
========================================================
* Linux:
  - little improvements for 2.6.

July 3, 2005: Overview of changes from 2.11.0 to 2.11.1
=======================================================
* Linux:
  - glibtop_get_swap : added page(in|out) for linux 2.6.

June 8, 2005: Overview of changes from 2.10.x to 2.11.0
=======================================================
* Replaced a lot of macros by functions
* Got rid of dozens of useless files.
* libgtop 2.11.x are and will stay API and ABI compatible with 2.10.x, i swear.

diff --git a/sysutils/libgtop2/patches/patch-aa b/sysutils/libgtop2/patches/patch-aa
--- a/sysutils/libgtop2/patches/patch-aa
+++ b/sysutils/libgtop2/patches/patch-aa
@@ -1,8 +1,8 @@
-$NetBSD: patch-aa,v 1.2 2004/05/04 23:36:16 minskim Exp $
+$NetBSD: patch-aa,v 1.3 2005/10/12 21:49:39 jmmv Exp $
 
---- configure.orig	2004-04-07 05:19:43.000000000 -0500
+--- configure.orig	2005-09-04 17:54:58.000000000 +0200
 +++ configure
-@@ -20463,13 +20463,13 @@ echo $ECHO_N "checking for libgtop sysde
+@@ -20141,13 +20141,13 @@ echo $ECHO_N "checking for libgtop sysde
  	  libgtop_sysdeps_dir=freebsd
  	  libgtop_use_machine_h=yes
  	  libgtop_need_server=yes
@@ -18,7 +18,86 @@ $NetBSD: patch-aa,v 1.2 2004/05/04 23:36:16 minskim Exp $
  	  ;;
          aix*)
  	  libgtop_sysdeps_dir=aix
-@@ -30110,7 +30110,7 @@ cat >>conftest.$ac_ext <<_ACEOF
+@@ -23761,6 +23761,78 @@ fi
+ esac
+ 
+ 
++echo "$as_me:$LINENO: checking for kvm_open in -lkvm" >&5
++echo $ECHO_N "checking for kvm_open in -lkvm... $ECHO_C" >&6
++if test "${ac_cv_lib_mach_kvm_open+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_check_lib_save_LIBS=$LIBS
++LIBS="-lkvm  $LIBS"
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char kvm_open ();
++int
++main ()
++{
++kvm_open ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_cv_lib_mach_kvm_open=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_cv_lib_mach_kvm_open=no
++fi
++rm -f conftest.err conftest.$ac_objext \
++      conftest$ac_exeext conftest.$ac_ext
++LIBS=$ac_check_lib_save_LIBS
++fi
++echo "$as_me:$LINENO: result: $ac_cv_lib_mach_kvm_open" >&5
++echo "${ECHO_T}$ac_cv_lib_mach_kvm_open" >&6
++if test $ac_cv_lib_mach_kvm_open = yes; then
++  cat >>confdefs.h <<_ACEOF
++#define HAVE_LIBMACH 1
++_ACEOF
++
++  KVM_LIBS="-lkvm $KVM_LIBS"
++
++fi
++
+ echo "$as_me:$LINENO: checking for vm_statistics in -lmach" >&5
+ echo $ECHO_N "checking for vm_statistics in -lmach... $ECHO_C" >&6
+ if test "${ac_cv_lib_mach_vm_statistics+set}" = set; then
+@@ -30106,7 +30178,7 @@ cat >>conftest.$ac_ext <<_ACEOF
  
  _ACEOF
  if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
@@ -27,3 +106,11 @@ $NetBSD: patch-aa,v 1.2 2004/05/04 23:36:16 minskim Exp $
    ok=yes
  fi
  rm -f conftest*
+@@ -31512,6 +31584,7 @@ s,@ECHO_C@,$ECHO_C,;t t
+ s,@ECHO_N@,$ECHO_N,;t t
+ s,@ECHO_T@,$ECHO_T,;t t
+ s,@LIBS@,$LIBS,;t t
++s,@KVM_LIBS@,$KVM_LIBS,;t t
+ s,@build@,$build,;t t
+ s,@build_cpu@,$build_cpu,;t t
+ s,@build_vendor@,$build_vendor,;t t
