Readd -lkvm handling which got lost in the last commit.

diff --git a/sysutils/libgtop2/patches/patch-aa b/sysutils/libgtop2/patches/patch-aa
--- a/sysutils/libgtop2/patches/patch-aa
+++ b/sysutils/libgtop2/patches/patch-aa
@@ -1,6 +1,6 @@
-$NetBSD: patch-aa,v 1.4 2006/02/28 23:48:11 joerg Exp $
+$NetBSD: patch-aa,v 1.5 2006/03/08 15:52:54 joerg Exp $
 
---- configure.orig	2005-11-29 10:49:14.000000000 +0000
+--- configure.orig	2005-11-29 11:49:14.000000000 +0100
 +++ configure
 @@ -20691,17 +20691,17 @@ echo $ECHO_N "checking for libgtop sysde
  	  libgtop_have_sysinfo=yes
@@ -54,10 +54,82 @@ $NetBSD: patch-aa,v 1.4 2006/02/28 23:48:11 joerg Exp $
  #include <net/if_sppp.h>
  #else
  #include <i4b/sppp/if_sppp.h>
-@@ -24342,6 +24346,73 @@ fi
-      ;;
+@@ -24343,6 +24347,146 @@ fi
  esac
  
+ 
++echo "$as_me:$LINENO: checking for kvm_open in -lkvm" >&5
++echo $ECHO_N "checking for kvm_open in -lkvm... $ECHO_C" >&6
++if test "${ac_cv_lib_mach_kvm_open+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_check_lib_save_LIBS=$LIBS
++LIBS="-lkvm  $LIBS"
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char kvm_open ();
++int
++main ()
++{
++kvm_open ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_cv_lib_mach_kvm_open=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_cv_lib_mach_kvm_open=no
++fi
++rm -f conftest.err conftest.$ac_objext \
++      conftest$ac_exeext conftest.$ac_ext
++LIBS=$ac_check_lib_save_LIBS
++fi
++echo "$as_me:$LINENO: result: $ac_cv_lib_mach_kvm_open" >&5
++echo "${ECHO_T}$ac_cv_lib_mach_kvm_open" >&6
++if test $ac_cv_lib_mach_kvm_open = yes; then
++  cat >>confdefs.h <<_ACEOF
++#define HAVE_LIBMACH 1
++_ACEOF
++
++  KVM_LIBS="-lkvm $KVM_LIBS"
++
++fi
++
 +echo "$as_me:$LINENO: checking for kinfo_get_sched_hz in -lkinfo" >&5
 +echo $ECHO_N "checking for kinfo_get_sched_hz in -lkinfo... $ECHO_C" >&6
 +if test "${ac_cv_lib_kinfo_kinfo_get_sched_gz+set}" = set; then
@@ -123,12 +195,13 @@ $NetBSD: patch-aa,v 1.4 2006/02/28 23:48:11 joerg Exp $
 +echo "${ECHO_T}$ac_cv_lib_kinfo_kinfo_get_sched_hz" >&6
 +if test $ac_cv_lib_kinfo_kinfo_get_sched_hz = yes; then
 +
-+  LIBS="-lkinfo -lkvm $LIBS" # we need kvm as well
++  LIBS="-lkinfo $LIBS" # we need kvm as well
 +fi
- 
++
  echo "$as_me:$LINENO: checking for vm_statistics in -lmach" >&5
  echo $ECHO_N "checking for vm_statistics in -lmach... $ECHO_C" >&6
-@@ -30043,7 +30114,7 @@ if test x$cross_compiling = xyes ; then
+ if test "${ac_cv_lib_mach_vm_statistics+set}" = set; then
+@@ -30043,7 +30187,7 @@ if test x$cross_compiling = xyes ; then
          sunos*)
            fu_cv_sys_stat_statfs4=yes
            ;;
@@ -137,7 +210,7 @@ $NetBSD: patch-aa,v 1.4 2006/02/28 23:48:11 joerg Exp $
            fu_cv_sys_stat_statfs2_bsize=yes
            ;;
          osf*)
-@@ -30688,7 +30759,7 @@ cat >>conftest.$ac_ext <<_ACEOF
+@@ -30688,7 +30832,7 @@ cat >>conftest.$ac_ext <<_ACEOF
  
  _ACEOF
  if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
@@ -146,3 +219,11 @@ $NetBSD: patch-aa,v 1.4 2006/02/28 23:48:11 joerg Exp $
    ok=yes
  fi
  rm -f conftest*
+@@ -32094,6 +32240,7 @@ s,@ECHO_C@,$ECHO_C,;t t
+ s,@ECHO_N@,$ECHO_N,;t t
+ s,@ECHO_T@,$ECHO_T,;t t
+ s,@LIBS@,$LIBS,;t t
++s,@KVM_LIBS@,$KVM_LIBS,;t t
+ s,@build@,$build,;t t
+ s,@build_cpu@,$build_cpu,;t t
+ s,@build_vendor@,$build_vendor,;t t
