Provide code pathes using posix_memalign, applies  at leas to NetBSD current.

diff --git a/multimedia/ffmpeg/patches/patch-configure b/multimedia/ffmpeg/patches/patch-configure
--- a/multimedia/ffmpeg/patches/patch-configure
+++ b/multimedia/ffmpeg/patches/patch-configure
@@ -1,8 +1,16 @@
-$NetBSD: patch-configure,v 1.2 2008/09/08 00:16:35 ahoka Exp $
+$NetBSD: patch-configure,v 1.3 2008/09/11 12:08:41 joerg Exp $
 
 --- configure.orig	2008-07-24 12:53:32.000000000 +0200
 +++ configure
-@@ -891,7 +891,7 @@ rtp_muxer_deps="network rtp_protocol"
+@@ -763,6 +763,7 @@ HAVE_LIST="
+     memalign
+     mkstemp
+     pld
++    posix_memalign
+     ppc64
+     round
+     roundf
+@@ -891,7 +892,7 @@ rtp_muxer_deps="network rtp_protocol"
  rtsp_demuxer_deps="sdp_demuxer"
  sdp_demuxer_deps="rtp_protocol mpegts_demuxer"
  v4l_demuxer_deps="linux_videodev_h"
@@ -11,7 +19,7 @@ $NetBSD: patch-configure,v 1.2 2008/09/08 00:16:35 ahoka Exp $
  vfwcap_demuxer_deps="capCreateCaptureWindow"
  vfwcap_demuxer_extralibs="-lvfw32"
  x11_grab_device_demuxer_deps="x11grab XShmCreateImage"
-@@ -1586,10 +1586,14 @@ enabled vis && add_cflags "-mcpu=ultrasp
+@@ -1586,10 +1587,14 @@ enabled vis && add_cflags "-mcpu=ultrasp
  
  # ---
  # big/little-endian test
@@ -29,7 +37,24 @@ $NetBSD: patch-configure,v 1.2 2008/09/08 00:16:35 ahoka Exp $
  
  # ---
  # check availability of some header files
-@@ -1789,6 +1793,7 @@ EOF
+@@ -1605,6 +1610,7 @@ check_func  gethrtime
+ check_func  getrusage
+ check_func  inet_aton $network_extralibs
+ check_func  memalign
++check_func  posix_memalign
+ check_func  mkstemp
+ check_func2 windows.h GetProcessTimes
+ 
+@@ -1616,7 +1622,7 @@ check_header sys/mman.h
+ check_header sys/resource.h
+ check_header termios.h
+ 
+-if ! enabled_any memalign memalign_hack && enabled need_memalign ; then
++if ! enabled_any memalign memalign_hack posix_memalign && enabled need_memalign ; then
+     die "Error, no memalign() but SSE enabled, disable it or use --enable-memalign-hack."
+ fi
+ 
+@@ -1789,6 +1795,7 @@ EOF
  
  check_header linux/videodev.h
  check_header linux/videodev2.h
