The first raw cd device is _not_ rcd0d. Use sysctl kern.rawpartition.

diff --git a/audio/abcde/patches/patch-ac b/audio/abcde/patches/patch-ac
--- a/audio/abcde/patches/patch-ac
+++ b/audio/abcde/patches/patch-ac
@@ -1,22 +1,89 @@
-$NetBSD: patch-ac,v 1.1.1.1 2001/08/16 06:02:48 lukem Exp $
+$NetBSD: patch-ac,v 1.2 2001/10/03 21:58:28 abs Exp $
 
---- abcde.1.orig	Thu Aug 16 08:12:25 2001
-+++ abcde.1	Thu Aug 16 15:55:04 2001
-@@ -42,7 +42,7 @@
- .TP
- .B \-c [filename]
- Specifies an additional configuration file to parse. Configuration options
--in this file override those in /etc/abcde.conf or $HOME/.abcde.conf.
-+in this file override those in @ETCDIR@/abcde.conf or $HOME/.abcde.conf.
- .TP
- .B \-C [discid]
- Allows you to resume a session for
-@@ -91,7 +91,7 @@
- '.mp3'. This can be modified using the OUTPUTFORMAT and VAOUTPUTFORMAT
- variables in your abcde.conf.
- .SH CONFIGURATION
--abcde sources two configuration files on startup - /etc/abcde.conf and
-+abcde sources two configuration files on startup - @ETCDIR@/abcde.conf and
- $HOME/.abcde.conf, in that order. Here is a list of options abcde recognizes:
- .TP
- .B CDDBURL
+--- abcde.orig	Wed Aug 15 22:39:29 2001
++++ abcde
+@@ -552,7 +552,7 @@
+ 			fi
+ 			# List out disc title/author and contents
+ 			echo ---- $(cut '-d ' -f4- "$ABCDETEMPDIR/cddbquery") ---- >> "$ABCDETEMPDIR/cddbchoices"
+-			for TRACK in $(seq 1 $TRACKS)
++			for TRACK in $(jot $TRACKS)
+ 			do
+ 				echo $TRACK: $(grep ^TTITLE$(expr $TRACK - 1)= "$ABCDETEMPDIR/cddbread.1" | cut -f2- -d= | tr -d \\r\\n) >> "$ABCDETEMPDIR/cddbchoices"
+ 			done
+@@ -568,7 +568,7 @@
+ 			$CDDBTOOL template $(cat "$ABCDETEMPDIR/discid") > "$ABCDETEMPDIR/cddbread.1"
+ 			# List out disc title/author and contents of template
+ 			echo ---- Unknown Artist / Unknown Album ---- >> "$ABCDETEMPDIR/cddbchoices"
+-			for TRACK in $(seq 1 $TRACKS)
++			for TRACK in $(jot $TRACKS)
+ 			do
+ 				echo $TRACK: $(grep ^TTITLE$(expr $TRACK - 1)= "$ABCDETEMPDIR/cddbread.1" | cut -f2- -d= | tr -d \\r\\n) >> "$ABCDETEMPDIR/cddbchoices"
+ 			done
+@@ -598,7 +598,7 @@
+ 				fi
+ 				# List out disc title/author and contents
+ 				echo \#$X: ---- "$DISCINFO" ---- >> "$ABCDETEMPDIR/cddbchoices"
+-				for TRACK in $(seq 1 $TRACKS)
++				for TRACK in $(jot $TRACKS)
+ 				do
+ 					echo $TRACK: $(grep ^TTITLE$(expr $TRACK - 1)= $ABCDETEMPDIR/cddbread.$X | cut -f2- -d= | tr -d \\r\\n) >> "$ABCDETEMPDIR/cddbchoices"
+ 				done
+@@ -757,7 +757,7 @@
+ 			echo $DEFAULTSTYLE >&2
+ 			VARIOUSARTISTSTYLE=$DEFAULTSTYLE
+ 		fi
+-		VARIOUSARTISTSTYLE=$(echo $VARIOUSARTISTSTYLE | xargs printf %d)
++		VARIOUSARTISTSTYLE=$(echo 0$VARIOUSARTISTSTYLE | xargs printf %d)
+ 		# If they press Enter, then the default style (0) was chosen
+ 		while [ $VARIOUSARTISTSTYLE -lt 0 ] || [ $VARIOUSARTISTSTYLE -gt 6 ]; do
+ 			echo "Invalid selection. Please choose a number between 1 and 6."
+@@ -765,7 +765,7 @@
+ 
+ 
+ 			read VARIOUSARTISTSTYLE
+-			VARIOUSARTISTSTYLE=$(echo $VARIOUSARTISTSTYLE | xargs printf %d)
++			VARIOUSARTISTSTYLE=$(echo 0$VARIOUSARTISTSTYLE | xargs printf %d)
+ 		done
+ 		if [ "$VARIOUSARTISTSTYLE" = "0" ]; then
+ 			VARIOUSARTISTSTYLE=$DEFAULTSTYLE
+@@ -926,17 +926,12 @@
+ 	WAVOUTPUTDIR="$OUTPUTDIR"
+ fi
+ 
+-# If this is a devfs system, default to /dev/cdroms/cdrom0
+-# instead of /dev/cdrom
+-if [ -f /dev/cdroms/cdrom0 ]; then
+-	CDROM=/dev/cdroms/cdrom0
+-else
+-	CDROM=/dev/cdrom
+-fi
++RAWPART=`sysctl -n kern.rawpartition | awk '{printf "%c",97+$0}'`
++CDROM=/dev/rcd0$RAWPART
+ 
+ # Load system defaults
+-if [ -r /etc/abcde.conf ]; then
+-	. /etc/abcde.conf
++if [ -r /usr/pkg/etc/abcde.conf ]; then
++	. /usr/pkg/etc/abcde.conf
+ fi
+ # Load user preference defaults
+ if [ -r $HOME/.abcde.conf ]; then
+@@ -972,7 +967,7 @@
+ 	if [ "$RSTART" = "$REND" ]; then 
+ 		NEWTRACKS="$RSTART"
+ 	else
+-		NEWTRACKS=$(seq -s ' ' $RSTART $REND)
++ 		NEWTRACKS=$(jot -s ' ' $(($REND - $RSTART + 1)) $RSTART $REND)
+ 	fi
+ 	TRACKQUEUE=$(echo "$TRACKQUEUE" "$NEWTRACKS")
+ 
+@@ -1145,7 +1140,7 @@
+ do
+ 	ENCODELOCATIONS="$ENCODELOCATIONS $REMOTEHOST"
+ done
+-for NUM in $(seq 1 "$MAXPROCS")
++for NUM in $(jot "$MAXPROCS")
+ do
+ 	ENCODELOCATIONS="$ENCODELOCATIONS %local%"
+ done
