add missing lex/yacc to USE_TOOLS and fix a stupid configure test that forces the name of LEX and YACC to be "flex" and "bison -y".  The old test doesn't even allow a path name.

diff --git a/cad/adms/patches/patch-ab b/cad/adms/patches/patch-ab
--- a/cad/adms/patches/patch-ab
+++ b/cad/adms/patches/patch-ab
@@ -1,4 +1,4 @@
-$NetBSD: patch-ab,v 1.1.1.1 2007/05/09 02:40:18 dmcmahill Exp $
+$NetBSD: patch-ab,v 1.2 2007/05/12 11:33:42 dmcmahill Exp $
 
 --- configure.orig	2007-02-05 12:21:02.000000000 +0000
 +++ configure
@@ -11,3 +11,32 @@ $NetBSD: patch-ab,v 1.1.1.1 2007/05/09 02:40:18 dmcmahill Exp $
  
  # specific configuration.
  ac_aux_dir=
+@@ -4116,20 +4116,14 @@ fi
+ 
+ 
+ #force use of flex/bison
+-if test "x$LEX" != "xflex"; then
+-  { echo "$as_me:$LINENO: WARNING: Program flex not found (found $LEX)" >&5
+-echo "$as_me: WARNING: Program flex not found (found $LEX)" >&2;}
+-  { { echo "$as_me:$LINENO: error: Please install gnu flex from http://www.gnu.org/software/flex/" >&5
+-echo "$as_me: error: Please install gnu flex from http://www.gnu.org/software/flex/" >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
+-if test "x$YACC" != "xbison -y"; then
+-  { echo "$as_me:$LINENO: WARNING: Program bison not found (found $YACC)" >&5
+-echo "$as_me: WARNING: Program bison not found (found $YACC)" >&2;}
+-  { { echo "$as_me:$LINENO: error: Please install gnu bison from http://www.gnu.org/software/bison/" >&5
+-echo "$as_me: error: Please install gnu bison from http://www.gnu.org/software/bison/" >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
++#if test "x$LEX" != "xflex"; then
++#  AC_MSG_WARN(Program flex not found (found $LEX))
++#  AC_MSG_ERROR(Please install gnu flex from http://www.gnu.org/software/flex/)
++#fi
++#if test "x$YACC" != "xbison -y"; then
++#  AC_MSG_WARN(Program bison not found (found $YACC))
++#  AC_MSG_ERROR(Please install gnu bison from http://www.gnu.org/software/bison/)
++#fi
+ 
+ #advice use of gcc
+ if test "x$GCC" = "xyes"; then
