Update to 21.0 and mark as BROKEN.
* Introduce WEBRTC patches for FreeBSD, this patches are not work for
  NetBSD.
* When firefox/xulrunner-22.0 is released, I will check the functionality
  of xulrunner package again.
* Patches and dist.mk are used by www/firefox.
* Take MAINATINERship.

diff --git a/devel/xulrunner/patches/patch-aa b/devel/xulrunner/patches/patch-aa
--- a/devel/xulrunner/patches/patch-aa
+++ b/devel/xulrunner/patches/patch-aa
@@ -1,8 +1,26 @@
-$NetBSD: patch-aa,v 1.18 2013/04/05 13:30:17 ryoon Exp $
+$NetBSD: patch-aa,v 1.19 2013/05/19 08:47:41 ryoon Exp $
 
---- configure.in.orig	2013-03-26 22:17:37.000000000 +0000
+--- configure.in.orig	2013-05-11 19:19:23.000000000 +0000
 +++ configure.in
-@@ -2130,6 +2130,9 @@ ia64*-hpux*)
+@@ -1404,6 +1404,17 @@ if test "$GNU_CC"; then
+     CFLAGS=$_SAVE_CFLAGS
+     AC_SUBST(HAVE_TOOLCHAIN_SUPPORT_MSSSE3)
+ 
++    # Check for -msse4.1 on $CC
++    AC_MSG_CHECKING([if toolchain supports -msse4.1 option])
++    HAVE_TOOLCHAIN_SUPPORT_MSSE4_1=
++    _SAVE_CFLAGS=$CFLAGS
++    CFLAGS="$CFLAGS -msse4.1"
++    AC_TRY_COMPILE([asm ("pmulld %xmm6,%xmm0");],,AC_MSG_RESULT([yes])
++                     [HAVE_TOOLCHAIN_SUPPORT_MSSE4_1=1],
++                     AC_MSG_RESULT([no]))
++    CFLAGS=$_SAVE_CFLAGS
++    AC_SUBST(HAVE_TOOLCHAIN_SUPPORT_MSSE4_1)
++
+     # Turn on GNU-specific warnings:
+     # -Wall - turn on a lot of warnings
+     # -Wpointer-arith - good to have
+@@ -2066,6 +2077,9 @@ ia64*-hpux*)
      if test -z "$MC"; then
          MC=mc.exe
      fi
@@ -12,7 +30,24 @@ $NetBSD: patch-aa,v 1.18 2013/04/05 13:30:17 ryoon Exp $
      ;;
  *-mingw*)
      DSO_CFLAGS=
-@@ -3071,6 +3074,9 @@ dnl ====================================
+@@ -2848,6 +2862,7 @@ EOF
+ #pragma GCC visibility push(hidden)
+ #pragma GCC visibility push(default)
+ #include <string.h>
++#include <iterator>
+ #pragma GCC visibility pop
+ 
+ __attribute__ ((visibility ("default"))) void Func() {
+@@ -2856,7 +2871,7 @@ __attribute__ ((visibility ("default")))
+ }
+ EOF
+                        ac_cv_have_visibility_builtin_bug=no
+-                       if ! ${CC-cc} ${CFLAGS} ${DSO_PIC_CFLAGS} ${DSO_LDOPTS} -O2 -S -o conftest.S conftest.c > /dev/null 2>&1 ; then
++                       if ! ${CXX-c++} ${CXXFLAGS} ${DSO_PIC_CFLAGS} ${DSO_LDOPTS} -O2 -S -o conftest.S conftest.c > /dev/null 2>&1 ; then
+                          ac_cv_have_visibility_builtin_bug=yes
+                        else
+                          if test `grep -c "@PLT" conftest.S` = 0; then
+@@ -3018,6 +3033,9 @@ dnl ====================================
  case $target in
  *-hpux11.*)
  	;;
@@ -22,17 +57,17 @@ $NetBSD: patch-aa,v 1.18 2013/04/05 13:30:17 ryoon Exp $
  *)
  	AC_CHECK_LIB(c_r, gethostbyname_r)
  	;;
-@@ -3372,6 +3378,9 @@ AC_CACHE_CHECK(
+@@ -3319,6 +3337,9 @@ AC_CACHE_CHECK(
          #ifdef linux
          #define _BSD_SOURCE 1
          #endif
-+	#ifdef __NetBSD__
-+	#error use of global _res variable in threaded programs is not portable
-+	#endif
++        #ifdef __NetBSD__
++        #error use of global _res variable in threaded programs is not portable
++        #endif
          #include <resolv.h>
          ],
          [int foo = res_ninit(&_res);],
-@@ -4042,6 +4051,14 @@ if test -n "$YASM"; then
+@@ -3989,6 +4010,14 @@ if test -n "$YASM"; then
    _YASM_BUILD=`        echo ${YASM_VERSION} | $AWK -F\. '{ print $4 }'`
  fi
  
@@ -47,7 +82,43 @@ $NetBSD: patch-aa,v 1.18 2013/04/05 13:30:17 ryoon Exp $
  if test -z "$SKIP_LIBRARY_CHECKS"; then
  dnl system JPEG support
  dnl ========================================================
-@@ -5326,8 +5343,8 @@ AC_SUBST(MOZ_WEBRTC_IN_LIBXUL)
+@@ -4016,11 +4045,7 @@ if test "$MOZ_NATIVE_JPEG" = 1; then
+                      #include <jpeglib.h> ],
+                    [ #if JPEG_LIB_VERSION < $MOZJPEG
+                      #error "Insufficient JPEG library version ($MOZJPEG required)."
+-                     #endif
+-                     #ifndef JCS_EXTENSIONS
+-                     #error "libjpeg-turbo JCS_EXTENSIONS required"
+-                     #endif
+-                     ],
++                     #endif ],
+                    MOZ_NATIVE_JPEG=1,
+                    AC_MSG_ERROR([Insufficient JPEG library version for --with-system-jpeg]))
+ fi
+@@ -5212,7 +5237,11 @@ if test -n "$MOZ_WEBRTC"; then
+         dnl Make sure doesn't get matched by *-linux*
+         MOZ_WEBRTC=
+         ;;
+-    *-linux*|*-mingw*|*-darwin*)
++    *-netbsd*)
++        dnl Custom socketvar.h is not compatible with NetBSD.
++        MOZ_WEBRTC=
++        ;;
++    *-linux*|*-mingw*|*-darwin*|*-dragonfly*|*-freebsd*|*-openbsd*)
+         dnl Leave enabled
+         ;;
+     *)
+@@ -5263,6 +5292,9 @@ if test -n "$MOZ_WEBRTC"; then
+     MOZ_VP8_ENCODER=1
+     MOZ_VP8_ERROR_CONCEALMENT=1
+ 
++    dnl with libv4l2 we can support more cameras
++    PKG_CHECK_MODULES(MOZ_LIBV4L2, libv4l2)
++
+     dnl OpenSLES is only available in Android 2.3 and later; we'll change this
+     dnl hard dependency to a dynamic load with graceful runtime failure before
+     dnl we make --enable-webrtc on by default in Android (bug 815905)
+@@ -5299,8 +5331,8 @@ AC_SUBST(MOZ_WEBRTC_IN_LIBXUL)
  AC_SUBST(MOZ_SCTP)
  AC_SUBST(MOZ_SRTP)
  
@@ -58,7 +129,7 @@ $NetBSD: patch-aa,v 1.18 2013/04/05 13:30:17 ryoon Exp $
      MOZ_SAMPLE_TYPE_S16=1
      AC_DEFINE(MOZ_SAMPLE_TYPE_S16)
      AC_SUBST(MOZ_SAMPLE_TYPE_S16)
-@@ -5731,7 +5748,7 @@ MOZ_ALSA=)
+@@ -5704,7 +5736,7 @@ MOZ_ALSA=)
  
  if test -n "$MOZ_ALSA"; then
      AC_DEFINE(MOZ_CUBEB)
@@ -67,3 +138,68 @@ $NetBSD: patch-aa,v 1.18 2013/04/05 13:30:17 ryoon Exp $
           [echo "$MOZ_ALSA_PKG_ERRORS"
            AC_MSG_ERROR([Need alsa for Ogg, Wave or WebM decoding on Linux.  Disable with --disable-ogg --disable-wave --disable-webm.  (On Ubuntu, you might try installing the package libasound2-dev.)])])
  fi
+@@ -8311,16 +8343,26 @@ MOZ_ARG_DISABLE_BOOL(necko-wifi,
+     NECKO_WIFI=,
+     NECKO_WIFI=1)
+ 
+-if test "$OS_ARCH" = "OS2"; then
+-  dnl OS/2 implementation of Necko-WiFi support will be added in bug 506566
+-  NECKO_WIFI=
+-fi
+-if test "$NECKO_WIFI" -a \
+-        "$OS_ARCH" != "Linux" -a \
+-        "$OS_ARCH" != "Darwin" -a \
+-        "$OS_ARCH" != "SunOS" -a \
+-        "$OS_ARCH" != "WINNT"; then
+-  AC_MSG_ERROR([Necko WiFi scanning not supported on your platform, use --disable-necko-wifi])
++if test "$NECKO_WIFI"; then
++  case "$OS_TARGET" in
++    Android)
++      ;;
++    Darwin)
++      ;;
++    SunOS)
++      ;;
++    WINNT)
++      ;;
++    OS2)
++      dnl OS/2 implementation of Necko-WiFi support will be added in bug 506566
++      NECKO_WIFI=
++      ;;
++    *)
++      if test -z "$MOZ_ENABLE_DBUS"; then
++        AC_MSG_ERROR([Necko WiFi scanning needs DBus on your platform, remove --disable-dbus or use --disable-necko-wifi])
++      fi
++      ;;
++  esac
+ fi
+ 
+ if test "$NECKO_WIFI"; then
+@@ -8981,6 +9023,27 @@ elif test "${OS_TARGET}" = "Android"; th
+    fi
+ fi
+ 
++# Keep libcubeb and audio_device backends in sync
++if test -n "$MOZ_ALSA"; then
++   EXTRA_GYP_DEFINES="$EXTRA_GYP_DEFINES -D include_alsa_audio=1"
++else
++   EXTRA_GYP_DEFINES="$EXTRA_GYP_DEFINES -D include_alsa_audio=0"
++fi
++if test -n "$MOZ_PULSEAUDIO"; then
++   EXTRA_GYP_DEFINES="$EXTRA_GYP_DEFINES -D include_pulse_audio=1"
++else
++   EXTRA_GYP_DEFINES="$EXTRA_GYP_DEFINES -D include_pulse_audio=0"
++fi
++
++# Don't try to compile sse4.1 code if toolchain doesn't support
++if test -z "$HAVE_TOOLCHAIN_SUPPORT_MSSE4_1"; then
++  EXTRA_GYP_DEFINES="$EXTRA_GYP_DEFINES -D yuv_disable_asm=1"
++fi
++
++if test -n "$MOZ_LIBV4L2_LIBS"; then
++   EXTRA_GYP_DEFINES="$EXTRA_GYP_DEFINES -D use_libv4l2=1"
++fi
++
+ if test -n "$MOZ_WEBRTC"; then
+    AC_MSG_RESULT("generating WebRTC Makefiles...")
+ 
