Whitespace changes.

diff --git a/mk/plist/libtool-expand b/mk/plist/libtool-expand
--- a/mk/plist/libtool-expand
+++ b/mk/plist/libtool-expand
@@ -1,6 +1,6 @@
 # /bin/sh
 #
-# $NetBSD: libtool-expand,v 1.2 2006/03/30 03:02:40 jlam Exp $
+# $NetBSD: libtool-expand,v 1.3 2006/03/30 03:03:52 jlam Exp $
 #
 # Copyright (c) 2004 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -76,18 +76,18 @@ do
 		continue
 	fi
 
-		if ${GREP} -q "libtool library file" "$lapath"; then
-			. "$lapath"
-			if ${TEST} "$installed" = "no"; then
-				${ECHO} 1>&2 "$self: \`$lapath' was not properly installed"
-				exit 1
-			fi
-			for lib in $library_names $old_library; do
-				libpath="$dir$lib"
-				if ${TEST} ! -f "$libpath"; then
-					${ECHO} 1>&2 "$self: \`$libpath' was not found"
-				fi
-				${ECHO} "$libpath"
-			done
+	if ${GREP} -q "libtool library file" "$lapath"; then
+		. "$lapath"
+		if ${TEST} "$installed" = "no"; then
+			${ECHO} 1>&2 "$self: \`$lapath' was not properly installed"
+			exit 1
 		fi
+		for lib in $library_names $old_library; do
+			libpath="$dir$lib"
+			if ${TEST} ! -f "$libpath"; then
+				${ECHO} 1>&2 "$self: \`$libpath' was not found"
+			fi
+			${ECHO} "$libpath"
+		done
+	fi
 done | ${SORT} -u
