Patch out another unportable "if ! which ..." line. From Sergey Svishchev.

diff --git a/textproc/dict-server/patches/patch-al b/textproc/dict-server/patches/patch-al
--- a/textproc/dict-server/patches/patch-al
+++ b/textproc/dict-server/patches/patch-al
@@ -1,10 +1,10 @@
-$NetBSD: patch-al,v 1.6 2006/06/26 11:39:01 rillig Exp $
+$NetBSD: patch-al,v 1.7 2007/05/19 14:12:05 wiz Exp $
 
 Self-written configure tests are generally not of high quality. This one
 fails to work on NetBSD 3.0.
 
---- configure.orig	2006-06-26 13:34:22.000000000 +0200
-+++ configure	2006-06-26 13:36:17.000000000 +0200
+--- configure.orig	2004-12-23 19:23:26.000000000 +0000
++++ configure
 @@ -3166,7 +3166,7 @@ fi
  done
  test -n "$YACC" || YACC="yacc"
@@ -14,3 +14,12 @@ fails to work on NetBSD 3.0.
     { { echo "$as_me:$LINENO: error: 'yacc' is missing on your system.
  You can get \`bison' from any GNU archive site." >&5
  echo "$as_me: error: 'yacc' is missing on your system.
+@@ -3445,7 +3445,7 @@ _ACEOF
+ fi
+ 
+ fi
+-if ! which `echo $LEX | cut -f 1 -d ' '` >/dev/null 2>&1; then
++if false && ! which `echo $LEX | cut -f 1 -d ' '` >/dev/null 2>&1; then
+    { { echo "$as_me:$LINENO: error: 'lex' is missing on your system.
+ You can get \`flex' from any GNU archive site." >&5
+ echo "$as_me: error: 'lex' is missing on your system.
