Fixed patch-ad: now configure doesn't stop on Mac OS X.

diff --git a/emulators/atari800/patches/patch-ad b/emulators/atari800/patches/patch-ad
--- a/emulators/atari800/patches/patch-ad
+++ b/emulators/atari800/patches/patch-ad
@@ -1,15 +1,17 @@
-$NetBSD: patch-ad,v 1.5 2009/11/04 11:44:15 adam Exp $
+$NetBSD: patch-ad,v 1.6 2010/12/25 10:53:22 adam Exp $
 
 --- configure.orig	2009-03-27 10:13:51.000000000 +0100
 +++ configure
-@@ -3507,7 +3507,6 @@ case "$a8_target" in
+@@ -3506,9 +3506,6 @@ case "$a8_target" in
+         sdlcheck="X_`sdl-config --cflags`"
          if [ "$sdlcheck" != "X_" ]; then
              CFLAGS="$CFLAGS `sdl-config --cflags`"
-             if [ "$a8_host" = "win" ]; then
+-            if [ "$a8_host" = "win" ]; then
 -                CFLAGS=${CFLAGS/-Dmain=SDL_main/}
-             fi
+-            fi
          else
              { { echo "$as_me:$LINENO: error: \"No output from sdl-config!  Is sdl-config installed?\"" >&5
+ echo "$as_me: error: \"No output from sdl-config!  Is sdl-config installed?\"" >&2;}
 @@ -6558,10 +6557,8 @@ _ACEOF
          OBJS="atari_sdl.o"
          CFLAGS="$CFLAGS -ansi -pedantic -Waggregate-return -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wstrict-prototypes -Winline"
