Update sudo to 1.6.9.  We don't take the new default of PAM and no other authentication; that can be enabled by adding pam to the package options if users desire.

diff --git a/security/sudo/patches/patch-ag b/security/sudo/patches/patch-ag
--- a/security/sudo/patches/patch-ag
+++ b/security/sudo/patches/patch-ag
@@ -1,16 +1,52 @@
-$NetBSD: patch-ag,v 1.6 2005/10/10 17:48:10 joerg Exp $
+/* $NetBSD: patch-ag,v 1.7 2007/07/23 16:38:36 tls Exp $ */
 
---- configure.orig	2004-11-26 21:04:30.000000000 +0100
-+++ configure	2005-05-10 21:38:19.000000000 +0200
-@@ -1051,6 +1051,7 @@
+--- configure.orig	2007-07-16 22:47:55.000000000 -0400
++++ configure	2007-07-23 11:16:44.000000000 -0400
+@@ -561,7 +561,7 @@
+       *=*) ac_optarg=`echo "$ac_optarg" | sed "s/'/'\\\\\\\\''/g"`;;
+       *) ac_optarg=yes ;;
+     esac
+-    eval enable_$ac_feature='$ac_optarg' ;;
++    eval "enable_$ac_feature='$ac_optarg'" ;;
+ 
+   -exec-prefix | --exec_prefix | --exec-prefix | --exec-prefi \
+   | --exec-pref | --exec-pre | --exec-pr | --exec-p | --exec- \
+@@ -743,7 +743,7 @@
+       *=*) ac_optarg=`echo "$ac_optarg" | sed "s/'/'\\\\\\\\''/g"`;;
+       *) ac_optarg=yes ;;
+     esac
+-    eval with_$ac_package='$ac_optarg' ;;
++    eval "with_$ac_package='$ac_optarg'" ;;
+ 
+   -without-* | --without-*)
+     ac_package=`expr "x$ac_option" : 'x-*without-\(.*\)'`
+@@ -968,7 +968,7 @@
+   --sbindir=DIR          system admin executables [EPREFIX/sbin]
+   --libexecdir=DIR       program executables [EPREFIX/libexec]
+   --datadir=DIR          read-only architecture-independent data [PREFIX/share]
+-  --sysconfdir=DIR       read-only single-machine data [/etc]
++  --sysconfdir=DIR       read-only single-machine data [PREFIX/etc]
+   --sharedstatedir=DIR   modifiable architecture-independent data [PREFIX/com]
+   --localstatedir=DIR    modifiable single-machine data [PREFIX/var]
+   --libdir=DIR           object code libraries [EPREFIX/lib]
+@@ -1032,6 +1032,7 @@
    --with-devel            add development options
    --with-efence           link with -lefence for malloc() debugging
    --with-csops            add CSOps standard options
 +  --with-nbsdops          add NetBSD standard options
    --without-passwd        don't use passwd/shadow file for authentication
-   --with-skey=DIR       enable S/Key support
-   --with-opie=DIR       enable OPIE support
-@@ -1622,7 +1623,6 @@
+   --with-skey=DIR         enable S/Key support
+   --with-opie=DIR         enable OPIE support
+@@ -1310,7 +1311,7 @@
+ 	  -* ) ac_must_keep_next=true ;;
+ 	esac
+       fi
+-      ac_configure_args="$ac_configure_args$ac_sep\"$ac_arg\""
++      ac_configure_args="$ac_configure_args$ac_sep'$ac_arg'"
+       # Get rid of the leading space.
+       ac_sep=" "
+       ;;
+@@ -1634,7 +1635,6 @@
  test "$mandir" = '${prefix}/man' && mandir='$(prefix)/man'
  test "$bindir" = '${exec_prefix}/bin' && bindir='$(exec_prefix)/bin'
  test "$sbindir" = '${exec_prefix}/sbin' && sbindir='$(exec_prefix)/sbin'
@@ -18,7 +54,7 @@ $NetBSD: patch-ag,v 1.6 2005/10/10 17:48:10 joerg Exp $
  
  
  
-@@ -1820,6 +1820,22 @@
+@@ -1826,6 +1826,23 @@
  fi;
  
  
@@ -38,183 +74,315 @@ $NetBSD: patch-ag,v 1.6 2005/10/10 17:48:10 joerg Exp $
 +esac
 +fi;
 +
++
  # Check whether --with-passwd or --without-passwd was given.
  if test "${with_passwd+set}" = set; then
    withval="$with_passwd"
-@@ -5228,7 +5244,7 @@
-   lt_cv_deplibs_check_method=pass_all
+@@ -7066,7 +7083,7 @@
+   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
+   lt_status=$lt_dlunknown
+   cat > conftest.$ac_ext <<_LT_EOF
+-#line 7069 "configure"
++#line 7086 "configure"
+ #include "confdefs.h"
+ 
+ #if HAVE_DLFCN_H
+@@ -7164,7 +7181,7 @@
+   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
+   lt_status=$lt_dlunknown
+   cat > conftest.$ac_ext <<_LT_EOF
+-#line 7167 "configure"
++#line 7184 "configure"
+ #include "confdefs.h"
+ 
+ #if HAVE_DLFCN_H
+@@ -7313,7 +7330,7 @@
    ;;
+ *-*-irix6*)
+   # Find out which ABI we are using.
+-  $ECHO '#line 7316 "configure"' > conftest.$ac_ext
++  $ECHO '#line 7333 "configure"' > conftest.$ac_ext
+   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+   (eval $ac_compile) 2>&5
+   ac_status=$?
+@@ -7964,11 +7981,11 @@
+    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:7967: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:7984: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:7971: \$? = $ac_status" >&5
++   echo "$as_me:7988: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings
+@@ -8239,11 +8256,11 @@
+    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:8242: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:8259: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:8246: \$? = $ac_status" >&5
++   echo "$as_me:8263: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings
+@@ -8336,11 +8353,11 @@
+    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:8339: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:8356: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>out/conftest.err)
+    ac_status=$?
+    cat out/conftest.err >&5
+-   echo "$as_me:8343: \$? = $ac_status" >&5
++   echo "$as_me:8360: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s out/conftest2.$ac_objext
+    then
+      # The compiler can only warn and ignore the option if not recognized
+@@ -8390,11 +8407,11 @@
+    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:8393: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:8410: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>out/conftest.err)
+    ac_status=$?
+    cat out/conftest.err >&5
+-   echo "$as_me:8397: \$? = $ac_status" >&5
++   echo "$as_me:8414: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s out/conftest2.$ac_objext
+    then
+      # The compiler can only warn and ignore the option if not recognized
+@@ -11372,7 +11389,7 @@
  
--freebsd*)
-+freebsd*|dragonfly*)
-   if echo __ELF__ | $CC -E - | grep __ELF__ > /dev/null; then
-     case $host_cpu in
-     i*86 )
-@@ -8440,7 +8456,7 @@
-       ;;
- 
-     # FreeBSD 3 and greater uses gcc -shared to do shared libraries.
--    freebsd*)
-+    dragonfly*|freebsd*)
-       archive_cmds='$CC -shared -o $lib $libobjs $deplibs $compiler_flags'
-       hardcode_libdir_flag_spec='-R$libdir'
-       hardcode_direct=yes
-@@ -9071,11 +9087,11 @@
-   dynamic_linker=no
-   ;;
- 
--freebsd*)
-+dragonfly*|freebsd*)
-   objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
-   version_type=freebsd-$objformat
-   case $version_type in
--    freebsd-elf*)
-+    dragonfly*|freebsd-elf*)
-       library_names_spec='${libname}${release}${shared_ext}$versuffix ${libname}${release}${shared_ext} $libname${shared_ext}'
-       ;;
-     freebsd-*)
-@@ -11205,7 +11221,7 @@
-   freebsd-elf*)
-     archive_cmds_need_lc_CXX=no
-     ;;
--  freebsd*)
-+  dragonfly*|freebsd*)
-     # FreeBSD 3 and later use GNU C++ and GNU ld with standard ELF
-     # conventions
-     ld_shlibs_CXX=yes
-@@ -12576,11 +12592,11 @@
-   dynamic_linker=no
-   ;;
- 
--freebsd*)
-+dragonfly*|freebsd*)
-   objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
-   version_type=freebsd-$objformat
-   case $version_type in
--    freebsd-elf*)
-+    dragonfly*|freebsd-elf*)
-       library_names_spec='${libname}${release}${shared_ext}$versuffix ${libname}${release}${shared_ext} $libname${shared_ext}'
-       ;;
-     freebsd-*)
-@@ -14890,7 +14906,7 @@
-       ;;
- 
-     # FreeBSD 3 and greater uses gcc -shared to do shared libraries.
--    freebsd*)
-+    dragonfly*|freebsd*)
-       archive_cmds_F77='$CC -shared -o $lib $libobjs $deplibs $compiler_flags'
-       hardcode_libdir_flag_spec_F77='-R$libdir'
-       hardcode_direct_F77=yes
-@@ -15521,11 +15537,11 @@
-   dynamic_linker=no
-   ;;
- 
--freebsd*)
-+dragonfly*|freebsd*)
-   objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
-   version_type=freebsd-$objformat
-   case $version_type in
--    freebsd-elf*)
-+    dragonfly*|freebsd-elf*)
-       library_names_spec='${libname}${release}${shared_ext}$versuffix ${libname}${release}${shared_ext} $libname${shared_ext}'
-       ;;
-     freebsd-*)
-@@ -17123,7 +17139,7 @@
-       ;;
- 
-     # FreeBSD 3 and greater uses gcc -shared to do shared libraries.
--    freebsd*)
-+    dragonfly*|freebsd*)
-       archive_cmds_GCJ='$CC -shared -o $lib $libobjs $deplibs $compiler_flags'
-       hardcode_libdir_flag_spec_GCJ='-R$libdir'
-       hardcode_direct_GCJ=yes
-@@ -17754,11 +17770,11 @@
-   dynamic_linker=no
-   ;;
- 
--freebsd*)
-+dragonfly*|freebsd*)
-   objformat=`test -x /usr/bin/objformat && /usr/bin/objformat || echo aout`
-   version_type=freebsd-$objformat
-   case $version_type in
--    freebsd-elf*)
-+    dragonfly*|freebsd-elf*)
-       library_names_spec='${libname}${release}${shared_ext}$versuffix ${libname}${release}${shared_ext} $libname${shared_ext}'
-       ;;
-     freebsd-*)
-@@ -21737,7 +21753,7 @@
- 		    esac
  		fi
  		;;
 -    *-*-freebsd*)
 +    *-*-freebsd*|*-*-dragonfly*)
  		# FreeBSD has a real setreuid(2) starting with 2.1 and
  		# backported to 2.0.5.  We just take 2.1 and above...
- 		case "`echo $host_os | sed 's/^freebsd\([0-9\.]*\).*$/\1/'`" in
-@@ -29049,6 +29065,58 @@
- _ACEOF
- 
- 	    SUDO_LIBS="${SUDO_LIBS} -lkrb5 -ldes -lcom_err -lasn1"
-+	    echo "$as_me:$LINENO: checking for main in -lcrypto" >&5
-+echo $ECHO_N "checking for main in -lcrypto... $ECHO_C" >&6
-+if test "${ac_cv_lib_crypto_main+set}" = set; then
-+  echo $ECHO_N "(cached) $ECHO_C" >&6
-+else
-+  ac_check_lib_save_LIBS=$LIBS
-+LIBS="-lcrypto  $LIBS"
-+cat >conftest.$ac_ext <<_ACEOF
-+#line $LINENO "configure"
-+/* confdefs.h.  */
-+_ACEOF
-+cat confdefs.h >>conftest.$ac_ext
-+cat >>conftest.$ac_ext <<_ACEOF
-+/* end confdefs.h.  */
-+
-+
-+int
-+main ()
-+{
-+main ();
-+  ;
-+  return 0;
-+}
-+_ACEOF
-+rm -f conftest.$ac_objext conftest$ac_exeext
-+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-+  (eval $ac_link) 2>&5
-+  ac_status=$?
-+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-+  (exit $ac_status); } &&
-+         { ac_try='test -s conftest$ac_exeext'
-+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-+  (eval $ac_try) 2>&5
-+  ac_status=$?
-+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-+  (exit $ac_status); }; }; then
-+  ac_cv_lib_crypto_main=yes
-+else
-+  echo "$as_me: failed program was:" >&5
-+sed 's/^/| /' conftest.$ac_ext >&5
-+
-+ac_cv_lib_crypto_main=no
-+fi
-+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-+LIBS=$ac_check_lib_save_LIBS
-+fi
-+echo "$as_me:$LINENO: result: $ac_cv_lib_crypto_main" >&5
-+echo "${ECHO_T}$ac_cv_lib_crypto_main" >&6
-+if test $ac_cv_lib_crypto_main = yes; then
-+  SUDO_LIBS="${SUDO_LIBS} -lcrypto"
-+fi
-+
- 	    echo "$as_me:$LINENO: checking for main in -lroken" >&5
- echo $ECHO_N "checking for main in -lroken... $ECHO_C" >&6
- if test "${ac_cv_lib_roken_main+set}" = set; then
-@@ -29101,7 +29169,6 @@
-   SUDO_LIBS="${SUDO_LIBS} -lroken"
- fi
- 
--
+ 		case "$OSREV" in
+@@ -11388,6 +11405,8 @@
+ 		fi
+ 		: ${with_pam='maybe'}
+ 		: ${with_logincap='maybe'}
++		# We really want libutil.
++		SUDO_LIBS="${SUDO_LIBS} -lutil"
+ 		;;
+     *-*-*openbsd*)
+ 		# OpenBSD has a real setreuid(2) starting with 3.3 but
+@@ -11420,10 +11439,12 @@
+ 		fi
+ 		: ${with_logincap='maybe'}
+ 				: ${with_pam='maybe'}
++		# We really want libutil.
++		SUDO_LIBS="${SUDO_LIBS} -lutil"
+ 		;;
+     *-*-dragonfly*)
+ 		if test "$with_skey" = "yes"; then
+-		     SUDO_LIBS="${SUDO_LIBS} -lmd"
++		     SUDO_LIBS="${SUDO_LIBS} -lutil -lmd"
+ 		fi
+ 		if test "$CHECKSHADOW" = "true"; then
+ 		    CHECKSHADOW="false"
+@@ -17731,7 +17752,7 @@
+ echo "$as_me: WARNING: unable to find socket() trying -lsocket -lnsl" >&2;}
+ echo "$as_me:$LINENO: checking for socket in -lsocket" >&5
+ echo $ECHO_N "checking for socket in -lsocket... $ECHO_C" >&6
+-if test "${ac_cv_lib_socket_socket_lnsl+set}" = set; then
++if test "${ac_cv_lib_socket_socket+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+@@ -17780,20 +17801,20 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_lib_socket_socket_lnsl=yes
++  ac_cv_lib_socket_socket=yes
  else
    echo "$as_me: failed program was:" >&5
  sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-ac_cv_lib_socket_socket_lnsl=no
++ac_cv_lib_socket_socket=no
+ fi
+ rm -f conftest.err conftest.$ac_objext \
+       conftest$ac_exeext conftest.$ac_ext
+ LIBS=$ac_check_lib_save_LIBS
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_lib_socket_socket_lnsl" >&5
+-echo "${ECHO_T}$ac_cv_lib_socket_socket_lnsl" >&6
+-if test $ac_cv_lib_socket_socket_lnsl = yes; then
++echo "$as_me:$LINENO: result: $ac_cv_lib_socket_socket" >&5
++echo "${ECHO_T}$ac_cv_lib_socket_socket" >&6
++if test $ac_cv_lib_socket_socket = yes; then
+   NET_LIBS="${NET_LIBS} -lsocket -lnsl"; LIBS="${LIBS} -lsocket -lnsl"
+ fi
+ 
+@@ -18127,7 +18148,7 @@
+ echo "$as_me: WARNING: unable to find inet_addr() trying -lsocket -lnsl" >&2;}
+ echo "$as_me:$LINENO: checking for inet_addr in -lsocket" >&5
+ echo $ECHO_N "checking for inet_addr in -lsocket... $ECHO_C" >&6
+-if test "${ac_cv_lib_socket_inet_addr_lnsl+set}" = set; then
++if test "${ac_cv_lib_socket_inet_addr+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+@@ -18176,20 +18197,20 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_lib_socket_inet_addr_lnsl=yes
++  ac_cv_lib_socket_inet_addr=yes
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-ac_cv_lib_socket_inet_addr_lnsl=no
++ac_cv_lib_socket_inet_addr=no
+ fi
+ rm -f conftest.err conftest.$ac_objext \
+       conftest$ac_exeext conftest.$ac_ext
+ LIBS=$ac_check_lib_save_LIBS
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_lib_socket_inet_addr_lnsl" >&5
+-echo "${ECHO_T}$ac_cv_lib_socket_inet_addr_lnsl" >&6
+-if test $ac_cv_lib_socket_inet_addr_lnsl = yes; then
++echo "$as_me:$LINENO: result: $ac_cv_lib_socket_inet_addr" >&5
++echo "${ECHO_T}$ac_cv_lib_socket_inet_addr" >&6
++if test $ac_cv_lib_socket_inet_addr = yes; then
+   NET_LIBS="${NET_LIBS} -lsocket -lnsl"; LIBS="${LIBS} -lsocket -lnsl"
+ fi
+ 
+@@ -19511,10 +19532,9 @@
+ 
+ fi
+ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+-                as_ac_Lib=`echo "ac_cv_lib_krb_main$K4LIBS" | $as_tr_sh`
+-echo "$as_me:$LINENO: checking for main in -lkrb" >&5
++                echo "$as_me:$LINENO: checking for main in -lkrb" >&5
+ echo $ECHO_N "checking for main in -lkrb... $ECHO_C" >&6
+-if eval "test \"\${$as_ac_Lib+set}\" = set"; then
++if test "${ac_cv_lib_krb_main+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+@@ -19557,27 +19577,26 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  eval "$as_ac_Lib=yes"
++  ac_cv_lib_krb_main=yes
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-eval "$as_ac_Lib=no"
++ac_cv_lib_krb_main=no
+ fi
+ rm -f conftest.err conftest.$ac_objext \
+       conftest$ac_exeext conftest.$ac_ext
+ LIBS=$ac_check_lib_save_LIBS
+ fi
+-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+-echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
+-if test `eval echo '${'$as_ac_Lib'}'` = yes; then
++echo "$as_me:$LINENO: result: $ac_cv_lib_krb_main" >&5
++echo "${ECHO_T}$ac_cv_lib_krb_main" >&6
++if test $ac_cv_lib_krb_main = yes; then
+   K4LIBS="-lkrb $K4LIBS"
+ else
+ 
+-	as_ac_Lib=`echo "ac_cv_lib_krb4_main$K4LIBS" | $as_tr_sh`
+-echo "$as_me:$LINENO: checking for main in -lkrb4" >&5
++	echo "$as_me:$LINENO: checking for main in -lkrb4" >&5
+ echo $ECHO_N "checking for main in -lkrb4... $ECHO_C" >&6
+-if eval "test \"\${$as_ac_Lib+set}\" = set"; then
++if test "${ac_cv_lib_krb4_main+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+@@ -19620,20 +19639,20 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  eval "$as_ac_Lib=yes"
++  ac_cv_lib_krb4_main=yes
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-eval "$as_ac_Lib=no"
++ac_cv_lib_krb4_main=no
+ fi
+ rm -f conftest.err conftest.$ac_objext \
+       conftest$ac_exeext conftest.$ac_ext
+ LIBS=$ac_check_lib_save_LIBS
+ fi
+-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+-echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
+-if test `eval echo '${'$as_ac_Lib'}'` = yes; then
++echo "$as_me:$LINENO: result: $ac_cv_lib_krb4_main" >&5
++echo "${ECHO_T}$ac_cv_lib_krb4_main" >&6
++if test $ac_cv_lib_krb4_main = yes; then
+   K4LIBS="-lkrb4 $K4LIBS"
+ else
+   K4LIBS="-lkrb $K4LIBS"
+@@ -20102,13 +20121,6 @@
+     LIBS="$_LIBS"
+ fi
+ 
+-if test "$with_logincap" = "yes"; then
+-    case "$OS" in
+-	freebsd|netbsd)	SUDO_LIBS="${SUDO_LIBS} -lutil"
+-	;;
+-    esac
+-fi
+-
+ if test ${with_pam-'no'} != "no"; then
+                 echo "$as_me:$LINENO: checking for main in -ldl" >&5
+ echo $ECHO_N "checking for main in -ldl... $ECHO_C" >&6
+@@ -21724,7 +21736,7 @@
+     #
+     echo "$as_me:$LINENO: checking for SD_Init in -laceclnt" >&5
+ echo $ECHO_N "checking for SD_Init in -laceclnt... $ECHO_C" >&6
+-if test "${ac_cv_lib_aceclnt_SD_Init_______lpthread_______+set}" = set; then
++if test "${ac_cv_lib_aceclnt_SD_Init+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+@@ -21776,20 +21788,20 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_lib_aceclnt_SD_Init_______lpthread_______=yes
++  ac_cv_lib_aceclnt_SD_Init=yes
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-ac_cv_lib_aceclnt_SD_Init_______lpthread_______=no
++ac_cv_lib_aceclnt_SD_Init=no
+ fi
+ rm -f conftest.err conftest.$ac_objext \
+       conftest$ac_exeext conftest.$ac_ext
+ LIBS=$ac_check_lib_save_LIBS
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_lib_aceclnt_SD_Init_______lpthread_______" >&5
+-echo "${ECHO_T}$ac_cv_lib_aceclnt_SD_Init_______lpthread_______" >&6
+-if test $ac_cv_lib_aceclnt_SD_Init_______lpthread_______ = yes; then
++echo "$as_me:$LINENO: result: $ac_cv_lib_aceclnt_SD_Init" >&5
++echo "${ECHO_T}$ac_cv_lib_aceclnt_SD_Init" >&6
++if test $ac_cv_lib_aceclnt_SD_Init = yes; then
+ 
+ 
+ if test X"$AUTH_EXCL" != X""; then
