If the configure script can't figure out the correct answer, bail out with exit 1 instead of trying an interactive prompt that goes into an infinite loop if stdin is not a tty.

diff --git a/graphics/rayshade/patches/patch-aa b/graphics/rayshade/patches/patch-aa
--- a/graphics/rayshade/patches/patch-aa
+++ b/graphics/rayshade/patches/patch-aa
@@ -1,4 +1,4 @@
-$NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
+$NetBSD: patch-aa,v 1.4 2016/03/11 08:18:12 tnn Exp $
 
 --- Configure.orig	1992-02-10 03:04:23.000000000 +0000
 +++ Configure
@@ -17,7 +17,16 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  
  (alias) >/dev/null 2>&1 && \
      echo "(I see you are using the Korn shell.  Some ksh's blow up on Configure," && \
-@@ -364,7 +364,7 @@ where this is allowed will be marked "(~
+@@ -321,6 +321,8 @@ rm -f .echotmp
+ 
+ : now set up to do reads with possible shell escape and default assignment
+ cat <<EOSC >myread
++echo "ERROR: Configure script tried to use interactive prompt" 1>&2
++exit 1
+ case "\$fastread" in
+ yes) ans=''; echo " " ;;
+ *) ans='!';;
+@@ -364,7 +366,7 @@ where this is allowed will be marked "(~
  EOH
  rp="[Type carriage return to continue]"
  echo $n "$rp $c"
@@ -26,7 +35,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  cat <<EOH
  
  Much effort has been expended to ensure that this shell script will run on
-@@ -386,7 +386,7 @@ SH files.  Configure will offer to let y
+@@ -386,7 +388,7 @@ SH files.  Configure will offer to let y
  EOH
  rp="[Type carriage return to continue]"
  echo $n "$rp $c"
@@ -35,7 +44,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  
  : get old answers, if there is a config file out there
  if test -f ../config.sh; then
-@@ -616,7 +616,8 @@ EOM
+@@ -616,7 +618,8 @@ EOM
  echo " "
  rp="Any additional libraries? [$dflt]"
  $echo $n "$rp $c"
@@ -45,7 +54,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  case "$ans" in
  none) ans='';
  esac
-@@ -720,7 +721,14 @@ fi
+@@ -720,7 +723,14 @@ fi
  echo " "
  set `echo $libc $libnames | tr ' ' '\012' | sort | uniq`
  $echo $n "Extracting names from $* for later perusal...$c"
@@ -61,7 +70,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  $grep printf libc.tmp > libc.ptf
  com="$sed -n -e 's/^.* [ADTS]  *_[_.]*//p' -e 's/^.* [ADTS] //p'"
  eval "$com <libc.ptf >libc.list"
-@@ -823,7 +831,8 @@ if $contains '^times$' libc.list >/dev/n
+@@ -823,7 +833,8 @@ if $contains '^times$' libc.list >/dev/n
  	echo " "
  	rp="What type is returned by times() on this sytem? [$dflt]"
  	$echo $n "$rp $c"
@@ -71,7 +80,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  	clocktype="$ans"
  else
      echo 'times() not found, hope that will do.'
-@@ -872,7 +881,7 @@ $eunicefix filexp
+@@ -872,7 +883,7 @@ $eunicefix filexp
  : determine where manual pages are on this system
  echo " "
  case "$sysman" in
@@ -80,7 +89,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
      ;;
  esac
  if test -d "$sysman"; then
-@@ -1007,7 +1016,8 @@ Venix systems may wish to put "none" and
+@@ -1007,7 +1018,8 @@ Venix systems may wish to put "none" and
  EOM
  rp="Which models are supported? [$dflt]"
  $echo $n "$rp $c"
@@ -90,7 +99,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  models="$ans"
  
  case "$models" in
-@@ -1147,7 +1157,8 @@ else
+@@ -1147,7 +1159,8 @@ else
  	esac
  	rp="Use which C compiler? [$dflt]"
  	$echo $n "$rp $c"
@@ -100,7 +109,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  	cc="$ans"
  fi
  case "$cc" in
-@@ -1171,7 +1182,8 @@ specify the word "none".
+@@ -1171,7 +1184,8 @@ specify the word "none".
  EOH
  rp="What optimizer/debugger flag should be used? [$dflt]"
  $echo $n "$rp $c"
@@ -110,7 +119,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  optimize="$ans"
  case "$optimize" in
  'none') optimize=" ";;
-@@ -1220,7 +1232,8 @@ the C compiler, but you should NOT inclu
+@@ -1220,7 +1234,8 @@ the C compiler, but you should NOT inclu
  EOH
  rp="Any additional cc flags? [$dflt]"
  $echo $n "$rp $c"
@@ -120,7 +129,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  case "$ans" in
  none) ans='';
  esac
-@@ -1258,7 +1271,8 @@ esac
+@@ -1258,7 +1273,8 @@ esac
  echo " "
  rp="Any additional ld flags (NOT including libraries)? [$dflt]"
  $echo $n "$rp $c"
@@ -130,7 +139,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  case "$ans" in
  none) ans='';
  esac
-@@ -1421,7 +1435,8 @@ if $contains '^index$' libc.list >/dev/n
+@@ -1421,7 +1437,8 @@ if $contains '^index$' libc.list >/dev/n
  				echo "Your system has both index() and strchr().  Shall I use"
  				rp="index() rather than strchr()? [$dflt]"
  				$echo $n "$rp $c"
@@ -140,7 +149,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  				case "$ans" in
  					n*) d_index="$define" ;;
  					*)  d_index="$undef" ;;
-@@ -1567,7 +1582,8 @@ EOT
+@@ -1567,7 +1584,8 @@ EOT
  
  rp="What directory holds the Utah Raster Toolkit include files? [$dflt]"
  $echo $n "$rp $c"
@@ -150,7 +159,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  case "$ans" in
  'none')
      urtinc=''
-@@ -1591,7 +1607,8 @@ case "$ans" in
+@@ -1591,7 +1609,8 @@ case "$ans" in
      echo " "
      rp="Where is the Utah Raster Toolkit library? [$dflt]"
      $echo $n "$rp $c"
@@ -160,7 +169,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
      urtlib="$ans"
      urtinc="-I$urtinc"
      ;;
-@@ -1629,7 +1646,8 @@ cont=true
+@@ -1629,7 +1648,8 @@ cont=true
  while $test "$cont"; do
  	rp="Use which function to generate random numbers? [$dflt]"
  	$echo $n "$rp $c"
@@ -170,7 +179,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  	if $test "$ans" = "$dflt"; then
  		: null
  	else
-@@ -1802,7 +1820,8 @@ esac
+@@ -1802,7 +1822,8 @@ esac
  dflt="$voidflags";
  rp="Your void support flags add up to what? [$dflt]"
  $echo $n "$rp $c"
@@ -180,7 +189,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  voidflags="$ans"
  $rm -f try.* .out
  
-@@ -1824,7 +1843,8 @@ while $test "$cont" ; do
+@@ -1824,7 +1845,8 @@ while $test "$cont" ; do
      echo " "
      rp="Where do you want to put the public executables? (~name ok) [$dflt]"
      $echo $n "$rp $c"
@@ -190,7 +199,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
      bin="$ans"
      bin=`filexp $bin`
      if test -d $bin; then
-@@ -1833,7 +1853,8 @@ while $test "$cont" ; do
+@@ -1833,7 +1855,8 @@ while $test "$cont" ; do
  	dflt=n
  	rp="Directory $bin doesn't exist.  Use that name anyway? [$dflt]"
  	$echo $n "$rp $c"
@@ -200,7 +209,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  	dflt=''
  	case "$ans" in
  	y*) cont='';;
-@@ -1968,7 +1989,8 @@ while $test "$cont" ; do
+@@ -1968,7 +1991,8 @@ while $test "$cont" ; do
  	echo " "
  rp="Name of program to make makefile dependencies? [$dflt]"
  $echo $n "$rp $c"
@@ -210,7 +219,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  mkdep="$ans"
  mkdep=`filexp $mkdep`
  if test -f "$mkdep"; then
-@@ -1988,12 +2010,12 @@ $rm -f dep.c dep.h dep.o dep.out
+@@ -1988,12 +2012,12 @@ $rm -f dep.c dep.h dep.o dep.out
  : see if ar generates random libraries by itself
  echo " "
  echo "Checking how to generate random libraries on your machine..."
@@ -229,7 +238,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  	if test -f /usr/bin/ranlib; then
  		ranlib=/usr/bin/ranlib
  	elif test -f /bin/ranlib; then
-@@ -2009,7 +2031,7 @@ else
+@@ -2009,7 +2033,7 @@ else
  		orderlib=true
  		ranlib=":"
  	fi
@@ -238,7 +247,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  
  : determine compiler compiler
  case "$bison" in
-@@ -2024,7 +2046,8 @@ cont=true
+@@ -2024,7 +2048,8 @@ cont=true
      echo " "
  rp="Which compiler compiler (yacc or bison -y) will you use? [$dflt]"
  $echo $n "$rp $c"
@@ -248,7 +257,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  case "$ans" in
  '') ans="$dflt";;
  *bis*) ans="bison -y";;
-@@ -2153,7 +2176,8 @@ fastread=''
+@@ -2153,7 +2178,8 @@ fastread=''
  echo "If you didn't make any mistakes, then just type a carriage return here."
  rp="If you need to edit config.sh, do it as a shell escape here:"
  $echo $n "$rp $c"
@@ -258,7 +267,7 @@ $NetBSD: patch-aa,v 1.3 2006/06/20 22:50:13 joerg Exp $
  case "$ans" in
  '') ;;
  *) : in case they cannot read
-@@ -2205,7 +2229,8 @@ It can take a while, so you might not wa
+@@ -2205,7 +2231,8 @@ It can take a while, so you might not wa
  EOM
      rp="Run make depend now? [$dflt]"
      $echo $n "$rp $c"
