dar: updated to 2.8.5
from 2.8.4 to 2.8.5
- fixing bug of one-hour-shift in non-daylight saving months for
  time-zones that have one.
  dar_manager and dar can be given a date (-w option for dar_manager,
  -af option for dar) which is expected to be provided in local time.
  But libdar wrongly assumed it to always be given as summer time (or
  daylight saving time) even when the given date took place in a
  non-daylight saving period (winter time), which led most of the
  time to a shift of one hour in the past in the selected files.
  Dar_manager using the -w option was restoring files older than the
  provided date but forgot the ones having a modification date less
  than one hour before the provided date/time when this date/time
  was not in non-daylight saving period (winter time). Those were
  restored in a earlier state or not restored at all if they did not
  exist before that one hour shifted date.
  With dar using -af option, this led dar to save files after the
  given date as expected but also saving the files older than the
  provided date for less an one hour, when this date was in non-daylight
  saving period (winter time). Other files being saved as expected
  as "un-modified" (only metadata saved).
- fixed one field lack of initialization in archive_options_isolate
  classes (copy and move constructors).
- fixing bug that could occur while more bytes are read than available

diff --git a/archivers/dar/patches/patch-configure b/archivers/dar/patches/patch-configure
--- a/archivers/dar/patches/patch-configure
+++ b/archivers/dar/patches/patch-configure
@@ -1,15 +1,15 @@
-$NetBSD: patch-configure,v 1.1 2022/10/03 13:59:05 nros Exp $
+$NetBSD: patch-configure,v 1.2 2026/07/19 08:23:59 adam Exp $
 
-* compatability fix
+Portability fix
 
---- configure.orig	2022-08-07 10:42:43.000000000 +0000
+--- configure.orig	2026-04-27 14:22:54.000000000 +0000
 +++ configure
-@@ -27616,7 +27616,7 @@ $as_echo "$as_me: WARNING: python bindin
+@@ -30067,7 +30067,7 @@ printf "%s\n" "$as_me: WARNING: python b
  
- else
+ else $as_nop
  
 -                 if test "x$enable_shared" != "xyes" -o "$debug_static" == "yes" ; then
 +                 if test "x$enable_shared" != "xyes" -o "$debug_static" = "yes" ; then
-                    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot build python binding without shared library support" >&5
- $as_echo "$as_me: WARNING: Cannot build python binding without shared library support" >&2;}
+                    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Cannot build python binding without shared library support" >&5
+ printf "%s\n" "$as_me: WARNING: Cannot build python binding without shared library support" >&2;}
                     local_python="no"
