Update pan to 0.10.0.92.  Changes are too many to list in detail, but include tons of bugfixes and feature updates.  For a detailled list, please see http://pan.rebelbase.com/#010092

diff --git a/news/pan/patches/patch-aa b/news/pan/patches/patch-aa
--- a/news/pan/patches/patch-aa
+++ b/news/pan/patches/patch-aa
@@ -1,24 +1,23 @@
-$NetBSD: patch-aa,v 1.1.1.1 2001/04/24 14:14:09 rh Exp $
+$NetBSD: patch-aa,v 1.2 2001/10/15 07:24:38 rh Exp $
 
---- configure.orig	Sun Apr 22 11:51:35 2001
+--- configure.orig	Sat Oct  6 17:49:48 2001
 +++ configure
-@@ -3009,13 +3009,13 @@
- if { (eval echo configure:3010: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-   rm -rf conftest*
+@@ -5424,12 +5424,12 @@
+   echo "$as_me:5424: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
    CATOBJEXT=.gmo
 -		   DATADIRNAME=share
 +		   DATADIRNAME=${LOCALEDIR}
  else
-   echo "configure: failed program was:" >&5
-   cat conftest.$ac_ext >&5
-   rm -rf conftest*
-   CATOBJEXT=.mo
+   echo "$as_me: failed program was:" >&5
+ cat conftest.$ac_ext >&5
+ CATOBJEXT=.mo
 -		   DATADIRNAME=lib
 +		   DATADIRNAME=${LOCALEDIR}
  fi
- rm -f conftest*
+ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
  		INSTOBJEXT=.mo
-@@ -3244,7 +3244,7 @@
+@@ -5682,7 +5682,7 @@
        # We need to process the po/ directory.
        POSUB=po
      else
