Update to 0.85.4: Downloads are now automatically handled by one client instead of spreading them among the running clients. A problem with incorrectly handling trailing corrupted segments was fixed, and users with a slash in their nicknames are handled properly.

diff --git a/net/dctc/patches/patch-ab b/net/dctc/patches/patch-ab
--- a/net/dctc/patches/patch-ab
+++ b/net/dctc/patches/patch-ab
@@ -1,12 +1,12 @@
-$NetBSD: patch-ab,v 1.4 2003/06/10 13:20:24 wiz Exp $
+$NetBSD: patch-ab,v 1.5 2003/07/15 19:46:15 wiz Exp $
 
---- configure.orig	Tue Jun 10 12:13:42 2003
+--- configure.orig	Sun Jul 13 23:40:52 2003
 +++ configure
-@@ -6591,6 +6591,7 @@ fi
+@@ -9752,6 +9752,7 @@ fi
  							if test "x$HAVE_DB40" = "xyes"; then
- 								
+ 
  								berkeleydb_libs="-ldb4"
-+      								CPPFLAGS="$CPPFLAGS -DBDB_V4"
++							        CPPFLAGS="$CPPFLAGS -DBDB_V4"
  							else
- 								{ echo "configure: error: no supported BerkeleyDB found (4.1, 4.0, 3.1, 3.2, 3.3)" 1>&2; exit 1; }
- 							fi
+ 								{ { echo "$as_me:$LINENO: error: no supported BerkeleyDB found (4.1, 4.0, 3.1, 3.2, 3.3)" >&5
+ echo "$as_me: error: no supported BerkeleyDB found (4.1, 4.0, 3.1, 3.2, 3.3)" >&2;}
