Update to 1.5.1:
Version 1.5.1 <2007.07.07>
--------------------------

  * added burning under Windows
  * added support of dvdisaster (thanks to Torsten Rupp)
  * added Czech translation (thanks to Vlastimil Skacel)
  * added Dutch translation (thanks to Patrick Vijgeboom)
  * added Swedish translation (thanks to Daniel Nylander)

Version 1.5 final <2007.05.16>
------------------------------

  * new stable release
  * fixed some bugs

Version 1.5 beta 7 <2006.11.10>
-------------------------------

  * added selection of video and audio format for DVD
  * fixed spumux error

Version 1.5 beta 6 <2006.10.12>
-------------------------------

  * new logo (thanks to Alejandro Slocker Escarpa)
  * added play all flag to button action
  * added displaying of safe tv area
  * added displaying of grid
  * now buttons are always over objects
  * fixed error when generating dvd with text based buttons
  * added new button based upon a picture by Benji Park (thanks to Fgoset)

Version 1.5 beta 5 <2006.03.15>
-------------------------------

  * added possibility to arrange menu objects/buttons
  * added possibility to specify volume name
  * added two new buttons
  * fixed some bugs

diff --git a/multimedia/dvdstyler/patches/patch-ac b/multimedia/dvdstyler/patches/patch-ac
--- a/multimedia/dvdstyler/patches/patch-ac
+++ b/multimedia/dvdstyler/patches/patch-ac
@@ -1,8 +1,8 @@
-$NetBSD: patch-ac,v 1.1 2007/10/15 06:07:19 wiz Exp $
+$NetBSD: patch-ac,v 1.2 2007/10/25 00:02:02 wiz Exp $
 
---- configure.orig	2005-10-19 09:02:58.000000000 +0000
+--- configure.orig	2007-03-19 17:18:01.000000000 +0000
 +++ configure
-@@ -873,6 +1325,10 @@ Optional Features:
+@@ -1325,6 +1325,10 @@ Optional Features:
    --enable-debug          Enable debugging information
    --disable-dependency-tracking Speeds up one-time builds
    --enable-dependency-tracking  Do not reject slow dependency extractors
@@ -13,7 +13,7 @@ $NetBSD: patch-ac,v 1.1 2007/10/15 06:07:19 wiz Exp $
  
  Optional Packages:
    --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
-@@ -4047,11 +4524,19 @@ else
+@@ -4505,6 +4509,14 @@ else
  fi
  
  else
@@ -28,12 +28,7 @@ $NetBSD: patch-ac,v 1.1 2007/10/15 06:07:19 wiz Exp $
  
    # Extract the first word of "kde-config", so it can be a program name with args.
  set dummy kde-config; ac_word=$2
- echo "$as_me:$LINENO: checking for $ac_word" >&5
- echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
- if test "${ac_cv_path_KDE_CONFIG+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-@@ -4115,16 +4601,29 @@ else
+@@ -4574,6 +4586,19 @@ else
  fi
  
  
@@ -51,19 +46,9 @@ $NetBSD: patch-ac,v 1.1 2007/10/15 06:07:19 wiz Exp $
 +
 +	if test x"$ac_cv_enable_gnome" = x"yes" ; then
  
-   echo "$as_me:$LINENO: checking for GNOME data directory" >&5
- echo $ECHO_N "checking for GNOME data directory... $ECHO_C" >&6
-   GNOME_DATA_DIR=`gnome-config --datadir 2>/dev/null`
-   if test x$GNOME_DATA_DIR = x ; then
-      echo "$as_me:$LINENO: result: no" >&5
- echo "${ECHO_T}no" >&6
-   else
-      echo "$as_me:$LINENO: result: $GNOME_DATA_DIR" >&5
- echo "${ECHO_T}$GNOME_DATA_DIR" >&6
-   fi
- 
- 
-@@ -4138,13 +4637,18 @@ else
+   { echo "$as_me:$LINENO: checking for GNOME data directory" >&5
+ echo $ECHO_N "checking for GNOME data directory... $ECHO_C" >&6; }
+@@ -4597,11 +4622,18 @@ else
  fi
  
  
@@ -77,25 +62,12 @@ $NetBSD: patch-ac,v 1.1 2007/10/15 06:07:19 wiz Exp $
  LIBS="$LIBS $WX_LIBS "
  
  
- echo "$as_me:$LINENO: checking for main in -lwxsvg" >&5
- echo $ECHO_N "checking for main in -lwxsvg... $ECHO_C" >&6
++
++
+ { echo "$as_me:$LINENO: checking for main in -lwxsvg" >&5
+ echo $ECHO_N "checking for main in -lwxsvg... $ECHO_C" >&6; }
  if test "${ac_cv_lib_wxsvg_main+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-@@ -4611,28 +5259,37 @@ fi
- 
- 
- 
-   echo "$as_me:$LINENO: checking if wxWindows was linked with GTK2" >&5
- echo $ECHO_N "checking if wxWindows was linked with GTK2... $ECHO_C" >&6
-   if $WX_CONFIG_NAME --libs | grep 'gtk2' > /dev/null ; then
-      GTK_USEDVERSION=2
-      echo "$as_me:$LINENO: result: yes" >&5
- echo "${ECHO_T}yes" >&6
-   else
-      echo "$as_me:$LINENO: result: no" >&5
- echo "${ECHO_T}no" >&6
-   fi
+@@ -5225,7 +5257,16 @@ echo "${ECHO_T}no" >&6; }
  
  
  
@@ -113,20 +85,8 @@ $NetBSD: patch-ac,v 1.1 2007/10/15 06:07:19 wiz Exp $
  
  
  if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
- 	if test -n "$ac_tool_prefix"; then
-   # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
- set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
- echo "$as_me:$LINENO: checking for $ac_word" >&5
- echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
- if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-@@ -4777,13 +5449,16 @@ echo "$as_me: WARNING: libgnomeui will n
- else
- 	GNOMEUI2_CFLAGS=$pkg_cv_GNOMEUI2_CFLAGS
- 	GNOMEUI2_LIBS=$pkg_cv_GNOMEUI2_LIBS
-         echo "$as_me:$LINENO: result: yes" >&5
- echo "${ECHO_T}yes" >&6
+@@ -5417,9 +5458,12 @@ else
+ echo "${ECHO_T}yes" >&6; }
  	GNOME2="-DGNOME2"
  fi
 +	CXXFLAGS="$CXXFLAGS $GNOME2"
@@ -140,3 +100,20 @@ $NetBSD: patch-ac,v 1.1 2007/10/15 06:07:19 wiz Exp $
  
  CXXFLAGS="$CXXFLAGS -DDATADIR=\\\"$datadir/$PACKAGE\\\""
  
+@@ -5787,7 +5831,7 @@ echo "$as_me: error:
+    { (exit 1); exit 1; }; }
+ fi
+ 
+-ac_config_files="$ac_config_files Makefile src/Makefile src/rc/Makefile wxVillaLib/Makefile locale/Makefile backgrounds/Makefile buttons/Makefile objects/Makefile data/Makefile install.win32/Makefile"
++ac_config_files="$ac_config_files Makefile src/Makefile src/rc/Makefile wxVillaLib/Makefile locale/Makefile backgrounds/Makefile buttons/Makefile objects/Makefile data/Makefile"
+ 
+ cat >confcache <<\_ACEOF
+ # This file is a shell script that caches the results of configure
+@@ -6432,7 +6476,6 @@ do
+     "buttons/Makefile") CONFIG_FILES="$CONFIG_FILES buttons/Makefile" ;;
+     "objects/Makefile") CONFIG_FILES="$CONFIG_FILES objects/Makefile" ;;
+     "data/Makefile") CONFIG_FILES="$CONFIG_FILES data/Makefile" ;;
+-    "install.win32/Makefile") CONFIG_FILES="$CONFIG_FILES install.win32/Makefile" ;;
+ 
+   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
+ echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
