Fix up sysutils/tkdesk, some.
 - Fix up the TCL interpreter result handling so we don't need to use
   USE_INTERP_RESULT.

 - Fix the first startup segfault (probably the one seen in PR 32807
   but not necessarily) by using Tcl_Free instead of trying to bypass
   it. Unfortunately, there's at least one more segfault at startup
   with no obvious cause.

 - Don't run off the end of string buffers.

 - Remove some uses of sprintf. Use standard headers. Other minor
   tidyups.

 - Correct glitch in the configury patches that made it link
   statically to blt.

 - Avoid passing empty variable names to test(1) during configure.

 - Fix some pkglint.

Bump PKGREVISION to 4, because even though it didn't run and still
doesn't, it does build. :-|

diff --git a/sysutils/tkdesk/patches/patch-aa b/sysutils/tkdesk/patches/patch-aa
--- a/sysutils/tkdesk/patches/patch-aa
+++ b/sysutils/tkdesk/patches/patch-aa
@@ -1,7 +1,12 @@
-$NetBSD: patch-aa,v 1.3 2006/10/14 02:18:37 rillig Exp $
+$NetBSD: patch-aa,v 1.4 2022/06/06 05:11:58 dholland Exp $
 
---- configure.orig	2004-04-14 05:39:47.000000000 +0200
-+++ configure	2006-10-14 04:17:03.000000000 +0200
+- Remove bashisms.
+- Fix itcl library names.
+- Fix BLT library names.
+- Avoid print from test(1) because ITCL_MAJOR_VERSION is never actually set.
+
+--- configure.orig	2004-04-14 03:39:47.000000000 +0000
++++ configure
 @@ -1430,7 +1430,7 @@ TK_LIB_STATIC=${TKCONF_PATH}/libtk${TK_V
  # Check for the TkStep libraries (if needed)...
  #
@@ -29,9 +34,12 @@ $NetBSD: patch-aa,v 1.3 2006/10/14 02:18:37 rillig Exp $
        { echo "$as_me:$LINENO: WARNING: you may be attempting to use TkDesk 2.x with an unsupported version of Tk.  Good luck.  Hope it works out for you." >&5
  echo "$as_me: WARNING: you may be attempting to use TkDesk 2.x with an unsupported version of Tk.  Good luck.  Hope it works out for you." >&2;}
     else
-@@ -1505,7 +1505,7 @@ echo $ECHO_N "checking version of Itcl..
+@@ -1503,9 +1503,9 @@ echo "${ECHO_T}$ITCLCONF_PATH/$ITCLCONF_
+ echo $ECHO_N "checking version of Itcl... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $ITCL_VERSION" >&5
  echo "${ECHO_T}$ITCL_VERSION" >&6
-    if test "$ITCL_MAJOR_VERSION" -ne 3; then
+-   if test "$ITCL_MAJOR_VERSION" -ne 3; then
++   if test "${ITCL_MAJOR_VERSION:-3}" -ne 3; then
        echo
 -      if test "$ENABLE_UNSUPPORTED" == "yes" ; then
 +      if test "$ENABLE_UNSUPPORTED" = "yes" ; then
@@ -52,17 +60,28 @@ $NetBSD: patch-aa,v 1.3 2006/10/14 02:18:37 rillig Exp $
    fi
  fi
  
-@@ -1570,11 +1570,9 @@ else
-    BLT_LIB_SPEC="-L$BLT_LIB_PATH -lBLT"
-    BLT_LIB_STATIC=$BLT_LIB_PATH/libBLT.a
+@@ -1567,17 +1567,17 @@ if test -z "$BLT_LIB_PATH" ; then
+    echo "$as_me:$LINENO: result: ./blt" >&5
+ echo "${ECHO_T}./blt" >&6
+ else
+-   BLT_LIB_SPEC="-L$BLT_LIB_PATH -lBLT"
+-   BLT_LIB_STATIC=$BLT_LIB_PATH/libBLT.a
++   BLT_LIB_SPEC="-L$BLT_LIB_PATH -lBLT24"
++   BLT_LIB_STATIC=$BLT_LIB_PATH/libBLT24.a
     NEED_BLT_LIB=
 -   if test   ! -f $BLT_LIB_PATH/libBLT.a \
 -          -a ! -f $BLT_LIB_PATH/libBLT.so
-+   if test   ! -f $BLT_LIB_PATH/libBLT.a
++   if test   ! -f $BLT_LIB_PATH/libBLT24.a \
++          -a ! -f $BLT_LIB_PATH/libBLT24.so
     then
 -      if test   ! -f $BLT_LIB_PATH/lib/libBLT.a \
 -	     -a ! -f $BLT_LIB_PATH/lib/libBLT.so
-+      if test   ! -f $BLT_LIB_PATH/lib/libBLT.a
++      if test   ! -f $BLT_LIB_PATH/lib/libBLT24.a \
++	     -a ! -f $BLT_LIB_PATH/lib/libBLT24.so
        then
  	 echo
- 	 { { echo "$as_me:$LINENO: error: could not find libBLT.a or libBLT.so in $BLT_LIB_PATH or in $BLT_LIB_PATH/lib." >&5
+-	 { { echo "$as_me:$LINENO: error: could not find libBLT.a or libBLT.so in $BLT_LIB_PATH or in $BLT_LIB_PATH/lib." >&5
++	 { { echo "$as_me:$LINENO: error: could not find libBLT24.a or libBLT24.so in $BLT_LIB_PATH or in $BLT_LIB_PATH/lib." >&5
+ echo "$as_me: error: could not find libBLT.a or libBLT.so in $BLT_LIB_PATH or in $BLT_LIB_PATH/lib." >&2;}
+    { (exit 1); exit 1; }; }
+       else
