Update net/rabbitmq to 3.6.0. Clean up and simplify Makefile.
Breaking changes in 3.6.0:

- Minimum required Erlang version is R16B03 for plain ("just TCP")
  connections for all protocols and 17.5 for TLS ones (18.x is
  recommended for both).
- .NET client now requires .NET 4.5.
- "Immediate" flag is removed from the .NET client (it hasn't been
  supported by the server since RabbitMQ 3.0).
- Default subscription TTL in MQTT is now 24 hours.
- Server artifacts are now distributed as xz archives and not gz.
- Build system has been completely reworked and now uses erlang.mk.
  3rd party plugins must be adapted to the new build system.

Key improvements in this release are:

- Lazy queues
- Much better queue synchronisation throughput
- Lower RAM use, tunable flow control
- Stronger password encryption with pluggable algorithms
- Development moved to GitHub; build system now uses erlang.mk
- Significant improvements to Web STOMP
- Experimental WinRT-compatible .NET client, SQL CLR compatibility
  in the "regular" one
- Pagination in management UI
- More popular plugins now ship with the broker: rabbitmq_sharding
  and rabbitmq_event_exchange, for example.

Full release notes:

  https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_0

diff --git a/net/rabbitmq/patches/patch-scripts_rabbitmq-env b/net/rabbitmq/patches/patch-scripts_rabbitmq-env
--- a/net/rabbitmq/patches/patch-scripts_rabbitmq-env
+++ b/net/rabbitmq/patches/patch-scripts_rabbitmq-env
@@ -1,37 +1,37 @@
-$NetBSD: patch-scripts_rabbitmq-env,v 1.1 2015/11/20 12:26:21 fhajny Exp $
+$NetBSD: patch-scripts_rabbitmq-env,v 1.2 2015/12/31 22:16:33 fhajny Exp $
 
 Remove cumbersome symlink handling, we know where stuff is.
 
---- scripts/rabbitmq-env.orig	2015-10-07 12:45:15.000000000 +0000
+--- scripts/rabbitmq-env.orig	2015-11-12 16:42:49.000000000 +0000
 +++ scripts/rabbitmq-env
-@@ -15,29 +15,7 @@
- ##  Copyright (c) 2007-2015 Pivotal Software, Inc.  All rights reserved.
- ##
+@@ -20,29 +20,7 @@ if [ "$RABBITMQ_ENV_LOADED" = 1 ]; then
+ fi
  
--# We set +e here since since our test for "readlink -f" below needs to
--# be able to fail.
--set +e
--# Determine where this script is really located (if this script is
--# invoked from another script, this is the location of the caller)
--SCRIPT_PATH="$0"
--while [ -h "$SCRIPT_PATH" ] ; do
--    # Determine if readlink -f is supported at all. TODO clean this up.
--    FULL_PATH=`readlink -f $SCRIPT_PATH 2>/dev/null`
--    if [ "$?" != "0" ]; then
--      REL_PATH=`readlink $SCRIPT_PATH`
--      if expr "$REL_PATH" : '/.*' > /dev/null; then
--        SCRIPT_PATH="$REL_PATH"
--      else
--        SCRIPT_PATH="`dirname "$SCRIPT_PATH"`/$REL_PATH"
--      fi
--    else
--      SCRIPT_PATH=$FULL_PATH
--    fi
--done
--set -e
+ if [ -z "$RABBITMQ_SCRIPTS_DIR" ]; then
+-    # We set +e here since since our test for "readlink -f" below needs to
+-    # be able to fail.
+-    set +e
+-    # Determine where this script is really located (if this script is
+-    # invoked from another script, this is the location of the caller)
+-    SCRIPT_PATH="$0"
+-    while [ -h "$SCRIPT_PATH" ] ; do
+-        # Determine if readlink -f is supported at all. TODO clean this up.
+-        FULL_PATH=`readlink -f $SCRIPT_PATH 2>/dev/null`
+-        if [ "$?" != "0" ]; then
+-          REL_PATH=`readlink $SCRIPT_PATH`
+-          if expr "$REL_PATH" : '/.*' > /dev/null; then
+-            SCRIPT_PATH="$REL_PATH"
+-          else
+-            SCRIPT_PATH="`dirname "$SCRIPT_PATH"`/$REL_PATH"
+-          fi
+-        else
+-          SCRIPT_PATH=$FULL_PATH
+-        fi
+-    done
+-    set -e
 -
--SCRIPT_DIR=`dirname $SCRIPT_PATH`
-+SCRIPT_DIR="@RABBITMQ_HOME@/sbin"
- RABBITMQ_HOME="${SCRIPT_DIR}/.."
+-    RABBITMQ_SCRIPTS_DIR=`dirname $SCRIPT_PATH`
++    RABBITMQ_SCRIPTS_DIR="@RABBITMQ_HOME@/sbin"
+ fi
  
- ## Set defaults
+ rmq_realpath() {
