Update to 0.8.6d (latest stable version), based on wip/vlc update done by Adam Hoka (thank you!).
Changes between 0.8.6c and 0.8.6d:
----------------------------------------------------------

Various bugfixes:
* Mozilla plugin: supports a reasonable amount of MIME types on Windows
* Linux: Fixed S/PDIF passthrough with ALSA
* Automatic recovery on unexpected stream discontinuity (clock gap) occurrences in input
* Use field order (top/bottom) for correct bob/linear deinterlacing
* Fix invalid free in bookmarks loading code

Windows and Mac OS Binaries
* FLAC Security Update (CVE-2007-4619) to prevent multiple integer overflows

Active X plugin:
* Security update (VideoLAN-SA-0703)

Mac OS X Interface & Port:
* Apple Remote support on Mac OS X 10.5 Leopard with enhanced functionality
* Improved Video Output compatibility for Mac OS X 10.5 Leopard
* Improved behavior of the Fullscreen Controller and mode changes between
  Fullscreen and Windowed Video Output
* Softened the white flash artifacts that may appear during the transition
  of two different movies
* Support for current Ogg file formats
NOTE: This release requires Mac OS X 10.4 or higher. Mac OS X 10.3.9 is
not supported anymore.

Encoders:
* Improved H.264 encoding speed on Mac OS X

Other changes:
* The automatic updating facility was removed
* You now need to append --m3u-extvlcopt to your command line to enable
  EXTVLCOPT options parsing in m3u playlists.

...and more, see the NEWS file.

diff --git a/multimedia/vlc/patches/patch-aa b/multimedia/vlc/patches/patch-aa
--- a/multimedia/vlc/patches/patch-aa
+++ b/multimedia/vlc/patches/patch-aa
@@ -1,13 +1,13 @@
-$NetBSD: patch-aa,v 1.4 2006/09/26 07:27:19 martti Exp $
+$NetBSD: patch-aa,v 1.5 2008/02/20 13:11:00 xtraeme Exp $
 
---- include/vlc_common.h.orig	2006-05-19 19:46:18.000000000 +0000
-+++ include/vlc_common.h
-@@ -873,7 +873,7 @@ static inline void _SetQWBE( uint8_t *p,
- #   define vlc_strtoll NULL
- #endif
+--- configure.orig	2007-11-27 20:22:58.000000000 +0100
++++ configure
+@@ -64116,7 +64116,7 @@ fi
  
--#if defined(SYS_BEOS)
-+#if defined(SYS_BEOS) || defined(__DragonFly__)
-     typedef struct {
-         long long quot; /* Quotient. */
-         long long rem;  /* Remainder. */
+ if test "${enable_java_bindings}" = "yes"
+ then
+-  if test "x${JAVA_HOME}" == "x"; then
++  if test "x${JAVA_HOME}" = "x"; then
+   { { echo "$as_me:$LINENO: error: Please set the JAVA_HOME variable to your JDK environment" >&5
+ echo "$as_me: error: Please set the JAVA_HOME variable to your JDK environment" >&2;}
+    { (exit 1); exit 1; }; }
