update to 3.5.22, from Ryo ONODERA per PR pkg/43711 changes: Various bug fixes
(tested the lib part with evince)

diff --git a/graphics/djvulibre-lib/patches/patch-ad b/graphics/djvulibre-lib/patches/patch-ad
--- a/graphics/djvulibre-lib/patches/patch-ad
+++ b/graphics/djvulibre-lib/patches/patch-ad
@@ -1,8 +1,8 @@
-$NetBSD: patch-ad,v 1.4 2009/02/20 10:52:57 drochner Exp $
+$NetBSD: patch-ad,v 1.5 2010/08/09 11:05:55 drochner Exp $
 
---- configure.orig	2008-07-03 00:43:52.000000000 +0200
+--- configure.orig	2009-05-21 15:15:50.000000000 +0000
 +++ configure
-@@ -21069,13 +21069,12 @@ fi
+@@ -21124,13 +21124,12 @@ fi
     for opt in $saved_CXXFLAGS ; do
       case $opt in
         -g*) test $ac_debug != no && OPTS="$OPTS $opt" ;;
@@ -17,7 +17,7 @@ $NetBSD: patch-ad,v 1.4 2009/02/20 10:52:57 drochner Exp $
         *) CFLAGS="$CFLAGS $opt" ;;
       esac
     done
-@@ -21107,7 +21106,6 @@ echo $ECHO_N "checking if $CXX accepts $
+@@ -21162,7 +21161,6 @@ echo $ECHO_N "checking if $CXX accepts $
      { echo "$as_me:$LINENO: result: yes" >&5
  echo "${ECHO_T}yes" >&6; }
      rm conftest.*
@@ -25,7 +25,7 @@ $NetBSD: patch-ad,v 1.4 2009/02/20 10:52:57 drochner Exp $
   else
      { echo "$as_me:$LINENO: result: no" >&5
  echo "${ECHO_T}no" >&6; }
-@@ -21121,7 +21119,6 @@ echo $ECHO_N "checking if $CXX accepts $
+@@ -21176,7 +21174,6 @@ echo $ECHO_N "checking if $CXX accepts $
      { echo "$as_me:$LINENO: result: yes" >&5
  echo "${ECHO_T}yes" >&6; }
      rm conftest.*
@@ -33,7 +33,7 @@ $NetBSD: patch-ad,v 1.4 2009/02/20 10:52:57 drochner Exp $
   else
      { echo "$as_me:$LINENO: result: no" >&5
  echo "${ECHO_T}no" >&6; }
-@@ -21162,7 +21159,6 @@ echo $ECHO_N "checking if $CXX accepts $
+@@ -21217,7 +21214,6 @@ echo $ECHO_N "checking if $CXX accepts $
      { echo "$as_me:$LINENO: result: yes" >&5
  echo "${ECHO_T}yes" >&6; }
      rm conftest.*
@@ -41,11 +41,12 @@ $NetBSD: patch-ad,v 1.4 2009/02/20 10:52:57 drochner Exp $
   else
      { echo "$as_me:$LINENO: result: no" >&5
  echo "${ECHO_T}no" >&6; }
-@@ -21691,6 +21687,7 @@ main ()
- __sync_lock_test_and_set(&l,1);
-   __sync_lock_release(&l);
-   __sync_add_and_fetch(&l,1);
-+  __sync_bool_compare_and_swap(&l,0,1);
-   return 0;
-   ;
-   return 0;
+@@ -27704,7 +27700,7 @@ fi
+ 
+ 
+     CFLAGS="$savedCFLAGS"
+-    if test "$no_xt" == "yes" ; then
++    if test "$no_xt" = "yes" ; then
+         { echo "$as_me:$LINENO: WARNING: Xt include files not found" >&5
+ echo "$as_me: WARNING: Xt include files not found" >&2;}
+     else
