Update to 1.0.8:
Adam Jackson (1):
      xinit 1.0.8

David Nusinow (1):
      Unbreak installs on non-launchd systems

James Cloos (1):
      Add missing PHONY line for automatic ChangeLog generation

Jeremy Huddleston (19):
      Added some support for Xquartz on OS-X.
      Added Apple launchd support
      Changed x11-exec to actually start X11.app.  X11.app will be responsible for calling xinit.
      OS-X: Added argv[0] hack for finding Xquartz UI and icon as well as claiming its dock icon
      Added support for OS-X preferences to disable tcp/ip connections and xauth
      OS-X: Made defaults test more robust
      OS-X: Need to use bash --login to setup the environment from launchd.
      XQuartz doesn't need the -launchd command line argument anymore.
      OS-X: Properly set enable_xauth if the user has no defaults set and choose a valid $display for fast-user-switching.
      OS-X: Add bindir to $PATH in startx if it's not there
      OS-X: Fixed typo
      OS-X: Set fontpath in xinitrc to include system / user fonts.  Additionally fixed font scaling issues (trac #52)
      Apple: use -nocpp arg to xrdb if cpp is not installed
      Apple: Cleaned up font path setting and added font caching to xinitrc
      Apple: Support spaces in $HOME for font path, and remove duplicate entry
      Added org.x.X11.plist.cpp to EXTRA_DIST
      Apple: font caching and defaults
      Apple: Adding support for an xinitrc.d directory on OSX, so fink doesn't need to clobber files
      Apple: Use -c in the launchd plist, so broken .profile/.bashrc don't much up startx

Matthieu Herrb (1):
      Use /dev/arandom instead of /dev/urandom to generate the cookie

root (1):
      Define APPLE for the rest of us

diff --git a/x11/xinit/patches/patch-aa b/x11/xinit/patches/patch-aa
--- a/x11/xinit/patches/patch-aa
+++ b/x11/xinit/patches/patch-aa
@@ -1,17 +1,17 @@
-$NetBSD: patch-aa,v 1.1 2008/03/15 16:39:32 joerg Exp $
+$NetBSD: patch-aa,v 1.2 2008/04/16 22:07:24 wiz Exp $
 
---- startx.cpp.orig	2007-09-16 23:24:48.000000000 +0200
+--- startx.cpp.orig	2008-03-06 22:08:48.000000000 +0000
 +++ startx.cpp
-@@ -188,7 +188,11 @@ authdisplay=${display:-:0}
+@@ -243,7 +243,11 @@ if [ x"$enable_xauth" = x1 ] ; then
  #if defined(HAS_COOKIE_MAKER) && defined(MK_COOKIE)
- mcookie=`MK_COOKIE`
+     mcookie=`MK_COOKIE`
  #else
--mcookie=`dd if=/dev/random bs=16 count=1 2>/dev/null | hexdump -e \\"%08x\\"`
-+if [ -r /dev/urandom ]; then
+-    mcookie=`dd if=/dev/random bs=16 count=1 2>/dev/null | hexdump -e \\"%08x\\"`
++    if [ -r /dev/urandom ]; then
 +	mcookie=`dd if=/dev/urandom bs=16 count=1 2>/dev/null | hexdump -e \\"%08x\\"`
-+else
++    else
 +	mcookie=`dd if=/dev/random bs=16 count=1 2>/dev/null | hexdump -e \\"%08x\\"`
-+fi
- if test x"$mcookie" = x; then
-                 echo "Couldn't create cookie"
-                 exit 1
++    fi
+     if test x"$mcookie" = x; then
+         echo "Couldn't create cookie"
+         exit 1
