Build a shared library version as well...

diff --git a/databases/db3/patches/patch-ab b/databases/db3/patches/patch-ab
--- a/databases/db3/patches/patch-ab
+++ b/databases/db3/patches/patch-ab
@@ -1,7 +1,5 @@
-$NetBSD: patch-ab,v 1.1 2001/02/21 15:56:02 fvdl Exp $
-
---- ../dist/configure.orig	Wed Jan 24 16:16:18 2001
-+++ ../dist/configure	Wed Feb 21 14:59:15 2001
+--- ../dist/configure.orig	Wed Jan 24 15:16:18 2001
++++ ../dist/configure	Thu Mar 22 17:36:06 2001
 @@ -1605,6 +1605,7 @@
  if test "$GXX" = "yes"; then
  	CXXVERSION=`${MAKEFILE_CXX} --version`
@@ -10,3 +8,21 @@ $NetBSD: patch-ab,v 1.1 2001/02/21 15:56:02 fvdl Exp $
  	1.*|2.[01234567].*|*-1.*|*-2.[01234567].* )
  		CXXFLAGS="-fhandle-exceptions $CXXFLAGS";;
  	* )	CXXFLAGS="-fexceptions $CXXFLAGS";;
+@@ -1632,7 +1633,7 @@
+ 		--disable-static \
+ 	|| { echo "configure: error: libtool configure failed" 1>&2; exit 1; }
+ 
+-	SOSUFFIX=`sed -e '/^library_names_spec=/!d' -e 's/.*\.\([a-zA-Z0-9_]*\).*/\1/' ./libtool`
++	SOSUFFIX=`./libtool --config | sed -e '/^library_names_spec=/!d' -e 's/.*\.\([a-zA-Z0-9_]*\).*/\1/'`
+ 	DEFAULT_LIB="\$(libso_target)"
+ 	DEFAULT_INSTALL="install_dynamic"
+ 	LIBDB_ARGS="\$(libso_linkname)"
+@@ -1644,7 +1645,7 @@
+ 
+ 	INSTALLER="\$(LIBTOOL) --mode=install cp"
+ 	POSTLINK="\$(LIBTOOL) --mode=execute true"
+-	SOLINK="\$(LIBTOOL) --mode=link ${SAVE_CC} -avoid-version"
++	SOLINK="\$(LIBTOOL) --mode=link ${SAVE_CC}"
+ 	SOFLAGS="-rpath \$(libdir)"
+ 	o=".lo"
+ fi
