Update chasen to 2.4.1.
pkgsrc change:

  o Add DESTDIR supoprt.
  o Update MASTER_SITES and HOMEPAGE.

chasen changes from 2.3.3 to 2.4.1.

----------------------------------------------------------------------
ChaSen 2.4.1 (2007/07/03)
----------------------------------------------------------------------
- bug fix
  https://sourceforge.jp/tracker/index.php?func=detail&aid=10259&group_id=2619&atid=9708

----------------------------------------------------------------------
ChaSen 2.4.0 (2007/03/30)
----------------------------------------------------------------------
- bug fix
- -s option (re-analysis)

diff --git a/textproc/chasen-base/patches/patch-an b/textproc/chasen-base/patches/patch-an
--- a/textproc/chasen-base/patches/patch-an
+++ b/textproc/chasen-base/patches/patch-an
@@ -1,56 +1,71 @@
-$NetBSD: patch-an,v 1.1 2004/06/09 05:42:31 taca Exp $
+$NetBSD: patch-an,v 1.2 2007/08/02 15:03:11 taca Exp $
 
---- configure.orig	Fri Aug 15 13:00:58 2003
+--- configure.orig	2007-07-03 15:27:07.000000000 +0900
 +++ configure
-@@ -8497,13 +8497,10 @@ if test "${with_libiconv+set}" = set; th
- fi;
+@@ -20608,7 +20608,8 @@ done
  
  
--echo "$as_me:$LINENO: checking for iconv in -liconv" >&5
--echo $ECHO_N "checking for iconv in -liconv... $ECHO_C" >&6
+ 
+-for ac_header in io.h windows.h
++
++for ac_header in io.h windows.h iconv.h
+ do
+ as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+ if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+@@ -22331,32 +22332,20 @@ if test "${with_libiconv+set}" = set; th
+ fi
+ 
+ 
+-
+-{ echo "$as_me:$LINENO: checking for iconv in -liconv" >&5
+-echo $ECHO_N "checking for iconv in -liconv... $ECHO_C" >&6; }
 -if test "${ac_cv_lib_iconv_iconv+set}" = set; then
 -  echo $ECHO_N "(cached) $ECHO_C" >&6
 -else
 -  ac_check_lib_save_LIBS=$LIBS
 -LIBS="-liconv  $LIBS"
-+echo "$as_me:$LINENO: checking iconv()" >&5
-+echo $ECHO_N "checking iconv()... $ECHO_C" >&6
 +save_libs="$LIBS"
 +LIBS="$LIBS -liconv"
++ac_cv_lib_iconv_iconv=no
  cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
- #include "confdefs.h"
-@@ -8512,9 +8509,7 @@ cat >conftest.$ac_ext <<_ACEOF
- #ifdef __cplusplus
- extern "C"
- #endif
--/* We use char because int might match the return type of a gcc2
+ /* confdefs.h.  */
+ _ACEOF
+ cat confdefs.h >>conftest.$ac_ext
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+-
+-/* Override any GCC internal prototype to avoid an error.
+-   Use char because int might match the return type of a GCC
 -   builtin and then its argument prototype would still apply.  */
+-#ifdef __cplusplus
+-extern "C"
+-#endif
 -char iconv ();
 +#include <iconv.h>
- #ifdef F77_DUMMY_MAIN
- #  ifdef __cplusplus
-      extern "C"
-@@ -8524,7 +8519,7 @@ char iconv ();
  int
  main ()
  {
--iconv ();
+-return iconv ();
 +iconv(0, 0, 0, 0, 0)
    ;
    return 0;
  }
-@@ -8545,135 +8540,12 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
- else
+@@ -22384,160 +22373,15 @@ else
    echo "$as_me: failed program was:" >&5
- cat conftest.$ac_ext >&5
--ac_cv_lib_iconv_iconv=no
--fi
--rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-	ac_cv_lib_iconv_iconv=no
++	{ { echo "$as_me:$LINENO: error: ChaSen needs iconv" >&5
++echo "$as_me: error: ChaSen needs iconv" >&2;}
++   { (exit 1); exit 1; }; }
+ fi
+ 
+ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+       conftest$ac_exeext conftest.$ac_ext
 -LIBS=$ac_check_lib_save_LIBS
 -fi
--echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_iconv" >&5
--echo "${ECHO_T}$ac_cv_lib_iconv_iconv" >&6
+ { echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_iconv" >&5
+ echo "${ECHO_T}$ac_cv_lib_iconv_iconv" >&6; }
 -if test $ac_cv_lib_iconv_iconv = yes; then
 -  cat >>confdefs.h <<_ACEOF
 -#define HAVE_LIBICONV 1
@@ -61,121 +76,141 @@ $NetBSD: patch-an,v 1.1 2004/06/09 05:42:31 taca Exp $
 -else
 -
 -	if test "${ac_cv_header_iconv_h+set}" = set; then
--  echo "$as_me:$LINENO: checking for iconv.h" >&5
--echo $ECHO_N "checking for iconv.h... $ECHO_C" >&6
+-  { echo "$as_me:$LINENO: checking for iconv.h" >&5
+-echo $ECHO_N "checking for iconv.h... $ECHO_C" >&6; }
 -if test "${ac_cv_header_iconv_h+set}" = set; then
 -  echo $ECHO_N "(cached) $ECHO_C" >&6
 -fi
--echo "$as_me:$LINENO: result: $ac_cv_header_iconv_h" >&5
--echo "${ECHO_T}$ac_cv_header_iconv_h" >&6
+-{ echo "$as_me:$LINENO: result: $ac_cv_header_iconv_h" >&5
+-echo "${ECHO_T}$ac_cv_header_iconv_h" >&6; }
 -else
 -  # Is the header compilable?
--echo "$as_me:$LINENO: checking iconv.h usability" >&5
--echo $ECHO_N "checking iconv.h usability... $ECHO_C" >&6
+-{ echo "$as_me:$LINENO: checking iconv.h usability" >&5
+-echo $ECHO_N "checking iconv.h usability... $ECHO_C" >&6; }
 -cat >conftest.$ac_ext <<_ACEOF
--#line $LINENO "configure"
--#include "confdefs.h"
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
 -$ac_includes_default
 -#include <iconv.h>
 -_ACEOF
 -rm -f conftest.$ac_objext
--if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
--  (eval $ac_compile) 2>&5
+-if { (ac_try="$ac_compile"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_compile") 2>conftest.er1
 -  ac_status=$?
--  echo "$as_me:$LINENO: \$? = $ac_status" >&5
--  (exit $ac_status); } &&
--         { ac_try='test -s conftest.$ac_objext'
--  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
--  (eval $ac_try) 2>&5
--  ac_status=$?
--  echo "$as_me:$LINENO: \$? = $ac_status" >&5
--  (exit $ac_status); }; }; then
--  ac_header_compiler=yes
--else
--  echo "$as_me: failed program was:" >&5
--cat conftest.$ac_ext >&5
--ac_header_compiler=no
--fi
--rm -f conftest.$ac_objext conftest.$ac_ext
--echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
--echo "${ECHO_T}$ac_header_compiler" >&6
--
--# Is the header present?
--echo "$as_me:$LINENO: checking iconv.h presence" >&5
--echo $ECHO_N "checking iconv.h presence... $ECHO_C" >&6
--cat >conftest.$ac_ext <<_ACEOF
--#line $LINENO "configure"
--#include "confdefs.h"
--#include <iconv.h>
--_ACEOF
--if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
--  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
--  ac_status=$?
--  egrep -v '^ *\+' conftest.er1 >conftest.err
+-  grep -v '^ *+' conftest.er1 >conftest.err
 -  rm -f conftest.er1
 -  cat conftest.err >&5
 -  echo "$as_me:$LINENO: \$? = $ac_status" >&5
--  (exit $ac_status); } >/dev/null; then
--  if test -s conftest.err; then
--    ac_cpp_err=$ac_c_preproc_warn_flag
--  else
--    ac_cpp_err=
--  fi
+-  (exit $ac_status); } && {
+-	 test -z "$ac_c_werror_flag" ||
+-	 test ! -s conftest.err
+-       } && test -s conftest.$ac_objext; then
+-  ac_header_compiler=yes
 -else
--  ac_cpp_err=yes
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-	ac_header_compiler=no
 -fi
--if test -z "$ac_cpp_err"; then
+-
+-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+-{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+-echo "${ECHO_T}$ac_header_compiler" >&6; }
+-
+-# Is the header present?
+-{ echo "$as_me:$LINENO: checking iconv.h presence" >&5
+-echo $ECHO_N "checking iconv.h presence... $ECHO_C" >&6; }
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-#include <iconv.h>
+-_ACEOF
+-if { (ac_try="$ac_cpp conftest.$ac_ext"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } >/dev/null && {
+-	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+-	 test ! -s conftest.err
+-       }; then
 -  ac_header_preproc=yes
 -else
 -  echo "$as_me: failed program was:" >&5
--  cat conftest.$ac_ext >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
 -  ac_header_preproc=no
 -fi
+-
 -rm -f conftest.err conftest.$ac_ext
--echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
--echo "${ECHO_T}$ac_header_preproc" >&6
+-{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+-echo "${ECHO_T}$ac_header_preproc" >&6; }
 -
 -# So?  What about this header?
--case $ac_header_compiler:$ac_header_preproc in
--  yes:no )
+-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+-  yes:no: )
 -    { echo "$as_me:$LINENO: WARNING: iconv.h: accepted by the compiler, rejected by the preprocessor!" >&5
 -echo "$as_me: WARNING: iconv.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
--    { echo "$as_me:$LINENO: WARNING: iconv.h: proceeding with the preprocessor's result" >&5
--echo "$as_me: WARNING: iconv.h: proceeding with the preprocessor's result" >&2;};;
--  no:yes )
+-    { echo "$as_me:$LINENO: WARNING: iconv.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: iconv.h: proceeding with the compiler's result" >&2;}
+-    ac_header_preproc=yes
+-    ;;
+-  no:yes:* )
 -    { echo "$as_me:$LINENO: WARNING: iconv.h: present but cannot be compiled" >&5
 -echo "$as_me: WARNING: iconv.h: present but cannot be compiled" >&2;}
--    { echo "$as_me:$LINENO: WARNING: iconv.h: check for missing prerequisite headers?" >&5
--echo "$as_me: WARNING: iconv.h: check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: iconv.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: iconv.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: iconv.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: iconv.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: iconv.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: iconv.h:     section \"Present But Cannot Be Compiled\"" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: iconv.h: proceeding with the preprocessor's result" >&5
--echo "$as_me: WARNING: iconv.h: proceeding with the preprocessor's result" >&2;};;
+-echo "$as_me: WARNING: iconv.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: iconv.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: iconv.h: in the future, the compiler will take precedence" >&2;}
+-
+-    ;;
 -esac
--echo "$as_me:$LINENO: checking for iconv.h" >&5
--echo $ECHO_N "checking for iconv.h... $ECHO_C" >&6
+-{ echo "$as_me:$LINENO: checking for iconv.h" >&5
+-echo $ECHO_N "checking for iconv.h... $ECHO_C" >&6; }
 -if test "${ac_cv_header_iconv_h+set}" = set; then
 -  echo $ECHO_N "(cached) $ECHO_C" >&6
 -else
 -  ac_cv_header_iconv_h=$ac_header_preproc
 -fi
--echo "$as_me:$LINENO: result: $ac_cv_header_iconv_h" >&5
--echo "${ECHO_T}$ac_cv_header_iconv_h" >&6
+-{ echo "$as_me:$LINENO: result: $ac_cv_header_iconv_h" >&5
+-echo "${ECHO_T}$ac_cv_header_iconv_h" >&6; }
 -
 -fi
 -if test $ac_cv_header_iconv_h = yes; then
 -  :
 -else
 -  { { echo "$as_me:$LINENO: error: ChaSen needs iconv" >&5
-+{ { echo "$as_me:$LINENO: error: ChaSen needs iconv" >&5
- echo "$as_me: error: ChaSen needs iconv" >&2;}
-    { (exit 1); exit 1; }; }
- fi
+-echo "$as_me: error: ChaSen needs iconv" >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
 -
 -
 -fi
 -
--
-+echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_iconv" >&5
-+echo "${ECHO_T}$ac_cv_lib_iconv_iconv" >&6
  
  
- echo "$as_me:$LINENO: checking iconv args" >&5
+ 
