update to 1.10 changes: * Added h4fromh5 utility.  (NCSA seems to be no longer shipping   the HDF5/HDF4 conversion tools with the latest HDF5 release.) * Added dkbluered color map, which is similar to bluered but   uses a somewhat wider range of colors.

diff --git a/graphics/h5utils/patches/patch-aa b/graphics/h5utils/patches/patch-aa
--- a/graphics/h5utils/patches/patch-aa
+++ b/graphics/h5utils/patches/patch-aa
@@ -1,8 +1,8 @@
-$NetBSD: patch-aa,v 1.1 2006/01/25 19:47:48 wiz Exp $
+$NetBSD: patch-aa,v 1.2 2006/07/10 11:19:21 drochner Exp $
 
---- configure.orig	2006-01-25 12:30:42.000000000 +0000
+--- configure.orig	2005-09-02 23:39:35.000000000 +0200
 +++ configure
-@@ -3866,7 +3866,7 @@ if test "${ac_cv_lib_df_DFSDgetdata+set}
+@@ -3916,7 +3916,7 @@ if test "${ac_cv_lib_df_DFSDgetdata+set}
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -11,12 +11,12 @@ $NetBSD: patch-aa,v 1.1 2006/01/25 19:47:48 wiz Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -3925,7 +3925,7 @@ fi
+@@ -3975,7 +3975,7 @@ fi
  echo "$as_me:$LINENO: result: $ac_cv_lib_df_DFSDgetdata" >&5
  echo "${ECHO_T}$ac_cv_lib_df_DFSDgetdata" >&6
  if test $ac_cv_lib_df_DFSDgetdata = yes; then
--  H4_LIBS="-ldf -ljpeg"; H5FROMH4=yes
-+  H4_LIBS="-ldf -lsz -ljpeg"; H5FROMH4=yes
+-  H4_LIBS="-ldf -ljpeg"; HDF4=yes
++  H4_LIBS="-ldf -lsz -ljpeg"; HDF4=yes
  else
-   { echo "$as_me:$LINENO: WARNING: can't find libdf (HDF4): won't be able to compile h5fromh4" >&5
- echo "$as_me: WARNING: can't find libdf (HDF4): won't be able to compile h5fromh4" >&2;}
+   { echo "$as_me:$LINENO: WARNING: can't find libdf (HDF4): won't be able to compile h5fromh4 or h4fromh5" >&5
+ echo "$as_me: WARNING: can't find libdf (HDF4): won't be able to compile h5fromh4 or h4fromh5" >&2;}
