"imlib" really doesn't work with "libpng-1.0.2". Because we can't upgrade "libpng" and don't want to downgrade it disable PNG support for now.

diff --git a/graphics/imlib/patches/patch-aa b/graphics/imlib/patches/patch-aa
--- a/graphics/imlib/patches/patch-aa
+++ b/graphics/imlib/patches/patch-aa
@@ -1,6 +1,7 @@
-$NetBSD: patch-aa,v 1.3 1999/01/01 02:41:16 garbled Exp $
---- configure.orig	Tue Dec 15 20:14:28 1998
-+++ configure	Thu Dec 31 19:35:27 1998
+$NetBSD: patch-aa,v 1.4 1999/01/06 00:42:37 tron Exp $
+
+--- configure.orig	Wed Dec 16 04:14:28 1998
++++ configure	Wed Jan  6 01:36:14 1999
 @@ -1174,6 +1174,7 @@
  
  
@@ -25,28 +26,23 @@ $NetBSD: patch-aa,v 1.3 1999/01/01 02:41:16 garbled Exp $
      gtk_config_major_version=`$GTK_CONFIG $gtk_config_args --version | \
             sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/'`
      gtk_config_minor_version=`$GTK_CONFIG $gtk_config_args --version | \
-@@ -4234,24 +4237,6 @@
- else
-   echo "configure: warning: *** Native PNG support will not be built (PNG header file not found) ***" 1>&2
+@@ -4130,7 +4133,7 @@
+ echo "configure: warning: *** Native GIF support will not be built (GIF header not found) ***" 1>&2
  fi
+ 
 -
--echo $ac_n "checking for libpng version other than 1.0.2""... $ac_c" 1>&6
--echo "configure:4240: checking for libpng version other than 1.0.2" >&5
--cat > conftest.$ac_ext <<EOF
--#line 4242 "configure"
--#include "confdefs.h"
--#include <png.h>
--PNG_LIBPNG_VER_STRING
--EOF
--if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
--  egrep ""1.0.2"" >/dev/null 2>&1; then
--  rm -rf conftest*
--  echo "********* WARNING *********** Your libpng version is 1.0.2. Build will not continue until you revert to 1.0.1 or a newer version.";exit
--else
--  rm -rf conftest*
--  png_ok=yes
--fi
--rm -f conftest*
++if false; then
+ echo $ac_n "checking for png_read_info in -lpng""... $ac_c" 1>&6
+ echo "configure:4136: checking for png_read_info in -lpng" >&5
+ ac_lib_var=`echo png'_'png_read_info | sed 'y%./+-%__p_%'`
+@@ -4252,6 +4255,10 @@
+   png_ok=yes
+ fi
+ rm -f conftest*
++
++else
++  png_ok=no
++fi
  
  echo "$ac_t""$png_ok" 1>&6
  
