Fix test ==. Reported by Robert Elz in PR 43046.

diff --git a/net/proftpd/patches/patch-ab b/net/proftpd/patches/patch-ab
--- a/net/proftpd/patches/patch-ab
+++ b/net/proftpd/patches/patch-ab
@@ -1,10 +1,19 @@
-$NetBSD: patch-ab,v 1.10 2010/03/21 21:24:25 kim Exp $
+$NetBSD: patch-ab,v 1.11 2010/03/23 13:45:28 wiz Exp $
 
 Make this pkgsrc friendly.
 
---- configure.orig	2010-02-15 14:32:24.000000000 -0500
-+++ configure	2010-03-21 16:35:31.000000000 -0400
-@@ -31715,7 +31715,7 @@
+--- configure.orig	2010-02-15 19:32:24.000000000 +0000
++++ configure
+@@ -12862,7 +12862,7 @@ if test "${with_modules+set}" = set; the
+     if test x"$withval" != x; then
+       modules_list=`echo "$withval" | sed -e 's/:/ /g'`;
+       for amodule in $modules_list; do
+-        if test x"$amodule" == xmod_dso ; then
++        if test x"$amodule" = xmod_dso ; then
+           { { echo "$as_me:$LINENO: error: use --enable-dso instead of --with-modules=mod_dso for DSO support" >&5
+ echo "$as_me: error: use --enable-dso instead of --with-modules=mod_dso for DSO support" >&2;}
+    { (exit 1); exit 1; }; }
+@@ -31715,7 +31715,7 @@ _ACEOF
  
  
  cat >>confdefs.h <<_ACEOF
@@ -13,7 +22,7 @@ Make this pkgsrc friendly.
  _ACEOF
  
  cat >>confdefs.h <<_ACEOF
-@@ -31723,7 +31723,7 @@
+@@ -31723,7 +31723,7 @@ cat >>confdefs.h <<_ACEOF
  _ACEOF
  
  cat >>confdefs.h <<_ACEOF
