pbulk-0.32: Make bulkbuild-rebuild over 200 times faster when running against a full tree scan by using awk to filter out the data instead of the while read shell builtin.

diff --git a/pkgtools/pbulk/files/pbulk/scripts/bulkbuild-rebuild b/pkgtools/pbulk/files/pbulk/scripts/bulkbuild-rebuild
--- a/pkgtools/pbulk/files/pbulk/scripts/bulkbuild-rebuild
+++ b/pkgtools/pbulk/files/pbulk/scripts/bulkbuild-rebuild
@@ -1,19 +1,15 @@
 #!@SH@
-# $NetBSD: bulkbuild-rebuild,v 1.1 2008/01/26 01:57:00 joerg Exp $
+# $NetBSD: bulkbuild-rebuild,v 1.2 2008/06/20 11:51:50 joerg Exp $
 
 . @PBULK_CONFIG@
 
 set -e
 
 check_pkg() {
-	found=0
-	while read line; do
-		if [ "$line" = "PKGNAME=$1" ]; then
-			return 0
-		fi
-	done < ${loc}/presolve
-	echo "Package $1 not found, aborting."
-	exit 1
+	if @AWK@ '{ if ($0 == "PKGNAME='$1'") exit 1 }' < ${loc}/presolve; then
+		echo "Package $1 not found, aborting."
+		exit 1
+	fi
 }
 
 pkg_failed() {
@@ -23,18 +19,10 @@ pkg_failed() {
 
 build_pkg() {
 	printf "Building package %s... " "$1"
-	do_print=0
-	while read line; do
-		case "$line" in
-		"PKGNAME=$1")
-			do_print=1
-			;;
-		"PKGNAME="*)
-			do_print=0
-			;;
-		esac
-		[ "$do_print" = 1 ] && echo "$line"
-	done < ${loc}/presolve | ${pbuild_script} || pkg_failed "$1"
+	@AWK@ '{ if ($0 == "PKGNAME='$1'") p=1; \
+	       else if ($0 ~ "^PKGNAME=") p=0; \
+	       if (p) print $0 }' < ${loc}/presolve | \
+	${pbuild_script} || pkg_failed "$1"
 	echo "done"
 }
 
