Removed code duplication by calling the client-clean script.
Before removing prefix, fix the permissions. Everything inside that
directory must be writable and all directories must be searchable.
NetBSD's chmod has an option -P which I would have liked to use, but
POSIX requires only -R to be implemented. Therefore, it is possible that
permissions of files outside the prefix are changed due to symlinks.

The client-clean program promises to clean $prefix, so fail if that is
not possible. A common cause for this is that some files inside have
their flags set (see chflags(1) on NetBSD).

When installing the bootstrap kit, the source may be either a regular
file (which is then assumed to be a tar archive) or a directory (which
is copied directly). The latter option is new and allows for easier
changes of files once the bulk build has started.

diff --git a/pkgtools/pbulk/files/pbulk/scripts/client-clean b/pkgtools/pbulk/files/pbulk/scripts/client-clean
--- a/pkgtools/pbulk/files/pbulk/scripts/client-clean
+++ b/pkgtools/pbulk/files/pbulk/scripts/client-clean
@@ -1,11 +1,23 @@
 #!@SH@
-# $NetBSD: client-clean,v 1.3 2007/08/15 21:10:55 joerg Exp $
+# $NetBSD: client-clean,v 1.4 2007/09/21 13:42:54 rillig Exp $
 
 . @PBULK_CONFIG@
 
 set -e
 
 # Clean build system first
+chmod -R 700 ${prefix} ${pkgdb} ${varbase}/qmail 2> /dev/null || true
 rm -rf ${prefix} ${pkgdb} ${varbase}/qmail 2> /dev/null || true
+if [ -d "${prefix}" ]; then
+	echo "ERROR: [client-clean] Could not remove $prefix" 1>&2
+	exit 1
+fi
+
 # Install fresh bootstrap state
-[ -z "${bootstrapkit}" ] || ${tar} -xzf ${bootstrapkit} -C /
+if [ -f "${bootstrapkit}" ]; then
+	${tar} -xzf ${bootstrapkit} -C /
+elif [ -d "${bootstrapkit}" ]; then
+	cp -R ${bootstrapkit} ${prefix}
+else
+	# Do nothing
+fi
