pbulk-0.57: Reorder build phases slightly to make better use of destdir builds. Introduce hooks for sending bulklog and package explicitly the master. The default bulklog action is a nop and the package action mirrors the normal package step, i.e. copying to ${packages}/All and adding the category symlinks.

diff --git a/pkgtools/pbulk/files/pbulk/scripts/pkg-build b/pkgtools/pbulk/files/pbulk/scripts/pkg-build
--- a/pkgtools/pbulk/files/pbulk/scripts/pkg-build
+++ b/pkgtools/pbulk/files/pbulk/scripts/pkg-build
@@ -1,5 +1,5 @@
 #!@SH@
-# $NetBSD: pkg-build,v 1.26 2015/09/08 17:35:07 joerg Exp $
+# $NetBSD: pkg-build,v 1.27 2015/09/13 11:45:37 joerg Exp $
 #
 # Copyright (c) 2007, 2008 Joerg Sonnenberger <joerg@NetBSD.org>.
 # All rights reserved.
@@ -38,6 +38,14 @@ if [ "${config_version}" != "@PBULK_CONFIG_VERSION@" ]; then
 	exit 1
 fi
 
+default_sync_package() {
+	cp "$1" "${packages}/All/${pkgname}${pkg_sufx}"
+	for cat in $3; do
+		mkdir -p ${packages}/$cat
+		ln -fs ../All/${pkgname}${pkg_sufx} ${packages}/$cat/${pkgname}${pkg_sufx}
+	done
+}
+
 cleanup() {
 	if [ "$keep_wrkdir" = yes ]; then
 		${make} pbulk-save-wrkdir INTO=${bulklog}/${pkgname}/wrkdir.tar.gz TAR="${tar}"
@@ -51,6 +59,7 @@ cleanup() {
 		${tar} -czf ${bulklog}/${pkgname}/prefix.tar.gz ${cur_destdir}${prefix}
 	fi
 	${make} clean > /dev/null 2>&1 || true
+	${sync_buildlog} ${bulklog} ${pkgname}
 	exit 1
 }
 
@@ -61,12 +70,11 @@ run_make() {
 	local run_cmd
 	run_cmd=$1
 	shift
-	${run_cmd} ${make} $1 \
+	${run_cmd} ${make} "$@" \
 		BATCH=1 \
 		DEPENDS_TARGET=/nonexistent \
 		${MAKE_FLAGS} \
 		WRKLOG=${bulklog}/${pkgname}/work.log
-
 }
 
 run_usergroup() {
@@ -94,6 +102,9 @@ while read build_info_line; do
 		;;
 	DEPENDS=*)
 		dependencies=${build_info_line#DEPENDS=}
+		;;
+	CATEGORIES=*)
+		categories=${build_info_line#CATEGORIES=}
 		;;
 	MULTI_VERSION=*)
 		MAKE_FLAGS=${build_info_line#MULTI_VERSION=}
@@ -191,34 +202,37 @@ run_usergroup build> ${bulklog}/${pkgname}/build.log 2>&1 || cleanup
 run_make ${run_build} all >> ${bulklog}/${pkgname}/build.log 2>&1 || cleanup
 run_usergroup install > ${bulklog}/${pkgname}/install.log 2>&1 || cleanup
 run_make ${run_install} stage-install >> ${bulklog}/${pkgname}/install.log 2>&1 || cleanup
-run_make run_direct package  > ${bulklog}/${pkgname}/package.log 2>&1 || cleanup
+run_make run_direct stage-package-create > ${bulklog}/${pkgname}/package.log 2>&1 || cleanup
+
+pkgfile=$(run_make run_direct show-var VARNAME=STAGE_PKGFILE)
 
 # When using DESTDIR build, add the package once to test install rules.
 # This is not done for potential bootstrap packages as they might already
 # be installed.
 if [ "${use_destdir}" != "no" ] && \
    [ -z "${is_bootstrap}" ]; then
-	if ! ${pkg_add_cmd} ${pkgname} \
+	if ! ${pkg_add_cmd} ${pkgfile} \
 	    >> ${bulklog}/${pkgname}/package.log 2>&1; then
-		run_make run_direct package-clean
 		cleanup
 	fi
 fi
-
-# Clean build area
-${make} clean > ${bulklog}/${pkgname}/clean.log 2>&1
 
 # Test uninstall rules. This is not for cross-compiling as the install script
 # is not run in that case anyway. This is also not done for packages marked as
 # part of the bootstrap, those have the preserve flag set.
 if [ "$cross_compile" = "no" ] && \
    [ -z "${is_bootstrap}" ]; then
-	${pkg_delete} -K ${cur_pkgdb} ${pkgname} > ${bulklog}/${pkgname}/deinstall.log 2>&1
+	${pkg_delete} -K ${cur_pkgdb} ${pkgname} > ${bulklog}/${pkgname}/deinstall.log 2>&1 || cleanup
 fi
 
 # Comment the following out if you want to test all deinstall scripts.
 # This is quite expensive and mostly redundant, so it is disabled by default.
-#${pkg_delete} -r \* > /dev/null 2>&1 || true
+#${pkg_delete} -r \* > /dev/null 2>&1 || cleanup
+
+${sync_package} ${pkgfile} ${pkgname} "${categories}"
+
+# Clean build area
+${make} clean > ${bulklog}/${pkgname}/clean.log 2>&1 || true
 
 # Cleanup build logs on success
 rm -R ${bulklog}/${pkgname}
