pbulk*: add a 'strict_mode' option to pbulk
When this is set to 'yes', pbulk will just exit if there is an
unresolvable dependency in the resolve phase, like it did before
pbulk-base-0.58/pbulk-0.74.

Bump version.

diff --git a/pkgtools/pbulk/files/pbulk/scripts/scan b/pkgtools/pbulk/files/pbulk/scripts/scan
--- a/pkgtools/pbulk/files/pbulk/scripts/scan
+++ b/pkgtools/pbulk/files/pbulk/scripts/scan
@@ -1,5 +1,5 @@
 #!@SH@
-# $NetBSD: scan,v 1.11 2025/01/13 11:03:03 wiz Exp $
+# $NetBSD: scan,v 1.12 2025/04/09 00:26:33 wiz Exp $
 #
 # Copyright (c) 2007 Joerg Sonnenberger <joerg@NetBSD.org>.
 # All rights reserved.
@@ -47,6 +47,17 @@ else
 	extra_pscan_args=""
 fi
 
+case "${strict_mode}" in
+[yY][eE][sS])
+	extra_presolve_args="-s"
+	strict_mode=yes
+	;;
+*)
+	extra_presolve_args=""
+	strict_mode=no
+	;;
+esac
+
 if [ -n "${ignore_missing_dependencies}" ]; then
 	echo "The 'ignore_missing_dependencies' configuration variable is obsolete and has no effect." >&2
 fi
@@ -66,7 +77,10 @@ if [ -z "${limited_list}" ]; then
 		;;
 	esac
 	echo "Resolving..."
-	${presolve} -v ${loc}/pscan > ${loc}/presolve 2> ${loc}/presolve-err.log
+	if ! ${presolve} ${extra_presolve_args} -v ${loc}/pscan > ${loc}/presolve 2> ${loc}/presolve-err.log; then
+		# can only happen in strict mode
+		echo "Global dependency resolution failed, check ${loc}/presolve-err.log for details" >&2
+	fi
 else
 	initial=1
 	mkdir -p ${loc}
@@ -99,6 +113,11 @@ else
 	done
 
 	if [ -s ${loc}/missing ]; then
+		if [ "${strict_mode}" = "yes" ]; then
+			echo "Unresolvable dependencies found, exiting"
+			cat ${loc}/missing
+			exit 1
+		fi
 		echo "Unresolvable dependencies found, marking packages depending on them as broken:"
 		cat ${loc}/missing
 		${presolve} -v ${loc}/presolve ${loc}/pscan > ${loc}/presolve.new
