Update to 1.1 - Give a slightly more friendly error message if vulnerabilities file not present.

diff --git a/security/audit-packages/files/audit-packages b/security/audit-packages/files/audit-packages
--- a/security/audit-packages/files/audit-packages
+++ b/security/audit-packages/files/audit-packages
@@ -1,5 +1,10 @@
 #! /bin/sh
 
+if [ ! -f ${DISTDIR}/vulnerabilities ] ;then
+    echo "** Missing ${DISTDIR}/vulnerabilities"
+    echo "** run download-vulnerability-list"
+    exit 1
+fi
 ${AWK} '
 	/^#.*/ { next }
 	NF == 0 { next }
