Update audit-packages to 1.18.
Changes from previous version:

+ rely on an embedded sha1 digest to tell whether the vulnerabilities
  file has been damaged in transit or received successfully, rather than
  trusting that the file will not grow smaller

+ use the new filename "pkg-vulnerabilities"

+ use definitions from defs.${OPSYS}.mk in the download-vulnerability-list
  script

+ at installation time, don't rely on "ln -sf" to DTRT - explicitly call
  "rm -f" before attempting the symbolc link

With thanks to seb@ for testing.

diff --git a/security/audit-packages/files/audit-packages b/security/audit-packages/files/audit-packages
--- a/security/audit-packages/files/audit-packages
+++ b/security/audit-packages/files/audit-packages
@@ -1,19 +1,19 @@
 #! @SH@
-# $NetBSD: audit-packages,v 1.10 2003/05/21 14:07:45 seb Exp $
+
+# $NetBSD: audit-packages,v 1.11 2003/09/02 10:20:28 agc Exp $
 
 : ${PKGVULNDIR=@PKGVULNDIR@}
 
-if [ ! -f ${PKGVULNDIR}/vulnerabilities ] ;then
-    echo "** Missing ${PKGVULNDIR}/vulnerabilities" 1>&2
-    echo "** run download-vulnerability-list" 1>&2
-    exit 1
+if [ ! -f ${PKGVULNDIR}/vulnerabilities ]; then
+	echo "** Missing ${PKGVULNDIR}/pkg-vulnerabilities" 1>&2
+	echo "** run download-vulnerability-list" 1>&2
+	exit 1
 fi
 
-if [ -n "$(find ${PKGVULNDIR}/vulnerabilities -ctime +7)" ]
-then
-    echo "** ${PKGVULNDIR}/vulnerabilities more than a week old" 1>&2
-    echo "** run download-vulnerability-list" 1>&2
-    exit 1
+if [ -n "$(find ${PKGVULNDIR}/pkg-vulnerabilities -ctime +7)" ]; then
+	echo "** ${PKGVULNDIR}/pkg-vulnerabilities more than a week old" 1>&2
+	echo "** run download-vulnerability-list" 1>&2
+	exit 1
 fi
 
 @AWK@ '
@@ -21,6 +21,6 @@ fi
 	NF == 0 { next }
 	{ cmd = sprintf("@PKG_TOOLS_BIN@/pkg_info -qe \"%s\" && echo Package \"`@PKG_TOOLS_BIN@/pkg_info -e '\''%s\'\''`\" has a %s vulnerability, see %s ; wait", $1, $1, $2, $3);
 	  system(cmd); }
-' ${PKGVULNDIR}/vulnerabilities
+' ${PKGVULNDIR}/pkg-vulnerabilities
 
 exit 0
