audit-packages 1.2: 	check if vulnerabilities file is more than a week old, and whine if it is 	whine to stderr rather than stdout

diff --git a/security/audit-packages/files/audit-packages b/security/audit-packages/files/audit-packages
--- a/security/audit-packages/files/audit-packages
+++ b/security/audit-packages/files/audit-packages
@@ -1,10 +1,18 @@
 #! /bin/sh
 
 if [ ! -f ${DISTDIR}/vulnerabilities ] ;then
-    echo "** Missing ${DISTDIR}/vulnerabilities"
-    echo "** run download-vulnerability-list"
+    echo "** Missing ${DISTDIR}/vulnerabilities" 1>&2
+    echo "** run download-vulnerability-list" 1>&2
     exit 1
 fi
+
+if [ -n "$(find ${DISTDIR}/vulnerabilities -mtime +7)" ]
+then
+    echo "** ${DISTDIR}/vulnerabilities more than a week old" 1>&2
+    echo "** run download-vulnerability-list" 1>&2
+    exit 1
+fi
+
 ${AWK} '
 	/^#.*/ { next }
 	NF == 0 { next }
