Store vulnerabilities file in ${PKGVULNDIR} instead of ${DISTDIR}, in case the latter is not appropriate.  The former defaults to the latter. Bump version to 1.12.  Per discussion with Alistair Crooks.

diff --git a/security/audit-packages/files/audit-packages b/security/audit-packages/files/audit-packages
--- a/security/audit-packages/files/audit-packages
+++ b/security/audit-packages/files/audit-packages
@@ -1,15 +1,15 @@
 #! ${SH}
-# $NetBSD: audit-packages,v 1.7 2001/12/29 10:07:31 agc Exp $
+# $NetBSD: audit-packages,v 1.8 2002/04/26 12:45:24 lukem Exp $
 
-if [ ! -f ${DISTDIR}/vulnerabilities ] ;then
-    echo "** Missing ${DISTDIR}/vulnerabilities" 1>&2
+if [ ! -f ${PKGVULNDIR}/vulnerabilities ] ;then
+    echo "** Missing ${PKGVULNDIR}/vulnerabilities" 1>&2
     echo "** run download-vulnerability-list" 1>&2
     exit 1
 fi
 
-if [ -n "$(find ${DISTDIR}/vulnerabilities -ctime +7)" ]
+if [ -n "$(find ${PKGVULNDIR}/vulnerabilities -ctime +7)" ]
 then
-    echo "** ${DISTDIR}/vulnerabilities more than a week old" 1>&2
+    echo "** ${PKGVULNDIR}/vulnerabilities more than a week old" 1>&2
     echo "** run download-vulnerability-list" 1>&2
     exit 1
 fi
@@ -19,6 +19,6 @@ ${AWK} '
 	NF == 0 { next }
 	{ cmd = sprintf("${PKG_TOOLS_BIN}/pkg_info -qe \"%s\" && echo Package \"`${PKG_TOOLS_BIN}/pkg_info -e '\''%s\'\''`\" has a %s vulnerability, see %s", $1, $1, $2, $3);
 	  system(cmd); }
-' ${DISTDIR}/vulnerabilities
+' ${PKGVULNDIR}/vulnerabilities
 
 exit 0
