Changes 2.0.2: * PostgreSQL 8.4 compatibility * Fix - config dump was failing on string entries that were NULL * Fix - REPAIR CONFIG could have collisions where, when we   load a schema, one entry in sl_table already has an OID value   that incorrectly matches a value that another update is trying to fix. * Updated release notes to indicate that 2.0 only supports PostgreSQL 8.3+ * Change to configure.ac to allow it to run on autoconf 2.63; there was   something unsuitable about SLONREL_VERSION processing * Fixes to Makefile for admin guide * Various fixes to admin guide material * Added an extra test to Schema name test that validates that things   can operate properly even if the DB lacks a "public" schema * Fixed bug in tools/start_slon.sh * Fixed pathname substitutions in a couple of altperl scripts * Add a test which validates that the cluster schema name is valid;   pgAdminIII allowed setting up cluster names that slonik would refuse   to connect to. * Revised regression tests to use SYNC/WAIT FOR EVENT instead of   queries that try to coordinate sl_status information with rather   less determinacy... * Cleanup thread was generating spurious error messages due to   misinterpreting PG return codes.  Rectified this, and added a   test in to make sure we're exercising the logic

diff --git a/databases/slony1/patches/patch-ab b/databases/slony1/patches/patch-ab
--- a/databases/slony1/patches/patch-ab
+++ b/databases/slony1/patches/patch-ab
@@ -1,31 +1,13 @@
-$NetBSD: patch-ab,v 1.1 2008/01/14 18:58:03 adam Exp $
+$NetBSD: patch-ab,v 1.2 2010/04/15 07:55:32 adam Exp $
 
---- tests/run_test.sh.orig	2008-01-13 22:38:16.000000000 +0100
-+++ tests/run_test.sh
-@@ -179,7 +179,7 @@ store_node()
+--- tools/start_slon.sh.orig	2010-04-15 09:45:28.000000000 +0000
++++ tools/start_slon.sh
+@@ -16,7 +16,7 @@ test -r "$SLON_CONF" || (echo "No slon c
  
-       if [ -n "${db}" -a "${host}" -a "${user}" -a "${port}" ]; then
-         if [ ${alias} -ne ${originnode} ]; then
--          if [ "x${logship}" == "xtrue" ]; then    # Don't bother generating nodes used for log shipping
-+          if [ "x${logship}" = "xtrue" ]; then    # Don't bother generating nodes used for log shipping
-             status "Node ${alias} is a log shipping node - no need for STORE NODE"
-           else
-             echo "STORE NODE (id=${alias}, comment='node ${alias}');" >> $mktmp/slonik.script
-@@ -219,7 +219,7 @@ store_path()
-           eval bport=\$PORT${j}
-           eval blogship=\$LOGSHIP${j}
-           if [ -n "${bdb}" -a "${bhost}" -a "${buser}" -a "${bport}" ]; then
--            if [[ "x${logship}" == "xtrue" || "x${blogship}" == "xtrue" ]]; then
-+            if [[ "x${logship}" = "xtrue" || "x${blogship}" = "xtrue" ]]; then
-                 # log shipping node - no paths need exist that involve this node
-                 status "log shipping between nodes(${i}/${j}) - ls(${logship}/${blogship}) - omit STORE PATH"
-             else
-@@ -499,7 +499,7 @@ launch_slon()
-        fi
-         conninfo="dbname=${db} host=${host} user=${user} port=${port}"
- 
--        if [ "x${logship}" == "xtrue" ]; then
-+        if [ "x${logship}" = "xtrue" ]; then
-           status "do not launch slon for node ${alias} - it receives data via log shipping"
-         else
-           status "launching: $pgbindir/slon -s500 -g10 -d2 ${archiveparm} $cluster \"$conninfo\""
+ PID_LINE=`grep pid_file $SLON_CONF | cut -d "#" -f 1 | grep "^[:space:]*pid_file='.*'"`
+ PID_FILE=`echo $PID_LINE | cut -d "=" -f 2 | cut -d "'" -f 2`
+-if [ "x$PID_FILE" == "x" ]; then
++if [ "x$PID_FILE" = "x" ]; then
+     echo "pid_file not found in slon conf file - $SLON_CONF"
+     exit 1
+ else
