update to 2.8.4
pilrcui (ui previewer) is broken in 2.8, but we get support for LP64.


What's new in 2.8 (Tue, 1 May 2001)
-----------------
o added new resources
- WORDLIST, GRAFITTIINPUTAREA, COLORTABLE, KEYBOARD, COUNTRYLOCALIZATION etc
- [MOST ARE SYSTEM USE ONLY], see doc/manual.html for more information
o ID generation consistancy fixes
- ie: VERSION ID 1 "1.0", VERSION 1 "1.0" and VERSION "1.0" should work
- restore's old behaviour to maintain compatibility in older sample code
o SLIDER changes
- fix warnings for sliders, no longer complain when legal :))
o error message fix
- adjust include file messing error to have line # printed :)
o DATA change
- such that the data file can be found in include directories specified
o added -LE32 flag, generate little endian 32bit compatible resources (ARM, NT)
o various bugfixes et al :P
o recursive includes (32-level deep) now supported
o added src2unix.sh script to strip ^M chars for UN*X users
o fixed strdup complaints
o updated documentation (POPUPLIST example)
o added "-R output.ro -prc" option
- resources are bundled into a prc database (instead of .bin) !yay!
- DEFAULT: cr8r: 'pRES' type: 'data' name: "PilRC resources"
- (can be installed on device)
o ability to custom specify the above using -creator -type and -name
o added srcindent.sh script to indent all source files using indent tool
o VC++ error/warning message syntax fix
o added creationDate/modificationDate chunks
o added support for non-32bit operating systems (alpha etc)

diff --git a/devel/pilrc/patches/patch-ab b/devel/pilrc/patches/patch-ab
--- a/devel/pilrc/patches/patch-ab
+++ b/devel/pilrc/patches/patch-ab
@@ -1,7 +1,7 @@
-$NetBSD: patch-ab,v 1.1.1.1 2001/04/25 17:39:16 wiz Exp $
+$NetBSD: patch-ab,v 1.2 2001/05/11 08:14:34 dillo Exp $
 
---- configure.orig	Thu Mar 22 15:09:11 2001
-+++ configure	Thu Mar 22 15:09:18 2001
+--- configure.orig	Wed May  9 11:27:23 2001
++++ configure
 @@ -12,6 +12,8 @@
  ac_default_prefix=/usr/local
  # Any additions from configure.in:
@@ -11,24 +11,6 @@ $NetBSD: patch-ab,v 1.1.1.1 2001/04/25 17:39:16 wiz Exp $
    --with-gtk-prefix=PFX   Prefix where GTK is installed (optional)"
  ac_help="$ac_help
    --with-gtk-exec-prefix=PFX Exec prefix where GTK is installed (optional)"
-@@ -558,7 +560,7 @@
- # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
- # ./install, which can be erroneously created by make from ./install.sh.
- echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
--echo "configure:562: checking for a BSD compatible install" >&5
-+echo "configure:564: checking for a BSD compatible install" >&5
- if test -z "$INSTALL"; then
- if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
-   echo $ac_n "(cached) $ac_c" 1>&6
-@@ -611,7 +613,7 @@
- test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
- 
- echo $ac_n "checking whether build environment is sane""... $ac_c" 1>&6
--echo "configure:615: checking whether build environment is sane" >&5
-+echo "configure:617: checking whether build environment is sane" >&5
- # Just in case
- sleep 1
- echo timestamp > conftestfile
 @@ -1033,7 +1035,19 @@
  fi
  
@@ -50,7 +32,7 @@ $NetBSD: patch-ab,v 1.1.1.1 2001/04/25 17:39:16 wiz Exp $
  if test "${with_gtk_prefix+set}" = set; then
    withval="$with_gtk_prefix"
    gtk_config_prefix="$withval"
-@@ -1315,12 +1329,24 @@
+@@ -1315,17 +1329,186 @@
    PILRCUI_TRUE='#'
    PILRCUI_FALSE=
  fi
@@ -76,3 +58,165 @@ $NetBSD: patch-ab,v 1.1.1.1 2001/04/25 17:39:16 wiz Exp $
  
  # Check for warnings flag if gcc was detected.
  if test "x$ac_cv_prog_gcc" = "xyes"; then
+   CFLAGS="$CFLAGS -Wall"
+ fi
++
++echo $ac_n "checking size of short""... $ac_c" 1>&6
++echo "configure:1358: checking size of short" >&5
++if eval "test \"`echo '$''{'ac_cv_sizeof_short'+set}'`\" = set"; then
++  echo $ac_n "(cached) $ac_c" 1>&6
++else
++  if test "$cross_compiling" = yes; then
++    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
++else
++  cat > conftest.$ac_ext <<EOF
++#line 1366 "configure"
++#include "confdefs.h"
++#include <stdio.h>
++main()
++{
++  FILE *f=fopen("conftestval", "w");
++  if (!f) exit(1);
++  fprintf(f, "%d\n", sizeof(short));
++  exit(0);
++}
++EOF
++if { (eval echo configure:1377: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
++then
++  ac_cv_sizeof_short=`cat conftestval`
++else
++  echo "configure: failed program was:" >&5
++  cat conftest.$ac_ext >&5
++  rm -fr conftest*
++  ac_cv_sizeof_short=0
++fi
++rm -fr conftest*
++fi
++
++fi
++echo "$ac_t""$ac_cv_sizeof_short" 1>&6
++cat >> confdefs.h <<EOF
++#define SIZEOF_SHORT $ac_cv_sizeof_short
++EOF
++
++
++echo $ac_n "checking size of int""... $ac_c" 1>&6
++echo "configure:1397: checking size of int" >&5
++if eval "test \"`echo '$''{'ac_cv_sizeof_int'+set}'`\" = set"; then
++  echo $ac_n "(cached) $ac_c" 1>&6
++else
++  if test "$cross_compiling" = yes; then
++    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
++else
++  cat > conftest.$ac_ext <<EOF
++#line 1405 "configure"
++#include "confdefs.h"
++#include <stdio.h>
++main()
++{
++  FILE *f=fopen("conftestval", "w");
++  if (!f) exit(1);
++  fprintf(f, "%d\n", sizeof(int));
++  exit(0);
++}
++EOF
++if { (eval echo configure:1416: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
++then
++  ac_cv_sizeof_int=`cat conftestval`
++else
++  echo "configure: failed program was:" >&5
++  cat conftest.$ac_ext >&5
++  rm -fr conftest*
++  ac_cv_sizeof_int=0
++fi
++rm -fr conftest*
++fi
++
++fi
++echo "$ac_t""$ac_cv_sizeof_int" 1>&6
++cat >> confdefs.h <<EOF
++#define SIZEOF_INT $ac_cv_sizeof_int
++EOF
++
++
++echo $ac_n "checking size of long""... $ac_c" 1>&6
++echo "configure:1436: checking size of long" >&5
++if eval "test \"`echo '$''{'ac_cv_sizeof_long'+set}'`\" = set"; then
++  echo $ac_n "(cached) $ac_c" 1>&6
++else
++  if test "$cross_compiling" = yes; then
++    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
++else
++  cat > conftest.$ac_ext <<EOF
++#line 1444 "configure"
++#include "confdefs.h"
++#include <stdio.h>
++main()
++{
++  FILE *f=fopen("conftestval", "w");
++  if (!f) exit(1);
++  fprintf(f, "%d\n", sizeof(long));
++  exit(0);
++}
++EOF
++if { (eval echo configure:1455: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
++then
++  ac_cv_sizeof_long=`cat conftestval`
++else
++  echo "configure: failed program was:" >&5
++  cat conftest.$ac_ext >&5
++  rm -fr conftest*
++  ac_cv_sizeof_long=0
++fi
++rm -fr conftest*
++fi
++
++fi
++echo "$ac_t""$ac_cv_sizeof_long" 1>&6
++cat >> confdefs.h <<EOF
++#define SIZEOF_LONG $ac_cv_sizeof_long
++EOF
++
++
++echo $ac_n "checking size of char *""... $ac_c" 1>&6
++echo "configure:1475: checking size of char *" >&5
++if eval "test \"`echo '$''{'ac_cv_sizeof_char_p'+set}'`\" = set"; then
++  echo $ac_n "(cached) $ac_c" 1>&6
++else
++  if test "$cross_compiling" = yes; then
++    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
++else
++  cat > conftest.$ac_ext <<EOF
++#line 1483 "configure"
++#include "confdefs.h"
++#include <stdio.h>
++main()
++{
++  FILE *f=fopen("conftestval", "w");
++  if (!f) exit(1);
++  fprintf(f, "%d\n", sizeof(char *));
++  exit(0);
++}
++EOF
++if { (eval echo configure:1494: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
++then
++  ac_cv_sizeof_char_p=`cat conftestval`
++else
++  echo "configure: failed program was:" >&5
++  cat conftest.$ac_ext >&5
++  rm -fr conftest*
++  ac_cv_sizeof_char_p=0
++fi
++rm -fr conftest*
++fi
++
++fi
++echo "$ac_t""$ac_cv_sizeof_char_p" 1>&6
++cat >> confdefs.h <<EOF
++#define SIZEOF_CHAR_P $ac_cv_sizeof_char_p
++EOF
++
++
+ 
+ cat >> confdefs.h <<\EOF
+ #define UNIX 1
