Changes 3.0.2: * Fix 1323 about a problem when mounting a requested volume during a restore. * Add more example SD Device configurations. * Force the client_encoding to SQL_ASCII when database is already using this   mode. * Fix 1335 about postgresql error message during copy session * Cleanup old job records when starting the director (Created/Running -> Failed) * Apply patch in bug 1315 by McMichaeli that fixes scripts/logwatch * Add more output when spooling and no space left * Fix postgresql driver bug that displayed <NULL> rows from time to time. * Implement the project 'restore' menu: enter a JobId, automatically   select dependents * Should fix 1323 about verify accurate jobs and deleted files. * more...

diff --git a/sysutils/bacula/patches/patch-ao b/sysutils/bacula/patches/patch-ao
--- a/sysutils/bacula/patches/patch-ao
+++ b/sysutils/bacula/patches/patch-ao
@@ -1,9 +1,9 @@
-$NetBSD: patch-ao,v 1.1 2009/05/15 10:29:05 adam Exp $
+$NetBSD: patch-ao,v 1.2 2009/08/24 08:23:41 adam Exp $
 
---- configure.orig	2009-05-15 10:52:32.000000000 +0200
+--- configure.orig	2009-07-10 16:12:39.000000000 +0200
 +++ configure
-@@ -45609,7 +45609,7 @@ if test "${support_bat}" = "yes" ; then
-       exit 1
+@@ -45726,7 +45726,7 @@ echo "$as_me: error: Could not find qmak
+    { (exit 1); exit 1; }; }
     fi
  
 -   QMAKEBIN="qmake"
