Fixed a segmentation fault on IRIX. Although IRIX provides the REG_STARTEND macro, it doesn't work as expected. A simple test case is:
	printf '\0\n\0\n' | nbsed /a/d

This test does not yet work as expected, but at least it doesn't cause
segmentation faults anymore. Handling of '\0' bytes must be improved.

diff --git a/textproc/nbsed/files/configure b/textproc/nbsed/files/configure
--- a/textproc/nbsed/files/configure
+++ b/textproc/nbsed/files/configure
@@ -3765,6 +3765,66 @@ fi
 done
 
 
+echo "$as_me:$LINENO: checking for working REG_STARTEND" >&5
+echo $ECHO_N "checking for working REG_STARTEND... $ECHO_C" >&6
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#undef NDEBUG
+#include <assert.h>
+#include <regex.h>
+int main(void) {
+	regex_t re;
+	regmatch_t rm;
+
+	assert(regcomp(&re, "lo", 0) == 0);
+	rm.rm_so = 0, rm.rm_eo = 7;
+	assert(regexec(&re, "hel\0lo\n", 1, &rm, REG_STARTEND) == 0);
+	assert(rm.rm_so == 4 && rm.rm_eo == 6);
+	return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_REG_STARTEND 1
+_ACEOF
+
+echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
 echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
 echo $ECHO_N "checking for an ANSI C-conforming const... $ECHO_C" >&6
 if test "${ac_cv_c_const+set}" = set; then
