fix a bug created by last fix.  We need to use gmake for the configure step as well as the build instead of only the build.  Should fix problems noted in Hubert's recent bulk builds.

diff --git a/x11/qt2-libs/patches/patch-ad b/x11/qt2-libs/patches/patch-ad
--- a/x11/qt2-libs/patches/patch-ad
+++ b/x11/qt2-libs/patches/patch-ad
@@ -1,9 +1,8 @@
-$NetBSD: patch-ad,v 1.2 2001/03/28 09:27:51 skrll Exp $
+$NetBSD: patch-ad,v 1.3 2003/02/07 02:10:41 dmcmahill Exp $
 
---- configure.orig	Mon Mar  5 18:12:49 2001
+--- configure.orig	Wed Jun 13 04:57:02 2001
 +++ configure
-@@ -17,25 +17,6 @@
-     HELP=yes
+@@ -18,37 +18,13 @@
  else
  
 -touch .test.qt.
@@ -26,5 +25,19 @@ $NetBSD: patch-ad,v 1.2 2001/03/28 09:27:51 skrll Exp $
 -rm .test.qt.
 -
  # Find a make command
- if ( make /dev/null ) >/dev/null 2>/dev/null
- then
+-if ( make /dev/null ) >/dev/null 2>/dev/null
+-then
+-    MAKE=make
+-else
+     if ( gmake /dev/null ) >/dev/null 2>/dev/null
+     then
+ 	MAKE=gmake
+     else
+-	echo "You don't seem to have 'make' or 'gmake' in your PATH."
++	echo "You don't seem to have 'gmake' in your PATH."
+ 	echo "Cannot proceed."
+ 	exit 1
+     fi
+-fi
+ 
+ # Check licensed modules
