Update "a2ps" package to version 4.12.

diff --git a/print/a2ps/patches/patch-aj b/print/a2ps/patches/patch-aj
--- a/print/a2ps/patches/patch-aj
+++ b/print/a2ps/patches/patch-aj
@@ -1,21 +1,33 @@
-$NetBSD: patch-aj,v 1.2 1998/08/07 11:11:22 agc Exp $
+$NetBSD: patch-aj,v 1.3 1999/06/20 15:53:29 tron Exp $
 
---- configure.orig	Fri Jul 17 13:52:31 1998
-+++ configure	Fri Jul 17 13:53:03 1998
-@@ -1764,7 +1764,7 @@
- NM="$ac_cv_path_NM"
- echo "$ac_t""$NM" 1>&6
+--- configure.orig	Thu Feb 18 16:17:21 1999
++++ configure	Sat Jun 19 17:45:34 1999
+@@ -641,10 +641,12 @@
  
--
+ echo $ac_n "checking whether build environment is sane""... $ac_c" 1>&6
+ echo "configure:644: checking whether build environment is sane" >&5
++if false; then
+ if test -n "`cd /`"; then
+   { echo "configure: error: Running cd is not silent as it should be.
+ Make sure to unset the environment variable CDPATH." 1>&2; exit 1; }
+ fi
++fi
+ # Just in case
+ sleep 1
+ echo timestamp > conftestfile
+@@ -2253,6 +2255,7 @@
+   ac_tool_prefix=
+ fi
+ 
 +if false; then
  # Always use our own libtool.
- LIBTOOL='$(top_builddir)/libtool'
+ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
  
-@@ -1814,6 +1814,7 @@
+@@ -2489,6 +2492,7 @@
  # Redirect the config.log output again, so that the ltconfig log is not
  # clobbered by the next message.
  exec 5>>./config.log
 +fi
  
- for ac_prog in 'bison -y' byacc
- do
+ 
+ #########################################################################
