Update to 0.6.0:
Overview of changes in libgpod 0.6.0
====================================

* support for iPod Classics and Video Nanos

The database from these models is protected by a checksum. When this checksum
doesn't match the content of the iPod database, the iPod won't show any
track (ie it will look empty). Support for writing this checksum has been
implemented in this release thanks to the awesome work of a few people in
#gtkpod. However, to calculate this checksum, a so called "firewire ID" is
needed which is different from iPod to iPod. Since reading it from the iPod
requires special permissions, the firewire ID must be written in a regular
file on the iPod so that libgpod can find it and use it to generate the
checksum.

libgpod installs a HAL callout to do that automatically when
everything is installed in an appropriate place. It can also be done manually,
see README.SysInfo for more information.

Cover art should be working except for non square covers, preliminary photo
support but this hasn't been widely tested yet.


* support for iPhone and iPod Touch

This requires manual user intervention: the devices must be jailbroken and
mounted through sshfs. The iPod Touch also needs a firewire ID which must be
manually set, see README.SysInfo

Cover art is implemented but not tested at all, ditto for photo support on
the iPod Touch


* additional tools to get the firewire id from new iPods including a HAL
  callout which will make the process totally automatic when it's properly
  installed. These tools need libsgutils to be installed.

* endianness fixes in the artwork writing code
* now depends on glib 2.8 or newer

Huge thanks to wtbw and Simon Schulz without whom that release wouldn't have
been possible. Thanks as well to the people on #gtkpod for the testing they
provided.

Other contributors to the release:
- Jesse Bouwman
- Alex Eftimie
- Christophe Fergeau
- Filippo Giunchedi
- Javier Kohen
- Tobias Kreisel
- Eric Lassauge
- Nicholas Piper
- Jorg Schuler
- Simon Schulz
- Todd Zullinger

diff --git a/audio/libgpod/patches/patch-aa b/audio/libgpod/patches/patch-aa
--- a/audio/libgpod/patches/patch-aa
+++ b/audio/libgpod/patches/patch-aa
@@ -1,8 +1,17 @@
-$NetBSD: patch-aa,v 1.2 2007/02/07 22:30:11 drochner Exp $
+$NetBSD: patch-aa,v 1.3 2007/11/29 18:47:28 wiz Exp $
 
---- configure.orig	2007-01-15 16:46:04.000000000 +0100
+--- configure.orig	2007-11-10 11:16:17.000000000 +0000
 +++ configure
-@@ -21991,7 +21991,7 @@ echo $ECHO_N "checking whether to build 
+@@ -20379,7 +20379,7 @@ echo "$as_me: error: HAL support explici
+    { (exit 1); exit 1; }; }
+   fi
+ 
+-  if test "x$enable_hal" == "xyes"; then
++  if test "x$enable_hal" = "xyes"; then
+ 
+ cat >>confdefs.h <<\_ACEOF
+ #define HAVE_HAL 1
+@@ -22370,7 +22370,7 @@ echo $ECHO_N "checking whether to build 
      { echo "$as_me:$LINENO: result: $with_python" >&5
  echo "${ECHO_T}$with_python" >&6; }
  
@@ -11,7 +20,7 @@ $NetBSD: patch-aa,v 1.2 2007/02/07 22:30:11 drochner Exp $
          if test -z "$PYTHON"; then
              # Extract the first word of "python", so it can be a program name with args.
  set dummy python; ac_word=$2
-@@ -22274,7 +22274,7 @@ rm -f conftest.err conftest.$ac_ext
+@@ -22653,7 +22653,7 @@ rm -f conftest.err conftest.$ac_ext
  CPPFLAGS="$save_CPPFLAGS"
  
  
@@ -20,8 +29,8 @@ $NetBSD: patch-aa,v 1.2 2007/02/07 22:30:11 drochner Exp $
                                                  if test `uname` = Darwin; then
                      PYTHON_LDFLAGS="-Wl,-F. -Wl,-F. -bundle"
                      if $PYTHON -c 'import sys, string; sys.exit(string.find(sys.prefix,"Framework")+1)'; then
-@@ -22330,7 +22330,7 @@ echo "${ECHO_T}no" >&6; }
- fi
+@@ -22713,7 +22713,7 @@ fi
+ 
  
  
 -                                if test "X$with_python" == Xyes; then
