Link libwine with -li386 so that it gets i386_set_ldt() defined.
XXX I updated configure.ac, but I can't actually patch that without running
into severe automake lossage, so that patch is not named patch-?? right now.

diff --git a/graphics/xine-lib/patches/patch-ag b/graphics/xine-lib/patches/patch-ag
--- a/graphics/xine-lib/patches/patch-ag
+++ b/graphics/xine-lib/patches/patch-ag
@@ -1,8 +1,114 @@
-$NetBSD: patch-ag,v 1.2 2003/04/11 09:19:54 rh Exp $
+$NetBSD: patch-ag,v 1.3 2003/10/02 14:20:35 mycroft Exp $
 
---- configure.orig	2003-04-09 02:17:18.000000000 +1000
-+++ configure
-@@ -13808,7 +13808,7 @@ if test "${ac_cv_lib_GL_glBegin+set}" = 
+--- configure.orig	2003-08-02 13:50:43.000000000 +0000
++++ configure	2003-10-02 13:03:23.000000000 +0000
+@@ -467,7 +467,7 @@
+ # include <unistd.h>
+ #endif"
+ 
+-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS XINE_MAJOR XINE_MINOR XINE_SUB XINE_IFACE_AGE XINE_BIN_AGE LT_CURRENT LT_REVISION LT_AGE TAR_NAME SPEC_VERSION LIBNAME build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CPP EGREP LN_S CCAS CCASFLAGS CCASCOMPILE ECHO RANLIB ac_ct_RANLIB LIBTOOL LIBTOOL_DEPS STATIC ALLOCA GLIBC21 LIBICONV USE_NLS MSGFMT GMSGFMT XGETTEXT INTLBISON BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATALOGS CATOBJEXT GMOFILES INTLLIBS INTLOBJS POFILES POSUB DATADIRNAME INSTOBJEXT GENCAT MKINSTALLDIRS INTL_LIBTOOL_SUFFIX_PREFIX INCLUDED_INTL_TRUE INCLUDED_INTL_FALSE DEBUG_CFLAGS ASFLAGS THREAD_LIBS THREAD_CFLAGS DYNAMIC_LD_LIBS LIBMPEG2_CFLAGS LIBA52_CFLAGS LIBFFMPEG_CFLAGS HAVE_MLIB_TRUE HAVE_MLIB_FALSE MLIB_CFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS HAVE_X11_TRUE HAVE_X11_FALSE HAVE_NVTV_TRUE HAVE_NVTV_FALSE NET_LIBS HAVE_ZLIB_TRUE HAVE_ZLIB_FALSE ZLIB_LIBS OPENGL_LIBS GLUT_LIBS GLU_LIBS HAVE_OPENGL_TRUE HAVE_OPENGL_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE GICONV_BSD_LIBS HAVE_GICONV_TRUE HAVE_GICONV_FALSE PPC_ARCH_TRUE PPC_ARCH_FALSE HAVE_XV_TRUE HAVE_XV_FALSE HAVE_XV_STATIC_TRUE HAVE_XV_STATIC_FALSE XV_LIB EXTRA_X_LIBS EXTRA_X_CFLAGS HAVE_XINERAMA_TRUE HAVE_XINERAMA_FALSE AALIB_CONFIG AAINFO AALIB_CFLAGS AALIB_LIBS HAVE_AA_TRUE HAVE_AA_FALSE HAVE_SUNFB_TRUE HAVE_SUNFB_FALSE HAVE_FB_TRUE HAVE_FB_FALSE PKG_CONFIG DIRECTFB_CFLAGS DIRECTFB_LIBS HAVE_DIRECTFB_TRUE HAVE_DIRECTFB_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_DXR3_TRUE HAVE_DXR3_FALSE HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE HAVE_LIBRTE_TRUE HAVE_LIBRTE_FALSE HAVE_ENCODER_TRUE HAVE_ENCODER_FALSE LINUX_INCLUDE HAVE_VIDIX_TRUE HAVE_VIDIX_FALSE HAVE_LINUX_TRUE HAVE_LINUX_FALSE BUILD_DHA_KMOD_TRUE BUILD_DHA_KMOD_FALSE MKNOD DEPMOD VORBIS_CFLAGS VORBIS_LIBS VORBISFILE_LIBS VORBISENC_LIBS OGG_CFLAGS OGG_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE THEORA_CFLAGS THEORA_LIBS THEORAFILE_LIBS THEORAENC_LIBS HAVE_THEORA_TRUE HAVE_THEORA_FALSE SPEEX_CFLAGS SPEEX_LIBS HAVE_SPEEX_TRUE HAVE_SPEEX_FALSE LIBFLAC_CFLAGS LIBFLAC_LIBS HAVE_FLAC_TRUE HAVE_FLAC_FALSE XVID_CFLAGS XVID_LIBS HAVE_XVID_TRUE HAVE_XVID_FALSE HAVE_LIBMNG_TRUE HAVE_LIBMNG_FALSE MNG_LIBS LIBPNG_CONFIG HAVE_LIBPNG_TRUE HAVE_LIBPNG_FALSE PNG_CFLAGS PNG_LIBS FREETYPE_CONFIG HAVE_FT2_TRUE HAVE_FT2_FALSE FT2_CFLAGS FT2_LIBS HAVE_OSS_TRUE HAVE_OSS_FALSE ALSA_CFLAGS ALSA_STATIC_LIB ALSA_LIBS HAVE_ALSA_TRUE HAVE_ALSA_FALSE HAVE_ALSA09_TRUE HAVE_ALSA09_FALSE ESD_CONFIG ESD_CFLAGS ESD_LIBS HAVE_ESD_TRUE HAVE_ESD_FALSE ARTS_CONFIG ARTS_CFLAGS ARTS_LIBS HAVE_ARTS_TRUE HAVE_ARTS_FALSE GNOME_VFS_CFLAGS GNOME_VFS_LIBS HAVE_GNOME_VFS_TRUE HAVE_GNOME_VFS_FALSE HAVE_SUNAUDIO_TRUE HAVE_SUNAUDIO_FALSE IRIXAL_CFLAGS IRIXAL_STATIC_LIB IRIXAL_LIBS HAVE_IRIXAL_TRUE HAVE_IRIXAL_FALSE KSTAT_LIBS HAVE_CDROM_IOCTLS_TRUE HAVE_CDROM_IOCTLS_FALSE DVDNAV_CONFIG DVDNAV_CFLAGS DVDNAV_LIBS HAVE_DVDNAV_TRUE HAVE_DVDNAV_FALSE BUILD_ASF_TRUE BUILD_ASF_FALSE BUILD_FAAD_TRUE BUILD_FAAD_FALSE XINE_PLUGIN_MIN_SYMS W32_NO_OPTIMIZE ANSI_FLAGS PASS1_CFLAGS PASS2_CFLAGS HAVE_W32DLL_TRUE HAVE_W32DLL_FALSE W32DLL_DEP HAVE_FFMMX_TRUE HAVE_FFMMX_FALSE HAVE_ARMV4L_TRUE HAVE_ARMV4L_FALSE XINE_PLUGINPATH XINE_FONTPATH XINE_LOCALEPATH XINE_PLUGINDIR XINE_FONTDIR XINE_LOCALEDIR XINE_ACFLAGS XINE_DATADIR XINE_SCRIPTPATH XINE_BUILD_CC XINE_BUILD_OS XINE_BUILD_DATE w32_path INCLUDES ACLOCAL_DIR INSTALL_M4_TRUE INSTALL_M4_FALSE DEPCOMP LIBOBJS LTLIBOBJS'
++ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS XINE_MAJOR XINE_MINOR XINE_SUB XINE_IFACE_AGE XINE_BIN_AGE LT_CURRENT LT_REVISION LT_AGE TAR_NAME SPEC_VERSION LIBNAME build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CPP EGREP LN_S CCAS CCASFLAGS CCASCOMPILE ECHO RANLIB ac_ct_RANLIB LIBTOOL LIBTOOL_DEPS STATIC ALLOCA GLIBC21 LIBICONV USE_NLS MSGFMT GMSGFMT XGETTEXT INTLBISON BUILD_INCLUDED_LIBINTL USE_INCLUDED_LIBINTL CATALOGS CATOBJEXT GMOFILES INTLLIBS INTLOBJS POFILES POSUB DATADIRNAME INSTOBJEXT GENCAT MKINSTALLDIRS INTL_LIBTOOL_SUFFIX_PREFIX INCLUDED_INTL_TRUE INCLUDED_INTL_FALSE DEBUG_CFLAGS ASFLAGS THREAD_LIBS THREAD_CFLAGS DYNAMIC_LD_LIBS LIBMPEG2_CFLAGS LIBA52_CFLAGS LIBFFMPEG_CFLAGS HAVE_MLIB_TRUE HAVE_MLIB_FALSE MLIB_CFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS HAVE_X11_TRUE HAVE_X11_FALSE HAVE_NVTV_TRUE HAVE_NVTV_FALSE NET_LIBS WINE_LIBS HAVE_ZLIB_TRUE HAVE_ZLIB_FALSE ZLIB_LIBS OPENGL_LIBS GLUT_LIBS GLU_LIBS HAVE_OPENGL_TRUE HAVE_OPENGL_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE GICONV_BSD_LIBS HAVE_GICONV_TRUE HAVE_GICONV_FALSE PPC_ARCH_TRUE PPC_ARCH_FALSE HAVE_XV_TRUE HAVE_XV_FALSE HAVE_XV_STATIC_TRUE HAVE_XV_STATIC_FALSE XV_LIB EXTRA_X_LIBS EXTRA_X_CFLAGS HAVE_XINERAMA_TRUE HAVE_XINERAMA_FALSE AALIB_CONFIG AAINFO AALIB_CFLAGS AALIB_LIBS HAVE_AA_TRUE HAVE_AA_FALSE HAVE_SUNFB_TRUE HAVE_SUNFB_FALSE HAVE_FB_TRUE HAVE_FB_FALSE PKG_CONFIG DIRECTFB_CFLAGS DIRECTFB_LIBS HAVE_DIRECTFB_TRUE HAVE_DIRECTFB_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_DXR3_TRUE HAVE_DXR3_FALSE HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE HAVE_LIBRTE_TRUE HAVE_LIBRTE_FALSE HAVE_ENCODER_TRUE HAVE_ENCODER_FALSE LINUX_INCLUDE HAVE_VIDIX_TRUE HAVE_VIDIX_FALSE HAVE_LINUX_TRUE HAVE_LINUX_FALSE BUILD_DHA_KMOD_TRUE BUILD_DHA_KMOD_FALSE MKNOD DEPMOD VORBIS_CFLAGS VORBIS_LIBS VORBISFILE_LIBS VORBISENC_LIBS OGG_CFLAGS OGG_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE THEORA_CFLAGS THEORA_LIBS THEORAFILE_LIBS THEORAENC_LIBS HAVE_THEORA_TRUE HAVE_THEORA_FALSE SPEEX_CFLAGS SPEEX_LIBS HAVE_SPEEX_TRUE HAVE_SPEEX_FALSE LIBFLAC_CFLAGS LIBFLAC_LIBS HAVE_FLAC_TRUE HAVE_FLAC_FALSE XVID_CFLAGS XVID_LIBS HAVE_XVID_TRUE HAVE_XVID_FALSE HAVE_LIBMNG_TRUE HAVE_LIBMNG_FALSE MNG_LIBS LIBPNG_CONFIG HAVE_LIBPNG_TRUE HAVE_LIBPNG_FALSE PNG_CFLAGS PNG_LIBS FREETYPE_CONFIG HAVE_FT2_TRUE HAVE_FT2_FALSE FT2_CFLAGS FT2_LIBS HAVE_OSS_TRUE HAVE_OSS_FALSE ALSA_CFLAGS ALSA_STATIC_LIB ALSA_LIBS HAVE_ALSA_TRUE HAVE_ALSA_FALSE HAVE_ALSA09_TRUE HAVE_ALSA09_FALSE ESD_CONFIG ESD_CFLAGS ESD_LIBS HAVE_ESD_TRUE HAVE_ESD_FALSE ARTS_CONFIG ARTS_CFLAGS ARTS_LIBS HAVE_ARTS_TRUE HAVE_ARTS_FALSE GNOME_VFS_CFLAGS GNOME_VFS_LIBS HAVE_GNOME_VFS_TRUE HAVE_GNOME_VFS_FALSE HAVE_SUNAUDIO_TRUE HAVE_SUNAUDIO_FALSE IRIXAL_CFLAGS IRIXAL_STATIC_LIB IRIXAL_LIBS HAVE_IRIXAL_TRUE HAVE_IRIXAL_FALSE KSTAT_LIBS HAVE_CDROM_IOCTLS_TRUE HAVE_CDROM_IOCTLS_FALSE DVDNAV_CONFIG DVDNAV_CFLAGS DVDNAV_LIBS HAVE_DVDNAV_TRUE HAVE_DVDNAV_FALSE BUILD_ASF_TRUE BUILD_ASF_FALSE BUILD_FAAD_TRUE BUILD_FAAD_FALSE XINE_PLUGIN_MIN_SYMS W32_NO_OPTIMIZE ANSI_FLAGS PASS1_CFLAGS PASS2_CFLAGS HAVE_W32DLL_TRUE HAVE_W32DLL_FALSE W32DLL_DEP HAVE_FFMMX_TRUE HAVE_FFMMX_FALSE HAVE_ARMV4L_TRUE HAVE_ARMV4L_FALSE XINE_PLUGINPATH XINE_FONTPATH XINE_LOCALEPATH XINE_PLUGINDIR XINE_FONTDIR XINE_LOCALEDIR XINE_ACFLAGS XINE_DATADIR XINE_SCRIPTPATH XINE_BUILD_CC XINE_BUILD_OS XINE_BUILD_DATE w32_path INCLUDES ACLOCAL_DIR INSTALL_M4_TRUE INSTALL_M4_FALSE DEPCOMP LIBOBJS LTLIBOBJS'
+ ac_subst_files=''
+ 
+ # Initialize some variables set by options.
+@@ -2874,12 +2874,12 @@
+   (exit $ac_status); }; }; then
+   for ac_declaration in \
+    ''\
++   '#include <stdlib.h>' \
+    'extern "C" void std::exit (int) throw (); using std::exit;' \
+    'extern "C" void std::exit (int); using std::exit;' \
+    'extern "C" void exit (int) throw ();' \
+    'extern "C" void exit (int);' \
+-   'void exit (int);' \
+-   '#include <stdlib.h>'
++   'void exit (int);'
+ do
+   cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+@@ -3671,12 +3671,12 @@
+   (exit $ac_status); }; }; then
+   for ac_declaration in \
+    ''\
++   '#include <stdlib.h>' \
+    'extern "C" void std::exit (int) throw (); using std::exit;' \
+    'extern "C" void std::exit (int); using std::exit;' \
+    'extern "C" void exit (int) throw ();' \
+    'extern "C" void exit (int);' \
+-   'void exit (int);' \
+-   '#include <stdlib.h>'
++   'void exit (int);'
+ do
+   cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+@@ -14158,6 +14158,66 @@
+ 
+ 
+ 
++WINE_LIBS=""
++echo "$as_me:$LINENO: checking for i386_set_ldt in -li386" >&5
++echo $ECHO_N "checking for i386_set_ldt in -li386... $ECHO_C" >&6
++if test "${ac_cv_lib_i386_i386_set_ldt+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_check_lib_save_LIBS=$LIBS
++LIBS="-li386  $LIBS"
++cat >conftest.$ac_ext <<_ACEOF
++#line $LINENO "configure"
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char i386_set_ldt ();
++int
++main ()
++{
++i386_set_ldt ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++         { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_cv_lib_i386_i386_set_ldt=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_cv_lib_i386_i386_set_ldt=no
++fi
++rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
++LIBS=$ac_check_lib_save_LIBS
++fi
++echo "$as_me:$LINENO: result: $ac_cv_lib_i386_i386_set_ldt" >&5
++echo "${ECHO_T}$ac_cv_lib_i386_i386_set_ldt" >&6
++if test $ac_cv_lib_i386_i386_set_ldt = yes; then
++  WINE_LIBS="-li386 $WINE_LIBS"
++fi
++
++
+ 
+ echo "$as_me:$LINENO: checking for gzsetparams in -lz" >&5
+ echo $ECHO_N "checking for gzsetparams in -lz... $ECHO_C" >&6
+@@ -14398,7 +14458,7 @@
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -11,7 +117,7 @@ $NetBSD: patch-ag,v 1.2 2003/04/11 09:19:54 rh Exp $
  cat >conftest.$ac_ext <<_ACEOF
  #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -13988,7 +13988,7 @@ echo "${ECHO_T}$ac_cv_header_GL_gl_h" >&
+@@ -14578,7 +14638,7 @@
  fi
  if test $ac_cv_header_GL_gl_h = yes; then
     ac_have_opengl="yes"
@@ -20,12 +126,115 @@ $NetBSD: patch-ag,v 1.2 2003/04/11 09:19:54 rh Exp $
  	       echo "$as_me:$LINENO: checking for glutInit in -lglut" >&5
  echo $ECHO_N "checking for glutInit in -lglut... $ECHO_C" >&6
  if test "${ac_cv_lib_glut_glutInit+set}" = set; then
-@@ -19238,7 +19238,7 @@ fi
-         echo "$as_me:$LINENO: checking for gnome-vfs-2.0" >&5
- echo $ECHO_N "checking for gnome-vfs-2.0... $ECHO_C" >&6
+@@ -20505,102 +20565,7 @@
+ fi
  
+ 
+-
+-  succeeded=no
+-
+-  if test -z "$PKG_CONFIG"; then
+-    # Extract the first word of "pkg-config", so it can be a program name with args.
+-set dummy pkg-config; ac_word=$2
+-echo "$as_me:$LINENO: checking for $ac_word" >&5
+-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+-if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  case $PKG_CONFIG in
+-  [\\/]* | ?:[\\/]*)
+-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+-  ;;
+-  *)
+-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+-for as_dir in $PATH
+-do
+-  IFS=$as_save_IFS
+-  test -z "$as_dir" && as_dir=.
+-  for ac_exec_ext in '' $ac_executable_extensions; do
+-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+-    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+-    break 2
+-  fi
+-done
+-done
+-
+-  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+-  ;;
+-esac
+-fi
+-PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+-
+-if test -n "$PKG_CONFIG"; then
+-  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+-echo "${ECHO_T}$PKG_CONFIG" >&6
+-else
+-  echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6
+-fi
+-
+-  fi
+-
+-  if test "$PKG_CONFIG" = "no" ; then
+-     echo "*** The pkg-config script could not be found. Make sure it is"
+-     echo "*** in your path, or set the PKG_CONFIG environment variable"
+-     echo "*** to the full path to pkg-config."
+-     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+-  else
+-     PKG_CONFIG_MIN_VERSION=0.9.0
+-     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+-        echo "$as_me:$LINENO: checking for gnome-vfs-2.0" >&5
+-echo $ECHO_N "checking for gnome-vfs-2.0... $ECHO_C" >&6
+-
 -        if $PKG_CONFIG --exists "gnome-vfs-2.0" ; then
-+        if false ; then
-             echo "$as_me:$LINENO: result: yes" >&5
- echo "${ECHO_T}yes" >&6
-             succeeded=yes
+-            echo "$as_me:$LINENO: result: yes" >&5
+-echo "${ECHO_T}yes" >&6
+-            succeeded=yes
+-
+-            echo "$as_me:$LINENO: checking GNOME_VFS_CFLAGS" >&5
+-echo $ECHO_N "checking GNOME_VFS_CFLAGS... $ECHO_C" >&6
+-            GNOME_VFS_CFLAGS=`$PKG_CONFIG --cflags "gnome-vfs-2.0"`
+-            echo "$as_me:$LINENO: result: $GNOME_VFS_CFLAGS" >&5
+-echo "${ECHO_T}$GNOME_VFS_CFLAGS" >&6
+-
+-            echo "$as_me:$LINENO: checking GNOME_VFS_LIBS" >&5
+-echo $ECHO_N "checking GNOME_VFS_LIBS... $ECHO_C" >&6
+-            GNOME_VFS_LIBS=`$PKG_CONFIG --libs "gnome-vfs-2.0"`
+-            echo "$as_me:$LINENO: result: $GNOME_VFS_LIBS" >&5
+-echo "${ECHO_T}$GNOME_VFS_LIBS" >&6
+-        else
+-            GNOME_VFS_CFLAGS=""
+-            GNOME_VFS_LIBS=""
+-            ## If we have a custom action on failure, don't print errors, but
+-            ## do set a variable so people can do so.
+-            GNOME_VFS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gnome-vfs-2.0"`
+-
+-        fi
+-
+-
+-
+-     else
+-        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+-        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+-     fi
+-  fi
+-
+-  if test $succeeded = yes; then
+-     no_gnome_vfs=no
+-  else
+-     no_gnome_vfs=yes
+-  fi
+-
++no_gnome_vfs=yes
+ 
+ 
+ if test x"$no_gnome_vfs" != "xyes"; then
+@@ -24379,6 +24344,7 @@
+ s,@HAVE_NVTV_TRUE@,$HAVE_NVTV_TRUE,;t t
+ s,@HAVE_NVTV_FALSE@,$HAVE_NVTV_FALSE,;t t
+ s,@NET_LIBS@,$NET_LIBS,;t t
++s,@WINE_LIBS@,$WINE_LIBS,;t t
+ s,@HAVE_ZLIB_TRUE@,$HAVE_ZLIB_TRUE,;t t
+ s,@HAVE_ZLIB_FALSE@,$HAVE_ZLIB_FALSE,;t t
+ s,@ZLIB_LIBS@,$ZLIB_LIBS,;t t
