Respect TCL_INCLUDE_SPEC from tclConfig.sh if specified. Bump PKGREVISION.

diff --git a/net/tcl-scotty/patches/patch-unix_configure b/net/tcl-scotty/patches/patch-unix_configure
--- a/net/tcl-scotty/patches/patch-unix_configure
+++ b/net/tcl-scotty/patches/patch-unix_configure
@@ -1,4 +1,4 @@
-$NetBSD: patch-unix_configure,v 1.2 2018/04/13 19:10:50 he Exp $
+$NetBSD: patch-unix_configure,v 1.3 2018/05/28 14:14:02 he Exp $
 
 Regen after unix/configure.in patching.
 
@@ -383,6 +383,15 @@ Regen after unix/configure.in patching.
      test -z "$ac_dir" && ac_dir=.
      if test -f $ac_dir/$ac_word; then
        ac_cv_path_tclsh="$ac_dir/$ac_word"
+@@ -1400,7 +1496,7 @@ SHLIB_SUFFIX=$TCL_SHLIB_SUFFIX
+ DL_LIBS=$TCL_DL_LIBS
+ LD_FLAGS=$TCL_LD_FLAGS
+ LD_SEARCH_FLAGS=$TCL_LD_SEARCH_FLAGS
+-TCL_INCLUDES=-I$TCL_PREFIX/include
++TCL_INCLUDES=${TCL_INCLUDE_SPEC:-"-I$TCL_PREFIX/include"}
+ 
+ if test -z "$SHLIB_LD" ; then
+     { echo "configure: error: no shared linker definition (TCL_SHLIB_LD) in tclConfig.sh" 1>&2; exit 1; }
 @@ -1431,9 +1527,13 @@ else
    /*)
    ac_cv_path_wish="$wish" # Let the user override the test with a path.
