Update sysutils/webmin to 1.270.  Changes from version 1.170 include:
+ Add a wbm.mk makefile fragment which can be used to create pkgsrc-managed
  Webmin modules.

! Fixed a possible remotely exploitable security hole caused by a bug
  Webmin's use of the Perl syslog function.

* Multiple Webmin users and groups can be deleted at once.
* The Webmin Servers Index module can automatically scan for new servers
  on the local network on a regular schedule.
* The idle automatic logout time can be configured on a per-user basis
  in the Webmin Users and Usermin Configuration modules.
* Increased the speed of Webmin configuration reloads done by the
  Webmin Users and Webmin Configuration module. This also prevents any
  down-time while the config is being re-read.
* Improved the timeout detection in HTTP requests, to reduce the ability
  of incorrect or malicious clients to tie up the Webmin webserver
  process.
* Enhanced the Unix User Authentication feature to allow different
  users and group members to be treated as different Webmin users.
* Improved the way the OS is detected at install time, so that new
  versions will be automatically supported.
* Different SSL certificates for virtual IP interfaces can be specified
  in the Webmin and Usermin modules, for sites doing SSL virtual hosting.
* Fixed a nasty bug that could cause configuration file permissions
  and ownership to be changed when they are modified.
* An option has been added in the Webmin Configuration module to enable
  full PAM conversations when logging in. This is necessary for systems
  on which PAM asks for more than just a username and password.
* All modules now use a new API for writing to configuration files,
  which ensures that the file does not get written to or truncated if
  the system is out of disk space.
* Added a button to the Webmin Actions Log module for rolling back
  configuration files to before an action was taken.
* Password timeouts are now enabled by default, to prevent brute-force
  password guessing attacks.

diff --git a/sysutils/webmin/patches/patch-aa b/sysutils/webmin/patches/patch-aa
--- a/sysutils/webmin/patches/patch-aa
+++ b/sysutils/webmin/patches/patch-aa
@@ -1,43 +1,112 @@
-$NetBSD: patch-aa,v 1.3 2005/01/23 04:36:27 jlam Exp $
+$NetBSD: patch-aa,v 1.4 2006/05/16 04:01:28 jlam Exp $
 
---- setup.sh.orig	2004-11-12 23:26:56.000000000 -0500
+--- setup.sh.orig	2006-04-04 19:12:35.000000000 -0400
 +++ setup.sh
-@@ -425,6 +425,7 @@ else
- 	fi
+@@ -35,6 +35,11 @@ echo ""
  
- 	# Ask whether to run at boot time
-+	atboot=0
- 	if [ "$atboot" = "" ]; then
- 		initsupp=`grep "^os_support=" "$srcdir/init/module.info" | sed -e 's/os_support=//g' | grep $os_type`
- 		atboot=0
-@@ -550,6 +551,7 @@ EOF
- 	fi
+ # Only root can run this
+ id | grep "uid=0(" >/dev/null
++#
++# For pkgsrc, we allow anyone to run this script, including unprivileged
++# users.
++#
++true
+ if [ $? != "0" ]; then
+ 	uname -a | grep -i CYGWIN >/dev/null
+ 	if [ $? != "0" ]; then
+@@ -122,6 +127,9 @@ if [ -r "$config_dir/config" ]; then
+ 	upgrading=1
  fi
  
-+noperlpath=yes
- if [ "$noperlpath" = "" ]; then
- 	echo "Inserting path to perl into scripts.."
- 	(find "$wadir" -name '*.cgi' -print ; find "$wadir" -name '*.pl' -print) | $perl "$wadir/perlpath.pl" $perl -
-@@ -641,6 +643,13 @@ if [ "$?" != "0" ]; then
- 	echo passwd_mode=0 >> $config_dir/miniserv.conf
- fi
- 
-+# Default to having delays on successive incorrect passwords for the same
-+# username.
-+grep passdelay= $config_dir/miniserv.conf >/dev/null
-+if [ "$?" != "0" ]; then
-+	echo passdelay=1 >> $config_dir/miniserv.conf
-+fi
++# For pkgsrc, we are never upgrading, only installing.
++upgrading=0
 +
- # If Perl crypt supports MD5, then make it the default
- if [ "$md5pass" = "1" ]; then
- 	echo md5pass=1 >> $config_dir/config
-@@ -681,8 +690,6 @@ if [ "\$answer" = "y" ]; then
- 	$config_dir/stop
- 	echo "Running uninstall scripts .."
- 	(cd "$wadir" ; WEBMIN_CONFIG=$config_dir WEBMIN_VAR=$var_dir LANG= "$wadir/run-uninstalls.pl")
--	echo "Deleting $wadir .."
--	rm -rf "$wadir"
- 	echo "Deleting $config_dir .."
- 	rm -rf "$config_dir"
- 	echo "Done!"
+ # Check if upgrading from an old version
+ if [ "$upgrading" = 1 ]; then
+ 	echo ""
+@@ -199,6 +207,10 @@ if [ "$upgrading" = 1 ]; then
+ else
+ 	# Config directory exists .. make sure it is not in use
+ 	ls $config_dir | grep -v rpmsave >/dev/null 2>&1
++	#
++	# For pkgsrc, we don't care if the config directory already exists.
++	#
++	false
+ 	if [ "$?" = "0" -a "$config_dir" != "/etc/webmin" ]; then
+ 		echo "ERROR: Config directory $config_dir is not empty"
+ 		echo ""
+@@ -518,6 +530,12 @@ else
+ 
+ 	kfile=$config_dir/miniserv.pem
+ 	openssl version >/dev/null 2>&1
++	#
++	# For pkgsrc, we always want to use the default miniserv.pem, though
++	# we'll recommend to the user at post-install time to generate a
++	# new certificate.
++	#
++	false
+ 	if [ "$?" = "0" ]; then
+ 		# We can generate a new SSL key for this host
+ 		host=`hostname`
+@@ -719,32 +737,35 @@ EOF
+ 	echo ""
+ fi
+ 
+-echo "Changing ownership and permissions .."
+-for m in $newmods; do
+-	echo Chowning $config_dir/$m
+-	chown -R root $config_dir/$m
+-	chgrp -R bin $config_dir/$m
+-	chmod -R og-rw $config_dir/$m
+-done
+-for f in miniserv.conf miniserv.pem miniserv.users; do
+-	chown -R root $config_dir/$f
+-	chgrp -R bin $config_dir/$f
+-	chmod -R og-rw $config_dir/$f
+-done
+-chmod +r $config_dir/version
+-if [ "$nochown" = "" ]; then
+-	chown -R root "$wadir"
+-	chgrp -R bin "$wadir"
+-	chmod -R og-w "$wadir"
+-	chmod -R a+rx "$wadir"
+-fi
+-if [ $var_dir != "/var" ]; then
+-	chown -R root $var_dir
+-	chgrp -R bin $var_dir
+-	chmod -R og-rwx $var_dir
+-fi
+-echo "..done"
+-echo ""
++# For pkgsrc, we skip changing ownership and permissions as we allow the
++# INSTALL/DEINSTALL to manage this for us.
++#
++#echo "Changing ownership and permissions .."
++#for m in $newmods; do
++#	echo Chowning $config_dir/$m
++#	chown -R root $config_dir/$m
++#	chgrp -R bin $config_dir/$m
++#	chmod -R og-rw $config_dir/$m
++#done
++#for f in miniserv.conf miniserv.pem miniserv.users; do
++#	chown -R root $config_dir/$f
++#	chgrp -R bin $config_dir/$f
++#	chmod -R og-rw $config_dir/$f
++#done
++#chmod +r $config_dir/version
++#if [ "$nochown" = "" ]; then
++#	chown -R root "$wadir"
++#	chgrp -R bin "$wadir"
++#	chmod -R og-w "$wadir"
++#	chmod -R a+rx "$wadir"
++#fi
++#if [ $var_dir != "/var" ]; then
++#	chown -R root $var_dir
++#	chgrp -R bin $var_dir
++#	chmod -R og-rwx $var_dir
++#fi
++#echo "..done"
++#echo ""
+ 
+ # Save target directory if one was specified
+ if [ "$wadir" != "$srcdir" ]; then
