print/foo2zjs: Remove bad dependency check of dc
The package assumes that if the dc program doesn't support -V, it must
not support -e either.  This is a bad assumption; DragonFly supports
-e but doesn't support -V.  Rather than try to fix a bad conftest, just
remove it completely.  There's a previous test for dc presence.  If dc
doesn't support -e, let it break during the build rather than before it.
It doesn't take long to build.

diff --git a/print/foo2zjs/patches/patch-Makefile b/print/foo2zjs/patches/patch-Makefile
--- a/print/foo2zjs/patches/patch-Makefile
+++ b/print/foo2zjs/patches/patch-Makefile
@@ -1,6 +1,9 @@
-$NetBSD: patch-Makefile,v 1.1 2012/07/25 17:15:45 imil Exp $
+$NetBSD: patch-Makefile,v 1.2 2012/08/10 16:30:53 marino Exp $
 
 Fix PREFIX path
+Remove extra dc check. The DragonFly version has dc that supports the -e
+option, but it doesn't support -V.  It's a bad check, the conftest should
+actually test for -e support.  Just remove it completely.
 
 --- Makefile.orig	2012-06-01 23:10:31.000000000 +0000
 +++ Makefile
@@ -24,3 +27,16 @@ Fix PREFIX path
  DOCDIR=$(PREFIX)/share/doc/foo2zjs/
  INSTALL=install
  ROOT=root
+@@ -409,12 +407,6 @@ all-test:
+ 	    echo "      ***"; \
+ 	    exit 1; \
+ 	fi
+-	@if ! dc -V >/dev/null 2>&1; then \
+-	    echo "      ***"; \
+-	    echo "      *** Error: must install GNU dc with the -e option!"; \
+-	    echo "      ***"; \
+-	    exit 1; \
+-	fi
+ ifeq ($(UNAME),Darwin)
+ 	@if ! type gsed >/dev/null 2>&1; then \
+ 	    echo "      ***"; \
