If dirfd is either a function or a macro, use it. If it doesn't exist, but DIR contains dd_fd, define it as macro. Otherwise use -1 when calling fts_safe_changedir in fts(3). Based on patch from Sean Boudreau.

diff --git a/pkgtools/libnbcompat/files/configure b/pkgtools/libnbcompat/files/configure
--- a/pkgtools/libnbcompat/files/configure
+++ b/pkgtools/libnbcompat/files/configure
@@ -10998,7 +10998,213 @@ _ACEOF
 else
   :
 fi
+{ echo "$as_me:$LINENO: checking for DIR.dd_fd" >&5
+echo $ECHO_N "checking for DIR.dd_fd... $ECHO_C" >&6; }
+if test "${ac_cv_member_DIR_dd_fd+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <sys/types.h>
+	  #if HAVE_DIRENT_H
+	  # include <dirent.h>
+	  #else
+	  # define dirent direct
+	  # if HAVE_SYS_NDIR_H
+	  #  include <sys/ndir.h>
+	  # endif
+	  # if HAVE_SYS_DIR_H
+	  #  include <sys/dir.h>
+	  # endif
+	  # if HAVE_NDIR_H
+	  #  include <ndir.h>
+	  # endif
+	  #endif
 
+int
+main ()
+{
+static DIR ac_aggr;
+if (ac_aggr.dd_fd)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_DIR_dd_fd=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <sys/types.h>
+	  #if HAVE_DIRENT_H
+	  # include <dirent.h>
+	  #else
+	  # define dirent direct
+	  # if HAVE_SYS_NDIR_H
+	  #  include <sys/ndir.h>
+	  # endif
+	  # if HAVE_SYS_DIR_H
+	  #  include <sys/dir.h>
+	  # endif
+	  # if HAVE_NDIR_H
+	  #  include <ndir.h>
+	  # endif
+	  #endif
+
+int
+main ()
+{
+static DIR ac_aggr;
+if (sizeof ac_aggr.dd_fd)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_DIR_dd_fd=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_member_DIR_dd_fd=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_member_DIR_dd_fd" >&5
+echo "${ECHO_T}$ac_cv_member_DIR_dd_fd" >&6; }
+if test $ac_cv_member_DIR_dd_fd = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DIR_DD_FD 1
+_ACEOF
+
+:
+else
+  :
+fi
+
+
+{ echo "$as_me:$LINENO: checking for dirfd" >&5
+echo $ECHO_N "checking for dirfd... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <sys/types.h>
+    #if HAVE_DIRENT_H
+    # include <dirent.h>
+    #else
+    # define dirent direct
+    # if HAVE_SYS_NDIR_H
+    #  include <sys/ndir.h>
+    # endif
+    # if HAVE_SYS_DIR_H
+    #  include <sys/dir.h>
+    # endif
+    # if HAVE_NDIR_H
+    #  include <ndir.h>
+    # endif
+    #endif
+    int dummy_var;
+
+int
+main ()
+{
+ dummy_var = dirfd((DIR *)0)
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DIRFD 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
 
 if test $ac_cv_type_long_long = yes; then
 
