Update pkgtools/libnbcompat to 20030826.  Changes from previous version:
    * Properly declare statfs() and fstatfs() if we use the libnbcompat
      versions.

    * Move some headers into a private directory in the installed
      location so that they don't override headers of the same name
      on the system.

    * Define TAILQ_HEAD_INITIALIZER if it doesn't exist.

    * Add a poll() implementation using select() for poll()-less systems.
      Thanks for Charles Blundell for the implementation!

    * Fix the vis.h check for systems whose vis() is not as featureful
      as NetBSD's.

diff --git a/pkgtools/libnbcompat/files/configure b/pkgtools/libnbcompat/files/configure
--- a/pkgtools/libnbcompat/files/configure
+++ b/pkgtools/libnbcompat/files/configure
@@ -1274,7 +1274,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-          ac_config_headers="$ac_config_headers nbconfig.h"
+          ac_config_headers="$ac_config_headers nbcompat/nbconfig.h"
 
 test "$program_prefix" != NONE &&
   program_transform_name="s,^,$program_prefix,;$program_transform_name"
@@ -3166,7 +3166,6 @@ done
 
 
 
-
 for ac_header in arpa/nameser.h assert.h bind/bitypes.h dirent.h err.h \
 	errno.h fcntl.h fts.h inttypes.h libutil.h limits.h \
 	machine/endian.h memory.h ndir.h netdb.h netinet/in6_machtypes.h \
@@ -3175,7 +3174,7 @@ for ac_header in arpa/nameser.h assert.h bind/bitypes.h dirent.h err.h \
 	sys/endian.h sys/file.h sys/mkdev.h sys/mount.h sys/ndir.h \
 	sys/param.h sys/poll.h sys/queue.h sys/time.h sys/ttycom.h \
 	sys/stat.h sys/statvfs.h sys/vfs.h sys/types.h sys/vfs.h termcap.h \
-	termios.h time.h tzfile.h unistd.h util.h utmp.h vis.h
+	termios.h time.h tzfile.h unistd.h util.h utmp.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -3315,6 +3314,201 @@ _ACEOF
 fi
 
 done
+
+
+pkg_use_nbcompat_vis=yes
+if test "${ac_cv_header_vis_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for vis.h" >&5
+echo $ECHO_N "checking for vis.h... $ECHO_C" >&6
+if test "${ac_cv_header_vis_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_vis_h" >&5
+echo "${ECHO_T}$ac_cv_header_vis_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking vis.h usability" >&5
+echo $ECHO_N "checking vis.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <vis.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking vis.h presence" >&5
+echo $ECHO_N "checking vis.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <vis.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: vis.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: vis.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vis.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: vis.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: vis.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: vis.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vis.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: vis.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vis.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: vis.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for vis.h" >&5
+echo $ECHO_N "checking for vis.h... $ECHO_C" >&6
+if test "${ac_cv_header_vis_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_vis_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_vis_h" >&5
+echo "${ECHO_T}$ac_cv_header_vis_h" >&6
+
+fi
+if test $ac_cv_header_vis_h = yes; then
+
+
+	echo "$as_me:$LINENO: checking for VIS_WHITE in vis.h" >&5
+echo $ECHO_N "checking for VIS_WHITE in vis.h... $ECHO_C" >&6
+if test "${pkg_cv_have_vis_white+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+		cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+  #include <sys/types.h>
+		  #include <vis.h>
+int
+main ()
+{
+  int X = VIS_WHITE ;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+   pkg_cv_have_vis_white=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ pkg_cv_have_vis_white=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $pkg_cv_have_vis_white" >&5
+echo "${ECHO_T}$pkg_cv_have_vis_white" >&6
+	if test "x$pkg_cv_have_vis_white" = "xyes"; then
+		 cat >>confdefs.h <<\_ACEOF
+#define HAVE_VIS_H 1
+_ACEOF
+
+	else
+		 pkg_use_nbcompat_vis=no
+		:
+	fi
+
+
+fi
+
 
 
 
@@ -5558,9 +5752,10 @@ done
 
 
 
+
 for ac_func in err fgetln fparseln fseeko getenv glob inet_ntop \
 		inet_pton isblank lchflags lchmod lchown lutimes mkstemp \
-		mkdtemp setenv setprogname snprintf strdup strerror \
+		mkdtemp poll setenv setprogname snprintf strdup strerror \
 		strlcat strlcpy strmode strptime strsep strtoll timegm \
 		usleep
 do
@@ -6168,10 +6363,21 @@ if test `eval echo '${'$as_ac_var'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
 _ACEOF
-
+ pkg_use_nbcompat_vis=no
+else
+  pkg_use_nbcompat_vis=yes
 fi
 done
 
+
+if test $pkg_use_nbcompat_vis = yes; then
+	cat >>confdefs.h <<\_ACEOF
+#define HAVE_NBCOMPAT_VIS 1
+_ACEOF
+
+	LIBOBJS="$LIBOBJS vis.$ac_objext"
+	LIBOBJS="$LIBOBJS unvis.$ac_objext"
+fi
 
 
 
@@ -6550,7 +6756,6 @@ echo "$as_me:$LINENO: result: $ac_cv_func_sl_init" >&5
 echo "${ECHO_T}$ac_cv_func_sl_init" >&6
 if test $ac_cv_func_sl_init = yes; then
 
-	if test $ac_cv_func_sl_init = yes; then
 
 	echo "$as_me:$LINENO: checking if sl_add() returns int" >&5
 echo $ECHO_N "checking if sl_add() returns int... $ECHO_C" >&6
@@ -6605,13 +6810,12 @@ echo "${ECHO_T}$pkg_cv_INT_SL_ADD" >&6
 		:
 	fi
 
-	fi
 
 fi
 
 
 
-pkg_have_nbcompat_statfs=yes
+pkg_use_nbcompat_statfs=yes
 echo "$as_me:$LINENO: checking for statfs" >&5
 echo $ECHO_N "checking for statfs... $ECHO_C" >&6
 if test "${ac_cv_func_statfs+set}" = set; then
@@ -6772,14 +6976,14 @@ fi
 
 		;;
 	*)
-		pkg_have_nbcompat_statfs=no
+		pkg_use_nbcompat_statfs=no
 		;;
 	esac
 
 fi
 
 
-if test $pkg_have_nbcompat_statfs = yes; then
+if test $pkg_use_nbcompat_statfs = yes; then
 	cat >>confdefs.h <<\_ACEOF
 #define HAVE_NBCOMPAT_STATFS 1
 _ACEOF
@@ -6991,65 +7195,6 @@ fi
 done
 
 
-	fi
-
-fi
-
-if test $ac_cv_header_vis_h = yes; then
-
-	echo "$as_me:$LINENO: checking for VIS_WHITE in vis.h" >&5
-echo $ECHO_N "checking for VIS_WHITE in vis.h... $ECHO_C" >&6
-if test "${pkg_cv_have_vis_white+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-		cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-	#include <sys/types.h>
-	#include <vis.h>
-int
-main ()
-{
-  int X = VIS_WHITE ;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-   pkg_cv_have_vis_white=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
- pkg_cv_have_vis_white=no
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-
-fi
-echo "$as_me:$LINENO: result: $pkg_cv_have_vis_white" >&5
-echo "${ECHO_T}$pkg_cv_have_vis_white" >&6
-	if test "x$pkg_cv_have_vis_white" = "xyes"; then
-		:
-	else
-		ac_cv_header_vis_h=no
-		:
 	fi
 
 fi
@@ -7704,7 +7849,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-  "nbconfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS nbconfig.h" ;;
+  "nbcompat/nbconfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS nbcompat/nbconfig.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
