Adapt this package for Mesa 3.1 or newer.

diff --git a/net/xtraceroute/patches/patch-ab b/net/xtraceroute/patches/patch-ab
--- a/net/xtraceroute/patches/patch-ab
+++ b/net/xtraceroute/patches/patch-ab
@@ -1,7 +1,43 @@
-$NetBSD: patch-ab,v 1.3 1999/07/07 20:47:43 tron Exp $
+$NetBSD: patch-ab,v 1.4 2000/04/05 20:56:03 tron Exp $
 
 --- configure.orig	Sun Feb 28 05:56:14 1999
-+++ configure	Wed Jul  7 22:40:36 1999
++++ configure	Wed Apr  5 22:53:00 2000
+@@ -3422,14 +3422,14 @@
+ fi
+ 
+ 
+-echo $ac_n "checking for glBegin in -lMesaGL""... $ac_c" 1>&6
+-echo "configure:3427: checking for glBegin in -lMesaGL" >&5
++echo $ac_n "checking for glBegin in -lGL""... $ac_c" 1>&6
++echo "configure:3427: checking for glBegin in -lGL" >&5
+ ac_lib_var=`echo MesaGL'_'glBegin | sed 'y%./+-%__p_%'`
+ if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+   echo $ac_n "(cached) $ac_c" 1>&6
+ else
+   ac_save_LIBS="$LIBS"
+-LIBS="-lMesaGL $GTK_LIBS $GL_LDOPTS $LIBS"
++LIBS="-lGL $GTK_LIBS $GL_LDOPTS $LIBS"
+ cat > conftest.$ac_ext <<EOF
+ #line 3435 "configure"
+ #include "confdefs.h"
+@@ -3554,7 +3554,7 @@
+ elif test "x$with_lib_MesaGL" = "xyes"; then
+ 
+  if test "x$have_MesaGL" = "xyes"; then
+-  GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
++  GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+  else
+   { echo "configure: error: Missing MesaGL library" 1>&2; exit 1; }
+  fi
+@@ -3564,7 +3564,7 @@
+  if test "x$have_GL" = "xyes"; then
+   GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+  elif test "x$have_MesaGL" = "xyes"; then
+-  GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
++  GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+  else
+   { echo "configure: error: You need GL or MesaGL libraries" 1>&2; exit 1; }
+  fi
 @@ -3630,7 +3630,7 @@
    echo $ac_n "(cached) $ac_c" 1>&6
  else
