Update to openttd-0.6.0.
This release brings, among other things, newhouses/newindustries (with newGRF),
signals and diagonal tracks under bridges,trams, autoslope, oneway roads,
half tile slopes, drive through road stops and group management of vehicles.

diff --git a/games/openttd/patches/patch-aa b/games/openttd/patches/patch-aa
--- a/games/openttd/patches/patch-aa
+++ b/games/openttd/patches/patch-aa
@@ -1,31 +1,79 @@
-$NetBSD: patch-aa,v 1.5 2007/05/06 17:47:35 jdolecek Exp $
+$NetBSD: patch-aa,v 1.6 2008/04/07 19:44:19 tnn Exp $
 
---- Makefile.orig	2007-04-20 21:47:49.000000000 +0200
-+++ Makefile	2007-05-06 19:17:16.000000000 +0200
-@@ -213,7 +213,7 @@
- ifndef WIN32
- 	ifndef MORPHOS
- 		ifndef OSX
--			LDFLAGS+=-lpthread
-+			LDFLAGS+=${PTHREAD_LDFLAGS} ${PTHREAD_LIBS}
- 		endif
- 	endif
- endif
-@@ -585,17 +585,6 @@
- 		CDEFS += -DWITH_COCOA
- 		LIBS += -F/System/Library/Frameworks -framework Cocoa -framework Carbon -framework AudioUnit
- 	endif
--
--	# OSX path setup
--	ifndef SECOND_DATA_PATH
--		SECOND_DATA_PATH:="$(OSXAPP)/Contents/Data/"
--	endif
--
--	ifndef CUSTOM_LANG_DIR
--		ifndef DEDICATED
--		CUSTOM_LANG_DIR:="$(OSXAPP)/Contents/Lang/"
--		endif
--	endif
- endif
+--- config.lib.orig	2008-04-01 00:31:33.000000000 +0200
++++ config.lib
+@@ -392,9 +392,9 @@ check_params() {
+ 		exit 1
+ 	fi
+ 	# OS only allows DETECT, UNIX, OSX, FREEBSD, OPENBSD, MORPHOS, BEOS, SUNOS, CYGWIN, MINGW, OS2, WINCE, and PSP
+-	if [ -z "`echo $os | egrep '^(DETECT|UNIX|OSX|FREEBSD|OPENBSD|MORPHOS|BEOS|SUNOS|CYGWIN|MINGW|OS2|WINCE|PSP)$'`" ]; then
++	if [ -z "`echo $os | egrep '^(DETECT|UNIX|OSX|FREEBSD|OPENBSD|NETBSD|MORPHOS|BEOS|SUNOS|CYGWIN|MINGW|OS2|WINCE|PSP)$'`" ]; then
+ 		echo "configure: error: invalid option --os=$os"
+-		echo " Available options are: --os=[DETECT|UNIX|OSX|FREEBSD|OPENBSD|MORPHOS|BEOS|SUNOS|CYGWIN|MINGW|OS2|WINCE|PSP]"
++		echo " Available options are: --os=[DETECT|UNIX|OSX|FREEBSD|OPENBSD|NETBSD|MORPHOS|BEOS|SUNOS|CYGWIN|MINGW|OS2|WINCE|PSP]"
+ 		exit 1
+ 	fi
+ 	# cpu_type can be either 32 or 64
+@@ -1000,6 +1000,10 @@ make_cflags_and_ldflags() {
+ 		LIBS="$LIBS -pthread"
+ 	fi
  
- ifdef MIDI
++	if [ "$os" = "NETBSD" ]; then
++		LIBS="$LIBS -lpthread"
++	fi
++
+ 	if [ "$os" = "FREEBSD" ]; then
+ 		LIBS="$LIBS -lpthread"
+ 	fi
+@@ -1016,7 +1020,7 @@ make_cflags_and_ldflags() {
+ 	fi
+ 
+ 	# Most targets act like UNIX, just with some additions
+-	if [ "$os" = "BEOS" ] || [ "$os" = "OSX" ] || [ "$os" = "MORPHOS" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "SUNOS" ] || [ "$os" = "OS2" ]; then
++	if [ "$os" = "BEOS" ] || [ "$os" = "OSX" ] || [ "$os" = "MORPHOS" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "NETBSD" ] || [ "$os" = "SUNOS" ] || [ "$os" = "OS2" ]; then
+ 		CFLAGS="$CFLAGS -DUNIX"
+ 	fi
+ 	# And others like Windows
+@@ -1511,7 +1515,7 @@ detect_awk() {
+ 
+ detect_os() {
+ 	if [ "$os" = "DETECT" ]; then
+-		# Detect UNIX, OSX, FREEBSD, OPENBSD, MORPHOS, BEOS, SUNOS, CYGWIN, MINGW, OS2, WINCE, and PSP
++		# Detect UNIX, OSX, FREEBSD, OPENBSD, NETBSD, MORPHOS, BEOS, SUNOS, CYGWIN, MINGW, OS2, WINCE, and PSP
+ 
+ 		# Try first via dumpmachine, then via uname
+ 		os=`echo "$host" | tr '[A-Z]' '[a-z]' | $awk '
+@@ -1519,6 +1523,7 @@ detect_os() {
+ 					/darwin/       { print "OSX";     exit}
+ 					/freebsd/      { print "FREEBSD"; exit}
+ 					/openbsd/      { print "OPENBSD"; exit}
++					/netbsd/       { print "NETBSD";  exit}
+ 					/morphos/      { print "MORPHOS"; exit}
+ 					/beos/         { print "BEOS";    exit}
+ 					/sunos/        { print "SUNOS";   exit}
+@@ -1536,6 +1541,7 @@ detect_os() {
+ 					/darwin/       { print "OSX";     exit}
+ 					/freebsd/      { print "FREEBSD"; exit}
+ 					/openbsd/      { print "OPENBSD"; exit}
++					/netbsd/       { print "NETBSD";  exit}
+ 					/morphos/      { print "MORPHOS"; exit}
+ 					/beos/         { print "BEOS";    exit}
+ 					/sunos/        { print "SUNOS";   exit}
+@@ -1548,7 +1554,7 @@ detect_os() {
+ 		if [ -z "$os" ]; then
+ 			log 1 "detecting OS... none detected"
+ 			log 1 "I couldn't detect your OS. Please use --os=OS to force one"
+-			log 1 "Allowed values are: UNIX, OSX, FREEBSD, OPENBSD, MORPHOS, BEOS, SUNOS, CYGWIN, MINGW, OS2, WINCE, and PSP"
++			log 1 "Allowed values are: UNIX, OSX, FREEBSD, OPENBSD, NETBSD, MORPHOS, BEOS, SUNOS, CYGWIN, MINGW, OS2, WINCE, and PSP"
+ 			exit 1
+ 		fi
+ 
+@@ -2296,7 +2302,7 @@ showhelp() {
+ 	echo "  --awk=AWK                      the awk to use in configure [awk]"
+ 	echo "  --lipo=LIPO                    the lipo to use (OSX ONLY) [HOST-lipo]"
+ 	echo "  --os=OS                        the OS we are compiling for [DETECT]"
+-	echo "                                 DETECT/UNIX/OSX/FREEBSD/OPENBSD/MORPHOS/"
++	echo "                                 DETECT/UNIX/OSX/FREEBSD/OPENBSD/NETBSD/MORPHOS/"
+ 	echo "                                 BEOS/SUNOS/CYGWIN/MINGW/OS2/WINCE/PSP"
+ 	echo "  --endian=ENDIAN                set the endian of the HOST (AUTO/LE/BE)"
+ 	echo "  --revision=rXXXX               overwrite the revision detection."
