Fix basic NetBSD SPARC support. This currently disables Sbus until someone more involved in the platform take a look or I find the time to merge the xsrc changes.

diff --git a/x11/modular-xorg-server/patches/patch-ab b/x11/modular-xorg-server/patches/patch-ab
--- a/x11/modular-xorg-server/patches/patch-ab
+++ b/x11/modular-xorg-server/patches/patch-ab
@@ -1,54 +1,36 @@
-$NetBSD: patch-ab,v 1.2 2007/02/05 23:08:36 joerg Exp $
+$NetBSD: patch-ab,v 1.3 2007/08/16 20:10:15 joerg Exp $
 
---- configure.orig	2007-01-23 05:40:03.000000000 +0000
+--- configure.orig	2007-08-16 16:48:09.000000000 +0200
 +++ configure
-@@ -24300,6 +24300,10 @@ _ACEOF
- #define USE_DEV_IO 1
- _ACEOF
-  ;;
-+		*dragonfly*)	cat >>confdefs.h <<\_ACEOF
-+#define USE_DEV_IO 1
-+_ACEOF
-+ ;;
- 		*netbsd*)	cat >>confdefs.h <<\_ACEOF
- #define USE_I386_IOPL 1
- _ACEOF
-@@ -24406,7 +24410,7 @@ fi
- DRI=no
- KDRIVE_HW=no
- case $host_os in
--  *freebsd*)
-+  *freebsd* | *dragonfly*)
- 	case $host_os in
- 		kfreebsd*-gnu) ;;
- 		*)
-@@ -24445,6 +24449,11 @@ _ACEOF
- 
- 
- cat >>confdefs.h <<\_ACEOF
-+#define PCVT_SUPPORT 1
-+_ACEOF
-+
-+
-+cat >>confdefs.h <<\_ACEOF
- #define WSCONS_SUPPORT 1
- _ACEOF
- 
-@@ -27892,7 +27901,7 @@ _ACEOF
- 
+@@ -26426,15 +26426,7 @@ echo $ECHO_N "checking for $prefix/share
+ if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  test "$cross_compiling" = yes &&
+-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+-   { (exit 1); exit 1; }; }
+-if test -r "$prefix/share/X11/sgml/defs.ent"; then
+   eval "$as_ac_File=yes"
+-else
+-  eval "$as_ac_File=no"
+-fi
  fi
- 
--VENDOR_RELEASE="((($VERSION_MAJOR) * 10000000) + (($VERSION_MINOR) * 100000) + (($VERSION_PATCH) * 1000) + $VERSION_SNAP)"
-+VENDOR_RELEASE=`expr \( $VERSION_MAJOR \* 10000000 \) + \( $VERSION_MINOR \* 100000 \) + \( $VERSION_PATCH \* 1000 \) + $VERSION_SNAP`
- 
- if test $VERSION_SNAP = "0"; then
- 	if test $VERSION_PATCH = "0"; then
-@@ -30642,7 +30651,7 @@ cat >>confdefs.h <<_ACEOF
- _ACEOF
- 
+ ac_res=`eval echo '${'$as_ac_File'}'`
+ 	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+@@ -31155,7 +31147,14 @@ echo "$as_me: error: Your OS is unknown.
  		;;
--	  freebsd* | kfreebsd*-gnu)
-+	  freebsd* | kfreebsd*-gnu | dragonfly*)
- 	  	XORG_OS="freebsd"
- 		XORG_OS_SUBDIR="bsd"
- 		XORG_OS_KBD="BSD"
+ 	  sparc*)
+ 		xorg_bus_sparcpci="yes"
+-		xorg_bus_sparc="yes"
++		case $host_os in
++		netbsd*)
++			xorg_bus_sparc="no"
++			;;
++		*)
++			xorg_bus_sparc="yes"
++			;;
++		esac
+ 		;;
+ 	  x86_64*|amd64*)
+ 		case $host_os in
