Install mutt_dotlock unconditionally Re-enable user-destdir, by using SPECIAL_PERMS, thanks joerg@ for pointing that

diff --git a/mail/mutt-devel/patches/patch-ab b/mail/mutt-devel/patches/patch-ab
--- a/mail/mutt-devel/patches/patch-ab
+++ b/mail/mutt-devel/patches/patch-ab
@@ -1,8 +1,8 @@
-$NetBSD: patch-ab,v 1.11 2008/05/18 08:26:31 tonio Exp $
+$NetBSD: patch-ab,v 1.12 2009/01/27 19:50:33 tonio Exp $
 
---- Makefile.in.orig	Sat May 17 20:04:33 2008
+--- Makefile.in.orig	2009-01-05 20:24:13.000000000 +0100
 +++ Makefile.in
-@@ -161,7 +161,7 @@ DATADIRNAME = @DATADIRNAME@
+@@ -163,7 +163,7 @@ DATADIRNAME = @DATADIRNAME@
  DBX = @DBX@
  DEBUGGER = @DEBUGGER@
  DEFS = -DPKGDATADIR=\"$(pkgdatadir)\" -DSYSCONFDIR=\"$(sysconfdir)\" \
@@ -11,7 +11,7 @@ $NetBSD: patch-ab,v 1.11 2008/05/18 08:26:31 tonio Exp $
  	-DHAVE_CONFIG_H=1
  
  DEPDIR = @DEPDIR@
-@@ -271,7 +271,7 @@ infodir = @infodir@
+@@ -272,7 +272,7 @@ infodir = @infodir@
  install_sh = @install_sh@
  libdir = @libdir@
  libexecdir = @libexecdir@
@@ -20,14 +20,15 @@ $NetBSD: patch-ab,v 1.11 2008/05/18 08:26:31 tonio Exp $
  localstatedir = @localstatedir@
  mandir = @mandir@
  mkdir_p = @mkdir_p@
-@@ -1021,8 +1021,8 @@ install-exec-hook:
+@@ -1063,11 +1063,6 @@ install-exec-hook:
+ 		rm -f $(DESTDIR)$(bindir)/mutt.dotlock ;		\
  		ln -sf $(DESTDIR)$(bindir)/mutt_dotlock $(DESTDIR)$(bindir)/mutt.dotlock ; \
  	fi
- 	if test -f $(DESTDIR)$(bindir)/mutt_dotlock && test x@DOTLOCK_GROUP@ != x ; then \
+-	if test -f $(DESTDIR)$(bindir)/mutt_dotlock && test x@DOTLOCK_GROUP@ != x ; then \
 -		chgrp @DOTLOCK_GROUP@ $(DESTDIR)$(bindir)/mutt_dotlock && \
 -		chmod @DOTLOCK_PERMISSION@ $(DESTDIR)$(bindir)/mutt_dotlock || \
-+		${CHGRP} @DOTLOCK_GROUP@ $(DESTDIR)$(bindir)/mutt_dotlock && \
-+		${CHMOD} @DOTLOCK_PERMISSION@ $(DESTDIR)$(bindir)/mutt_dotlock || \
- 		{ echo "Can't fix mutt_dotlock's permissions!" >&2 ; exit 1 ; } \
- 	fi
+-		{ echo "Can't fix mutt_dotlock's permissions!" >&2 ; exit 1 ; } \
+-	fi
  
+ install-data-local:
+ 	$(srcdir)/mkinstalldirs $(DESTDIR)$(sysconfdir)
