Honor CHGRP.

diff --git a/mail/mutt-devel/patches/patch-ab b/mail/mutt-devel/patches/patch-ab
--- a/mail/mutt-devel/patches/patch-ab
+++ b/mail/mutt-devel/patches/patch-ab
@@ -1,6 +1,6 @@
-$NetBSD: patch-ab,v 1.5 2004/08/05 03:24:39 jlam Exp $
+$NetBSD: patch-ab,v 1.6 2005/05/29 05:09:55 minskim Exp $
 
---- Makefile.in.orig	Sun Feb  1 13:24:01 2004
+--- Makefile.in.orig	2004-02-01 12:24:01.000000000 -0600
 +++ Makefile.in
 @@ -26,6 +26,7 @@ datadir = @datadir@
  sysconfdir = @sysconfdir@
@@ -33,3 +33,12 @@ $NetBSD: patch-ab,v 1.5 2004/08/05 03:24:39 jlam Exp $
  
  
  INCLUDES = -I. -I$(top_srcdir) $(IMAP_INCLUDES) -Iintl
+@@ -874,7 +875,7 @@ install-exec-local:
+ 		ln -sf $(DESTDIR)$(bindir)/mutt_dotlock $(DESTDIR)$(bindir)/mutt.dotlock ; \
+ 	fi
+ 	if test -f $(DESTDIR)$(bindir)/mutt_dotlock && test x@DOTLOCK_GROUP@ != x ; then \
+-		chgrp @DOTLOCK_GROUP@ $(DESTDIR)$(bindir)/mutt_dotlock && \
++		$(CHGRP) @DOTLOCK_GROUP@ $(DESTDIR)$(bindir)/mutt_dotlock && \
+ 		chmod @DOTLOCK_PERMISSION@ $(DESTDIR)$(bindir)/mutt_dotlock || \
+ 		{ echo "Can't fix mutt_dotlock's permissions!" >&2 ; exit 1 ; } \
+ 	fi
