Update KDE to 3.1.
Many bugfixes and functionality enhancements including:

General

 New default widget style: Keramik
 New default icon theme: Crystal

 Created and enhanced framework to effectively disable certain features of
 the GUI, like for example shell access, disallowing to select custom wall
 papers. "Kiosk mode"
 Usability improvements:
   Kicker: Context menu, applet menus, wording and panel feature consistency
   improved
   Kicker: Redesigned control module.
   KCalc: Usability Improvements.
   KSnapshot: Usability Improvements.
   KsCD: User Interface Improvements in configuration and information dialogs


kdelibs

 Extended the DCOP commandline client to
   enable nonGUI applications (such as shell scripts) to use DCOP
   send DCOP messages to multiple users and/or sessions concurrently
 Added to notification dialog to allow applications to configure their
 notifications with a common GUI.
 Added "Open File", "Open Destination" and "Keep window open" to download
 progress dialog.
 KDatePicker has now week number display and selection.
 Added KLocale support for setting/retrieving the first day of a week
 Support for "Multimedia keys" on your keyboard.
 Added on-demand icon loading support to improve startup performance of
 applications.
 KHTML:
   Improvements to printing support.
   Page Info and Frame info dialog.
   Auto-Scroll support of webpages using Shift combined with arrow keys.
   Many, many Bugfixes and improvements.
   Small codebase merges with Safari. The main merge is planned for a future
   release however, as it requires more testing.
 KIO:
   Modified thumbnail ioslave that can extract a thumbnail from the file
   directly if it contains one, rather than generating one itself.
   Added fish:// protocol slave, which can access remote filesystems via
   SSH and SCP
   Cleanups and Corrections in smtp:// protocol slave.
   Activated rtsp:// protocol slave.
   Added support for Public Key Authentication and interopability with newer
   versions of OpenSSH to sftp:// protocol slave.
 KSSL:
   SSL certificate policies can now be configured based on the host name

diff --git a/x11/kdebase3/patches/patch-aa b/x11/kdebase3/patches/patch-aa
--- a/x11/kdebase3/patches/patch-aa
+++ b/x11/kdebase3/patches/patch-aa
@@ -1,31 +1,28 @@
-$NetBSD: patch-aa,v 1.4 2003/02/25 02:11:35 dmcmahill Exp $
+$NetBSD: patch-aa,v 1.5 2003/03/11 13:10:18 markd Exp $
 
---- configure.orig	Tue Dec 17 05:46:51 2002
+--- configure.orig	Fri Jan 17 09:03:15 2003
 +++ configure
-@@ -24829,7 +24829,7 @@ main ()
+@@ -30923,64 +30923,6 @@ _ACEOF
  
-  char buf[20];
-   buf[0]='\0';
--  strlat(buf, "KDE function test", sizeof(buf));
-+  strlcat(buf, "KDE function test", sizeof(buf));
  
-   ;
-   return 0;
-@@ -25442,57 +25442,6 @@ cat >>confdefs.h <<EOF
- #define SIZEOF_UNSIGNED_INT $ac_cv_sizeof_unsigned_int
- EOF
  
--  echo "$as_me:25445: checking sizeof(size_t) == sizeof(unsigned int)" >&5
--echo $ECHO_N "checking sizeof(size_t) == sizeof(unsigned int)... $ECHO_C" >&6
+-  echo "$as_me:$LINENO: checking sizeof(size_t) == sizeof(unsigned long)" >&5
+-echo $ECHO_N "checking sizeof(size_t) == sizeof(unsigned long)... $ECHO_C" >&6
 -  cat >conftest.$ac_ext <<_ACEOF
--#line 25448 "configure"
+-#line $LINENO "configure"
 -#include "confdefs.h"
 -
+-#ifdef F77_DUMMY_MAIN
+-#  ifdef __cplusplus
+-     extern "C"
+-#  endif
+-   int F77_DUMMY_MAIN() { return 1; }
+-#endif
 -int
 -main ()
 -{
 -
--    #if SIZEOF_SIZE_T != SIZEOF_UNSIGNED_INT
+-    #if SIZEOF_SIZE_T != SIZEOF_UNSIGNED_LONG
 -       choke me
 -    #endif
 -
@@ -34,31 +31,31 @@ $NetBSD: patch-aa,v 1.4 2003/02/25 02:11:35 dmcmahill Exp $
 -}
 -_ACEOF
 -rm -f conftest.$ac_objext
--if { (eval echo "$as_me:25464: \"$ac_compile\"") >&5
+-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 -  (eval $ac_compile) 2>&5
 -  ac_status=$?
--  echo "$as_me:25467: \$? = $ac_status" >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); } &&
 -         { ac_try='test -s conftest.$ac_objext'
--  { (eval echo "$as_me:25470: \"$ac_try\"") >&5
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
 -  (eval $ac_try) 2>&5
 -  ac_status=$?
--  echo "$as_me:25473: \$? = $ac_status" >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); }; }; then
--  echo "$as_me:25475: result: yes" >&5
+-  echo "$as_me:$LINENO: result: yes" >&5
 -echo "${ECHO_T}yes" >&6
 -else
 -  echo "$as_me: failed program was:" >&5
 -cat conftest.$ac_ext >&5
 -
--      echo "$as_me:25481: result: no" >&5
+-      echo "$as_me:$LINENO: result: no" >&5
 -echo "${ECHO_T}no" >&6
--      { { echo "$as_me:25483: error:
--      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-      { { echo "$as_me:$LINENO: error:
+-       Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned long)
 -       does not apply. Please mail kde-devel@kde.org with a description of your system!
 -      " >&5
 -echo "$as_me: error:
--      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-       Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned long)
 -       does not apply. Please mail kde-devel@kde.org with a description of your system!
 -      " >&2;}
 -   { (exit 1); exit 1; }; }
@@ -66,10 +63,11 @@ $NetBSD: patch-aa,v 1.4 2003/02/25 02:11:35 dmcmahill Exp $
 -fi
 -rm -f conftest.$ac_objext conftest.$ac_ext
 -
- echo "$as_me:25496: checking if it's safe to enable UTMP" >&5
+-
+ echo "$as_me:$LINENO: checking if it's safe to enable UTMP" >&5
  echo $ECHO_N "checking if it's safe to enable UTMP... $ECHO_C" >&6
  
-@@ -26368,7 +26317,24 @@ if { (eval echo "$as_me:26358: \"$ac_lin
+@@ -32958,7 +32900,24 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
    (exit $ac_status); }; }; then
  
                    ac_cv_have_dpms="-lXdpms"
@@ -95,11 +93,3 @@ $NetBSD: patch-aa,v 1.4 2003/02/25 02:11:35 dmcmahill Exp $
  else
    echo "$as_me: failed program was:" >&5
  cat conftest.$ac_ext >&5
-@@ -29555,6 +29521,7 @@ echo $ECHO_N "checking if ksysguardd can
- case "$host" in
-   *-*-linux*) ksysguardd_compile=yes; UNAME='Linux' ;;
-   *-*-freebsd*) ksysguardd_compile=yes; UNAME='FreeBSD' ;;
-+  *-*-netbsd*) ksysguardd_compile=yes; UNAME='FreeBSD' ;;
-   *-*-solaris*) ksysguardd_compile=yes; UNAME='Solaris' ;;
-   *-*-osf*) ksysguardd_compile=yes; UNAME='Tru64' ;;
-   *) ksysguardd_compile=no; UNAME='' ;;
