Fix PR 20090.
Remove the bogus sizeof(size_t) == sizeof(unsigned int) check.

diff --git a/x11/kdebase3/patches/patch-aa b/x11/kdebase3/patches/patch-aa
--- a/x11/kdebase3/patches/patch-aa
+++ b/x11/kdebase3/patches/patch-aa
@@ -1,8 +1,66 @@
-$NetBSD: patch-aa,v 1.2 2002/08/25 19:23:36 jlam Exp $
+$NetBSD: patch-aa,v 1.3 2003/01/31 11:43:33 skrll Exp $
 
---- configure.orig	Mon May 13 23:58:21 2002
+--- configure.orig	Tue Dec 17 10:46:51 2002
 +++ configure
-@@ -25606,7 +25606,24 @@
+@@ -25442,57 +25442,6 @@ cat >>confdefs.h <<EOF
+ #define SIZEOF_UNSIGNED_INT $ac_cv_sizeof_unsigned_int
+ EOF
+ 
+-  echo "$as_me:25445: checking sizeof(size_t) == sizeof(unsigned int)" >&5
+-echo $ECHO_N "checking sizeof(size_t) == sizeof(unsigned int)... $ECHO_C" >&6
+-  cat >conftest.$ac_ext <<_ACEOF
+-#line 25448 "configure"
+-#include "confdefs.h"
+-
+-int
+-main ()
+-{
+-
+-    #if SIZEOF_SIZE_T != SIZEOF_UNSIGNED_INT
+-       choke me
+-    #endif
+-
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext
+-if { (eval echo "$as_me:25464: \"$ac_compile\"") >&5
+-  (eval $ac_compile) 2>&5
+-  ac_status=$?
+-  echo "$as_me:25467: \$? = $ac_status" >&5
+-  (exit $ac_status); } &&
+-         { ac_try='test -s conftest.$ac_objext'
+-  { (eval echo "$as_me:25470: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:25473: \$? = $ac_status" >&5
+-  (exit $ac_status); }; }; then
+-  echo "$as_me:25475: result: yes" >&5
+-echo "${ECHO_T}yes" >&6
+-else
+-  echo "$as_me: failed program was:" >&5
+-cat conftest.$ac_ext >&5
+-
+-      echo "$as_me:25481: result: no" >&5
+-echo "${ECHO_T}no" >&6
+-      { { echo "$as_me:25483: error:
+-      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-       does not apply. Please mail kde-devel@kde.org with a description of your system!
+-      " >&5
+-echo "$as_me: error:
+-      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-       does not apply. Please mail kde-devel@kde.org with a description of your system!
+-      " >&2;}
+-   { (exit 1); exit 1; }; }
+-
+-fi
+-rm -f conftest.$ac_objext conftest.$ac_ext
+-
+ echo "$as_me:25496: checking if it's safe to enable UTMP" >&5
+ echo $ECHO_N "checking if it's safe to enable UTMP... $ECHO_C" >&6
+ 
+@@ -26368,7 +26317,24 @@ if { (eval echo "$as_me:26358: \"$ac_lin
    (exit $ac_status); }; }; then
  
                    ac_cv_have_dpms="-lXdpms"
@@ -28,7 +86,7 @@ $NetBSD: patch-aa,v 1.2 2002/08/25 19:23:36 jlam Exp $
  else
    echo "$as_me: failed program was:" >&5
  cat conftest.$ac_ext >&5
-@@ -28793,6 +28810,7 @@
+@@ -29555,6 +29521,7 @@ echo $ECHO_N "checking if ksysguardd can
  case "$host" in
    *-*-linux*) ksysguardd_compile=yes; UNAME='Linux' ;;
    *-*-freebsd*) ksysguardd_compile=yes; UNAME='FreeBSD' ;;
