Update cfengine2 and cfengine2-doc to version 2.0.6.
Package changes
	Vicf moved from $PREFIX/sbin to $PREFIX/share/examples/cfengine
	as it can really be used as is: site tuning is required.

	Both packages now share the same distinfo file.

Changes in version 2.0.6

	SKIPVERIFY removed from AccessControl checks. This was
	wrongly allowing access to files if they only had an accepted
	encryption key.

	SetLine added to AppendIfNoLineMatching to allow current
	line to be added.

	 ForEachLineIn "/tmp/in"
	    AppendIfNoLineMatching "ThisLine"
	 EndLoop

	Changed /etc/services reference to port 5308 in ipv6
	compatible calls.

	Efficiency, removed getpwnam from GetFile(). Was unnecessarily
	looking up the uid multiple times, which delays copying
	speed. Copy rates improved by five to ten times!!

	Single copy uses too much cache memory. Optimize by only
	caching copies that use the singlecopy keyword.

	Message status change: %s is a link which points to %s,
	but that file doesn't seem to exist Verbose only

	Patches to editfiles to check empty files. DefineinGroup
	added.

Changes in version 2.0.5

	Cfrun ipv6 patch

	Syslog messages name patch

	mountables, binservers variable usage fix

	backup=timestamp added in copy so that multiple backups
	can coexist.  Other backups use this by default.

	Cfenvd records loadaverage - and av.db renamed to cf_averages.db
	since records in av.db no longer compatible.

	Iteration added to disk paths

	Typo in filters.c UID -> USER meant that Owner field in
	filters would not always work for processes.  Bug in removal
	of spaces in process-filter matches could cause some criteria
	to fail to match.

	Netstat changed entry in solaris 2.9
	Hard class hpux10 -> hpux and the old hpux is deprecated

	tidy //tmp would start tidying / due to error in
	ExpandWildcardsAndDo. FIxed

	Cfenvd netstat state recorded in separate files now in
	WORKDIR, by protocol and incoming/outgoing. This allows
	accurate record of the state to which classes refer.

	excludes and ignores would not appended in a tidy command
	if a path already existed in another previous command.
	Fixed so that all excludes and ignores are concatenated
	for all related paths.

	Local AF_LOCAL addresses not handled by sockaddr in IPv6
	compatible functions.  Now returns 127.0.0.1 (why not ::1??)

	Typo in tidy.c prevented tidy old links from working.
	Documentation patches.

	Checksums no longer performed on dry run (-n) in files,
	but still in copy.

	No errors written to syslog in dryrun mode.
	Umask patch in editfiles - umask was not properly installed

	New copy options / variables singlecopy= and autodefine
	added.

	Alerts added as own section alerts: allow users to define
	a custom message triggered by a class activation. Alerts
	can also quote state information from cfenvd and the process
	table.

	tidy define= does not set class if file could not be tidied.

	debian detect patch (Andy Stribblehill)
	cfservd descriptor leak (Andy Stribblehill)
	cfservd daemonize modification

diff --git a/sysutils/cfengine2/patches/patch-af b/sysutils/cfengine2/patches/patch-af
--- a/sysutils/cfengine2/patches/patch-af
+++ b/sysutils/cfengine2/patches/patch-af
@@ -1,13 +1,26 @@
-$NetBSD: patch-af,v 1.1.1.1 2002/12/22 13:04:38 seb Exp $
+$NetBSD: patch-af,v 1.2 2003/04/26 08:33:01 seb Exp $
 
---- configure.orig	Tue Dec 17 14:08:36 2002
-+++ configure	Tue Dec 17 15:30:26 2002
-@@ -3488,6 +3488,6 @@
-         done
+--- configure.orig	2003-04-09 12:32:54.000000000 +0000
++++ configure
+@@ -4781,7 +4781,20 @@ echo "$as_me: error: Cannot find Berkele
+         echo "$as_me:4781: result: $BERKELEY_DB_DIR" >&5
+ echo "${ECHO_T}$BERKELEY_DB_DIR" >&6
+     else
+-        { { echo "$as_me:4784: error: Cannot find BerkeleyDB" >&5
++	d="$BERKELEY_DB_DIR"
++	for v in db-4 db4 db3 db; do
++	    if test -f "$d/include/$v/db.h" ; then
++		test "x$d" != "x/usr" && BERKELEY_DB_LDFLAGS="-L$d/lib"
++		BERKELEY_DB_CFLAGS="-I$d/include/$v"
++		BERKELEY_DB_LIB="-l$v"
++		echo "$as_me:4790: result: $d" >&5
++echo "${ECHO_T}$d" >&6
++		break
++	    fi
++	done
++    fi
++    if test x"$BERKELEY_DB_LIB" = "x"; then
++        { { echo "$as_me:4797: error: Cannot find BerkeleyDB" >&5
+ echo "$as_me: error: Cannot find BerkeleyDB" >&2;}
+    { (exit 1); exit 1; }; }
      fi
--    if test "x$BERKELEY_DB_DIR" = "xyes" ; then
--        for d in /opt /usr/local /usr; do
-+    if test "x$BERKELEY_DB_DIR" != "x" ; then
-+        for d in $BERKELEY_DB_DIR /opt /usr/local /usr; do
-             for v in db4 db3 db; do
-                 if test -f "$d/include/$v/db.h" ; then
