Updated cyrus-sasl to 2.1.13
* several bug fixes

Approved by chris.

diff --git a/security/cyrus-sasl2/patches/patch-ai b/security/cyrus-sasl2/patches/patch-ai
--- a/security/cyrus-sasl2/patches/patch-ai
+++ b/security/cyrus-sasl2/patches/patch-ai
@@ -1,8 +1,8 @@
-$NetBSD: patch-ai,v 1.2 2003/02/27 13:18:07 seb Exp $
+$NetBSD: patch-ai,v 1.3 2003/05/26 06:53:09 martti Exp $
 
---- configure.orig	Mon Feb  3 18:50:30 2003
-+++ configure
-@@ -673,6 +673,7 @@ host_os=`echo $host | sed 's/^\([^-]*\)-
+--- configure.orig	2003-04-14 21:07:48.000000000 +0300
++++ configure	2003-05-21 10:00:35.000000000 +0300
+@@ -673,6 +673,7 @@
  echo "$ac_t""$host" 1>&6
  
  
@@ -10,7 +10,7 @@ $NetBSD: patch-ai,v 1.2 2003/02/27 13:18:07 seb Exp $
  # Find a good install program.  We prefer a C program (faster),
  # so one script is as good as another.  But avoid the broken or
  # incompatible versions:
-@@ -840,16 +841,16 @@ EOF
+@@ -840,16 +841,16 @@
  
  
  missing_dir=`cd $ac_aux_dir && pwd`
@@ -32,7 +32,7 @@ $NetBSD: patch-ai,v 1.2 2003/02/27 13:18:07 seb Exp $
     echo "$ac_t""missing" 1>&6
  fi
  
-@@ -866,16 +867,16 @@ else
+@@ -866,16 +867,16 @@
     echo "$ac_t""missing" 1>&6
  fi
  
@@ -54,7 +54,7 @@ $NetBSD: patch-ai,v 1.2 2003/02/27 13:18:07 seb Exp $
     echo "$ac_t""missing" 1>&6
  fi
  
-@@ -1949,6 +1950,13 @@ fi
+@@ -1949,6 +1950,13 @@
  
  target=$save_target
  
@@ -68,42 +68,35 @@ $NetBSD: patch-ai,v 1.2 2003/02/27 13:18:07 seb Exp $
  if test "$ac_cv_can_build_shared" = no; then
  	enable_shared=no
  	enable_static=yes
-@@ -6822,8 +6830,37 @@ LTLIBOBJS=`echo "$LIBOBJS" | sed 's/\.o/
+@@ -6828,6 +6836,31 @@
  
  
  
-+
-+ac_safe=`echo "/dev/urandom" | sed 'y%./+-%__p_%'`
-+echo $ac_n "checking for /dev/urandom""... $ac_c" 1>&6
-+echo "configure:6837: checking for /dev/urandom" >&5
-+if eval "test \"`echo '$''{'ac_cv_file_$ac_safe'+set}'`\" = set"; then
-+  echo $ac_n "(cached) $ac_c" 1>&6
++echo "$as_me:$LINENO: checking for /dev/urandom" >&5
++echo $ECHO_N "checking for /dev/urandom... $ECHO_C" >&6
++if test "${ac_cv_file__dev_urandom+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
 +else
-+  if test "$cross_compiling" = yes; then
-+    { echo "configure: error: Cannot check for file existence when cross compiling" 1>&2; exit 1; }
++  test "$cross_compiling" = yes &&
++  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
++echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
++   { (exit 1); exit 1; }; }
++if test -r "/dev/urandom"; then
++  ac_cv_file__dev_urandom=yes
 +else
-+  if test -r /dev/urandom; then
-+    eval "ac_cv_file_$ac_safe=yes"
-+  else
-+    eval "ac_cv_file_$ac_safe=no"
-+  fi
++  ac_cv_file__dev_urandom=no
 +fi
 +fi
-+if eval "test \"`echo '$ac_cv_file_'$ac_safe`\" = yes"; then
-+  echo "$ac_t""yes" 1>&6
-+  cat >> confdefs.h <<EOF
++echo "$as_me:$LINENO: result: $ac_cv_file__dev_urandom" >&5
++echo "${ECHO_T}$ac_cv_file__dev_urandom" >&6
++if test $ac_cv_file__dev_urandom = yes; then
++  cat >>confdefs.h <<_ACEOF
 +#define SASL_DEV_RANDOM "/dev/urandom"
-+EOF
-+
-+else
-+  echo "$ac_t""no" 1>&6
++_ACEOF
 +
 +fi
 +
 +
  echo $ac_n "checking for working const""... $ac_c" 1>&6
--echo "configure:6827: checking for working const" >&5
-+echo "configure:6864: checking for working const" >&5
+ echo "configure:6833: checking for working const" >&5
  if eval "test \"`echo '$''{'ac_cv_c_const'+set}'`\" = set"; then
-   echo $ac_n "(cached) $ac_c" 1>&6
- else
