Update security/cyrus-sasl2 and associated plugins to 2.1.20.  Changes from version 2.1.19 include:
* Fixes to cram plugin to avoid attempting to canonify uninitialized data
  (This removes the need for patch-af).
* NTLM portability fixes.
* Avoid potential attack using SASL_PATH when sasl is used in a setuid
  environment.
* A trivial number of small bugfixes.

diff --git a/security/cyrus-sasl2/patches/patch-ai b/security/cyrus-sasl2/patches/patch-ai
--- a/security/cyrus-sasl2/patches/patch-ai
+++ b/security/cyrus-sasl2/patches/patch-ai
@@ -1,8 +1,26 @@
-$NetBSD: patch-ai,v 1.9 2004/08/04 19:41:07 jlam Exp $
+$NetBSD: patch-ai,v 1.10 2004/11/15 21:58:17 jlam Exp $
 
---- configure.orig	Fri Jul  2 15:39:54 2004
+--- configure.orig	2004-10-24 16:21:08.000000000 -0400
 +++ configure
-@@ -10765,7 +10765,14 @@ if test $ac_cv_lib_resolv_res_search = y
+@@ -5160,7 +5160,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  BDB_LIBADD="$BDB_LIBADD -l$dbname"; dblib="berkeley"; dbname=db
++  BDB_LIBADD="$BDB_LIBADD -l$dbname"; dblib="berkeley"; dbname=db; break
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+@@ -5916,7 +5916,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  BDB_LIBADD="$BDB_LIBADD -l$dbname"; dblib="berkeley"; dbname=db
++  BDB_LIBADD="$BDB_LIBADD -l$dbname"; dblib="berkeley"; dbname=db; break
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+@@ -10680,7 +10680,14 @@ if test $ac_cv_lib_resolv_res_search = y
  fi
  
    SASL_MECHS="$SASL_MECHS libgssapiv2.la"
@@ -18,18 +36,15 @@ $NetBSD: patch-ai,v 1.9 2004/08/04 19:41:07 jlam Exp $
  
    cmu_save_LIBS="$LIBS"
    LIBS="$LIBS $GSSAPIBASE_LIBS"
-@@ -10899,14 +10906,6 @@ _ACEOF
- echo "${ECHO_T}disabled" >&6
-  fi
+@@ -10778,11 +10785,6 @@ fi
  
--
--if test "$gssapi" != "no"; then
+ 
+ if test "$gssapi" != "no"; then
 -
 -cat >>confdefs.h <<\_ACEOF
 -#define STATIC_GSSAPIV2
 -_ACEOF
 -
--fi
- 
- # Check whether --enable-anon or --disable-anon was given.
- if test "${enable_anon+set}" = set; then
+   mutex_default="no"
+   if test "$gss_impl" = "mit"; then
+      mutex_default="yes"
