Maintaining this package seems like a full-time job!
Correct the sse2 detection logic in configure/configure.ac.
Bump PKGREVISION.

diff --git a/x11/pixman/patches/patch-ae b/x11/pixman/patches/patch-ae
--- a/x11/pixman/patches/patch-ae
+++ b/x11/pixman/patches/patch-ae
@@ -1,6 +1,6 @@
-$NetBSD: patch-ae,v 1.5 2008/07/13 23:16:02 bjs Exp $
+$NetBSD: patch-ae,v 1.6 2008/07/18 19:03:32 bjs Exp $
 
---- configure.orig	2008-06-25 07:55:10.000000000 -0400
+--- configure.orig	2008-07-17 13:39:07.000000000 -0400
 +++ configure
 @@ -19773,6 +19773,7 @@ fi
  
@@ -19,3 +19,12 @@ $NetBSD: patch-ae,v 1.5 2008/07/13 23:16:02 bjs Exp $
  if test "x$have_gcc4" = "xyes"; then
     CFLAGS="$CFLAGS -fvisibility=hidden"
  fi
+@@ -20057,7 +20058,7 @@ fi
+ 
+ { echo "$as_me:$LINENO: result: $have_sse2_intrinsics" >&5
+ echo "${ECHO_T}$have_sse2_intrinsics" >&6; }
+-if test $enable_sse2 = yes && test $have_sse_intrinsics = no ; then
++if test $enable_sse2 = yes && test $have_sse2_intrinsics = no ; then
+    { { echo "$as_me:$LINENO: error: SSE2 intrinsics not detected" >&5
+ echo "$as_me: error: SSE2 intrinsics not detected" >&2;}
+    { (exit 1); exit 1; }; }
