Make depends-cookie a flavor indendepent target. Before it was used to trace the dependency information. This is computed and stored in .depends directly now before anything else is done. The output is locked and the locking is supposed to work before the bootstrap-depends are installed.
Add a new hook for flavors after all dependencies are added and before
the depends-cookie is created. Use this to compute which package is used
to fulfill each dependency and store it in .rdepends. Adjust
register-dependencies and some other places to use this information
directly instead of recomputing it all the time.

The code to list all dependencies and to recursively install missing
ones is moved to a separate shell script. This makes it easier to
understand what is going on and extend them later.

Change the calling of pkg_create to prepend the dependencies directly to
the passed-in PLIST and not via -P and -T. This is in preperation of
changing the way they are stored in the packages.

Discussed with, recieved minor disagreement about install-dependencies,
but otherwise OKed by jlam.

diff --git a/mk/flavor/pkg/register-dependencies b/mk/flavor/pkg/register-dependencies
--- a/mk/flavor/pkg/register-dependencies
+++ b/mk/flavor/pkg/register-dependencies
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: register-dependencies,v 1.2 2006/06/04 05:43:56 jlam Exp $
+# $NetBSD: register-dependencies,v 1.3 2007/05/22 16:17:16 joerg Exp $
 #
 ######################################################################
 #
@@ -12,13 +12,10 @@
 #
 # DESCRIPTION
 #	register-dependencies registers a dependency relationship from
-#	the named package pkgname and the dependencies passed in via
-#	standard input.  The dependencies may be wildcard patterns.
+#	the named package pkgname and the packages passed in via 
+#	standard input.
 #
 # ENVIRONMENT
-#	PKG_ADMIN
-#		This is the path to the pkg_admin command.
-#
 #	PKG_DBDIR
 #		This is the package meta-data directory in which the
 #		packages are registered.  By default, this is /var/db/pkg.
@@ -28,7 +25,6 @@
 : ${AWK:=awk}
 : ${CP:=cp}
 : ${ECHO:=echo}
-: ${PKG_ADMIN:=pkg_admin}
 : ${PKG_DBDIR:=/var/db/pkg}
 : ${RM:=rm}
 : ${TEST:=test}
@@ -37,11 +33,10 @@
 
 PKGNAME="$1"
 
-while read dependency; do
-	pkg=`${PKG_ADMIN} -b -d ${PKG_DBDIR} -S lsbest "$dependency" || ${TRUE}`
+while read pkg; do
 	pkgdir="${PKG_DBDIR}/$pkg"
-	if ${TEST} -z "$pkg" -o ! -d "$pkgdir"; then
-		${ECHO} 1>&2 "$dependency not found - dependency NOT registered"
+	if ${TEST} ! -d "$pkgdir"; then
+		${ECHO} 1>&2 "$pkg not found - dependency NOT registered"
 		continue
 	fi
 	req="$pkgdir/+REQUIRED_BY"
