* Get -lgsm from ${PREFIX}/lib * Get Tcl and Tk build variables from tcl/tkConfig.sh instead of pawing   through directory trees.

diff --git a/mbone/vat/patches/patch-aa b/mbone/vat/patches/patch-aa
--- a/mbone/vat/patches/patch-aa
+++ b/mbone/vat/patches/patch-aa
@@ -1,27 +1,46 @@
-$NetBSD: patch-aa,v 1.5 1999/12/08 10:20:37 rh Exp $
+$NetBSD: patch-aa,v 1.6 2000/01/26 22:14:26 jlam Exp $
 
---- configure.in.orig	Thu May 16 14:21:17 1996
-+++ configure.in	Wed Dec  8 11:06:17 1999
-@@ -35,10 +35,10 @@
+--- configure.in.orig	Thu May 16 08:21:17 1996
++++ configure.in	Wed Jan 26 15:34:04 2000
+@@ -33,22 +33,15 @@
+ 		exit 1
+ 	fi
  else
- 	echo "checking for libgsm.a"
+-	echo "checking for libgsm.a"
++	echo "checking for -lgsm"
  	V_LIB_GSM=FAIL
 -	places="$PWD/../gsm-1.0-pl7 \
-+	places="$PWD/../gsm-1.0-pl10 \
- 		$PWD/../gsm-1.0 \
- 		$PWD/../gsm \
+-		$PWD/../gsm-1.0 \
+-		$PWD/../gsm \
 -		/usr/src/local/gsm-1.0-pl7 \
-+		/usr/src/local/gsm-1.0-pl10 \
- 		/usr/src/local/gsm-1.0 \
- 		/usr/src/local/gsm"
- 	for dir in $places; do
-@@ -165,7 +165,8 @@
+-		/usr/src/local/gsm-1.0 \
+-		/usr/src/local/gsm"
+-	for dir in $places; do
+-		if test -r $dir/lib/libgsm.a -a -r $dir/inc/private.h ; then
+-			V_LIB_GSM=$dir/lib/libgsm.a
+-			V_INCLUDE_GSM=-I$dir/inc
+-			break
+-		fi
+-	done
+-	if test "$V_LIB_GSM" = FAIL; then
++	V_INCLUDE_GSM=FAIL
++	AC_CHECK_LIB(gsm, gsm_create, V_LIB_GSM="-lgsm")
++	AC_CHECK_HEADERS(private.h)
++	if test "$ac_cv_header_private_h" = "yes"; then
++		V_INCLUDE_GSM=
++	fi
++	if test "$V_LIB_GSM" = FAIL || test "$V_INCLUDES_GSM" = FAIL ; then
+ 		echo "configure: can't find gsm library ... you can get it at"
+ 		echo "   http://www.cs.tu-berlin.de/~jutta/toast.html"
+ 		exit 1
+@@ -165,7 +158,9 @@
  	;;
  *-*-netbsd*)
  	V_TARCMD="tar -h -c -f"
 -	V_LIB="$V_LIB -L/usr/local/lib"
-+	V_LIB="$V_LIB -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lossaudio"
++	V_LIB="${LDFLAGS} $V_LIB -lossaudio"
 +	V_OBJ_AUDIO="audio-voxware.o"
++	V_CCOPT="${CPPFLAGS}"
  	;;
  *-*-hpux*)
  	V_DEFINE="$V_DEFINE"
diff --git a/mbone/vat/patches/patch-ah b/mbone/vat/patches/patch-ah
--- a/mbone/vat/patches/patch-ah
+++ b/mbone/vat/patches/patch-ah
@@ -1,98 +1,113 @@
 $NetBSD$
 
---- configure.in.tk.orig	Wed Dec  8 11:19:14 1999
-+++ configure.in.tk	Wed Dec  8 11:18:55 1999
-@@ -2,18 +2,19 @@
+--- configure.in.tk.orig	Thu May 16 04:06:05 1996
++++ configure.in.tk	Wed Jan 26 16:03:04 2000
+@@ -2,6 +2,8 @@
  dnl $Header: configure.in.tk,v 1.2 96/05/16 01:03:40 van Exp $ (LBL)
  
  AC_ARG_WITH(tcl,	--with-tcl=path	specify a pathname for tcl, d=$withval, d="")
-+tclposs="tcl8.0 tcl80 tcl"
++tcldir=tcl8.0
++tcllib=tcl80
  if test "$d" != "" ; then 
  	if test ! -d $d ; then 
  		echo "'$d' is not a directory"
- 		exit 1
- 	fi
--	V_INCLUDE_TCL=-I$d/include
--	if test ! -r $d/include/tcl.h ; then
--		echo "can't find tcl.h in $d/include"
-+	V_INCLUDE_TCL=-I$d
-+	if test ! -r $d/tcl.h ; then
-+		echo "can't find tcl.h in $d"
+@@ -12,8 +14,8 @@
+ 		echo "can't find tcl.h in $d/include"
  		exit 1
  	fi
 -	places="$d/lib/libtcl7.5.so \
 -		$d/lib/libtcl7.5.a \
-+	places="$d/lib/libtcl8.0.so \
-+		$d/lib/libtcl8.0.a \
++	places="$d/lib/lib${tcllib}.so \
++		$d/lib/lib${tcllib}.a \
  		$d/lib/libtcl.so \
  		$d/lib/libtcl.a"
  	V_LIB_TCL=FAIL
-@@ -27,7 +28,7 @@
+@@ -27,7 +29,7 @@
  		echo "can't find libtcl.a in $d/lib"
  		exit 1
  	fi
 -	places="$d/lib/tcl7.5 \
-+	places="$d/lib/tcl8.0 \
++	places="$d/lib/${tcldir} \
  		$d/lib/tcl"
  	V_LIBRARY_TCL=FAIL
  	for dir in $places; do
-@@ -44,13 +45,16 @@
+@@ -44,10 +46,11 @@
  	AC_TEST_CPP([#include <tcl.h>], V_INCLUDE_TCL="", V_INCLUDE_TCL=FAIL)
  	if test "$V_INCLUDE_TCL" = FAIL; then
  		echo "checking for tcl.h"
 -		places="$PWD/../tcl7.5 \
 -			/usr/src/local/tcl7.5 \
 -			/import/tcl/include/tcl7.5 \
-+		places="$PWD/../tcl8.0 \
-+			/usr/src/local/tcl8.0 \
-+			/import/tcl/include/tcl8.0 \
++		places="$PWD/../${tcldir} \
++			/usr/src/local/${tcldir} \
++			/import/tcl/include/${tcldir} \
  			$prefix/include \
++			$prefix/include/${tcldir} \
  			$x_includes/tk \
  			$x_includes \
-+			/usr/pkg/include \
-+			/usr/pkg/include/tcl8.0 \
  			/usr/local/include \
-+			/usr/local/include/tcl8.0 \
- 			/usr/contrib/include \
- 			/usr/include"
- 		for dir in $places; do
-@@ -64,26 +68,27 @@
+@@ -64,47 +67,43 @@
  			exit 1
  		fi
  	fi
 -	AC_CHECK_LIB(tcl7.5, main, V_LIB_TCL="-ltcl7.5", V_LIB_TCL="FAIL")
-+	AC_CHECK_LIB(tcl80, main, V_LIB_TCL="-ltcl80", V_LIB_TCL="FAIL")
- 	if test "$V_LIB_TCL" = FAIL; then
- 		echo "checking for libtcl.a"
- 		places="\
- 			$prefix/lib \
- 			$x_libraries \
-+			/usr/pkg/lib \
- 			/usr/contrib/lib \
- 			/usr/local/lib \
- 			/usr/lib \
+-	if test "$V_LIB_TCL" = FAIL; then
+-		echo "checking for libtcl.a"
+-		places="\
+-			$prefix/lib \
+-			$x_libraries \
+-			/usr/contrib/lib \
+-			/usr/local/lib \
+-			/usr/lib \
 -			$PWD/../tcl7.5 \
 -			/usr/src/local/tcl7.5 \
 -			/import/tcl/lib/tcl7.5 \
-+			$PWD/../tcl8.0 \
-+			/usr/src/local/tcl8.0 \
-+			/import/tcl/lib/tcl8.0 \
- 			"
- 		for dir in $places; do
+-			"
+-		for dir in $places; do
 -			if test -r $dir/libtcl7.5.so -o -r $dir/libtcl7.5.a; then
 -				V_LIB_TCL="-L$dir -ltcl7.5"
-+			if test -r $dir/libtcl80.so -o -r $dir/libtcl80.a; then
-+				V_LIB_TCL="-Wl,-R$dir -L$dir -ltcl80"
- 				break
- 			fi
- 			if test -r $dir/libtcl.so -o -r $dir/libtcl.a; then
+-				break
+-			fi
+-			if test -r $dir/libtcl.so -o -r $dir/libtcl.a; then
 -				V_LIB_TCL="-L$dir -ltcl"
-+				V_LIB_TCL="-Wl,-R$dir -L$dir -ltcl"
- 				break
- 			fi
- 		done
-@@ -98,13 +103,14 @@
+-				break
+-			fi
+-		done
+-		if test "$V_LIB_TCL" = FAIL; then
+-			echo "can't find libtcl.a"
+-			exit 1
+-		else
+-			if test $solaris ; then
+-				V_LIB_TCL="-R$dir $V_LIB_TCL"
+-			fi
++	V_TCL_CONFIG=FAIL
++	echo "checking for tclConfig.sh"
++	places="/usr/local/lib/${tcldir} \
++		/usr/contrib/lib/${tcldir} \
++		/usr/lib/${tcldir} \
++		/usr/lib/tk/${tcldir} \
++		/import/tcl/lib/${tcldir} \
++		$prefix/lib/${tcldir} \
++		$x_libraries/${tcldir} \
++		/usr/local/lib/tcl \
++		/usr/lib/tcl \
++		/usr/lib/tk/tcl \
++		/import/tcl/lib/tcl \
++		$prefix/lib/tcl \
++		$x_libraries/tcl \
++		$x_libraries/tcl"
++	for dir in $places; do
++		if test -r $dir/tclConfig.sh ; then
++			V_TCL_CONFIG=$dir/tclConfig.sh
++		        break
+ 		fi
++	done
++	if test "$V_TCL_CONFIG" = FAIL; then
++		echo "can't find tclConfig.sh"
++		exit 1
  	fi
++	. ${V_TCL_CONFIG}
++	V_LIB_TCL="${TCL_LIB_FLAG}"
  	echo "checking for tcl/init.tcl"
  	V_LIBRARY_TCL=FAIL
 -	places="/usr/local/lib/tcl7.5 \
@@ -102,63 +117,51 @@ $NetBSD$
 -		/import/tcl/lib/tcl7.5 \
 -		$prefix/lib/tcl7.5 \
 -		$x_libraries/tcl7.5 \
-+	places="/usr/local/lib/tcl8.0 \
-+		/usr/pkg/lib/tcl8.0 \
-+		/usr/contrib/lib/tcl8.0 \
-+		/usr/lib/tcl8.0 \
-+		/usr/lib/tk/tcl8.0 \
-+		/import/tcl/lib/tcl8.0 \
-+		$prefix/lib/tcl8.0 \
-+		$x_libraries/tcl8.0 \
++	places="/usr/local/lib/${tcldir} \
++		/usr/contrib/lib/${tcldir} \
++		/usr/lib/${tcldir} \
++		/usr/lib/tk/${tcldir} \
++		/import/tcl/lib/${tcldir} \
++		$prefix/lib/${tcldir} \
++		$x_libraries/${tcldir} \
  		/usr/local/lib/tcl \
  		/usr/lib/tcl \
  		/usr/lib/tk/tcl \
-@@ -128,18 +134,19 @@
+@@ -128,6 +127,8 @@
  AC_SUBST(V_LIBRARY_TCL)
  
  AC_ARG_WITH(tk,	--with-tk=path	specify a pathname for tk, d=$withval, d="")
-+tkposs="tk8.0 tk80 tk"
++tkdir=tk8.0
++tklib=tk80
  if test "$d" != "" ; then 
  	if test ! -d $d ; then 
  		echo "'$d' is not a directory"
- 		exit 1
- 	fi
--	V_INCLUDE_TK=-I$d/include
--	if test ! -r $d/include/tk.h ; then
--		echo "can't find tk.h in $d/include"
-+	V_INCLUDE_TK=-I$d
-+	if test ! -r $d/tk.h ; then
-+		echo "can't find tk.h in $d"
+@@ -138,8 +139,8 @@
+ 		echo "can't find tk.h in $d/include"
  		exit 1
  	fi
 -	places="$d/lib/libtk4.1.so \
 -		$d/lib/libtk4.1.a \
-+	places="$d/lib/libtk8.0.so \
-+		$d/lib/libtk8.0.a \
++	places="$d/lib/lib${tklib}.so \
++		$d/lib/lib${tklib}.a \
  		$d/lib/libtk.so \
  		$d/lib/libtk.a"
  	V_LIB_TK=FAIL
-@@ -153,7 +160,7 @@
+@@ -153,7 +154,7 @@
  		echo "can't find libtk.a in $d/lib"
  		exit 1
  	fi
 -	places="$d/lib/tk4.1 \
-+	places="$d/lib/tk8.0 \
++	places="$d/lib/${tkdir} \
  		$d/lib/tk"
  	V_LIBRARY_TK=FAIL
  	for dir in $places; do
-@@ -170,18 +177,21 @@
- 	AC_TEST_CPP([#include <tk.h>], V_INCLUDE_TK="", V_INCLUDE_TK=FAIL)
- 	if test "$V_INCLUDE_TK" = FAIL; then
- 		echo "checking for tk.h"
--		V_INCLUDE_TK=""
-+		V_INCLUDE_TK="FAIL"
+@@ -173,15 +174,16 @@
+ 		V_INCLUDE_TK=""
  		places="\
  			$prefix/include \
-+			/usr/pkg/include \
-+			/usr/pkg/include/tk8.0 \
++			$prefix/include/${tkdir} \
  			/usr/local/include \
-+			/usr/local/include/tk8.0 \
  			/usr/contrib/include \
  			/usr/include/tcl \
  			/usr/include\
@@ -167,47 +170,75 @@ $NetBSD$
 -			$PWD/../tk4.1 \
 -			/usr/src/local/tk4.1 \
 -			/import/tcl/include/tk4.1 \
-+			$PWD/../tk8.0 \
-+			/usr/src/local/tk8.0 \
-+			/import/tcl/include/tk8.0 \
++			$PWD/../${tkdir} \
++			/usr/src/local/${tkdir} \
++			/import/tcl/include/${tkdir} \
  			"
  		for dir in $places; do
  			if test -r $dir/tk.h ; then
-@@ -194,25 +204,26 @@
+@@ -194,48 +196,47 @@
  			exit 1
  		fi
  	fi
 -	AC_CHECK_LIB(tk4.1, main, V_LIB_TK="-ltk4.1", V_LIB_TK="FAIL")
-+	AC_CHECK_LIB(tk80, main, V_LIB_TK="-ltk80", V_LIB_TK="FAIL")
- 	if test "$V_LIB_TK" = FAIL; then
- 		echo "checking for libtk.a"
- 		places="/usr/local/lib \
-+			/usr/pkg/lib \
- 			/usr/contrib/lib \
- 			/usr/lib \
- 			/usr/lib/tk \
- 			/import/tcl/lib \
+-	if test "$V_LIB_TK" = FAIL; then
+-		echo "checking for libtk.a"
+-		places="/usr/local/lib \
+-			/usr/contrib/lib \
+-			/usr/lib \
+-			/usr/lib/tk \
+-			/import/tcl/lib \
 -			$PWD/../tk4.1 \
 -			/usr/src/local/tk4.1 \
-+			$PWD/../tk8.0 \
-+			/usr/src/local/tk8.0 \
- 			$prefix/lib \
- 			$x_libraries"
- 		for dir in $places; do
+-			$prefix/lib \
+-			$x_libraries"
+-		for dir in $places; do
 -			if test -r $dir/libtk4.1.so -o -r $dir/libtk4.1.a; then
 -				V_LIB_TK="-L$dir -ltk4.1"
-+			if test -r $dir/libtk80.so -o -r $dir/libtk80.a; then
-+				V_LIB_TK="-Wl,-R$dir -L$dir -ltk80"
- 				break
- 			fi
- 			if test -r $dir/libtk.so -o -r $dir/libtk.a; then
+-				break
+-			fi
+-			if test -r $dir/libtk.so -o -r $dir/libtk.a; then
 -				V_LIB_TK="-L$dir -ltk"
-+				V_LIB_TK="-Wl,-R$dir -L$dir -ltk"
- 				break
- 			fi
- 		done
-@@ -227,15 +238,16 @@
+-				break
+-			fi
+-		done
+-		if test "$V_LIB_TK" = FAIL; then
+-			echo "can't find libtk.a"
+-			exit 1
+-		else
+-			if test $solaris ; then
+-				V_LIB_TK="-R$dir $V_LIB_TK"
+-			fi
++	V_TK_CONFIG=FAIL
++	echo "checking for tkConfig.sh"
++	places="/usr/local/lib/${tkdir} \
++		/usr/contrib/lib/${tkdir} \
++		/usr/lib/${tkdir} \
++		/usr/lib/tk/${tkdir} \
++		/import/tcl/lib/${tkdir} \
++		$prefix/lib/${tkdir} \
++		$x_libraries/${tkdir} \
++		$PWD/../${tkdir}/library \
++		/usr/src/local/${tkdir}/library \
++		/usr/local/lib/tk \
++		/usr/lib/tk \
++		/usr/lib/tk/tk \
++		/import/tcl/lib/tk \
++		$prefix/lib/tk \
++		$x_libraries/tk \
++		$x_libraries/tk"
++	for dir in $places; do
++		if test -r $dir/tkConfig.sh ; then
++			V_TK_CONFIG=$dir/tkConfig.sh
++		        break
+ 		fi
++	done
++	if test "$V_TK_CONFIG" = FAIL; then
++		echo "can't find tkConfig.sh"
++		exit 1
  	fi
++	. ${V_TK_CONFIG}
++	V_LIB_TK="${TK_LIB_FLAG}"
  	echo "checking for tk/tk.tcl"
  	V_LIBRARY_TK=FAIL
 -	places="/usr/local/lib/tk4.1 \
@@ -219,16 +250,15 @@ $NetBSD$
 -		$x_libraries/tk4.1 \
 -		$PWD/../tk4.1/library \
 -		/usr/src/local/tk4.1/library \
-+	places="/usr/local/lib/tk8.0 \
-+		/usr/pkg/lib/tk8.0 \
-+		/usr/contrib/lib/tk8.0 \
-+		/usr/lib/tk8.0 \
-+		/usr/lib/tk/tk8.0 \
-+		/import/tcl/lib/tk8.0 \
-+		$prefix/lib/tk8.0 \
-+		$x_libraries/tk8.0 \
-+		$PWD/../tk8.0/library \
-+		/usr/src/local/tk8.0/library \
++	places="/usr/local/lib/${tkdir} \
++		/usr/contrib/lib/${tkdir} \
++		/usr/lib/${tkdir} \
++		/usr/lib/tk/${tkdir} \
++		/import/tcl/lib/${tkdir} \
++		$prefix/lib/${tkdir} \
++		$x_libraries/${tkdir} \
++		$PWD/../${tkdir}/library \
++		/usr/src/local/${tkdir}/library \
  		/usr/local/lib/tk \
  		/usr/lib/tk \
  		/usr/lib/tk/tk \
