Fix FLAC detection, and add dependency on flac package. Bump PKGREVISION to 1.

diff --git a/audio/easytag/patches/patch-aa b/audio/easytag/patches/patch-aa
--- a/audio/easytag/patches/patch-aa
+++ b/audio/easytag/patches/patch-aa
@@ -1,7 +1,16 @@
-$NetBSD: patch-aa,v 1.10 2003/01/09 01:19:11 wiz Exp $
+$NetBSD: patch-aa,v 1.11 2003/01/14 13:14:33 wiz Exp $
 
 --- configure.orig	Tue Dec 31 14:24:37 2002
 +++ configure
+@@ -8150,7 +8150,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  . conftest.flac; echo "${LIBFLAC_MAJOR}.${LIBFLAC_MINOR}.${LIBFLAC_PATCH}"
++  . ./conftest.flac; echo "${LIBFLAC_MAJOR}.${LIBFLAC_MINOR}.${LIBFLAC_PATCH}"
+ else
+   echo "$as_me: program exited with status $ac_status" >&5
+ echo "$as_me: failed program was:" >&5
 @@ -8312,8 +8312,7 @@ int
  main ()
  {
