Update KDE to 3.1.
Many bugfixes and functionality enhancements including:

kdeaddons

 NEW IN KDE: Noatun plugin to search for lyrics of the current song.

kdeadmin

 kcmlinuz: is now a standalone application
 kcmlinuz: Added capability to search for configuration options


kdeedu

 NEW IN KDE: Kiten, a Japanese Reference Tool.
 NEW IN KDE: FlashKard, a vocabulary tool. Is able to read KVTML files which
 were written by KVocTrain.
 NEW IN KDE: started a libkdeedu, which allows interopability and code
 sharing between KDE Educational applications.


kdepim

 libkabc
   Plugin interface for resources and formats.
   Control module for configuring multiple resources.
   Optional directory resource which stores each entry as own file.
   LDAP resource.
   Optional binary storage format for better performance with large
   addressbooks.
   Completed support for vCard entities: sound, geo, key and some more.
   vCard 2.1 import.
   LDAP aware mail address input field.
 KAddressbook
   New card and icon views.
   Multiple configurable views.
   "kab-style" details view for selected entry.
   Customizable view filters.
   Customizable categories for addressbook entries.
   Support for transparently accessing multiple addressbooks.
   Redesigned entry editor widget.
   Printing option supporting two different styles.
   Optional embedded entry and ditribution list editor.
   "Jump bar" for quick alphabetical access of entries.
   Fetch addresses from LDAP servers, including support for multiple servers.
   Importing of vCard 2.1 files.
   Improved CSV import (including template for import from Outlook 2000).
   vCard export.
 KAlarm
   Added option to execute commands in alarms.
   Implemented daily, weekly, monthly and annual recurrences.
   Optionally play audio notification when an alarm triggers.
 KPilot
   Added time conduit
   VCal conduits (TODO and Calendar) have been improved to function properly.
   Addressbook conduit has been ported to use libkabc.
 KOrganizer
   General
     User definable templates for events and TODOs.
     Alarms for TODOs.
     Added support for automatic HTML export on save of a calendar file.
     Time table print view.
     New "location" attribute for events.
     Experimental "Get Hot New Stuff" button for downloading and uploading
     calendar files of common interest.
   Views
     Added new "Next 3 days" view.
     Added selection of time span for a new event in day and week views.
     Direct manipulation of priority, completion status and categories of
     TODOs by context menus added.
     Deletion of individual instances of recurring events.
     Rewritten month view.
     Coloring of events in month view based on categories.
     Coloring of due and overdue todos.
     Improved "What's Next" view.
     Configurable cell height in week and day views
   Group scheduling
     iMIP group scheduling functions for TODOs.
     Publishing of Free/Busy information by iMIP conformant email.
     Improved automatisation of group scheduling.
   Interopability and integration
     Support for "webcal" URLs in Konqueror (known from Apple iCal).
     Support for iCalendar based drag&drop.
     KOrganizer now shares the dialogs for categories with KAddressBook.
     Improved iCalendar conformance.
     Improved right-to-left languages support.
     Bug fixes for non-latin1 encodings.
   Plugins
     New plugin for importing Birthdays of contacts in the KDE address book.
     New plugin for accessing calendar data stored on an Exchange 2000 server.


kdeutils

 Partially ACPI support in KLaptop.

diff --git a/misc/kdepim3/patches/patch-ai b/misc/kdepim3/patches/patch-ai
--- a/misc/kdepim3/patches/patch-ai
+++ b/misc/kdepim3/patches/patch-ai
@@ -1,32 +1,28 @@
-$NetBSD: patch-ai,v 1.2 2003/02/27 01:03:29 dmcmahill Exp $
+$NetBSD: patch-ai,v 1.3 2003/03/11 13:22:30 markd Exp $
 
---- configure.orig	Sat Dec 21 01:44:21 2002
+--- configure.orig	Fri Jan 17 08:54:05 2003
 +++ configure
-@@ -21496,7 +21496,7 @@ main ()
+@@ -25661,65 +25661,6 @@ _ACEOF
  
-  char buf[20];
-   buf[0]='\0';
--  strlat(buf, "KDE function test", sizeof(buf));
-+  strlcat(buf, "KDE function test", sizeof(buf));
  
-   ;
-   return 0;
-@@ -22108,57 +22108,6 @@ echo "${ECHO_T}$ac_cv_sizeof_unsigned_in
- cat >>confdefs.h <<EOF
- #define SIZEOF_UNSIGNED_INT $ac_cv_sizeof_unsigned_int
- EOF
--
--  echo "$as_me:22112: checking sizeof(size_t) == sizeof(unsigned int)" >&5
--echo $ECHO_N "checking sizeof(size_t) == sizeof(unsigned int)... $ECHO_C" >&6
+ 
+-  echo "$as_me:$LINENO: checking sizeof(size_t) == sizeof(unsigned long)" >&5
+-echo $ECHO_N "checking sizeof(size_t) == sizeof(unsigned long)... $ECHO_C" >&6
 -  cat >conftest.$ac_ext <<_ACEOF
--#line 22115 "configure"
+-#line $LINENO "configure"
 -#include "confdefs.h"
 -
+-#ifdef F77_DUMMY_MAIN
+-#  ifdef __cplusplus
+-     extern "C"
+-#  endif
+-   int F77_DUMMY_MAIN() { return 1; }
+-#endif
 -int
 -main ()
 -{
 -
--    #if SIZEOF_SIZE_T != SIZEOF_UNSIGNED_INT
+-    #if SIZEOF_SIZE_T != SIZEOF_UNSIGNED_LONG
 -       choke me
 -    #endif
 -
@@ -35,37 +31,40 @@ $NetBSD: patch-ai,v 1.2 2003/02/27 01:03:29 dmcmahill Exp $
 -}
 -_ACEOF
 -rm -f conftest.$ac_objext
--if { (eval echo "$as_me:22131: \"$ac_compile\"") >&5
+-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 -  (eval $ac_compile) 2>&5
 -  ac_status=$?
--  echo "$as_me:22134: \$? = $ac_status" >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); } &&
 -         { ac_try='test -s conftest.$ac_objext'
--  { (eval echo "$as_me:22137: \"$ac_try\"") >&5
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
 -  (eval $ac_try) 2>&5
 -  ac_status=$?
--  echo "$as_me:22140: \$? = $ac_status" >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); }; }; then
--  echo "$as_me:22142: result: yes" >&5
+-  echo "$as_me:$LINENO: result: yes" >&5
 -echo "${ECHO_T}yes" >&6
 -else
 -  echo "$as_me: failed program was:" >&5
 -cat conftest.$ac_ext >&5
 -
--      echo "$as_me:22148: result: no" >&5
+-      echo "$as_me:$LINENO: result: no" >&5
 -echo "${ECHO_T}no" >&6
--      { { echo "$as_me:22150: error:
--      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-      { { echo "$as_me:$LINENO: error:
+-       Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned long)
 -       does not apply. Please mail kde-devel@kde.org with a description of your system!
 -      " >&5
 -echo "$as_me: error:
--      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-       Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned long)
 -       does not apply. Please mail kde-devel@kde.org with a description of your system!
 -      " >&2;}
 -   { (exit 1); exit 1; }; }
 -
 -fi
 -rm -f conftest.$ac_objext conftest.$ac_ext
- 
- for ac_header in fcntl.h sys/sysctl.h sys/param.h sys/time.h sys/types.h unistd.h
- do
+-
+-
+-
+ echo "$as_me:$LINENO: checking for Qt docs" >&5
+ echo $ECHO_N "checking for Qt docs... $ECHO_C" >&6
+ kde_qtdir=
