Update to 1.9.7:
Version 1.9.7

  - The shared libraries now reside in $(pkglibdir)/modules
    (e.g. /usr/lib/g-wrap/modules).

  - Users are now allowed to chose in which module generic functions
    should be defined.

  - New feature: aggregated typespecs.  See the node `Wrapping a C
    Function' of the manual for details.

  - Users can now specify a free and a mark function, as well as an
    equality predicate for wrapped C types (WCTs) in `wrap-as-wct!'.

  - Improved documentation with an API reference (yet to be finished).

  - Several bugfixes.

diff --git a/devel/g-wrap/patches/patch-ac b/devel/g-wrap/patches/patch-ac
--- a/devel/g-wrap/patches/patch-ac
+++ b/devel/g-wrap/patches/patch-ac
@@ -1,35 +1,48 @@
-$NetBSD: patch-ac,v 1.6 2006/04/08 23:41:44 wiz Exp $
+$NetBSD: patch-ac,v 1.7 2007/01/14 14:24:31 wiz Exp $
 
---- configure.orig	2005-04-14 14:57:14.000000000 +0000
+--- configure.orig	2006-11-07 19:59:16.000000000 +0000
 +++ configure
-@@ -21699,8 +21699,8 @@ else
-   if test "x$ac_cv_env_GLIB_CFLAGS_set" = "xset"; then
- 	pkg_cv_GLIB_CFLAGS=$ac_cv_env_GLIB_CFLAGS_value
- elif test -n "$PKG_CONFIG"; then
--	if $PKG_CONFIG --exists "glib" >/dev/null 2>&1; then
--		pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib" 2>/dev/null`
-+	if $PKG_CONFIG --exists "glib-2.0" >/dev/null 2>&1; then
-+		pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0" 2>/dev/null`
- 	else
- 		pkg_failed=yes
- 	fi
-@@ -21718,8 +21718,8 @@ else
-   if test "x$ac_cv_env_GLIB_LIBS_set" = "xset"; then
- 	pkg_cv_GLIB_LIBS=$ac_cv_env_GLIB_LIBS_value
- elif test -n "$PKG_CONFIG"; then
--	if $PKG_CONFIG --exists "glib" >/dev/null 2>&1; then
--		pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib" 2>/dev/null`
-+	if $PKG_CONFIG --exists "glib-2.0" >/dev/null 2>&1; then
-+		pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0" 2>/dev/null`
- 	else
- 		pkg_failed=yes
- 	fi
-@@ -21731,7 +21731,7 @@ echo "$as_me:$LINENO: result: $pkg_cv_GL
- echo "${ECHO_T}$pkg_cv_GLIB_LIBS" >&6
- 
- if test $pkg_failed = yes; then
--	GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib"`
-+	GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0"`
+@@ -22859,12 +22859,12 @@ if test -n "$PKG_CONFIG"; then
+         pkg_cv_GLIB_CFLAGS="$GLIB_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "glib") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "glib-2.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib" 2>/dev/null`
++  pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22877,12 +22877,12 @@ if test -n "$PKG_CONFIG"; then
+         pkg_cv_GLIB_LIBS="$GLIB_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "glib") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "glib-2.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib" 2>/dev/null`
++  pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22901,9 +22901,9 @@ else
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        GLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glib"`
++	        GLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glib-2.0"`
+         else
+-	        GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib"`
++	        GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0"`
+         fi
  	# Put the nasty error message in config.log where it belongs
- 	echo "$GLIB_PKG_ERRORS" 1>&5
- 
+ 	echo "$GLIB_PKG_ERRORS" >&5
