Pullup ticket 2019 - requested by tron security update for samba
Revisions pulled up:
- pkgsrc/net/samba/Makefile				1.169
- pkgsrc/net/samba/PLIST				1.35
- pkgsrc/net/samba/distinfo				1.52
- pkgsrc/net/samba/patches/patch-ab			1.26
- pkgsrc/net/samba/patches/patch-ad			removed
- pkgsrc/net/samba/patches/patch-af			1.8
- pkgsrc/net/samba/patches/patch-ag			1.6
- pkgsrc/net/samba/patches/patch-ai			1.4
- pkgsrc/net/samba/patches/patch-al			1.5
- pkgsrc/net/samba/patches/patch-at			1.6
- pkgsrc/net/samba/patches/patch-au			1.6
- pkgsrc/net/samba/patches/patch-aw			1.2
- pkgsrc/net/samba/patches/patch-ay			1.2
- pkgsrc/net/samba/patches/patch-ba			1.4
- pkgsrc/net/samba/patches/patch-bb			1.2
- pkgsrc/net/samba/patches/patch-bg			1.2
- pkgsrc/net/samba/patches/patch-bi			1.4
- pkgsrc/net/samba/patches/patch-bl			removed
- pkgsrc/net/samba/patches/patch-bm			1.2
- pkgsrc/net/samba/patches/patch-bn			1.2
- pkgsrc/net/samba/patches/patch-bu			1.4
- pkgsrc/net/samba/patches/patch-bv			1.2
- pkgsrc/net/samba/patches/patch-cd			removed

   Module Name:		pkgsrc
   Committed By:	tron
   Date:		Sun Feb 11 18:39:04 UTC 2007

   Modified Files:
   	pkgsrc/net/samba: Makefile PLIST distinfo
   	pkgsrc/net/samba/patches: patch-ab patch-af patch-ag patch-ai patch-al
   	    patch-at patch-au patch-aw patch-ay patch-ba patch-bb patch-bg
   	    patch-bi patch-bm patch-bn patch-bu patch-bv
   Removed Files:
   	pkgsrc/net/samba/patches: patch-ad patch-bl patch-cd

   Log Message:
   Update "samba" package to version 3.0.24.
   Major changes since version 3.0.22:
   - CVE-2007-0452 (Potential Denial of Service bug in smbd)
   - CVE-2007-0453 (Buffer overrun in NSS host lookup Winbind
     NSS library on Solaris)
   - CVE-2007-0454 (Format string bug in afsacl.so VFS plugin)
   - Stability fixes for winbindd
   - Portability fixes on FreeBSD and Solaris operating systems.
   - Authentication failures in pam_winbind when the AD domain
     policy is set to not expire passwords.
   - Authorization failures when using smb.conf options such
     as "valid users" with the smbpasswd passdb backend.
   - Ambiguity with unqualified names in smb.conf parameters
     such as "force user" and "valid users".
   - Errors in 'net ads join' caused by bad IP address in the list
     of domain controllers.
   - SMB signing errors in the client and server code.
   - Domain join failures when using smbpasswd on a Samba PDC.
   - Failure to strip the domain name from groups when 'winbind
     use default domain =3D yes'
   - Failure in pam_winbind to correctly parse arguments.
   - Bad token creation of local users on member servers not
     running winbindd.
   - Failure to add users or groups to ACLs using the Windows
     object picker.
   - Failure in file serving code when 'kernel oplocks =3D yes'.
   - New "createupn" option to "net ads join"
   - Rewritten Kerberos keytab generation when 'use kerberos
     keytab =3D yes'
   - Improved 'make test'
   - New offline mode in winbindd.
   - New Kerberos support for pam_winbind.so.
   - New handling of unmapped users and groups.
   - New non-root share management tools.
   - Improved support for local and BUILTIN groups.
   - Winbind IDMAP integration with RFC2307 schema objects supported
     by Windows 2003 R2.
   - Rewritten 'net ads join' to mimic Windows XP without requiring
     administrative rights to join a domain.

diff --git a/net/samba/patches/patch-ay b/net/samba/patches/patch-ay
--- a/net/samba/patches/patch-ay
+++ b/net/samba/patches/patch-ay
@@ -1,31 +1,31 @@
-$NetBSD: patch-ay,v 1.1 2005/11/14 08:05:27 jlam Exp $
+$NetBSD: patch-ay,v 1.1.10.1 2007/02/15 13:14:50 salo Exp $
 
---- script/installswat.sh.orig	2005-10-12 13:03:44.000000000 -0400
-+++ script/installswat.sh
-@@ -84,7 +84,7 @@ if [ -d $SRCDIR../docs/htmldocs/ ]; then
+--- script/installswat.sh.orig	2007-02-04 18:59:25.000000000 +0000
++++ script/installswat.sh	2007-02-11 17:31:13.000000000 +0000
+@@ -136,7 +136,7 @@
        
-       INSTALLDIR=$SWATDIR/help/`echo $dir | sed 's/htmldocs\///g'`
-       if [ ! -d $INSTALLDIR ]; then
--        mkdir $INSTALLDIR
-+        mkdir -p $INSTALLDIR
-       fi
+       INSTALLDIR="$DESTDIR/$SWATDIR/help/`echo $dir | sed 's/htmldocs\///g'`"
+       if test ! -d "$INSTALLDIR" -a "$mode" = 'install'; then
+-        mkdir "$INSTALLDIR"
++        mkdir -p "$INSTALLDIR"
+         if test ! -d "$INSTALLDIR"; then
+           echo "Failed to make directory $INSTALLDIR, does $USER have privileges? "
+           exit 1
+@@ -164,7 +164,7 @@
  
-       for f in $SRCDIR../docs/$dir/*.html; do
-@@ -96,7 +96,7 @@ if [ -d $SRCDIR../docs/htmldocs/ ]; then
- 
-       if [ -d $SRCDIR../docs/$dir/images/ ]; then
-           if [ ! -d $INSTALLDIR/images/ ]; then
--              mkdir $INSTALLDIR/images
-+              mkdir -p $INSTALLDIR/images
-               if [ ! -d $INSTALLDIR/images/ ]; then
-                   echo Failed to make directory $SWATDIR/help/images, does $USER have privileges?
+       if test -d "$SRCDIR../docs/$dir/images/"; then
+           if test ! -d "$INSTALLDIR/images/" -a "$mode" = 'install'; then
+-              mkdir "$INSTALLDIR/images"
++              mkdir -p "$INSTALLDIR/images"
+               if test ! -d "$INSTALLDIR/images/"; then
+                   echo "Failed to make directory $INSTALLDIR/images, does $USER have privileges? "
                    exit 1
-@@ -120,7 +120,7 @@ if [ "x$BOOKDIR" != "x" -a -f $SRCDIR../
+@@ -200,7 +200,7 @@
  
      for d in $BOOKDIR $BOOKDIR/figs ; do
-         if [ ! -d $d ]; then
+         if test ! -d "$d" -a "$mode" = 'install'; then
 -            mkdir $d
 +            mkdir -p $d
-             if [ ! -d $d ]; then
-                 echo Failed to make directory $d, does $USER have privileges?
+             if test ! -d "$d"; then
+                 echo "Failed to make directory $d, does $USER have privileges? "
                  exit 1
