Update KDE to 3.1.
Many bugfixes and functionality enhancements including:

kdenetwork

 KMail
   The 'Delete' Action now irrevocably deletes messages. Use 'Move to Trash'
    to put messages into the trashcan. (Martin Koller)
   Optional columns for the number of unread messages and the total number
   of messages in the folder list (Carsten Burghardt)
   Custom folder icons (Zack Rusin)
   Improved OpenPGP support (Ingo Klöcker):
      Allow multiple encryption keys per email address, e.g. for
      distribution lists
      Allow rereading of keys in the key selection dialog, e.g. after the
      user has imported a key.
      Allow rechecking of keys in the key selection dialog, e.g. after the
      user has signed a key.
   PGP/MIME (encryption/signing of attachments, RFC 3156) for GnuPG users
   and S/MIME support via plugins (collective effort of Ägypten
   <gpa-dev@gnupg.org> and KMail <kmail@kde.org> developers)
   Redesign of the identity configuration dialog (Marc Mutz)
   Default identity can now be renamed (Marc Mutz)
   Identity-dependant default Bcc (Ingo Klöcker)
   Optional MIME tree viewer, allowing direct access to all body parts
   (attachments) (Karl-Heinz Zimmer)
   Custom date format (Zack Rusin)
   Improved IMAP support (Carsten Burghardt)
   Reorganized menu bar looks more like other KDE applications
   (Martin Koller, Marc Mutz)
   Support for decoding uuencoded attachments (Marc Mutz)
   Custom hostname to send to the SMTP server (Aaron Seigo)
   Improved 'Reply to Mailing-List' (Marc Mutz)
   Separate the 'New Message' action and the 'Post to Mailing-List' action.
   This means with 'New Message' the To: field of the new message will no
   longer be filled automatically with the mailing list's posting address
   if the currently selected folder is associated with a mailing list.
   (Ingo Klöcker)
   Improved support for RTL languages esp. Hebrew (Diego Iastrubni, Meni Livne)
   Allow the user to enable HTML rendering temporarily for HTML only
   messages (Ingo Klöcker)
   Optionally show the encryption/signature status of messages in the
   message list (Kalle Dalheimer)
   Optional popup after dragging a message onto a folder (Zack Rusin)
   Five fixed layouts for the main window (Karl-Heinz Zimmer)
   Send separately encrypted messages to Bcc recipients because else all
   recipients could deduce the Bcc recipients from the keys that were used
   for encryption (Steffen Hansen)
   Configurable default domain for sending (Ingo Klöcker)
   Don't check spelling of quoted text, urls or email addresses (Dave Corrie)
   New 'Add to Addressbook' action which doesn't open the addressbook when
   you add an email address to it. Use 'Open in Addressbook' if you want to
   add more information to a new address. (Cornelius Schumacher)
   IMAP accounts are now top level elements in the folder list (Carsten
   Burghardt)
   Configurable timeout for when the selected message will be marked as
   read (Tobias Koenig)
   Tips of the Day (Marc Mutz)
   Show progress dialog on exit so that the user sees that KMail is still
   doing something although all windows have already been closed (Waldo
   Bastian, Carsten Pfeiffer)
   Use KNotify to play an arbitrary sound on new mail arrival (Till Krech)
   Configurable alternative background color for the message list
   (Waldo Bastian)
   Display folder path in window caption (Carsten Burghardt)
 KNode
   Added "Find in Article..." command.
   Added "Mark Last as Unread..." command.
   Bug- and Stability fixes.
 Korn now supports APOP accounts.
 NEW IN KDE: Desktop Sharing (KRfb). KRfb is a VNC-compatible server to
 share KDE desktops.
 NEW IN KDE: Remote Desktop Connection (KRdb). VNC compatible client for
 sharing KDE desktops.

diff --git a/net/kdenetwork3/patches/patch-aa b/net/kdenetwork3/patches/patch-aa
--- a/net/kdenetwork3/patches/patch-aa
+++ b/net/kdenetwork3/patches/patch-aa
@@ -1,32 +1,28 @@
-$NetBSD: patch-aa,v 1.4 2003/02/26 10:46:13 dmcmahill Exp $
+$NetBSD: patch-aa,v 1.5 2003/03/11 13:13:28 markd Exp $
 
---- configure.orig	Tue Dec 17 05:49:48 2002
+--- configure.orig	Fri Jan 17 08:54:59 2003
 +++ configure
-@@ -22535,7 +22535,7 @@ main ()
+@@ -27870,65 +27870,6 @@ _ACEOF
  
-  char buf[20];
-   buf[0]='\0';
--  strlat(buf, "KDE function test", sizeof(buf));
-+  strlcat(buf, "KDE function test", sizeof(buf));
  
-   ;
-   return 0;
-@@ -23147,57 +23147,6 @@ echo "${ECHO_T}$ac_cv_sizeof_unsigned_in
- cat >>confdefs.h <<EOF
- #define SIZEOF_UNSIGNED_INT $ac_cv_sizeof_unsigned_int
- EOF
--
--  echo "$as_me:23151: checking sizeof(size_t) == sizeof(unsigned int)" >&5
--echo $ECHO_N "checking sizeof(size_t) == sizeof(unsigned int)... $ECHO_C" >&6
+ 
+-  echo "$as_me:$LINENO: checking sizeof(size_t) == sizeof(unsigned long)" >&5
+-echo $ECHO_N "checking sizeof(size_t) == sizeof(unsigned long)... $ECHO_C" >&6
 -  cat >conftest.$ac_ext <<_ACEOF
--#line 23154 "configure"
+-#line $LINENO "configure"
 -#include "confdefs.h"
 -
+-#ifdef F77_DUMMY_MAIN
+-#  ifdef __cplusplus
+-     extern "C"
+-#  endif
+-   int F77_DUMMY_MAIN() { return 1; }
+-#endif
 -int
 -main ()
 -{
 -
--    #if SIZEOF_SIZE_T != SIZEOF_UNSIGNED_INT
+-    #if SIZEOF_SIZE_T != SIZEOF_UNSIGNED_LONG
 -       choke me
 -    #endif
 -
@@ -35,37 +31,40 @@ $NetBSD: patch-aa,v 1.4 2003/02/26 10:46:13 dmcmahill Exp $
 -}
 -_ACEOF
 -rm -f conftest.$ac_objext
--if { (eval echo "$as_me:23170: \"$ac_compile\"") >&5
+-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 -  (eval $ac_compile) 2>&5
 -  ac_status=$?
--  echo "$as_me:23173: \$? = $ac_status" >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); } &&
 -         { ac_try='test -s conftest.$ac_objext'
--  { (eval echo "$as_me:23176: \"$ac_try\"") >&5
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
 -  (eval $ac_try) 2>&5
 -  ac_status=$?
--  echo "$as_me:23179: \$? = $ac_status" >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); }; }; then
--  echo "$as_me:23181: result: yes" >&5
+-  echo "$as_me:$LINENO: result: yes" >&5
 -echo "${ECHO_T}yes" >&6
 -else
 -  echo "$as_me: failed program was:" >&5
 -cat conftest.$ac_ext >&5
 -
--      echo "$as_me:23187: result: no" >&5
+-      echo "$as_me:$LINENO: result: no" >&5
 -echo "${ECHO_T}no" >&6
--      { { echo "$as_me:23189: error:
--      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-      { { echo "$as_me:$LINENO: error:
+-       Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned long)
 -       does not apply. Please mail kde-devel@kde.org with a description of your system!
 -      " >&5
 -echo "$as_me: error:
--      Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned int)
+-       Apparently on your system our assumption sizeof(size_t) == sizeof(unsigned long)
 -       does not apply. Please mail kde-devel@kde.org with a description of your system!
 -      " >&2;}
 -   { (exit 1); exit 1; }; }
 -
 -fi
 -rm -f conftest.$ac_objext conftest.$ac_ext
+-
+-
+-
  
- if test -z "$LIBPTHREAD" && test -z "$USE_THREADS"; then
-   DO_NOT_COMPILE="$DO_NOT_COMPILE knode kdict"
+     if test -z "$LIBPTHREAD"; then
+     if test -z "$USE_THREADS"; then
