Work around a bug in older -current' pax-as-tar (e.g. 1.6K): copy few files instead linking them.  Bump PKGREVISION.

diff --git a/devel/unproven-pthreads/patches/patch-af b/devel/unproven-pthreads/patches/patch-af
--- a/devel/unproven-pthreads/patches/patch-af
+++ b/devel/unproven-pthreads/patches/patch-af
@@ -1,7 +1,7 @@
-$NetBSD: patch-af,v 1.4 2002/08/25 19:22:43 jlam Exp $
+$NetBSD: patch-af,v 1.5 2003/02/15 00:06:05 salo Exp $
 
---- config/configure.orig	Mon Jul 10 14:03:06 2000
-+++ config/configure
+--- config/configure.orig	Mon Jul 10 21:03:06 2000
++++ config/configure	Sat Feb 15 00:10:29 2003
 @@ -1151,7 +1151,7 @@
  name=$host_cpu-$host_os
  
@@ -11,7 +11,7 @@ $NetBSD: patch-af,v 1.4 2002/08/25 19:22:43 jlam Exp $
  	name=alpha-netbsd-1.3
  	except="fork lseek ftruncate pipe fstat"
  	available_syscalls="sigsuspend sigaction sigprocmask"
-@@ -1161,24 +1161,44 @@
+@@ -1161,18 +1161,28 @@
  	except="fork lseek ftruncate pipe fstat"
  	available_syscalls="sigsuspend sigaction sigprocmask"
  	;;
@@ -41,19 +41,43 @@ $NetBSD: patch-af,v 1.4 2002/08/25 19:22:43 jlam Exp $
  #	CFLAGS="$CFLAGS -Werror"
  	name=i386-netbsd-1.3
  	except="fork lseek ftruncate pipe fstat"
+@@ -1183,6 +1193,16 @@
+ 	except="fork lseek ftruncate pipe fstat"
  	available_syscalls="sigsuspend sigaction sigprocmask"
- 		;;
-     m68*-*-netbsd1.4*)
-+	name=m68000-netbsd
-+	except="fork lseek ftruncate pipe fstat"
-+	available_syscalls="sigsuspend sigaction sigprocmask"
-+	;;
+ 	;;
 +    m68*-*-netbsd1.5*)
 +	name=m68000-netbsd
 +	except="fork lseek ftruncate pipe fstat"
 +	available_syscalls="sigsuspend sigaction sigprocmask"
 +	;;
 +    m68*-*-netbsd1.6*)
- 	name=m68000-netbsd
- 	except="fork lseek ftruncate pipe fstat"
- 	available_syscalls="sigsuspend sigaction sigprocmask"
++	name=m68000-netbsd
++	except="fork lseek ftruncate pipe fstat"
++	available_syscalls="sigsuspend sigaction sigprocmask"
++	;;
+     *)
+ 	{ echo "configure: error: System type $host not recognized or not supported.
+ See $srcdir/configure.in for supported systems." 1>&2; exit 1; }
+@@ -2026,7 +2046,7 @@
+   set $ac_dests; ac_dest=$1; shift; ac_dests=$*
+   set $ac_sources; ac_source=$1; shift; ac_sources=$*
+ 
+-  echo "linking $srcdir/$ac_source to $ac_dest"
++  echo "copying $srcdir/$ac_source to $ac_dest"
+ 
+   if test ! -r $srcdir/$ac_source; then
+     { echo "configure: error: $srcdir/$ac_source: File not found" 1>&2; exit 1; }
+@@ -2052,10 +2072,10 @@
+   esac
+ 
+   # Make a symlink if possible; otherwise try a hard link.
+-  if ln -s $ac_rel_source $ac_dest 2>/dev/null ||
+-    ln $srcdir/$ac_source $ac_dest; then :
++  if cp $ac_rel_source $ac_dest 2>/dev/null ||
++    cp -f $srcdir/$ac_source $ac_dest; then :
+   else
+-    { echo "configure: error: can not link $ac_dest to $srcdir/$ac_source" 1>&2; exit 1; }
++    { echo "configure: error: can not copy $ac_dest to $srcdir/$ac_source" 1>&2; exit 1; }
+   fi
+ done
+ EOF
