Update netatalk1 package to 1.6.4a.
pkgsrc change

- Take matainer ship by me.
- Introduce options.mk for PAM configure option.
- Minor clean up of Makefile.
- Added quick changes to avoid using <openssl/des.h>.

netatalk changes

Changes in 1.6.4a
=================

* FIX: insecure tempfile handling bug in etc2ps.sh, found by Trustix, CAN-2004-0974.

Changes in 1.6.4
================

* NEW: afpd: Using the mswindows option now implicitly specifies usedots.
  [Sam Noble]
* UPD: afpd.8: Updated the option documentation.
  [Thomas Kaiser, Sebastian Rittau]
* FIX: configure: Removed broken --with-flock-locks option. [Bj\M-C\M-6rn Fernhomberg]
* FIX: libatalk: Do not log network probe (OSX 10.3). [Didier Gautheron]
* FIX: libatalk: Deadlock in signal handlers. [Didier]
* FIX: libatalk: Compilation with Linux kernel 2.6 fixed. [Sebastian, Bj\M-C\M-6rn]
* FIX: afpd: Solaris compile issues. [Bj\M-C\M-6rn]
* FIX: afpd: If connection broke in dsi_tickle the child did never die. [Bj\M-C\M-6rn]
* FIX: afpd: Catsearch, fixes a possible segmentation fault. [Bj\M-C\M-6rn]
* FIX: afpd: Compilation issues. [Olaf Hering, Sebastian]
* FIX: cnid: Fix compile problems on Tru64. [Burkhard Schmidt]
* FIX: megatron: Fixed an uninitialized variable. [Olaf]
* FIX: installation: Don't overwrite PAM file if --enable-overwrite configure
       option is not set. [Sam, Ryan Cleary]
* FIX: installation: Fixed BSD installation. [Toru TAKAMIZU]
* FIX: docs: Removed ssl-dir/ssl-dirs confusion from doc/INSTALL. [Bj\M-C\M-6rn]

Changes in 1.6.3
================

* UPD: afpd: Infrastructural support for an upcoming Kerberos 5 UAM.
       [Sam Noble]
* UPD: uams_dhx_passwd: Better random seed in Tru64. [Burkhard Schmidt]
* FIX: afpd: Bug in AFP connection negotiation stage. [Sam]
* FIX: afpd: Catsearch, when Mac and unix name differ, search on attributes.
* FIX: afpd: Files could be opened for writing on read-only filesystems.
* FIX: afpd: Debugging using SIGUSR1 was broken. [Stefan Muenkner]
* FIX: afpd: Segfault after login. [Robby Griffin, Sean Bolton]
* FIX: psf: Correct path to etc2ps.sh.
* FIX: shell_utils: Don't distribute generated files.
* FIX: aecho: -A option didn't work. [Chris Shiels]
* FIX: configure: Berkeley DB path detection could be wrong. [Stefan]
* FIX: Automake build fixes.

diff --git a/net/netatalk1/patches/patch-af b/net/netatalk1/patches/patch-af
--- a/net/netatalk1/patches/patch-af
+++ b/net/netatalk1/patches/patch-af
@@ -1,7 +1,7 @@
-$NetBSD: patch-af,v 1.1.1.1 2004/11/02 11:20:10 markd Exp $
+$NetBSD: patch-af,v 1.2 2005/06/05 23:40:56 taca Exp $
 
---- etc/psf/etc2ps.sh.orig	Sun Apr 27 15:00:44 2003
-+++ etc/psf/etc2ps.sh	Sun Apr 27 19:51:31 2003
+--- etc/psf/etc2ps.sh.orig	2004-10-28 07:54:53.000000000 +0900
++++ etc/psf/etc2ps.sh
 @@ -9,15 +9,12 @@
  # tag in the case.
  #
@@ -19,12 +19,19 @@ $NetBSD: patch-af,v 1.1.1.1 2004/11/02 11:20:10 markd Exp $
  case $1 in
  
  #
-@@ -39,7 +36,7 @@
+@@ -40,12 +37,9 @@ df*)
  # troff2ps is from psroff by Chris Lewis.
  #
  tf*)
 -    if [ -x "$TROFF2PS" ]; then
-+    if [ -x "/usr/bin/groff" ]; then
- 	exec $TROFF2PS $TROFF2PSARGS
-     else
- 	echo "$0: filter troff2ps uninstalled" 1>&2
+-	exec $TROFF2PS $TROFF2PSARGS
+-    else
+-	echo "$0: filter troff2ps uninstalled" 1>&2
+-	exit 2
+-    fi
++    exec $TROFF2PS $TROFF2PSARGS
++    echo "$0: filter troff2ps failed" 1>&2
++    exit 2
+     ;;
+ 
+ *)
